from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ATOM-MAPPING-REACTION-BALANCE-008'
DOMAINS=(('unmapped-reactant-string', 'held-reactant-atom-support'), ('unmapped-product-string', 'held-product-atom-support'), ('partial-atom-map', 'complete-source-product-carrier-bijection'), ('mass-total-only-balance', 'element-by-element-conservation'), ('isotope-label-erasure', 'isotope-carrier-conservation'), ('signed-net-only-balance', 'held-charge-hand-and-magnitude-custody'), ('selected-main-component', 'all-reactant-product-components-retained'), ('balanced-boolean-only', 'mapping-inventory-and-change-certificate'))
SURVIVOR='held-reactant-atom-support__held-product-atom-support__complete-source-product-carrier-bijection__element-by-element-conservation__isotope-carrier-conservation__held-charge-hand-and-magnitude-custody__all-reactant-product-components-retained__mapping-inventory-and-change-certificate'
DIMENSION_KEYS=('sources', 'products', 'mapping', 'elements', 'isotopes', 'charge', 'components', 'certificate')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
