from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-RAMAN-TRANSITION-INTENSITY-009';DOMAINS=(('detached-raman-number', 'held-molecular-carrier'), ('peak-without-state-transition', 'held-initial-and-final-state'), ('imported-raman-selection-rule', 'held-polarizability-state-transformation'), ('signed-floating-line-position', 'held-side-positive-exact-shift-or-EmptyOne'), ('arbitrary-normalized-height', 'exact-positive-event-ratio-or-EmptyOne'), ('unconditioned-universal-spectrum', 'held-excitation-condition-and-unit'), ('selected-prominent-lines', 'complete-line-intensity-uncertainty-custody'), ('refitted-added-spectrum', 'successor-retains-and-appends-complete-lines'));SURVIVOR='held-molecular-carrier__held-initial-and-final-state__held-polarizability-state-transformation__held-side-positive-exact-shift-or-EmptyOne__exact-positive-event-ratio-or-EmptyOne__held-excitation-condition-and-unit__complete-line-intensity-uncertainty-custody__successor-retains-and-appends-complete-lines'
from fractions import Fraction
EMPTY="EmptyOne"
def relation(incident,scattered):
 if incident==scattered:return ("coincident",EMPTY)
 return ("stokes" if incident>scattered else "anti-stokes",abs(incident-scattered))
rows=(("molecule-a","state-a","state-b","changes",relation(Fraction(10),Fraction(7)),Fraction(3,5),("excitation-a","inverse-length")),("molecule-a","state-b","state-c","unresolved",relation(Fraction(10),Fraction(10)),EMPTY,("excitation-a","inverse-length")))
native={"carrier":all(x[0]=="molecule-a" for x in rows),"states":all(x[1]!=x[2] for x in rows),"polarizability":rows[0][3]=="changes","position":rows[0][4]==("stokes",Fraction(3)) and rows[1][4]==("coincident",EMPTY),"intensity":rows[0][5]==Fraction(3,5) and rows[1][5]==EMPTY,"condition":len({x[6] for x in rows})==1,"custody":len(rows)==2,"extension":len(rows+(("molecule-a","state-a","state-c","changes",("anti-stokes",Fraction(2)),Fraction(1,5),("excitation-a","inverse-length")),))==3}
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};passed=sealed["claim_id"]==CLAIM_ID and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(item["passed"] for item in sealed["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
