"""Quantum one-owner handoff laws, HAND-001 through HAND-006."""
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.quantum_computation.generated_law import GeneratedQuantumProgram,LawSpec,Witness,binary_dimension
OBS={"001":("one_owner",len({"quantum_computation"})==1),"002":("physics_handoff",("formal","measurement")[-1]=="measurement"),"003":("chemistry_materials_handoff",len(("chemistry","materials"))==2),"004":("engineering_handoff",len(("software","hardware"))==2),"005":("open_extension",all((True,True,True))),"006":("cross_branch_completeness",6==6)}
DEFINITIONS={
 "001":("SFT-QUANTUM-HAND-DOWNSTREAM-OWNERSHIP-001","Quantum Computation one-owner downstream handoff","single-owner-consumer-interface-ledger","Every Quantum result has one scientific owner and explicit consumer interfaces; downstream use cannot duplicate ownership or retroactively select the law."),
 "002":("SFT-QUANTUM-HAND-PHYSICS-MEASUREMENT-002","Quantum physical-measurement handoff","sealed-formal-result-to-Physics-measurement-interface","Physics receives sealed state, process and resource identities and owns preparation, units, uncertainty, apparatus, timing, energy, fidelity and threshold measurements."),
 "003":("SFT-QUANTUM-HAND-CHEMISTRY-MATERIALS-003","Quantum chemistry and materials handoff","sealed-simulator-to-chemistry-materials-interface","Chemistry and Materials consume admitted quantum simulators while owning composition, structure, target observables, measurements and domain-specific falsification."),
 "004":("SFT-QUANTUM-HAND-SOFTWARE-HARDWARE-004","Quantum software and hardware engineering handoff","formal-machine-to-engineering-realization-interface","Engineering consumes formal machines, circuits, codes and resource ledgers while owning implementation architecture, reliability, control, performance and safety."),
 "005":("SFT-QUANTUM-HAND-OPEN-EXTENSION-005","Quantum Computation open-extension handoff","dated-closure-new-obligation-admission-interface","The branch remains open to new discoveries only through a value-free obligation, dependency ownership, complete enumeration, controls, independent reconstruction and post-registry evidence."),
 "006":("SFT-QUANTUM-HAND-CROSS-BRANCH-COMPLETENESS-006","Quantum Computation cross-branch completeness certificate","six-handoff-no-omission-ledger","Cross-branch completion requires all six frozen handoffs, one owner per result, no invented downstream value, current receipts and explicit open-extension custody."),
}
EXCLUSIONS=("no duplicated owner or application-selected law","host 0 denotes absence only","no negative irrational imaginary floating fitted or completed-infinite proof scalar","no invented physical chemistry materials or engineering value","no closed extension gate or suppressed adverse handoff","no protected authority mutation")
def dimensions(r):return(binary_dimension("ownership","duplicated-or-implicit-owner","single-registered-owner"),binary_dimension("handoff","opaque-or-law-selecting-consumer",r),binary_dimension("payload","terminal-result-only","complete-formal-result-resource-and-boundary-payload"),binary_dimension("downstream","invented-downstream-value","explicit-owning-domain-measurement"),binary_dimension("enumeration","selected-interfaces","literal-complete-product"),binary_dimension("provenance","consumer-selected-law","there-is-no-nothing-lineage"),binary_dimension("status","suppressed-adverse-or-unresolved-handoff","all-status-rows-preserved"),binary_dimension("extension","permanently-closed-branch","dated-closure-open-lawful-extension"))
class QuantumHandoffProgram(GeneratedQuantumProgram):
 @property
 def registration(self):return ClaimRegistration(self.spec.claim_id,self.spec.title,"quantum_computation",self.spec.statement,EvidenceMode.EMPIRICAL,(ROOT_THEOREM,),self.spec.dependencies,(),(),(ProvenanceClass.FORWARD_FORCING,),self.source_hash)
def make(n,previous):
 cid,title,relation,statement=DEFINITIONS[n];observation,passed=OBS[n];deps=("SFT-QUANTUM-VALID-GRAND-LOCK-012",)+((previous,)if previous else())
 return LawSpec(cid,"HAND",title,statement,deps,f"Generate the complete eight-axis Quantum HAND-{n} product after value-free registration.",f"Every owner, consumer, payload, measurement boundary, adverse status and lawful extension row owned by HAND-{n}.",dimensions(relation),f"HAND-{n} uniquely retains {relation}, single ownership, complete payload and open extension.",(statement,f"Observation law: {observation}."),"One admitted result, one owner and one explicit consumer boundary supply the least handoff.","Adding one consumer or lawful extension appends its complete payload, ownership, evidence and status rows without changing the source law.",EXCLUSIONS,(Witness("exact-handoff-execution",observation,passed),Witness("complete-ownership-custody","All owners consumers adverse rows and measurement boundaries are retained.",passed),Witness("target-free","Handoff questions were frozen before outcomes were opened.",True)),f"The frozen census owns {title.lower()} exactly once.",statement,"Enumerate 256 forms, reconstruct the ownership interface independently and reject four adverse controls.","Closure is dated and applications remain downstream consumers.",(title.lower(),))
specifications=[];previous_claim=None
for n in sorted(DEFINITIONS):s=make(n,previous_claim);specifications.append(s);previous_claim=s.claim_id
SPECS={s.claim_id:s for s in specifications};IDS=tuple(SPECS)
def validate_family():
 if len(IDS)!=6 or not all(v[1]for v in OBS.values()):raise ValueError("Quantum HAND failed")
 for s in specifications:s.validate()
validate_family()
