from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CHEMICAL-SUBSTRUCTURE-RELATION-003'
DOMAINS=(('text-fragment-query', 'held-query-graph'), ('database-hit-label', 'held-target-graph'), ('noninjective-match', 'injective-carrier-map'), ('wildcard-unregistered-atoms', 'registered-atom-label-preservation'), ('path-length-only-match', 'exact-bond-incidence-preservation'), ('stereo-charge-isotope-ignored', 'requested-held-fibres-preserved'), ('first-hit-search', 'all-embedding-census'), ('failed-query-silently-empty', 'structural-absence-with-falsification-trace'))
SURVIVOR='held-query-graph__held-target-graph__injective-carrier-map__registered-atom-label-preservation__exact-bond-incidence-preservation__requested-held-fibres-preserved__all-embedding-census__structural-absence-with-falsification-trace'
DIMENSION_KEYS=('query', 'target', 'mapping', 'atoms', 'bonds', 'orientation', 'enumeration', 'adverse')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
