from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-POLYMER-DISPERSITY-004';DOMAINS=(('different-populations-for-moments', 'one-shared-complete-population'), ('number-average-untraced', 'forced-number-average-with-trace'), ('mass-average-untraced', 'forced-mass-average-with-trace'), ('subtracted-spread', 'mass-average-over-number-average'), ('floating-fit-statistic', 'exact-positive-rational-result'), ('named-distribution-assumption', 'no-distribution-shape-assumed'), ('unresolved-rows-discarded', 'all-source-bound-rows-retained'), ('scalar-only-output', 'population-both-moments-ratio-and-boundary-trace'));SURVIVOR='one-shared-complete-population__forced-number-average-with-trace__forced-mass-average-with-trace__mass-average-over-number-average__exact-positive-rational-result__no-distribution-shape-assumed__all-source-bound-rows-retained__population-both-moments-ratio-and-boundary-trace'
from fractions import Fraction
rows=((2,3),(5,2));count=sum(n for _,n in rows);first=sum(m*n for m,n in rows);second=sum(m*m*n for m,n in rows);number=Fraction(first,count);mass=Fraction(second,first);result=mass/number
native={"population":len(rows)==2,"number":number==Fraction(16,5),"mass":mass==Fraction(31,8),"ratio":result==Fraction(155,128),"arithmetic":result>0,"distribution":rows==((2,3),(5,2)),"adverse":Fraction(1011,890)!=Fraction(124,100),"certificate":result*number==mass}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
