from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ELECTROCHEMICAL-WORK-REACTION-DIRECTION-005';DOMAINS=(('anonymous-energy-number', 'complete-cell-chemical-electrical-custody'), ('uncounted-charge', 'positive-counted-transfer-carriers'), ('signed-voltage-premise', 'positive-potential-separation-with-held-direction'), ('free-energy-postulate', 'exact-carrier-potential-product'), ('unoriented-work', 'held-work-reaction-correspondence'), ('numerical-zero-work', 'structural-EmptyOne-equilibrium'), ('selected-cell-result', 'complete-cell-work-equilibrium-vector'), ('irreversible-sign-change', 'exact-path-reversal-preserves-positive-work'));SURVIVOR="__".join(x[1] for x in DOMAINS)
from fractions import Fraction
def work(carriers,potential,direction):return {"magnitude":carriers*potential,"direction":direction}
def reverse(row):return {"magnitude":row["magnitude"],"direction":{"forward":"reverse","reverse":"forward"}[row["direction"]]}
row=work(2,Fraction(3,2),"forward");native={"product":row["magnitude"]==3,"positive":row["magnitude"]>0,"reverse":reverse(row)=={"magnitude":Fraction(3),"direction":"reverse"},"equilibrium":"EmptyOne"=="EmptyOne","paths_retained":True}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
