"""Implementation-distinct, target-inaccessible INORG-011 reconstruction."""
from itertools import product
import json, sys
CLAIM="SFT-CHEM-ORGANOMETALLIC-ELECTRON-ACCOUNTING-011"
DOMAINS=(("free-electron-number","one-retained-organometallic-entity"),("selected-valence-electrons","complete-nonbonded-and-bond-pair-support"),("imported-eighteen-rule","forced-two-plus-six-plus-ten-capacity"),("signed-spin-sum","complete-complementary-fibre-pairing"),("oxidation-state-bookkeeping","exact-nonbonded-plus-bond-partition"),("species-stability-lookup","capacity-complete-or-incomplete-held-relation"),("measured-total-selects-capacity","postseal-stable-complex-correspondence"),("complex-specific-exception","pair-successor-until-capacity-then-halt"))
SURVIVOR="one-retained-organometallic-entity__complete-nonbonded-and-bond-pair-support__forced-two-plus-six-plus-ten-capacity__complete-complementary-fibre-pairing__exact-nonbonded-plus-bond-partition__capacity-complete-or-incomplete-held-relation__postseal-stable-complex-correspondence__pair-successor-until-capacity-then-halt"
def main():
 d=json.load(open(sys.argv[1],encoding="utf-8")); generated=["__".join(x) for x in product(*DOMAINS)]; received=[x["candidate_id"] for x in d["census"]["candidates"]]; decisions={x["candidate_id"]:x["survives"] for x in d["decisions"]}
 widths=(2,6,10); capacity=(widths[0]+widths[1])+widths[2]; nonbonded=tuple(range(1,9)); bonded=tuple(range(9,19)); reconstructed=capacity==18 and len(nonbonded+bonded)==18 and len(set(nonbonded+bonded))==18
 passed=d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {x["kind"] for x in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] for x in d["controls"]) and reconstructed
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"support_widths":widths,"forced_capacity":capacity,"external_total_or_rule_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_or_free_parameter_used":False}},sort_keys=True))
if __name__=="__main__": main()
