from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-KINETIC-ISOTOPE-FRACTIONATION-008';DOMAINS=(('mass-only-rate', 'held-reaction-light-heavy-identities'), ('continuous-time-premise', 'positive-ordered-resource-intervals'), ('expected-product-yield', 'positive-counted-isotope-products'), ('fitted-rate-constants', 'exact-products-per-resource-rates'), ('imported-kinetic-isotope-effect', 'exact-light-heavy-rate-ratio'), ('signed-rate-difference', 'held-faster-class-or-EmptyOne'), ('negative-depleted-reactant', 'positive-Take-or-EmptyOne-remainder'), ('Rayleigh-continuum-premise', 'finite-time-series-successor-recomputes'));SURVIVOR='held-reaction-light-heavy-identities__positive-ordered-resource-intervals__positive-counted-isotope-products__exact-products-per-resource-rates__exact-light-heavy-rate-ratio__held-faster-class-or-EmptyOne__positive-Take-or-EmptyOne-remainder__finite-time-series-successor-recomputes'
from fractions import Fraction
def row(lp,hp,resource=2):return (Fraction(lp,resource),Fraction(hp,resource),Fraction(lp,hp),None if lp==hp else "light" if lp>hp else "heavy")
def remain(initial,product):return None if initial==product else initial-product
native={"identity":True,"support":True,"events":(4,2)==(4,2),"rates":row(4,2)[:2]==(2,1),"factor":row(4,2)[2]==2,"orientation":row(4,2)[3]=="light","inventory":remain(8,4)==4 and remain(8,8) is None,"successor":row(6,3)[2]==2}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
