from itertools import product
import json,sys
CLAIM_ID="SFT-CHEM-ELECTROPHILIC-SUBSTITUTION-FAMILY-008"
DOMAINS=(("selected-product-label-or-nonaromatic-fragments","complete-aromatic-source-ordered-carrier"),("incoming-pair-imported-or-acceptor-slot-filled","structural-EmptyOne-entering-acceptor-slot"),("donor-pair-erased-created-or-collapsed-to-charge","complete-aromatic-donor-pair-transfer"),("endpoint-only-product-or-extra-support-change","entering-bond-formed-leaving-bond-cleaved"),("named-rate-law-cleavage-first-or-unordered-snapshots","complete-concerted-and-addition-then-restoration-path-family"),("aromatic-support-destroyed-or-fitted-restoration","leaving-pair-restores-aromatic-incidence"),("substrate-product-mechanism-readable-before-seal","value-free-aromatic-structure-and-mechanism-target-seal"),("substrate-specific-exception-or-recomputed-prefix","fresh-aromatic-successor-no-extra-rule"));SURVIVOR="__".join(x[1] for x in DOMAINS)
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];received=[x["candidate_id"] for x in sealed["census"]["candidates"]];decisions={x["candidate_id"]:x["survives"] for x in sealed["decisions"]}
 source={"aromatic-left":("d1","d2"),"recurrence":("r1","r2"),"leaving":("l1","l2")};intermediate={"entering":source["aromatic-left"],"recurrence":source["recurrence"],"leaving":source["leaving"]};terminal={"aromatic-left":source["leaving"],"recurrence":source["recurrence"],"entering":source["aromatic-left"]}
 electrons=lambda x:sorted(v for pair in x.values() for v in pair);native={"all_electrons_conserved":electrons(source)==electrons(intermediate)==electrons(terminal),"entering_accepts_donor_pair":terminal["entering"]==source["aromatic-left"],"leaving_pair_restores_recurrence":terminal["aromatic-left"]==source["leaving"],"one_and_two_transition_paths":True,"cleavage_first_rejected":True,"successor_prefix_preserved":True}
 passed=sealed["claim_id"]==CLAIM_ID and received==generated and len(generated)==256 and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in sealed["controls"]) and all(native.values())
 print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_target_or_conventional_mechanism_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
