from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-XRAY-DIFFRACTION-STRUCTURE-016'
DOMAINS=(('pattern-without-crystal', 'held-crystal-phase-and-composition'), ('chemistry-owned-xray-probe', 'explicit-physics-xray-scattering-handoff'), ('line-list-without-reciprocal-support', 'held-direct-and-reciprocal-support'), ('floating-two-theta', 'exact-positive-spacing-or-held-angle'), ('arbitrary-diffraction-intensity', 'exact-counted-relative-intensity-or-EmptyOne'), ('database-structure-label-only', 'complete-cell-symmetry-site-correspondence'), ('selected-major-reflections', 'complete-reflection-error-condition-custody'), ('refined-added-pattern', 'successor-retains-prior-reflections-and-structure'))
SURVIVOR='held-crystal-phase-and-composition__explicit-physics-xray-scattering-handoff__held-direct-and-reciprocal-support__exact-positive-spacing-or-held-angle__exact-counted-relative-intensity-or-EmptyOne__complete-cell-symmetry-site-correspondence__complete-reflection-error-condition-custody__successor-retains-prior-reflections-and-structure'
DIMENSION_KEYS=('carrier', 'probe', 'support', 'coordinate', 'response', 'structure', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
