from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ELECTROPHORETIC-MOBILITY-SEPARATION-019'
DOMAINS=(('mobility-without-species', 'held-species-and-particle-identity'), ('signed-negative-mobility', 'held-charge-motion-side'), ('medium-free-mobility', 'held-medium-pH-temperature-condition'), ('unrecorded-field', 'held-field-direction-and-resource'), ('floating-mobility', 'exact-positive-mobility-magnitude-or-EmptyOne'), ('named-separated-or-not', 'exact-trajectory-and-pairwise-separation'), ('selected-mobile-fraction', 'complete-mobility-error-absence-custody'), ('refitted-added-species', 'successor-retains-and-appends-species'))
SURVIVOR='held-species-and-particle-identity__held-charge-motion-side__held-medium-pH-temperature-condition__held-field-direction-and-resource__exact-positive-mobility-magnitude-or-EmptyOne__exact-trajectory-and-pairwise-separation__complete-mobility-error-absence-custody__successor-retains-and-appends-species'
DIMENSION_KEYS=('species', 'charge', 'medium', 'field', 'mobility', 'separation', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
