from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-UVVISIBLE-LINE-INTENSITY-013'
DOMAINS=(('detached-uvvis-number', 'held-molecule-and-electronic-carrier'), ('band-without-electronic-states', 'held-initial-final-electronic-states'), ('signed-floating-wavelength', 'exact-positive-absorption-coordinate-or-EmptyOne'), ('fitted-extinction-scalar', 'exact-counted-absorption-response-or-EmptyOne'), ('bright-transition-only', 'complete-electronic-transition-support'), ('solvent-free-universal-band', 'held-solvent-phase-temperature-condition'), ('selected-favorable-bands', 'complete-band-error-bound-absence-custody'), ('renormalized-added-band', 'successor-retains-and-appends-complete-bands'))
SURVIVOR='held-molecule-and-electronic-carrier__held-initial-final-electronic-states__exact-positive-absorption-coordinate-or-EmptyOne__exact-counted-absorption-response-or-EmptyOne__complete-electronic-transition-support__held-solvent-phase-temperature-condition__complete-band-error-bound-absence-custody__successor-retains-and-appends-complete-bands'
DIMENSION_KEYS=('carrier', 'states', 'coordinate', 'response', 'partition', 'condition', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
