"""Frozen declarative inventory for the classical-computation branch.

These records name the exact generated-finite kernels to be forced.  They do
not import conventional theorems as premises.  Familiar terms are retained only
as downstream correspondence labels after each result is sealed.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Topic:
    slug: str
    title: str
    subject: str
    components: str
    limitations: str
    correspondence: tuple[str, ...]


def T(slug: str, title: str, subject: str, components: str, limitations: str, *correspondence: str) -> Topic:
    return Topic(slug, title, subject, components, limitations, tuple(correspondence))


GROUP_CODES = {
    "formal_computation": "FORM",
    "computability": "CBL",
    "complexity": "CPLX",
    "algorithms": "ALG",
    "semantics": "SEM",
    "distributed_computation": "DIST",
    "cryptography_security": "SEC",
    "learning_intelligence": "LEARN",
    "scientific_computation": "SCI",
}


GROUP_TITLES = {
    "formal_computation": "Formal Computation",
    "computability": "Computability",
    "complexity": "Computational Complexity",
    "algorithms": "Algorithms and Mathematical Data Structures",
    "semantics": "Semantics and Mathematical Programming Theory",
    "distributed_computation": "Concurrent and Distributed Computation",
    "cryptography_security": "Cryptography and Computational Security",
    "learning_intelligence": "Learning and Intelligence Theory",
    "scientific_computation": "Scientific Computation",
}


GROUP_TOPICS: dict[str, tuple[Topic, ...]] = {
    "formal_computation": (
        T("STATE-TRANSITION", "Exact state and transition law", "generated configurations and change", "complete state carrier; held action labels; source-bound transition rows; initial and terminal classes; retained execution traces", "Does not yet define a language, machine model or resource bound.", "state", "transition system"),
        T("LANGUAGE-GRAMMAR", "Fold formal-language and grammar law", "generated symbol words and formation", "complete alphabet; empty-One word; finite successor words; named productions; derivation trees; exact membership certificates", "Closes generated finite languages and depth-independent word succession, not a completed infinite language object.", "formal language", "grammar"),
        T("AUTOMATON", "Fold finite automaton law", "finite recognition processes", "finite states; complete input alphabet; source-bound transition relation; initial state; accepting class; complete run trace", "Does not yet assert equivalence with every other model or universality.", "finite automaton", "recognizer"),
        T("REWRITING", "Fold rewriting-system law", "held-position replacement", "generated word; exact pattern occurrence; retained rule identity; held replacement position; successor word; terminal, cyclic and branching trace classes", "Only registered finite rules and generated words are admitted.", "rewriting system", "term rewriting"),
        T("RECURSIVE-FUNCTION", "Fold recursion law", "structural finite recursion", "structural-One base; generated successor trace; exact step relation; retained intermediate values; composition interface; terminal result", "Closes recursion over every generated finite successor trace, not completed transfinite recursion.", "recursive function", "primitive recursion"),
        T("LAMBDA-CALCULUS", "Fold binding and self-application calculus law", "binding, substitution and reduction", "generated term grammar; held binder identity; free and bound occurrence ledgers; capture-safe substitution; exact reduction; normal or cyclic trace", "No conventional lambda calculus is assumed; the result is the generated Fold term kernel.", "lambda calculus", "substitution"),
        T("ABSTRACT-MACHINE", "Fold abstract-machine law", "finite executable machine descriptions", "description word; configuration carrier; transition kernel; generated store or tape; initial configuration; complete execution and halt trace", "Machines outside the frozen description grammar remain outside the theorem.", "abstract machine", "Turing machine"),
        T("CIRCUIT", "Fold circuit syntax and evaluation law", "finite connected local transformations", "generated nodes and wires; typed interfaces; local transformations; feed-forward order or declared cycle; exact evaluation trace; output support", "Resource size and depth comparisons are deferred to Complexity.", "circuit", "Boolean circuit"),
        T("OPERATIONAL-PROCESS", "Fold operational-process law", "execution and observable process behavior", "initial configuration; enabled transitions; retained choices; complete path trace; terminal, failed and cyclic classes; observation record", "Does not import process algebra or distributed timing.", "operational process", "labelled transition system"),
        T("COMPOSITION", "Fold process composition and decomposition law", "serial and parallel process assembly", "exact input and output interfaces; serial matching; independent parallel support; retained component identities; reconstruction witness; failure on mismatch", "Concurrency laws requiring communication or shared causality remain downstream.", "composition", "decomposition"),
        T("MODEL-EQUIVALENCE", "Fold computational-model equivalence law", "bidirectional execution-preserving translations", "complete source descriptions; total encoding; target descriptions; step or trace simulation; result preservation; reverse reconstruction; overhead ledger", "Equivalence applies only to the two registered generated model grammars.", "model equivalence", "simulation"),
        T("UNIVERSALITY", "Fold universal-computation law", "interpretation of generated machine descriptions", "complete frozen description grammar; encoded machine and input; one interpreter process; exact simulated trace; preserved terminal result; explicit resource overhead", "Universality is exact for every description generated by the frozen grammar, not an unbounded completed totality.", "universal computation", "universal machine"),
    ),
    "computability": (
        T("RECOGNITION-DECISION", "Fold recognition and decision law", "acceptance, rejection and continued execution", "generated input domain; partial recognizer traces; total decider traces; accepting and rejecting labels; explicit unresolved continuation; exact domain ledger", "A recognizer need not terminate on every generated input; a decider must.", "recognizability", "decidability"),
        T("HALTING", "Fold halting boundary law", "terminal-state determination", "encoded process and input; complete execution trace when available; terminal witness; self-description support; held complement action; contradiction certificate for total internal prediction", "Does not decide halting for all generated universal-machine descriptions.", "halting problem", "diagonalization"),
        T("ENUMERATION", "Fold effective-enumeration law", "generated description ordering", "complete finite description support at each depth; canonical position labels; no duplicates; successor extension; recognizer linkage; reconstruction from position", "No completed infinite enumeration is installed as an object.", "enumerability", "effective enumeration"),
        T("REDUCTION", "Fold computability-reduction law", "problem translation preserving answers", "source domain; total encoding; target domain; target procedure; answer decoder; bidirectional correctness trace; composition law", "Reduction claims require explicit encoders, decoders and generated domains.", "many-one reduction", "computability reduction"),
        T("DEGREES", "Fold degrees-of-computability law", "relative reduction classes", "registered problems; mutual reduction relation; equivalence classes; strict one-way reachability; transitive closure; incomparability witness", "Degrees are finite generated relation classes; no completed transfinite hierarchy is claimed.", "Turing degree", "relative computability"),
        T("UNIVERSAL-MACHINE", "Fold universal-machine execution law", "one machine executing encoded machines", "frozen machine grammar; prefix-free exact descriptions; encoded input; interpreter transition kernel; trace correspondence; halt and output preservation", "Extends Formal Universality into recognizability boundaries but not an omniscient halting oracle.", "universal machine", "interpreter"),
        T("UNDECIDABILITY", "Fold undecidable-problem law", "failure of total internal decision", "generated self-descriptions; assumed total decider; exact diagonal constructor; complementary verdict; self-application; contradiction trace", "The theorem applies where the registered language supports the exact self-encoding and complement operation.", "undecidability", "diagonal argument"),
        T("INCOMPLETENESS", "Fold incompleteness-boundary law", "internal proof and self-verification limits", "effective proof enumeration; consistency-preserving verifier; self-referential description; missing decision class; external trace record; no truth oracle", "This is a computational proof-system boundary, not an imported arithmetic incompleteness axiom.", "incompleteness", "self-reference"),
        T("RELATIVE-ORACLE", "Fold relative and oracle-computation law", "explicit external answer interfaces", "base process; named query alphabet; declared oracle relation; query and answer trace; relative recognition; oracle-identity ledger; nesting boundary", "An oracle is a registered interface, never unexplained computational power.", "oracle machine", "relative computation"),
        T("HYPERCOMPUTATION-LIMIT", "Fold hypercomputation admissibility-limit law", "claims exceeding generated universal computation", "claimed input domain; operational transition law; finite evidence boundary; self-reference test; resource and oracle disclosures; falsification condition", "No hypercomputation claim is admitted without a generated executable law and depth-independent certificate; finite demonstrations remain conditional.", "hypercomputation", "computational limit"),
    ),
    "complexity": (
        T("INPUT-SIZE", "Fold input and problem-size law", "exact generated input extent", "canonical input encoding; complete occupied positions; structural size trace; representation invariance ledger; instance and family boundaries", "Size is representation-relative unless an exact encoding correspondence is supplied.", "input size", "problem size"),
        T("TIME-SPACE", "Fold time and space resource law", "transition and retained-state resources", "complete execution transitions; live configuration support; retained history; peak support class; terminal trace; reversible record boundary", "Counts are exact host reports over generated traces, not foundational magnitudes.", "time complexity", "space complexity"),
        T("CIRCUIT-RESOURCE", "Fold circuit size and depth law", "circuit structural resources", "generated gates; wires; dependency order; longest causal layer trace; output support; shared-subcircuit identity", "Closes resource accounting, not arbitrary lower bounds.", "circuit size", "circuit depth"),
        T("COMMUNICATION-QUERY", "Fold communication and query complexity law", "cross-interface and information-request resources", "distributed input support; sent records; received records; named query interface; answer trace; retained local knowledge; result certificate", "The exact protocol and oracle identity must be registered.", "communication complexity", "query complexity"),
        T("RANDOMNESS", "Fold randomness-resource law", "scheduled unresolved branch support", "complete branch schedule; deterministic source process; held branch labels; execution per branch; output partition; schedule-description cost", "Randomness is not a causal premise; results quantify complete registered branch support or an explicitly measured external source.", "randomized complexity", "random bits"),
        T("REVERSIBILITY-COST", "Fold reversibility-cost law", "information retained for inverse execution", "source configurations; transition fibres; merged-predecessor ledger; retained predecessor labels; inverse trace; erasure boundary", "This is the classical cost law; the universal reversible model belongs to the later quantum branch.", "reversible computation", "Landauer cost"),
        T("PARALLEL", "Fold parallel-complexity law", "independent and causally layered work", "task dependency graph; independent ready sets; layer schedule; work trace; span trace; synchronization rows; result reconstruction", "No physical processor count or timing constant is imported.", "parallel complexity", "work and span"),
        T("BOUNDS", "Fold lower- and upper-bound law", "resource comparison certificates", "problem family; registered model; resource measure; constructive algorithm trace; adversarial indistinguishability family; lower witness; upper witness", "Arbitrary asymptotic lower bounds remain separate claims requiring their own generated families.", "lower bound", "upper bound"),
        T("REDUCTION-COMPLETENESS", "Fold reduction and completeness law", "resource-preserving problem translations", "problem class inventory; complete source encodings; total reductions; answer preservation; resource-overhead ledger; hard and member certificates", "Completeness is relative to the frozen problem class and resource law.", "complexity reduction", "complete problem"),
        T("AVERAGE-WORST", "Fold average- and worst-case law", "complete instance-family resource profiles", "generated instance support; exact resource per instance; greatest-resource class; exact positive support parts; distribution provenance; aggregate ledger", "Average claims require a complete exact support relation or registered empirical distribution.", "average-case complexity", "worst-case complexity"),
        T("APPROXIMATION", "Fold approximation-complexity law", "resource versus retained objective distinction", "optimization domain; exact optimum class; candidate output; exact objective comparison; approximation ledger; resource trace; failure boundary", "No unregistered metric or irrational ratio is admitted.", "approximation complexity", "approximation ratio"),
        T("PARAMETERIZED", "Fold parameterized-complexity law", "resource stratification by exact structural coordinates", "input support; named structural parameter; parameter extraction proof; family partition; resource profiles; reduction preservation", "Parameters must be forced structural coordinates, never fitted constants.", "parameterized complexity", "fixed-parameter tractability"),
        T("DESCRIPTIVE", "Fold information and descriptive-complexity law", "shortest exact generated descriptions", "frozen description grammar; complete descriptions through a declared depth; decoding relation; object reconstruction; minimal-description class; invariance ledger", "Unrestricted shortest-description values remain uncomputable; finite censuses state their depth explicitly.", "Kolmogorov complexity", "descriptive complexity"),
    ),
    "algorithms": (
        T("SEARCH-ORDER", "Fold searching and ordering law", "location and exact order construction", "generated carrier; exact equality; comparison relation; search trace; ordering invariant; retained duplicate classes; terminal certificate", "Only registered finite carriers and comparison relations are covered.", "search", "sorting"),
        T("ARITHMETIC", "Fold exact arithmetic-algorithm law", "computation over exact positive parts", "canonical arithmetic inputs; structural operations; intermediate exact parts; normalization; termination trace; result reconstruction", "No floating, negative, irrational or imaginary proof value is admitted.", "arithmetic algorithm", "exact arithmetic"),
        T("STRINGS-SEQUENCES", "Fold string and sequence algorithm law", "finite ordered symbol organizations", "complete positions; held symbols; substring or subsequence relation; scan trace; match ledger; reconstruction witness", "No ungenerated infinite stream is treated as complete.", "string algorithm", "sequence algorithm"),
        T("TREES-GRAPHS", "Fold tree and graph algorithm law", "finite relational traversal and structure", "generated vertices and edges; root or start identity; frontier support; visited ledger; path or component witness; termination", "Applies to finite generated graphs; physical networks require empirical translation.", "graph algorithm", "tree algorithm"),
        T("ALGEBRAIC-GEOMETRIC", "Fold algebraic and geometric algorithm law", "finite algebraic operations and incidence", "exact carrier; closed operation tables or incidence relations; canonical coordinates; transformation trace; invariant ledger; result certificate", "Geometry remains finite and exact; no ungenerated continuum is imported.", "algebraic algorithm", "computational geometry"),
        T("DYNAMIC-PROGRAMMING", "Fold dynamic-programming law", "reuse of exact overlapping subproblem results", "problem decomposition graph; dependency order; subproblem identities; retained result table; composition recurrence; final reconstruction", "The decomposition and optimal-substructure conditions must be proved for each problem.", "dynamic programming", "memoization"),
        T("OPTIMIZATION", "Fold optimization-algorithm law", "selection of all exact optima", "complete feasible support; exact comparison relation; candidate traversal; incumbent equivalence class; dominance eliminations; optimum certificate", "Does not assume differentiability, convexity or a conventional metric.", "optimization algorithm", "exact optimum"),
        T("RANDOMIZED", "Fold randomized-algorithm law", "complete scheduled branch execution", "deterministic algorithm kernel; registered schedule support; one trace per schedule; output partition; success support part; resource ledger", "Superdeterminism is preserved: apparent random choice is an unresolved or externally measured schedule, not an uncaused event.", "randomized algorithm", "probabilistic algorithm"),
        T("PARALLEL", "Fold parallel-algorithm law", "causally independent algorithm steps", "dependency graph; ready-set layers; local invariants; synchronization rows; combined trace; output reconstruction; work and span ledgers", "No physical speedup is claimed without an implementation experiment.", "parallel algorithm", "parallel schedule"),
        T("DISTRIBUTED", "Fold distributed-algorithm law", "local processes exchanging exact records", "process identities; local states; message alphabet; send and receive rows; causal trace; fault boundary; global result reconstruction", "System implementation and physical network claims are outside this formal theorem.", "distributed algorithm", "message passing"),
        T("ONLINE-STREAMING", "Fold online and streaming algorithm law", "prefix-bounded processing", "generated input prefixes; retained state summary; update relation; output after each prefix; lost-distinction ledger; memory trace", "A completed infinite stream is not admitted; every result names its generated prefix boundary.", "online algorithm", "streaming algorithm"),
        T("NUMERICAL", "Fold numerical-algorithm law", "exactly bounded approximation procedures", "exact input parts; finite discretization; update trace; orientation-labelled error; stability witness; convergence certificate; output interval", "Decimal or floating results are measured/implementation records and cannot establish the proof.", "numerical algorithm", "numerical analysis"),
        T("SYMBOLIC", "Fold symbolic-computation law", "canonical expression transformation", "generated syntax tree; exact rewrite rules; held occurrence identity; normalization trace; equivalence proof; reconstructed expression", "Only expressions within the frozen grammar are closed.", "symbolic computation", "computer algebra"),
        T("APPROXIMATE", "Fold approximation-algorithm law", "bounded resource solution with exact error ledger", "feasible support; exact objective relation; approximate candidate; retained and lost objective distinctions; bound certificate; resource trace", "No imported norm, epsilon parameter or irrational threshold is permitted.", "approximation algorithm", "error bound"),
    ),
    "semantics": (
        T("SYNTAX", "Fold program-syntax law", "generated program forms", "complete token alphabet; formation productions; syntax trees; held constructor identities; membership derivation; malformed rejection", "Syntax alone assigns no execution meaning.", "abstract syntax", "program grammar"),
        T("BINDING-SUBSTITUTION", "Fold binding and substitution law", "name identity and replacement", "held binder identities; free and bound occurrence ledgers; scope relation; fresh-name construction; capture-safe substitution; reconstruction", "No presentation alias may replace canonical binding identity.", "binding", "substitution"),
        T("EVALUATION", "Fold evaluation law", "program-state execution", "syntax tree; exact environment; evaluation relation; intermediate configurations; terminal value or failure; complete trace", "Only exact positive parts and generated data forms are semantic values.", "evaluation", "interpreter"),
        T("OPERATIONAL-DENOTATIONAL", "Fold operational and denotational correspondence law", "trace-to-meaning agreement", "operational traces; compositional meaning records; syntax constructors; result map; soundness direction; adequacy direction; counterexample boundary", "Correspondence is proved only for the frozen language grammar.", "operational semantics", "denotational semantics"),
        T("TYPE", "Fold type-theory law", "structural admissibility of composition", "generated type forms; term forms; typing relation; exact interfaces; substitution preservation; evaluation preservation; rejected mismatch traces", "No conventional type calculus is assumed beyond downstream comparison.", "type theory", "type safety"),
        T("PROGRAM-EQUIVALENCE", "Fold program-equivalence law", "indistinguishable generated behavior", "two program descriptions; common input support; complete traces; observation relation; retained/closed distinctions; equivalence certificate", "Equivalence is relative to the registered observation and input boundary.", "program equivalence", "observational equivalence"),
        T("TERMINATION", "Fold termination law", "absence of continuing execution paths", "program and input support; transition relation; well-founded generated descent witness; complete traces; terminal coverage; cycle counterexample", "No total termination decider is claimed for the universal language.", "termination", "well-foundedness"),
        T("CORRECTNESS", "Fold program-correctness law", "agreement between execution and specification", "precondition support; program traces; postcondition relation; total or partial termination declaration; failure rows; proof certificate", "Correctness is conditional on the exact registered specification and input support.", "program correctness", "Hoare logic"),
        T("SPECIFICATION", "Fold formal-specification law", "exact admissible behavior descriptions", "input and output carriers; relation of allowed rows; invariant support; liveness or terminal obligations; refinement boundary; falsification rows", "A prose intention cannot substitute for the generated specification relation.", "formal specification", "refinement"),
        T("TRANSFORMATION", "Fold program-transformation law", "semantics-preserving program rewriting", "source syntax; transformation rules; target syntax; step trace; semantic correspondence; resource ledger; inverse or loss record", "Optimization claims require separate resource evidence.", "program transformation", "refactoring"),
        T("COMPILATION", "Fold semantics-preserving compilation law", "translation between executable languages", "source and target grammars; total compiler relation; source evaluation; target evaluation; result correspondence; failure rejection; overhead ledger", "Applies only to the two frozen language grammars and declared runtime interface.", "compiler correctness", "compilation"),
        T("VERIFICATION", "Fold verification and proof-system law", "machine-checkable program evidence", "specification; proof-object grammar; proof checker; source binding; program identity; correctness conclusion; tamper controls", "A passing test suite is not substituted for a proof over the complete declared boundary.", "program verification", "proof system"),
    ),
    "distributed_computation": (
        T("CONCURRENCY", "Fold concurrency law", "multiple enabled process transitions", "process identities; local states; enabled actions; interleaving or independent-step support; complete schedules; observation traces", "Concurrency is structural coexistence, not physical simultaneity.", "concurrency", "interleaving"),
        T("CAUSALITY", "Fold computational-causality law", "event predecessor structure", "generated events; process order; message edges; transitive closure; acyclicity; concurrent incomparability; retained provenance", "Physical causal claims require a later empirical branch.", "causality", "happens-before"),
        T("SYNCHRONIZATION", "Fold synchronization law", "jointly enabled process transitions", "participant identities; readiness states; rendezvous label; joint transition; blocked rows; causal trace; release state", "No timing or lock implementation is assumed.", "synchronization", "rendezvous"),
        T("COMMUNICATION", "Fold communication law", "exact record transfer", "sender and receiver; message identity; send event; channel row; receive event; retained/lost distinctions; delivery trace", "Reliability, ordering and delay are separate declared channel properties.", "communication", "message passing"),
        T("PARTIAL-ORDER", "Fold distributed partial-order law", "causal event ordering", "event carrier; reflexive identity ledger; antisymmetric strict precedence; transitive closure; incomparable pairs; linear-extension support", "A total global order is not assumed where events are incomparable.", "partial order", "event structure"),
        T("CONSENSUS", "Fold consensus law", "terminal common decision", "process inputs; proposal validity; message traces; decision states; agreement relation; termination declaration; fault boundary", "Every consensus claim must name its communication and fault model.", "consensus", "agreement"),
        T("AGREEMENT-IMPOSSIBILITY", "Fold agreement-impossibility law", "indistinguishable predecessor limits", "two executions; identical local observation; different required decisions; unrecorded predecessor distinction; scheduler support; contradiction witness", "Impossibility is relative to the exact asynchronous/fault grammar and does not transfer silently.", "consensus impossibility", "indistinguishability proof"),
        T("REPLICATION-CONSISTENCY", "Fold replication and consistency law", "multiple retained state copies", "replica identities; update events; propagation relation; conflict classes; consistency observation; convergence trace; lost-order ledger", "No implementation platform or wall-clock consistency is imported.", "replication", "consistency model"),
        T("FAULT-MODEL", "Fold computational fault-model law", "declared deviations from process rules", "nominal transition relation; generated fault actions; affected components; detection observations; recovery relation; uncorrectable boundary", "Faults not generated by the model remain outside the guarantee.", "fault model", "fault tolerance"),
        T("DISTRIBUTED-KNOWLEDGE", "Fold distributed-knowledge law", "information available to local processes", "global execution support; local observation maps; indistinguishability classes; individual knowledge ledgers; common-knowledge iteration; decision boundary", "Knowledge is observation-relative exact support, not an imported modal axiom.", "distributed knowledge", "epistemic logic"),
        T("LOCALITY", "Fold locality law", "bounded dependency neighborhoods", "network graph; process neighborhood; local inputs; communication radius trace; locally indistinguishable instances; output constraint; lower witness", "Locality is relative to the registered network and round relation.", "local computation", "distributed locality"),
        T("NETWORK-COMPUTATION", "Fold network-computation law", "computation over generated communication graphs", "network carrier; local machines; link channels; schedule support; message traces; aggregate result; resource and fault ledgers", "Operating systems, cloud platforms and physical networks are validation domains only.", "network algorithm", "distributed network"),
    ),
    "cryptography_security": (
        T("ONE-WAYNESS", "Fold one-wayness law", "forward computation versus inverse search", "finite source support; total forward map; image fibres; adversary process grammar; resource bound; exhaustive success ledger", "Unbounded finite inversion is not impossible; one-wayness is always resource-relative.", "one-way function", "inversion hardness"),
        T("SECRECY", "Fold secrecy law", "observation-relative message indistinguishability", "message support; key or transformation support; ciphertext relation; adversary observation; closed message distinctions; disclosure boundary", "Security requires exact adversary, resource and support definitions.", "secrecy", "confidentiality"),
        T("INTEGRITY", "Fold integrity law", "detection of unauthorized record change", "message identity; protected record; allowed transformations; adversarial changes; verification relation; accepted and rejected traces", "Integrity does not imply secrecy or authorship.", "integrity", "tamper detection"),
        T("AUTHENTICATION", "Fold authentication law", "source-identity verification", "principal identities; credential support; challenge records; response relation; verifier trace; impersonation support; acceptance boundary", "Identity claims are only as strong as the registered credential and adversary model.", "authentication", "challenge-response"),
        T("HASHING", "Fold hashing law", "fixed-interface many-to-one record mapping", "message support; deterministic map; complete output support; collision fibres; preimage ledger; composition and domain separation", "Collision resistance is resource-relative; collisions in finite larger domains are retained, not denied.", "hash function", "collision resistance"),
        T("COMMITMENT", "Fold commitment law", "binding and hiding record phases", "message support; opening support; commit relation; verification relation; hiding observation classes; binding collision ledger; phase trace", "Perfect hiding and perfect binding claims require compatible exact supports and may be mutually limited.", "commitment scheme", "binding and hiding"),
        T("SIGNATURE", "Fold signature law", "publicly checkable source authorization", "message support; signing relation; verification relation; key identities; accepted signatures; forgery adversary support; correctness trace", "No number-theoretic hardness assumption is imported; any computational claim states its resource boundary.", "digital signature", "unforgeability"),
        T("PROOF-KNOWLEDGE", "Fold proof-of-knowledge law", "extractable witness-bearing interaction", "statement support; witness relation; prover and verifier processes; transcript support; acceptance; extractor relation; adversary boundary", "Knowledge means existence of an exact extraction relation in the registered grammar.", "proof of knowledge", "witness extraction"),
        T("ZERO-KNOWLEDGE", "Fold zero-knowledge law", "verification without additional witness distinction", "statement and witness supports; real transcripts; simulator process; observation relation; acceptance correctness; retained/closed information ledger", "Zero knowledge is relative to the registered verifier observation and simulator support.", "zero-knowledge proof", "simulation"),
        T("MULTIPARTY", "Fold multiparty-computation law", "joint function evaluation with local privacy", "party identities; private inputs; communication process; joint output relation; local views; simulation or leakage ledger; fault boundary", "Security requires an explicit corruption and communication model.", "secure multiparty computation", "MPC"),
        T("ADVERSARIAL", "Fold adversarial-computation law", "computation against generated hostile strategies", "system process; adversary grammar; resources; interaction schedules; security property; complete favorable and unfavorable rows; stopping rule", "An undefined adversary cannot support a security theorem.", "adversary model", "security game"),
        T("SECURITY-DEFINITION", "Fold information-theoretic and computational-security law", "exact separation of unconditional and resource-bounded security", "secret support; observation classes; adversary support; resource law; exact success parts; perfect and bounded cases; reduction certificate", "Information-theoretic and computational claims must never be conflated.", "information-theoretic security", "computational security"),
        T("POST-QUANTUM-BOUNDARY", "Fold post-quantum security-boundary law", "classical claims under an enlarged adversary interface", "classical scheme; declared quantum-capable oracle interface; query and resource ledger; reduction dependencies; failure boundary; migration correspondence", "No quantum operation is derived here; operational quantum adversaries wait for the Quantum Computation branch.", "post-quantum cryptography", "quantum adversary"),
    ),
    "learning_intelligence": (
        T("INFERENCE", "Fold inference law", "selection among generated hypotheses", "hypothesis support; evidence rows; compatibility relation; retained candidates; eliminated candidates; proof trace; uncertainty ledger", "Inference cannot import a prior distribution or pretrained weight.", "inference", "hypothesis selection"),
        T("CLASSIFICATION-PREDICTION", "Fold classification and prediction law", "sealed mapping from inputs to held labels", "input support; label support; hypothesis relation; training rows; sealed rule; target-custody boundary; prediction and falsification records", "Natural-data performance requires the separate empirical constitution.", "classification", "prediction"),
        T("REPRESENTATION", "Fold representation-learning boundary law", "generated encodings preserving declared distinctions", "source forms; representation grammar; encoding relation; decoding or task relation; retained and closed distinctions; complexity ledger", "No opaque learned representation is admitted as a law without an exact transformation trace.", "representation learning", "feature representation"),
        T("GENERALIZATION", "Fold generalization law", "extension from registered evidence to generated unseen support", "hypothesis class; development rows; withheld support; structural invariance certificate; sealed predictor; complete target rows; failure condition", "Generalization is empirical unless a structural successor proof exhausts the target family.", "generalization", "out-of-sample prediction"),
        T("SAMPLE-COMPLEXITY", "Fold sample-complexity law", "evidence support required to close hypothesis distinctions", "hypothesis support; possible examples; distinction pairs; selected sample; retained ambiguity; complete teaching or witness set; resource ledger", "No asymptotic formula is imported; each family requires a generated certificate.", "sample complexity", "teaching dimension"),
        T("LEARNING-OPTIMIZATION", "Fold optimization-in-learning law", "exact objective selection over hypotheses", "hypothesis support; exact objective relation; evidence rows; complete search or certified elimination; tied optimum class; update trace", "Gradient, differentiability and fitted parameter spaces are not assumed.", "learning optimization", "empirical risk"),
        T("INDUCTION", "Fold computational-induction law", "rule construction from finite evidence", "observation rows; candidate rule grammar; consistency relation; minimality; successor test; retained alternatives; falsification boundary", "Finite agreement alone never proves unrestricted continuation.", "induction", "rule learning"),
        T("SEARCH-PLANNING", "Fold search and planning law", "action-sequence construction toward exact goals", "state carrier; action transitions; initial state; goal class; path support; plan selection; failure and resource ledgers", "Only the generated environment model is covered.", "planning", "state-space search"),
        T("REINFORCEMENT", "Fold reinforcement-computation law", "policy evaluation through generated interaction traces", "states; actions; deterministic or scheduled transitions; exact outcome labels; policy support; complete trajectory ledger; policy comparison", "No stochastic cause, fitted value function or external reward scale is imported.", "reinforcement learning", "policy"),
        T("MULTIAGENT", "Fold multi-agent computation law", "interacting adaptive processes", "agent identities; local observations; action supports; joint transition relation; communication; outcome classes; equilibrium or cycle ledger", "Game-theoretic correspondence is downstream and requires exact preference relations.", "multi-agent systems", "agent interaction"),
        T("ADAPTATION", "Fold adaptation law", "trace-bound change of computational rules or state", "initial process; observation history; admissible update grammar; retained rule identity; update trace; performance relation; rollback or failure boundary", "Adaptation cannot silently alter the constitutional engine or claim law.", "adaptation", "online learning"),
        T("LEARNING-LIMITS", "Fold computational limits-of-learning law", "indistinguishable evidence and unidentifiable hypotheses", "hypothesis pair; identical observed rows; different unobserved requirements; learner process; forced same decision; counterexample support", "Limits are relative to the exact evidence, hypothesis and target grammars.", "no-free-lunch", "identifiability"),
        T("INTERPRETABILITY-VERIFICATION", "Fold interpretability and verification law", "traceable relation from inputs to decisions", "model description; exact execution trace; premise ledger; decision certificate; counterfactual support; verifier process; tamper controls", "A narrative explanation or score cannot replace the exact trace.", "interpretability", "model verification"),
        T("CLASSICAL-LEARNING", "Fold classical-learning model law", "complete classical finite learning processes", "examples; hypotheses; inference or update process; exact support parts; sealed evaluation; resource ledger; reproducible result", "Quantum learning operations remain entirely outside this branch.", "classical learning", "machine learning theory"),
    ),
    "scientific_computation": (
        T("EXACT-APPROXIMATE", "Fold exact and approximate calculation law", "separation of proof values and bounded approximations", "exact reference forms; approximation forms; orientation-labelled difference; retained precision provenance; output interval; reconstruction boundary", "Approximate values cannot flow backward to select an exact law.", "exact computation", "approximate computation"),
        T("STABILITY", "Fold numerical-stability law", "output distinction under input or operation perturbation", "exact input support; registered perturbations; algorithm traces; exact output differences; amplification relation; stable and unstable classes", "No floating epsilon or norm is imported without derivation.", "numerical stability", "conditioning"),
        T("ERROR-PROPAGATION", "Fold error-propagation law", "transport of exact approximation distinctions", "local error ledgers; dependency graph; orientation labels; composition rules; accumulated bound; cancellation/merging provenance; terminal ledger", "Signed arithmetic is represented by held orientation labels, not negative proof values.", "error propagation", "uncertainty propagation"),
        T("DISCRETIZATION", "Fold discretization law", "finite generated representation of a declared model", "source relation; generated cells; coverage map; retained and closed distinctions; local operators; refinement successor; boundary ledger", "An ungenerated continuum is never the derivational premise.", "discretization", "mesh"),
        T("CONVERGENCE", "Fold convergence-certificate law", "successor refinement preserving and closing error distinctions", "refinement trace; exact outputs; comparison relation; nested error classes; structural base; successor descent; target boundary", "Closure is depth-independent only when the successor certificate proves the registered descent property.", "convergence", "convergence proof"),
        T("SYMBOLIC", "Fold scientific symbolic-computation law", "exact model-expression transformation", "model syntax; exact rewrite rules; dimensional or type interfaces; normalization; identity proof; evaluator correspondence; result trace", "Physical interpretation remains outside formal symbolic closure.", "symbolic scientific computing", "computer algebra"),
        T("SIMULATION", "Fold simulation law", "execution of a registered model relation", "model state carrier; transition law; initial support; schedule; complete trace; observation map; comparison boundary", "A simulation validates consequences of its model; it cannot establish the model as a natural law.", "simulation", "computational model"),
        T("COMPUTATIONAL-DYNAMICS", "Fold computational-dynamics law", "iterated exact finite state transformation", "state support; update relation; successor time labels; orbit traces; terminal and cycle classes; invariant ledger; perturbation support", "Physical time and continuous dynamics require later empirical correspondence.", "computational dynamics", "dynamical simulation"),
        T("INVERSE-PROBLEM", "Fold inverse-problem law", "reconstruction of sources from observations", "source support; forward relation; observation; predecessor fibres; identifiable and ambiguous classes; retained prior exclusions; reconstruction certificate", "No fitted regularizer or prior may select among unresolved fibres unless separately registered.", "inverse problem", "identifiability"),
        T("COMPUTATIONAL-STATISTICS", "Fold computational-statistics law", "exact support summaries and inference algorithms", "complete sample support; exact count relations; statistic map; fibres; algorithm trace; uncertainty ledger; empirical boundary", "Probability remains deterministic-support bookkeeping unless an external distribution is measured.", "computational statistics", "statistical computing"),
        T("HIGH-DIMENSIONAL", "Fold high-dimensional computation law", "product-support computation with retained coordinate structure", "generated coordinate carriers; complete product support; sparse or factored relation; algorithm trace; resource ledger; lost-interaction boundary", "Dimension is a generated coordinate trace, not a completed infinite vector space.", "high-dimensional computing", "curse of dimensionality"),
        T("MANY-BODY", "Fold many-body computation law", "composed local forms and interaction support", "body identities; local states; interaction graph; joint support; update relation; factorization and correlation ledgers; resource boundary", "No physical many-body law or quantum amplitude is imported.", "many-body computation", "interaction system"),
        T("MATHEMATICAL-MODELLING", "Fold mathematical-modelling law", "explicit relation between formal structures and observations", "phenomenon disclosure; model grammar; derivation or constitutional provenance; parameter prohibition; sealed predictions; external measurements; falsification and revision records", "A successful fit or opaque prediction does not force the model law.", "mathematical modelling", "scientific model"),
    ),
}


EXPECTED_GROUP_COUNTS = {
    "formal_computation": 12,
    "computability": 10,
    "complexity": 13,
    "algorithms": 14,
    "semantics": 12,
    "distributed_computation": 12,
    "cryptography_security": 13,
    "learning_intelligence": 14,
    "scientific_computation": 13,
}


def validate_topic_inventory() -> None:
    if tuple(GROUP_TOPICS) != tuple(EXPECTED_GROUP_COUNTS):
        raise ValueError("classical-computation group order differs from the frozen inventory")
    for group, expected in EXPECTED_GROUP_COUNTS.items():
        topics = GROUP_TOPICS[group]
        if len(topics) != expected:
            raise ValueError(f"{group} must contain exactly {expected} obligations")
        slugs = tuple(topic.slug for topic in topics)
        if len(set(slugs)) != len(slugs):
            raise ValueError(f"{group} contains duplicate topic slugs")
        if any(not topic.components or not topic.limitations or not topic.correspondence for topic in topics):
            raise ValueError(f"{group} contains an incomplete topic declaration")


validate_topic_inventory()
