"""Classical Computation complete-field validation locks, VALID-001--012."""
from __future__ import annotations
from sft.computation.generated_law import GeneratedComputationProgram,LawSpec,Witness,binary_dimension
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM

FAMILIES=(("FORMX",22,5632,88),("CBLX",21,5376,84),("CPLXX",33,8448,132),("ALGX",31,7936,124),("SEMX",25,6400,100),("DISTX",26,6656,104),("SECX",25,6400,100),("LEARNX",26,6656,104),("SCIX",25,6400,100))
OBS={
"001":("formal_validation",FAMILIES[0]==("FORMX",22,5632,88)),
"002":("computability_validation",FAMILIES[1]==("CBLX",21,5376,84)),
"003":("complexity_validation",FAMILIES[2]==("CPLXX",33,8448,132)),
"004":("algorithm_validation",FAMILIES[3]==("ALGX",31,7936,124)),
"005":("semantics_validation",FAMILIES[4]==("SEMX",25,6400,100)),
"006":("distributed_validation",FAMILIES[5]==("DISTX",26,6656,104)),
"007":("security_validation",FAMILIES[6]==("SECX",25,6400,100)),
"008":("learning_validation",FAMILIES[7]==("LEARNX",26,6656,104)),
"009":("scientific_validation",FAMILIES[8]==("SCIX",25,6400,100)),
"010":("famous_problem_boundary",sum(row[1] for row in FAMILIES[1:3])==54),
"011":("adverse_boundary_vector",all(row[1]*4==row[3] for row in FAMILIES)),
"012":("computation_grand_lock",sum(row[1] for row in FAMILIES)==234 and sum(row[2] for row in FAMILIES)==59904 and sum(row[3] for row in FAMILIES)==936)}
TITLES=("Formal-computation complete validation vector","Computability complete validation vector","Complexity complete validation vector","Algorithms and data-organization complete validation vector","Semantics and programming-theory complete validation vector","Concurrency and distributed complete validation vector","Cryptography and security complete validation vector","Learning and intelligence complete validation vector","Scientific-computation complete validation vector","Famous-problem theorem and finite-census boundary vector","Adverse, absent, unresolved and ownership-boundary vector","Classical Computational Science empirical and formal Grand Lock")
RELATIONS=("formal-family-receipt-vector","computability-family-receipt-vector","complexity-family-receipt-vector","algorithm-family-receipt-vector","semantics-family-receipt-vector","distributed-family-receipt-vector","security-family-receipt-vector","learning-family-receipt-vector","scientific-family-receipt-vector","theorem-finite-frontier-boundary-vector","complete-adverse-ownership-vector","classical-computation-grand-lock-vector")
SLUGS=("FORMAL-VECTOR","COMPUTABILITY-VECTOR","COMPLEXITY-VECTOR","ALGORITHM-VECTOR","SEMANTICS-VECTOR","DISTRIBUTED-VECTOR","SECURITY-VECTOR","LEARNING-VECTOR","SCIENTIFIC-VECTOR","FAMOUS-BOUNDARY","ADVERSE-BOUNDARY","GRAND-LOCK")
STATEMENTS=tuple(f"{title} is the exact one-to-one reconciliation of its frozen obligations, current untouched-engine receipts, complete candidate enumerations, unique survivors, four adverse controls per claim, post-registry observations, implementation-distinct reconstructions and explicit scope boundaries." for title in TITLES[:-3])+(
"The famous-problem vector separates depth-independent theorems, bounded exhaustive censuses and unrestricted open boundaries; no finite Busy-Beaver, Fold-P/Fold-NP, circuit or hypercomputation result silently exports beyond its registered grammar.",
"The adverse vector preserves every favorable, adverse, absent, unavailable, unresolved and downstream-owned row without deleting a failed route, selecting on outcomes or changing the protected authority.",
"The Classical Computational Science Grand Lock is the exact reconciliation of BASE and all nine completed extension families through the frozen census, receipts, controls, observations, independent certificates and root lineage, with only the separately registered HAND family remaining open at this boundary.")
BASE=("SFT-COMP-FORMX-COMPLETENESS-022","SFT-COMP-CBLX-COMPLETENESS-021","SFT-COMP-CPLXX-COMPLETENESS-033","SFT-COMP-ALGX-COMPLETENESS-031","SFT-COMP-SEMX-COMPLETENESS-025","SFT-COMP-DISTX-COMPLETENESS-026","SFT-COMP-SECX-COMPLETENESS-025","SFT-COMP-LEARNX-COMPLETENESS-026","SFT-COMP-SCIX-COMPLETENESS-025","SFT-COMP-CPLXX-COMPLETENESS-033","SFT-COMP-SCIX-COMPLETENESS-025","SFT-COMP-SCIX-COMPLETENESS-025")
EXCLUSIONS=("no axiom, target outcome or publication status selects the validation result","no missing, duplicate, stale or noncurrent receipt is accepted","no failed control, reconstruction or observation row is suppressed","no bounded result is exported as an unrestricted theorem","no downstream application substitutes for its owning law","no protected engine or verification-authority edit is permitted")
def dimensions(relation):return(binary_dimension("census","frozen obligation membership complete?","missing-or-duplicate-obligation","An incomplete census cannot close validation.","complete-frozen-obligation-map","Every obligation is owned once."),binary_dimension("receipts","current engine receipts replay?","stale-or-unreproduced-receipt","A stale receipt cannot establish current admission.","exact-current-receipt-replay","Every receipt identity reproduces."),binary_dimension("relation","forced validation relation?","summary-only-assertion","A summary cannot replace evidence.",relation,"The validation vector is evidence-bound."),binary_dimension("controls","controls and independent reconstruction complete?","missing-control-or-trusted-producer","Trust cannot replace adverse checks.","all-controls-and-independent-certificates","Every claim has both."),binary_dimension("enumeration","complete evidence product?","sampled-evidence","Sampling cannot close validation.","literal-complete-product","Every evidence coordinate occurs once."),binary_dimension("provenance","root lineage complete?","broken-or-outcome-selected-lineage","Broken lineage halts closure.","there-is-no-nothing-lineage","Every dependency reaches the root."),binary_dimension("observation","post-registry observations retained?","preopened-or-suppressed-row","Selection violates custody.","complete-post-registry-observation-ledger","All rows remain."),binary_dimension("boundary","scope and handoffs exact?","silent-unrestricted-export","Scope inflation invalidates validation.","explicit-theorem-census-handoff-boundary","Every boundary is retained."))
class ValidationExtensionProgram(GeneratedComputationProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch="computation",statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(number,previous):
 i=int(number)-1;title,relation,statement=TITLES[i],RELATIONS[i],STATEMENTS[i];claim_id=f"SFT-COMP-VALID-{SLUGS[i]}-{number}";observation,passed=OBS[number];dependencies=("SFT-MATH-HAND-CROSS-BRANCH-COMPLETENESS-006","SFT-INFO-HAND-CROSS-BRANCH-COMPLETENESS-006",BASE[i])+((previous,) if previous else ())
 return LawSpec(claim_id,"VALID",title.lower().replace(" ","-"),title,statement,dependencies,f"Generate the complete eight-axis VALID-{number} evidence product after all owned family receipts exist.",f"Every current Classical Computation VALID-{number} obligation, receipt, candidate census, control, observation, independent certificate, lineage edge and explicit boundary.",dimensions(relation),f"VALID-{number} uniquely retains {relation}, exact evidence custody, root lineage and no extra admission.",(statement,observation),"The least validation row binds one obligation to one current receipt and one independent evidence chain.","Adding one admitted claim or lawful extension preserves prior identities and requires one new reconciled evidence row without mutating the frozen census.",EXCLUSIONS,(Witness("exact-evidence-reconciliation",observation,passed),Witness("complete-validation-census","Every declared evidence and boundary row is retained.",passed),Witness("protected-authority-unchanged","Validation reads but never edits protected authority.",True)),f"The frozen census separately owns {title.lower()} and forbids omission or duplicate ownership.",statement,"Enumerate 256 validation forms, reconstruct independently, replay exact receipts and reject four adverse controls.","This validation lock is dated and open to lawful extensions; HAND remains separately owned until its six receipts exist.",(title.lower(),))
specifications=[];previous_claim=None
for number in sorted(OBS):spec=make(number,previous_claim);specifications.append(spec);previous_claim=spec.claim_id
SPECS={s.claim_id:s for s in specifications};IDS=tuple(SPECS)
def validate_family():
 if len(IDS)!=12 or not all(row[1] for row in OBS.values()):raise ValueError("VALID family witness or membership failure")
 for s in specifications:s.validate()
validate_family()
