"""Frozen Layer-One obligations for Engineering Translation."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EngineeringObligation:
    claim_id: str
    title: str
    family: str
    carrier: str
    relation: str
    retained_record: str
    evidence_boundary: str
    statement: str
    falsification_condition: str


FAMILY_ORDER = (
    "requirements_function_boundary",
    "components_interfaces_architecture",
    "resources_efficiency_reliability",
    "measurement_calibration_acceptance",
    "alternatives_tradeoffs_optimization",
    "control_feedback_stability",
    "safety_hazard_resilience",
    "verification_validation_traceability",
    "cross_platform_accessibility",
    "lifecycle_maintenance_sustainability",
    "science_design_evidence_boundary",
    "ownership_anomaly_handoffs",
)


def row(suffix, title, family, carrier, relation, record, boundary, statement, falsification):
    return EngineeringObligation("SFT-ENG-" + suffix + "-001", title, family, carrier, relation, record, boundary, statement, falsification)


DATA = (
    ("REQUIREMENT", "Engineering requirement", "requirements_function_boundary", "stakeholder-need-purpose-context-carrier", "need-to-verifiable-condition-relation", "source-purpose-priority-version-conflict-and-acceptance-held", "requirement-scope-bounded", "A requirement is a source-custodied, purpose-bound and verifiable condition with conflicts, revisions and acceptance retained.", "Reject if an unstated preference or implementation detail is presented as a scientific or stakeholder requirement."),
    ("FUNCTION", "Required function", "requirements_function_boundary", "input-operation-output-purpose-carrier", "declared-transformation-relation", "inputs-outputs-state-loss-context-and-failure-held", "function-domain-bounded", "A function is a declared input-to-output transformation whose state, loss, context and failure modes remain explicit.", "Reject if a product label, component name or favorable output substitutes for the transformation."),
    ("CONSTRAINT", "Engineering constraint", "requirements_function_boundary", "design-variable-limit-source-carrier", "variable-to-admissible-region-relation", "source-units-tolerance-context-version-and-conflict-held", "constraint-authority-bounded", "A constraint is a source- and context-bound limit on generated designs, never an unexplained fitted preference.", "Reject if a convenient target or hidden parameter is introduced as a necessary limit."),
    ("OPERATING-BOUNDARY", "Operating boundary", "requirements_function_boundary", "system-environment-state-limit-carrier", "condition-to-valid-operation-relation", "conditions-duration-loads-transients-exceptions-and-failures-held", "declared-operation-envelope", "An operating boundary retains environment, loads, duration, transients, exceptions and observed failures.", "Reject if success inside one test envelope is universalized beyond its registered boundary."),
    ("USE-CASE", "Use and misuse case", "requirements_function_boundary", "actor-goal-system-context-carrier", "action-to-system-response-relation", "actors-preconditions-path-outcomes-misuse-and-harm-held", "use-context-bounded", "A use case retains actor, goal, preconditions, path and outcome; foreseeable misuse and harm remain co-registered.", "Reject if intended use erases observed or foreseeable misuse."),
    ("ACCEPTANCE-BOUNDARY", "Requirement acceptance boundary", "requirements_function_boundary", "requirement-test-evidence-decision-carrier", "condition-to-acceptance-relation", "criterion-method-result-uncertainty-failure-and-approver-held", "acceptance-protocol-bounded", "Acceptance requires a preregistered criterion, method, result, uncertainty and preserved failure record.", "Reject if the criterion changes after outcome or authority alone declares compliance."),
    ("COMPONENT", "Engineering component", "components_interfaces_architecture", "bounded-part-state-capability-carrier", "part-to-declared-function-relation", "identity-version-input-output-state-and-failure-held", "component-boundary-declared", "A component is a versioned bounded part with declared state, capability, interfaces and failures.", "Reject if a name or vendor identity substitutes for measured behavior."),
    ("INTERFACE", "Engineering interface", "components_interfaces_architecture", "component-pair-exchange-contract-carrier", "typed-transfer-and-coordination-relation", "endpoints-signals-units-timing-errors-and-version-held", "interface-contract-bounded", "An interface is a typed exchange contract retaining endpoints, units, timing, errors and version.", "Reject if physical contact or a call name proves compatible exchange."),
    ("ARCHITECTURE", "System architecture", "components_interfaces_architecture", "components-interfaces-allocation-carrier", "composition-and-dependency-relation", "parts-links-responsibilities-failures-versions-and-rationale-held", "architecture-scope-bounded", "Architecture is a versioned composition of components, interfaces and allocated responsibilities.", "Reject if a diagram omits dependency, failure propagation or unrepresented components."),
    ("SYSTEM", "Engineered system", "components_interfaces_architecture", "parts-relations-boundary-purpose-carrier", "joint-operation-relation", "parts-environment-state-resources-users-and-failures-held", "system-purpose-bounded", "An engineered system composes parts and relations around a declared purpose while retaining environment, users and failures.", "Reject if system-level success is inferred from isolated component success."),
    ("MODULARITY", "Modular decomposition", "components_interfaces_architecture", "system-partition-interface-carrier", "decomposition-recomposition-relation", "partition-contract-coupling-state-loss-and-tests-held", "decomposition-boundary-declared", "A modular decomposition is lawful only when interface contracts permit exact recomposition of required behavior.", "Reject if decomposition hides cross-module state or failure coupling."),
    ("INTEGRATION", "System integration", "components_interfaces_architecture", "components-build-sequence-system-carrier", "assembly-to-joint-behaviour-relation", "versions-order-interfaces-tests-failures-and-rollbacks-held", "integration-build-bounded", "Integration retains component versions, assembly order, interface tests, failures and rollback state.", "Reject if a final demonstration erases failed intermediate integrations."),
    ("RESOURCE", "Engineering resource", "resources_efficiency_reliability", "system-operation-resource-carrier", "operation-to-consumption-relation", "resource-stock-flow-units-time-loss-and-source-held", "resource-accounting-bounded", "Resource accounting retains stock, flow, units, time, loss and source for each operation.", "Reject if an uncounted external supply or hidden computational service is omitted."),
    ("CAPACITY", "Capacity and load", "resources_efficiency_reliability", "system-demand-capability-carrier", "load-to-service-relation", "demand-capacity-duration-queue-degradation-and-failure-held", "load-profile-bounded", "Capacity is a load-profile-bound relation retaining duration, queuing, degradation and failure.", "Reject if peak, average or one successful load is universalized."),
    ("EFFICIENCY", "Engineering efficiency", "resources_efficiency_reliability", "input-useful-output-loss-carrier", "accounted-output-to-input-relation", "boundary-input-output-loss-time-and-uncertainty-held", "efficiency-boundary-declared", "Efficiency compares useful output with all registered input and loss inside an explicit boundary.", "Reject efficiency above the closed resource account or omit externalized loss."),
    ("RELIABILITY", "Reliability", "resources_efficiency_reliability", "system-demand-time-population-carrier", "required-service-over-trials-relation", "units-demands-duration-failures-censoring-and-repair-held", "reliability-population-bounded", "Reliability is a demand-, duration- and population-bound record of successful and failed service.", "Reject if demonstrations omit failures, censored units or changed operating conditions."),
    ("AVAILABILITY", "Availability", "resources_efficiency_reliability", "system-service-time-state-carrier", "serviceable-time-relation", "uptime-downtime-cause-maintenance-demand-and-window-held", "availability-window-bounded", "Availability retains serviceable and unavailable intervals, causes, maintenance and demand windows.", "Reject if scheduled observation or missing monitoring becomes uptime."),
    ("FAILURE-MODE", "Failure mode", "resources_efficiency_reliability", "component-condition-transition-consequence-carrier", "condition-to-loss-of-function-relation", "cause-detection-state-effect-severity-and-recovery-held", "failure-definition-bounded", "A failure mode is an observed or generated loss-of-function path retaining cause, detectability, effect and recovery.", "Reject if absence of observed failure proves impossibility or all failures share one cause."),
    ("MEASUREMENT", "Engineering measurement", "measurement_calibration_acceptance", "measurand-instrument-method-record-carrier", "property-to-record-relation", "definition-unit-instrument-condition-uncertainty-and-custody-held", "measurement-procedure-bounded", "Engineering measurement retains measurand, unit, instrument, conditions, uncertainty and record custody.", "Reject if display output alone proves the measurand or uncertainty is erased."),
    ("CALIBRATION", "Calibration", "measurement_calibration_acceptance", "instrument-reference-condition-result-carrier", "reference-to-indication-comparison", "reference-traceability-range-condition-result-and-date-held", "calibration-range-bounded", "Calibration is a dated comparison to a traceable reference across a declared range and condition.", "Reject if adjustment, self-test or manufacturer status is called calibration without comparison."),
    ("TOLERANCE", "Tolerance", "measurement_calibration_acceptance", "target-allowed-region-measurement-carrier", "measurement-to-acceptance-region-relation", "nominal-bounds-unit-uncertainty-rationale-and-version-held", "tolerance-purpose-bounded", "A tolerance is a purpose- and uncertainty-bound allowed region registered before acceptance data.", "Reject if tolerance is widened after measurement or used as a fitted physical constant."),
    ("TEST", "Engineering test", "measurement_calibration_acceptance", "article-condition-procedure-observation-carrier", "stimulus-to-response-comparison", "article-version-setup-procedure-raw-data-failures-and-deviations-held", "test-protocol-bounded", "A test retains article version, setup, procedure, raw observations, deviations and unfavorable outcomes.", "Reject if a demonstration without a criterion or preserved raw record is called a passed test."),
    ("ACCEPTANCE-TEST", "Acceptance test", "measurement_calibration_acceptance", "requirement-test-result-decision-carrier", "registered-criterion-to-result-relation", "requirement-method-threshold-uncertainty-result-and-decision-held", "acceptance-test-bounded", "An acceptance test compares a frozen requirement and threshold to a source-custodied result.", "Reject if target identity, threshold or scoring rule changes after the result opens."),
    ("MEASUREMENT-UNCERTAINTY", "Measurement uncertainty", "measurement_calibration_acceptance", "result-source-variation-bound-carrier", "sources-to-declared-result-region-relation", "components-method-correlation-coverage-boundary-and-version-held", "uncertainty-model-bounded", "Measurement uncertainty retains declared sources, correlations, method, coverage and revision.", "Reject if uncertainty is omitted, tuned to force agreement or treated as proof error."),
    ("ALTERNATIVE", "Design alternative", "alternatives_tradeoffs_optimization", "requirement-generated-design-carrier", "design-to-evaluation-relation", "generator-assumptions-resources-results-failures-and-rejection-held", "alternative-grammar-bounded", "A design alternative must be generated from the frozen requirement grammar with every rejected option retained.", "Reject if only the preferred design is generated or alternatives are invented after outcome."),
    ("TRADEOFF", "Engineering trade-off", "alternatives_tradeoffs_optimization", "alternatives-criteria-context-carrier", "criteria-wise-comparison-relation", "criteria-units-evidence-conflicts-stakeholders-and-losses-held", "tradeoff-context-bounded", "A trade-off retains distinct criteria, evidence, conflicts, stakeholders and losses without collapsing them into a hidden scalar.", "Reject if an unexplained weight converts value judgment into an exact law."),
    ("OPTIMIZATION", "Bounded engineering optimization", "alternatives_tradeoffs_optimization", "finite-design-set-objective-constraint-carrier", "enumeration-to-admissible-optimum-relation", "designs-objective-constraints-ties-failures-and-boundary-held", "finite-search-bounded", "Engineering optimization enumerates a declared finite design set and preserves ties, failures and constraint violations.", "Reject if an ungenerated design space, fitted weight or opaque oracle selects the optimum."),
    ("MULTI-CRITERIA", "Multi-criteria decision record", "alternatives_tradeoffs_optimization", "alternatives-criteria-decision-maker-carrier", "evidence-and-value-to-decision-relation", "evidence-values-priorities-conflicts-dissent-and-version-held", "decision-context-bounded", "Multi-criteria choice keeps measured evidence separate from declared values, priorities and dissent.", "Reject if the decision is presented as a uniquely forced scientific truth."),
    ("ROBUST-DESIGN", "Robust design", "alternatives_tradeoffs_optimization", "design-condition-family-performance-carrier", "condition-variation-to-performance-relation", "conditions-uncertainties-failures-margins-and-boundary-held", "registered-variation-bounded", "A robust design retains performance across the preregistered condition family, including adverse corners.", "Reject if favorable nominal operation proves robustness."),
    ("DESIGN-FREEZE", "Design freeze and change control", "alternatives_tradeoffs_optimization", "design-version-baseline-change-carrier", "proposal-to-approved-version-relation", "baseline-rationale-review-impact-tests-and-rollback-held", "configuration-boundary-declared", "A design freeze is a versioned baseline whose later changes require explicit impact, retest and provenance.", "Reject silent changes, retroactive baselines or unchanged receipts after source modification."),
    ("CONTROL", "Control action", "control_feedback_stability", "system-state-target-actuator-carrier", "observed-state-to-bounded-action-relation", "target-state-measurement-action-limit-time-and-effect-held", "control-envelope-bounded", "Control maps an observed state to a bounded action with target, latency, limits and effects retained.", "Reject if an unobserved state, hidden controller or unlimited action is assumed."),
    ("FEEDBACK", "Feedback loop", "control_feedback_stability", "plant-sensor-controller-actuator-carrier", "output-record-to-next-action-relation", "components-delays-gains-bounds-noise-and-failures-held", "loop-configuration-bounded", "A feedback loop retains plant, sensor, controller, actuator, delay, bounds, noise and failure paths.", "Reject if correlation or repeated adjustment proves closed-loop feedback."),
    ("STABILITY", "Operational stability", "control_feedback_stability", "system-perturbation-bound-return-carrier", "perturbed-trajectory-to-operating-region-relation", "initial-state-disturbance-time-bound-overshoot-and-failure-held", "stability-region-bounded", "Stability is a finite operating-region claim retaining perturbation, return bound, overshoot and failures.", "Reject if one settled trace proves global or infinite-time stability."),
    ("OBSERVABILITY", "Engineering observability", "control_feedback_stability", "internal-state-output-history-carrier", "state-distinction-to-record-relation", "state-set-sensors-history-resolution-and-ambiguity-held", "observation-depth-bounded", "Observability requires declared output histories to distinguish the registered internal state set.", "Reject if an unheld predecessor is claimed recoverable from a merged output."),
    ("CONTROLLABILITY", "Engineering controllability", "control_feedback_stability", "initial-target-action-sequence-carrier", "bounded-input-to-state-transition-relation", "states-actions-limits-duration-path-and-failures-held", "reachable-set-bounded", "Controllability is reachability under declared actions, limits and duration with failed paths retained.", "Reject if an unreachable state is assumed or an unlimited actuator proves reachability."),
    ("FAULT-RESPONSE", "Fault detection and response", "control_feedback_stability", "system-fault-sensor-response-carrier", "fault-evidence-to-bounded-response-relation", "fault-detection-latency-action-state-recovery-and-misses-held", "fault-family-bounded", "Fault response retains detection, misses, latency, bounded action, residual state and recovery.", "Reject if no alarm proves no fault or response success erases missed detections."),
    ("HAZARD", "Engineering hazard", "safety_hazard_resilience", "source-condition-exposed-carrier", "hazard-to-harm-path-relation", "source-path-exposure-severity-likelihood-and-uncertainty-held", "hazard-scenario-bounded", "A hazard is a source-to-harm path retaining exposure, severity, likelihood and uncertainty.", "Reject if absence of prior harm proves safety or hazard is equated with realised harm."),
    ("RISK", "Engineering risk record", "safety_hazard_resilience", "hazard-population-consequence-carrier", "scenario-to-consequence-comparison", "scenarios-exposure-severity-frequency-uncertainty-and-values-held", "risk-model-bounded", "Risk retains scenario evidence, exposure, consequence, uncertainty and declared value judgments separately.", "Reject if one scalar hides population distribution or ethical choice."),
    ("SAFETY", "Safety case", "safety_hazard_resilience", "system-claim-argument-evidence-carrier", "evidence-to-bounded-safety-claim-relation", "claim-scope-hazards-controls-evidence-gaps-and-review-held", "safety-case-bounded", "A safety case is a scoped claim supported by traceable evidence, controls, gaps and review.", "Reject if compliance, past success or authority alone proves safety."),
    ("FAIL-SAFE", "Fail-safe operation", "safety_hazard_resilience", "system-fault-safe-state-carrier", "detected-or-bounded-fault-to-safe-transition-relation", "faults-detection-actions-safe-state-residual-harm-and-test-held", "declared-fault-set-bounded", "Fail-safe operation requires every declared fault to reach a tested bounded safe state or preserve a visible halt.", "Reject if an untested fault or silent continuation is called fail-safe."),
    ("RESILIENCE", "Engineering resilience", "safety_hazard_resilience", "system-disruption-service-recovery-carrier", "disruption-to-bounded-recovery-relation", "service-loss-adaptation-resources-time-residual-and-learning-held", "disruption-family-bounded", "Resilience retains service loss, adaptation resources, recovery time, residual degradation and failed recovery.", "Reject if survival alone proves full recovery or hidden external aid is omitted."),
    ("DEFENCE-IN-DEPTH", "Defence in depth", "safety_hazard_resilience", "hazard-barrier-chain-carrier", "independent-barrier-to-residual-path-relation", "barriers-dependencies-common-causes-bypasses-tests-and-failures-held", "threat-and-hazard-bounded", "Defence in depth requires separately testable barriers with dependencies, bypasses and common causes retained.", "Reject if repeated copies with one common failure are called independent layers."),
    ("VERIFICATION", "Engineering verification", "verification_validation_traceability", "artifact-specification-evidence-carrier", "artifact-to-specified-condition-comparison", "version-requirement-method-result-deviation-and-review-held", "verification-baseline-bounded", "Verification tests whether a versioned artifact satisfies its frozen specification.", "Reject if intended use, user approval or later performance substitutes for specification evidence."),
    ("VALIDATION", "Engineering validation", "verification_validation_traceability", "system-use-context-user-evidence-carrier", "implemented-system-to-intended-use-comparison", "users-context-tasks-results-harms-limitations-and-review-held", "validation-use-bounded", "Validation tests whether the verified system serves its declared use in its declared context.", "Reject if verification alone proves fitness for every user or deployment."),
    ("TRACEABILITY", "Bidirectional traceability", "verification_validation_traceability", "need-requirement-design-test-result-carrier", "bidirectional-evidence-chain-relation", "source-versions-links-changes-gaps-and-owners-held", "trace-baseline-bounded", "Traceability connects need, requirement, design, implementation, test and result in both directions.", "Reject if an orphan requirement, untested design element or unowned result is admitted."),
    ("REPRODUCIBILITY", "Engineering reproducibility", "verification_validation_traceability", "artifact-environment-procedure-result-carrier", "declared-rebuild-to-comparable-result-relation", "source-dependencies-platform-commands-outputs-failures-and-hashes-held", "reproduction-environment-bounded", "Reproducibility retains source, dependencies, environment, commands, outputs, failures and identities.", "Reject if a private environment, missing dependency or unreconstructible manual step is required."),
    ("INDEPENDENT-CHECK", "Implementation-distinct check", "verification_validation_traceability", "claim-first-implementation-second-implementation-carrier", "independent-reconstruction-comparison", "specifications-codepaths-results-disagreements-and-provenance-held", "independence-criterion-bounded", "An independent check reconstructs the result through a separately identified implementation path.", "Reject if the checker imports the first implementation’s survivor or output."),
    ("E2E", "End-to-end verification", "verification_validation_traceability", "source-input-complete-pipeline-output-carrier", "declared-entry-to-final-result-relation", "versions-stages-intermediates-failures-duration-and-receipts-held", "pipeline-boundary-declared", "End-to-end verification exercises the declared public entry through every stage to its final receipt.", "Reject if mocks, placeholders, skipped stages or hidden manual corrections stand in for the pipeline."),
    ("CROSS-PLATFORM", "Cross-platform behavior", "cross_platform_accessibility", "artifact-platform-environment-result-carrier", "same-specification-across-platforms-relation", "platform-version-dependencies-commands-results-and-differences-held", "declared-platform-matrix", "Cross-platform evidence preserves macOS, Windows and Linux environments, results and platform-specific differences.", "Reject if success on one operating system proves portability."),
    ("PORTABLE-DATA", "Portable data and record format", "cross_platform_accessibility", "record-format-reader-platform-carrier", "serialized-record-to-equivalent-reading-relation", "schema-encoding-version-units-errors-and-migrations-held", "format-version-bounded", "A portable record has an open schema, explicit encoding, version, units, errors and migration path.", "Reject if one proprietary application or unstated locale is required to interpret it."),
    ("ACCESSIBLE-INTERFACE", "Accessible human interface", "cross_platform_accessibility", "user-task-interface-context-carrier", "action-to-understandable-result-relation", "users-input-modes-output-modes-errors-guidance-and-testing-held", "user-and-task-bounded", "An accessible interface retains user diversity, input and output modes, errors, guidance and direct testing.", "Reject if developer usability or visual presentation alone proves accessibility."),
    ("LIGHTWEIGHT-DEPLOYMENT", "Lightweight deployment", "cross_platform_accessibility", "artifact-minimal-runtime-install-carrier", "declared-package-to-working-system-relation", "runtime-dependencies-size-permissions-network-and-failures-held", "installation-environment-bounded", "Lightweight deployment declares and minimizes runtime dependencies, permissions, downloads and infrastructure.", "Reject if Docker, a cloud service, administrator access or a hidden heavyweight dependency is silently required."),
    ("ONE-COMMAND", "One-command public verification", "cross_platform_accessibility", "repository-public-command-result-carrier", "single-entry-to-complete-verification-relation", "command-platform-stages-progress-duration-failures-and-receipt-held", "repository-version-bounded", "A single documented command reaches the complete verification route and reports progress, duration, failures and receipt.", "Reject if the command skips claims, mutates authority or needs undisclosed setup."),
    ("LEARNABLE-USE", "Learnable public operation", "cross_platform_accessibility", "new-user-task-guidance-feedback-carrier", "instruction-and-feedback-to-correct-use-relation", "audience-prerequisites-steps-errors-examples-and-tests-held", "declared-audience-bounded", "Learnable operation retains audience, prerequisites, progressive guidance, errors, examples and user tests.", "Reject if expert familiarity is treated as evidence that any person can use the system."),
    ("CONFIGURATION", "Configuration identity", "lifecycle_maintenance_sustainability", "artifact-version-dependency-environment-carrier", "configuration-to-reproduced-behaviour-relation", "source-dependencies-settings-platform-hashes-and-date-held", "configuration-baseline-bounded", "Configuration identity binds source, dependencies, settings, platform and hashes to a dated behavior.", "Reject if mutable latest versions or hidden settings preserve the same identity."),
    ("MAINTENANCE", "Maintenance action", "lifecycle_maintenance_sustainability", "system-condition-action-result-carrier", "observed-condition-to-restorative-action-relation", "condition-diagnosis-parts-action-tests-downtime-and-result-held", "maintenance-event-bounded", "Maintenance retains diagnosis, parts, action, test, downtime and resulting configuration.", "Reject if maintenance history or induced failures are erased."),
    ("CHANGE-IMPACT", "Change impact", "lifecycle_maintenance_sustainability", "baseline-change-dependency-carrier", "changed-element-to-affected-evidence-relation", "proposal-links-risks-tests-results-and-rollback-held", "dependency-graph-bounded", "Change impact traces a proposed modification through affected requirements, interfaces, hazards, tests and releases.", "Reject if a changed dependency is declared irrelevant without trace evidence."),
    ("DECOMMISSION", "Decommissioning", "lifecycle_maintenance_sustainability", "system-service-end-assets-record-carrier", "active-to-retired-state-relation", "authority-users-data-materials-hazards-recovery-and-custody-held", "retirement-scope-bounded", "Decommissioning retains authority, users, data, materials, hazards, recovery and archive custody.", "Reject if disabling a service proves data, hazard or dependency removal."),
    ("LIFECYCLE", "Full lifecycle record", "lifecycle_maintenance_sustainability", "need-design-build-use-retire-carrier", "versioned-lifecycle-transition-relation", "resources-decisions-configurations-failures-impacts-and-ownership-held", "lifecycle-boundary-declared", "A lifecycle record connects need, design, build, use, maintenance and retirement with resources and impacts retained.", "Reject if manufacturing, operation, maintenance or end-of-life is omitted from a whole-life claim."),
    ("SUSTAINABILITY", "Bounded sustainability claim", "lifecycle_maintenance_sustainability", "system-lifecycle-resources-affected-carrier", "lifecycle-input-output-impact-relation", "boundary-resources-emissions-labour-distribution-uncertainty-and-tradeoffs-held", "declared-lifecycle-boundary", "A sustainability claim retains lifecycle boundary, resources, emissions, labour, distribution, uncertainty and trade-offs.", "Reject if one favorable indicator, offset or displaced harm proves sustainability."),
    ("LAW-TRANSLATION", "Scientific-law translation", "science_design_evidence_boundary", "admitted-law-requirement-design-test-carrier", "law-to-bounded-implementation-relation", "upstream-receipt-assumptions-choices-boundary-results-and-failures-held", "translation-purpose-bounded", "Engineering translation consumes an admitted law and records every added design choice, assumption, boundary and test.", "Reject if an application target selects or rewrites the upstream law."),
    ("PERFORMANCE", "Design performance", "science_design_evidence_boundary", "implementation-condition-metric-result-carrier", "test-condition-to-performance-relation", "artifact-version-metric-boundary-results-failures-and-uncertainty-held", "performance-test-bounded", "Performance is a version- and condition-bound implementation result, not a fundamental scientific law.", "Reject if successful performance is presented as retroactive proof of the law."),
    ("IMPLEMENTATION-FAILURE", "Implementation failure boundary", "science_design_evidence_boundary", "design-condition-failure-record-carrier", "implementation-path-to-failed-result-relation", "requirements-choices-build-state-test-cause-and-uncertainty-held", "implementation-version-bounded", "A failed implementation can falsify its operating claim while leaving the upstream law unchanged unless a valid anomaly bridge is established.", "Reject if engineering failure is automatically relabelled scientific falsification."),
    ("PROTOTYPE", "Prototype evidence", "science_design_evidence_boundary", "prototype-version-purpose-test-carrier", "partial-implementation-to-bounded-learning-relation", "omissions-fidelity-setup-results-failures-and-next-decision-held", "prototype-purpose-bounded", "Prototype evidence retains omissions, fidelity, setup, failures and the bounded question it answers.", "Reject if a prototype demonstration is called production validation or universal proof."),
    ("SIMULATION", "Engineering simulation boundary", "science_design_evidence_boundary", "model-input-assumption-output-carrier", "declared-model-to-computed-result-relation", "equations-discretization-inputs-assumptions-errors-and-comparison-held", "model-and-resolution-bounded", "A simulation retains its model, discretization, inputs, assumptions, error and comparison; it is not an observation.", "Reject if simulated output is relabelled measured performance."),
    ("DEMONSTRATION", "Engineering demonstration", "science_design_evidence_boundary", "artifact-scenario-observer-result-carrier", "declared-scenario-to-visible-behaviour-relation", "version-setup-scenario-observations-failures-and-limits-held", "demonstration-scenario-bounded", "A demonstration shows bounded behavior in a retained scenario and remains distinct from verification, validation and science admission.", "Reject if a compelling display replaces complete testing or external evidence."),
    ("ANOMALY", "Engineering anomaly", "ownership_anomaly_handoffs", "artifact-expected-observed-context-carrier", "registered-expectation-to-deviation-relation", "versions-setup-raw-data-controls-repeats-and-uncertainty-held", "anomaly-protocol-bounded", "An anomaly is a source-custodied deviation from a preregistered engineering expectation with controls and repeats retained.", "Reject if surprise, noise, undocumented configuration or post-hoc expectation is called an anomaly."),
    ("SCIENCE-RETURN", "Return of anomaly to science", "ownership_anomaly_handoffs", "engineering-anomaly-owner-question-carrier", "validated-deviation-to-categorical-handoff-relation", "upstream-receipts-implementation-audit-controls-data-and-open-question-held", "disciplinary-ownership-bounded", "A validated anomaly returns as a question to its categorical science owner; it does not enter the model through Engineering.", "Reject if the implementation directly edits a scientific law or bypasses branch admission."),
    ("SOFTWARE-HANDOFF", "Software and computation handoff", "ownership_anomaly_handoffs", "formal-process-implementation-platform-carrier", "semantics-to-executable-artifact-relation", "specification-source-build-platform-tests-and-resource-record-held", "software-implementation-bounded", "Computation owns formal semantics; Engineering owns the versioned executable translation and deployment evidence.", "Reject if platform behavior rewrites computation law or formal correctness proves usable deployment."),
    ("PHYSICAL-HANDOFF", "Physical sciences handoff", "ownership_anomaly_handoffs", "physical-law-component-environment-carrier", "law-to-physical-implementation-relation", "law-receipts-materials-geometry-boundary-measurements-and-failures-held", "physical-design-bounded", "Physics, Chemistry, Materials, Earth and Astronomy own their laws; Engineering owns bounded artifacts using them.", "Reject if material or environmental behavior is inferred from product success without scientific admission."),
    ("BIO-MED-SOCIAL-HANDOFF", "Biological, medical and social handoff", "ownership_anomaly_handoffs", "organism-user-population-device-carrier", "science-and-context-to-intervention-relation", "biological-clinical-social-receipts-users-ethics-harms-and-access-held", "human-use-bounded", "Biology, Medicine, Consciousness and Social Science retain their evidence while Engineering translates a bounded intervention.", "Reject if device performance proves diagnosis, subjective experience, equal access or ethical legitimacy."),
    ("V4-HANDOFF", "SFT-derived self-hosted V4 handoff", "ownership_anomaly_handoffs", "v3-corpus-language-compiler-runtime-carrier", "admitted-semantics-to-self-hosted-rebuild-relation", "all-upstream-receipts-specification-bootstrap-tests-divergences-and-provenance-held", "future-rebuild-authority-bounded", "A future V4 self-hosted rebuild must reproduce V3 semantics, receipts and constraints through an independently auditable bootstrap.", "Reject if a self-hosted implementation becomes authority merely by reproducing itself or changes the protected V3 record."),
)

ENGINEERING_OBLIGATIONS = tuple(row(*item) for item in DATA)
if len(ENGINEERING_OBLIGATIONS) != 72 or len({x.claim_id for x in ENGINEERING_OBLIGATIONS}) != 72:
    raise ValueError("Engineering obligation surface must contain 72 unique rows")
if tuple(dict.fromkeys(x.family for x in ENGINEERING_OBLIGATIONS)) != FAMILY_ORDER:
    raise ValueError("Engineering families are not in frozen dependency order")

OBLIGATIONS = ENGINEERING_OBLIGATIONS
__all__ = ("EngineeringObligation", "ENGINEERING_OBLIGATIONS", "OBLIGATIONS", "FAMILY_ORDER")
