from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-SENSITIVITY-003';DOMAINS=(('anonymous-response', 'held-analyte-method-condition'), ('continuum-input-premise', 'positive-ordered-input-support'), ('response-fit-only', 'paired-complete-response-support'), ('signed-response-change', 'held-response-side-positive-change-or-EmptyOne'), ('fitted-global-slope', 'exact-local-response-per-input-ratio'), ('universal-linearity', 'finite-registered-segment-domain'), ('drift-noise-erased', 'complete-drift-noise-custody'), ('refitted-history', 'successor-retains-and-adds-segment'));SURVIVOR='held-analyte-method-condition__positive-ordered-input-support__paired-complete-response-support__held-response-side-positive-change-or-EmptyOne__exact-local-response-per-input-ratio__finite-registered-segment-domain__complete-drift-noise-custody__successor-retains-and-adds-segment'
from fractions import Fraction
def segments(p):return tuple((None if b==a else "rises" if b>a else "falls",Fraction(abs(b-a),y-x)) for (x,a),(y,b) in zip(p,p[1:]))
p=((Fraction(1),Fraction(2)),(Fraction(2),Fraction(5)),(Fraction(3),Fraction(5)));x=segments(p)
native={"identity":True,"input":tuple(a for a,_ in p)==(1,2,3),"response":len(p)==3,"change":x[0][0]=="rises","relation":x[0][1]==3,"domain":len(x)==2,"noise":x[1][0] is None,"successor":len(segments(p+((Fraction(4),Fraction(6)),)))==3}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
