from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-DATABASE-IDENTITY-PROVENANCE-011'
DOMAINS=(('database-row-as-molecule', 'held-canonical-chemical-carrier'), ('source-free-copied-value', 'exact-source-record-identity'), ('mutable-current-record', 'captured-version-and-byte-identity'), ('format-specific-identity', 'reversible-format-to-carrier-translation'), ('name-only-cross-database-join', 'carrier-preserving-cross-source-map'), ('latest-value-overwrite', 'append-only-supersession-history'), ('derivation-database-conflation', 'explicit-postseal-observation-boundary'), ('source-disagreement-erasure', 'all-conflicts-and-unavailable-records-retained'))
SURVIVOR='held-canonical-chemical-carrier__exact-source-record-identity__captured-version-and-byte-identity__reversible-format-to-carrier-translation__carrier-preserving-cross-source-map__append-only-supersession-history__explicit-postseal-observation-boundary__all-conflicts-and-unavailable-records-retained'
DIMENSION_KEYS=('carrier', 'source', 'version', 'representation', 'crosswalk', 'history', 'observation', 'adverse')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
