from itertools import product
import json,sys
CLAIM="SFT-CHEM-OXIDATIVE-ADDITION-REDUCTIVE-ELIMINATION-012"
DOMAINS=(("anonymous-reaction-name","one-retained-organometallic-process"),("selected-reactant-fragments","complete-two-carrier-source-bond"),("asserted-oxidation-state-change","two-generated-metal-carrier-incidences"),("formal-charge-bookkeeping","exact-carrier-and-metal-conservation"),("signed-electron-loss","held-two-electron-transfer-orientation"),("single-conventional-mechanism","complete-one-metal-two-or-two-metal-one-one-partition"),("separate-reductive-rule","exact-reductive-inverse-correspondence"),("species-specific-exception","trace-composition-with-no-extra-rule"))
SURVIVOR="one-retained-organometallic-process__complete-two-carrier-source-bond__two-generated-metal-carrier-incidences__exact-carrier-and-metal-conservation__held-two-electron-transfer-orientation__complete-one-metal-two-or-two-metal-one-one-partition__exact-reductive-inverse-correspondence__trace-composition-with-no-extra-rule"
def main():
 d=json.load(open(sys.argv[1],encoding="utf-8")); generated=["__".join(x) for x in product(*DOMAINS)]; received=[x["candidate_id"] for x in d["census"]["candidates"]]; decisions={x["candidate_id"]:x["survives"] for x in d["decisions"]}; source=("X","Y"); single=(("M","X"),("M","Y")); split=(("M1","X"),("M2","Y")); reconstructed=len(single)==len(split)==2 and tuple(x[1] for x in single)==source and tuple(x[1] for x in split)==source
 passed=d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {x["kind"] for x in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] for x in d["controls"]) and reconstructed
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"single_distribution":[2],"split_distribution":[1,1],"exact_reverse":reconstructed,"external_mechanism_accessed":False,"signed_negative_irrational_imaginary_continuum_fitted_or_free_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
