"""Implementation-distinct value-free KIN-008 reconstruction."""
from itertools import product
import json,sys
CLAIM='SFT-CHEM-PARALLEL-MECHANISM-COMPOSITION-008'
DOMAINS=(('selected-dominant-or-favorable-path-subset', 'complete-registered-parallel-path-support'), ('unrelated-or-collapsed-initial-boundary', 'exact-common-initial-state-boundary'), ('endpoint-only-path-summary', 'complete-state-edge-word-for-every-path'), ('imported-stochastic-weight-or-parallel-rate-equation', 'finite-source-ordered-parallel-path-composition'), ('shared-prefix-terminal-or-occurrence-collapsed', 'shared-boundaries-retained-in-every-path-occurrence'), ('weak-adverse-unresolved-or-unassigned-path-omitted', 'all-path-statuses-and-unresolved-records-retained'), ('selected-plot-mean-or-answer-only-product-table', 'complete-article-supplement-and-twenty-eight-sheet-cell-ledger'), ('product-time-value-readable-before-seal-or-corrected-after-release', 'value-free-twenty-eight-sheet-identity-seal-and-depth-independent-path-successor'))
SURVIVOR='complete-registered-parallel-path-support__exact-common-initial-state-boundary__complete-state-edge-word-for-every-path__finite-source-ordered-parallel-path-composition__shared-boundaries-retained-in-every-path-occurrence__all-path-statuses-and-unresolved-records-retained__complete-article-supplement-and-twenty-eight-sheet-cell-ledger__value-free-twenty-eight-sheet-identity-seal-and-depth-independent-path-successor'
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; received=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}
 paths=(("source-a","state-b","terminal-d"),("source-a","state-c","terminal-d")); successor=("source-a","state-e","state-f","terminal-d"); extended=paths+(successor,)
 witnesses=(len(paths)==2 and len(set(paths))==2 and all(path[0]=="source-a" for path in paths) and tuple(path[-1] for path in paths)==("terminal-d","terminal-d") and extended[:len(paths)]==paths and len(extended)==3)
 passed=(d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={candidate:candidate==SURVIVOR for candidate in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {row["kind"] for row in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(row["passed"] for row in d["controls"]) and witnesses)
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"complete_parallel_family_reconstructed":witnesses,"common_initial_and_terminal_occurrences_retained":witnesses,"path_successor_preserves_complete_prior_family":witnesses,"numerical_zero_negative_irrational_imaginary_logarithmic_signed_or_continuum_proof_value_used":False,"parallel_equation_stochastic_premise_fit_path_weight_target_measurement_or_source_file_accessed":False}},sort_keys=True))
if __name__=="__main__":main()
