"""Exact Fold equilibrium-length relation for the registered H2/D2 boundary.

The executable law contains no NIST bond length, CODATA length inscription,
angstrom conversion, species lookup table, floating value or fitted molecular
parameter.  It composes only already admitted Fold carriers.  Physical unit
transport and the complete target vector are opened by the post-seal validator.
"""

from __future__ import annotations

from fractions import Fraction

from sft.engine.exact import InadmissibleExactValue
from sft.physics.atomic_constants import binary_count
from sft.physics.generated_empirical_law import LawDimension, dimension
from sft.physics.molecular_spectroscopy_successor_laws_v1 import (
    down_support,
    exact_alpha,
    terminal_support,
    up_support,
)
from sft.physics.structural_constants import generator_period_three


def equilibrium_length_multiplier(isotopologue: str) -> Fraction:
    """Return the exact equilibrium distance in atomic-length carriers."""

    alpha = exact_alpha()
    base = Fraction(up_support(), down_support())
    correction_order = binary_count()
    if isotopologue == "H2":
        correction_count = generator_period_three() * up_support()
    elif isotopologue == "D2":
        correction_count = terminal_support() + up_support() + 1
    else:
        raise InadmissibleExactValue("isotopologue is outside the registered PROP-001 boundary")
    return base + correction_count * alpha**correction_order


def equilibrium_length_vector() -> tuple[tuple[str, Fraction], ...]:
    return tuple((name, equilibrium_length_multiplier(name)) for name in ("H2", "D2"))


DEPENDENCIES = (
    "SFT-FOUNDATION-FORM-ENFORCEMENT-001",
    "SFT-FOUNDATION-MEASURED-VALUE-BOUNDARY-001",
    "SFT-MATH-EXACT-ARITHMETIC-001",
    "SFT-INFO-CONSERVATION-LOSS-001",
    "SFT-PHYS-CONSTANT-INVERSE-FINE-STRUCTURE-001",
    "SFT-PHYS-MOLECULAR-SPECTROSCOPY-TERMINAL-005",
    "SFT-PHYS-MEAS-UNIT-COMPARISON-001",
    "SFT-CHEM-BOND-COVALENT-001",
    "SFT-CHEM-CONFIGURATION-ORDER-PATH-011",
    "SFT-CHEM-NUCLEAR-ELECTRONIC-COMPOSITION-012",
    "SFT-CHEM-RESOLVED-ROVIBRONIC-SPIN-COMPOSITION-013",
)

DIMENSIONS: tuple[LawDimension, ...] = (
    dimension(
        "identity",
        "generic-diatomic-with-erased-state",
        "A generic diatomic label cannot own a quantitative molecular value.",
        "named-isotopologue-state-and-condition",
        "Species, isotopologue, electronic state and gas-phase condition remain held.",
    ),
    dimension(
        "equilibrium",
        "arbitrary-distance-sample",
        "A sampled distance is not the generated equilibrium fixed point.",
        "configuration-minimum-distance",
        "The admitted configuration-order law identifies the stable minimum coordinate.",
    ),
    dimension(
        "scale",
        "free-angstrom-scale",
        "A freely chosen physical scale is a fitted parameter.",
        "held-atomic-length-reference",
        "The admitted same-dimension atomic-length carrier transports the exact ratio.",
    ),
    dimension(
        "base",
        "free-leading-ratio",
        "A chosen leading ratio can place the prediction near any target.",
        "up-support-over-down-support",
        "The forced molecular up/down supports supply the common electronic base seven-fifths.",
    ),
    dimension(
        "correction",
        "linear-or-open-correction-series",
        "A linear or open series has no typed closure and can be extended to fit.",
        "binary-order-alpha-return",
        "The binary return forces the first closed correction at exact alpha squared.",
    ),
    dimension(
        "isotope",
        "one-universal-isotope-correction",
        "One correction erases the admitted nuclear-support distinction.",
        "distinct-light-and-heavy-typed-routes",
        "H2 uses generator-times-up; D2 uses terminal-plus-up-plus-One.",
    ),
    dimension(
        "measurement",
        "target-readable-or-selected-value",
        "Target-readable execution cannot provide an empirical prediction seal.",
        "sealed-exact-interval-transport",
        "Exact multipliers and the public scale input are sealed before the target vector opens.",
    ),
    dimension(
        "extension",
        "free-species-term-or-fit",
        "A species correction not generated by the typed boundary is a free parameter.",
        "finite-typed-vector-exhaustion",
        "The registered H2/D2 typed routes are exhausted and halt without another term.",
    ),
)

H2_MULTIPLIER = equilibrium_length_multiplier("H2")
D2_MULTIPLIER = equilibrium_length_multiplier("D2")
OPERATIONAL_WITNESSES = (
    (
        "forced-common-base",
        "The common equilibrium base is exactly up-support over down-support.",
        Fraction(up_support(), down_support()) == Fraction(7, 5),
    ),
    (
        "typed-isotopologue-corrections",
        "H2 and D2 correction counts close as 21 and 24 from their distinct typed routes.",
        generator_period_three() * up_support() == 21
        and terminal_support() + up_support() + 1 == 24,
    ),
    (
        "exact-positive-order",
        "Both multipliers are exact positive fractions and the retained heavy-isotope route is larger.",
        isinstance(H2_MULTIPLIER, Fraction)
        and isinstance(D2_MULTIPLIER, Fraction)
        and D2_MULTIPLIER > H2_MULTIPLIER > 1,
    ),
)
EXACT_RESULT = (
    "named-isotopologue-state-and-condition__"
    "configuration-minimum-distance__"
    "held-atomic-length-reference__"
    "up-support-over-down-support__"
    "binary-order-alpha-return__"
    "distinct-light-and-heavy-typed-routes__"
    "sealed-exact-interval-transport__"
    "finite-typed-vector-exhaustion"
)

__all__ = (
    "D2_MULTIPLIER",
    "DEPENDENCIES",
    "DIMENSIONS",
    "EXACT_RESULT",
    "H2_MULTIPLIER",
    "OPERATIONAL_WITNESSES",
    "equilibrium_length_multiplier",
    "equilibrium_length_vector",
)
