"""Registered INORG-013 law and complete sealed authority surface."""
from __future__ import annotations
import json
from pathlib import Path
from sft.chemistry.generated_law import ChemistryTargetReference,EmpiricalChemistrySpec
from sft.chemistry.insertion_elimination_pathway_law_v1 import DEPENDENCIES,DIMENSIONS,EXACT_RESULT,OPERATIONAL_WITNESSES
from sft.engine.source import hash_file
ROOT=Path(__file__).resolve().parents[2]
FAMILY_BOUNDARY_PATH="audits/CHEMISTRY_INORG_004_017_FAMILY_BOUNDARY_2026-07-27.json";FAMILY_BOUNDARY_HASH="sha256:87998e9fa168d82dd80c28abc9910502bfb23da0c26cb6b1ecedfb88142642bc"
FAMILY_REGISTRY_PATH="experiments/external_sources/chemistry/inorg_004_017_family_source_identity_registry_v1.json";FAMILY_REGISTRY_HASH="sha256:fce17d6e980696c8051f982ce0f4c8364520ea213f68153187253b96ec914bd2"
FAMILY_INVENTORY_PATH="experiments/external_sources/chemistry/snapshots/inorg-004-017-family-v1/source-inventory-v1.json";FAMILY_INVENTORY_HASH="sha256:e03724f16e4866b43b5f3b53a6804588a2c86f5405bcda37cfb717e5724bb7c2"
LAW_PATH="sft/chemistry/insertion_elimination_pathway_law_v1.py";LAW_HASH="sha256:64e46aaa3f696396f460d4d454e8e7269cddfa00a36e0bd559a55e589194fa01"
IDENTITY_PATH="experiments/external_sources/chemistry/inorg_013_target_identities_v1.json";IDENTITY_HASH="sha256:62bdd91e56629d4c841657ea94e339dd49b00913f11e58dbb73c67537ef46fa1"
TARGET_PATH="experiments/external_sources/chemistry/inorg_013_withheld_targets_v2.json";TARGET_HASH="sha256:f9366ae730b5a25b28b91c4a4f1f38e32e3669858023d1bf20f0fae86a67f3ca"
PRIMARY_PATH="experiments/external_sources/chemistry/snapshots/inorg-004-017-family-v1/inorg-013-primary-records-v2.json";PRIMARY_HASH="sha256:4b5266c18b8de2018bd9b3c24c5fa113162cff71c88c27a0cf75b49c1c3b8b5f"
for p,h in ((FAMILY_BOUNDARY_PATH,FAMILY_BOUNDARY_HASH),(FAMILY_REGISTRY_PATH,FAMILY_REGISTRY_HASH),(FAMILY_INVENTORY_PATH,FAMILY_INVENTORY_HASH),(LAW_PATH,LAW_HASH),(IDENTITY_PATH,IDENTITY_HASH),(TARGET_PATH,TARGET_HASH),(PRIMARY_PATH,PRIMARY_HASH)):
 if hash_file(ROOT/p)!=h:raise ValueError(f"INORG-013 registered authority changed: {p}")
_id=json.loads((ROOT/IDENTITY_PATH).read_text());_rows=tuple(_id.get("rows",()))
if _id.get("complete_registered_target_count")!=10 or _id.get("target_definitions_examples_values_outcomes_presence_flags_or_payload_hashes_present") is not False or len(_rows)!=10:raise ValueError("INORG-013 value-free boundary changed")
TARGET_REFERENCES=tuple(ChemistryTargetReference(x["target_id"],f"{x['authority']}::{x['source_id']}::{x['source_record_role']}::{x['custody_class']}",x["registered_identity"],x["snapshot_path"],x["snapshot_sha256"]) for x in _rows)
INSERTION_ELIMINATION_PATHWAY_SPEC=EmpiricalChemistrySpec(claim_id="SFT-CHEM-INSERTION-ELIMINATION-PATHWAY-013",title="Exact insertion, migratory-insertion and elimination adjacency-trace law",statement="Insertion replaces one X-Z adjacency by X-Y and Y-Z while conserving all three carriers. Extrusion is its exact inverse. Migratory insertion is the exact composition of migration and insertion, transforming metal-migrant and metal-inserted adjacency into retained metal-inserted and migrant-inserted adjacency. Elimination retains both eliminands and centres while generating the product adjacency and a held unsaturation, ring or carbene boundary.",dependencies=DEPENDENCIES,generation_rule="Generate the literal product of carrier, trace, insertion, migration, reverse, elimination, product and extension choices; decide all 256 candidates only from admitted graph, transition, conservation, mechanism and INORG-010/012 dependencies.",grammar_boundary="Every finite complete adjacency transformation for insertion, exact extrusion, migratory insertion and distinct- or single-centre elimination; all ten frozen IUPAC definition, composition, scope, absent-example and product-boundary surfaces.",dimensions=DIMENSIONS,exact_result=EXACT_RESULT,induction_base="Insertion on one X-Z edge and a distinct Y carrier removes one edge and adds exactly X-Y and Y-Z; the reverse restores X-Z.",induction_step="Composing a matching next trace preserves every retained carrier and prior endpoint while its removed and added supports remain the exact graph difference.",exclusions=("no numerical zero negative irrational imaginary signed continuum fitted free or imported parameter","no product formula named mechanism selected leaving group or observed outcome selecting the trace","no conflation of extrusion with generic elimination","no omission of the host-lattice scope distinction or absent rendered example structure"),operational_witnesses=OPERATIONAL_WITNESSES,experiment_id="SFT-EXP-CHEM-INSERTION-ELIMINATION-PATHWAY-013",expected_observation_label="complete-insertion-migratory-elimination-vector",target_rows=TARGET_REFERENCES,observation_registry_path=TARGET_PATH,falsification_condition="The claim fails if any carrier, centre, eliminand or before/after adjacency is lost, duplicated or invented; if removed/added support differs from the exact graph difference; if insertion, extrusion, migratory composition or elimination boundaries are conflated; if an observed product or named mechanism selects the law; if any of ten IUPAC surfaces, the host-lattice scope row or absent rendered example is removed; or if outcomes open before sealing.")
INSERTION_ELIMINATION_PATHWAY_SPEC.validate()
__all__=("FAMILY_BOUNDARY_PATH","FAMILY_INVENTORY_PATH","FAMILY_REGISTRY_PATH","IDENTITY_HASH","IDENTITY_PATH","INSERTION_ELIMINATION_PATHWAY_SPEC","PRIMARY_HASH","PRIMARY_PATH","TARGET_HASH","TARGET_PATH","TARGET_REFERENCES")
