"""Registered INORG-014 law and sealed authority surface."""
from __future__ import annotations
import json
from pathlib import Path
from sft.chemistry.generated_law import ChemistryTargetReference,EmpiricalChemistrySpec
from sft.chemistry.metal_cluster_bonding_law_v1 import DEPENDENCIES,DIMENSIONS,EXACT_RESULT,OPERATIONAL_WITNESSES
from sft.engine.source import hash_file
ROOT=Path(__file__).resolve().parents[2]
FAMILY_BOUNDARY_PATH="audits/CHEMISTRY_INORG_004_017_FAMILY_BOUNDARY_2026-07-27.json";FAMILY_BOUNDARY_HASH="sha256:4624c5ac9ae4981e1c4ad424e2bcfdb9ba0c43ddcdaabbd16bc84a30487ae7d1"
FAMILY_REGISTRY_PATH="experiments/external_sources/chemistry/inorg_004_017_family_source_identity_registry_v1.json";FAMILY_REGISTRY_HASH="sha256:fce17d6e980696c8051f982ce0f4c8364520ea213f68153187253b96ec914bd2"
FAMILY_INVENTORY_PATH="experiments/external_sources/chemistry/snapshots/inorg-004-017-family-v1/source-inventory-v1.json";FAMILY_INVENTORY_HASH="sha256:e631c5d914b9f18315a4fb7927044c4b76574bb7461c884a23ba835c504ecbd5"
LAW_PATH="sft/chemistry/metal_cluster_bonding_law_v1.py";LAW_HASH="sha256:461942241a61c5fb0cc2814eb94c93ed3410d80187be08906b1388f13010071d"
IDENTITY_PATH="experiments/external_sources/chemistry/inorg_014_target_identities_v1.json";IDENTITY_HASH="sha256:9fb4f98fd0946c187bb0e02e700d4f18e2df7455a445b2030d7a768f826db287"
TARGET_PATH="experiments/external_sources/chemistry/inorg_014_withheld_targets_v1.json";TARGET_HASH="sha256:68d44d6477269f114837fb23c58baa874adbf12c56bb81377c73558e0fcf547c"
PRIMARY_PATH="experiments/external_sources/chemistry/snapshots/inorg-004-017-family-v1/inorg-014-primary-records-v1.json";PRIMARY_HASH="sha256:2973e1623fb7fdfa890b600cc787d2c2e84cef65a8aff270a17a74f4d21495a8"
for p,h in ((FAMILY_BOUNDARY_PATH,FAMILY_BOUNDARY_HASH),(FAMILY_REGISTRY_PATH,FAMILY_REGISTRY_HASH),(FAMILY_INVENTORY_PATH,FAMILY_INVENTORY_HASH),(LAW_PATH,LAW_HASH),(IDENTITY_PATH,IDENTITY_HASH),(TARGET_PATH,TARGET_HASH),(PRIMARY_PATH,PRIMARY_HASH)):
 if hash_file(ROOT/p)!=h:raise ValueError(f"INORG-014 authority changed: {p}")
_d=json.loads((ROOT/IDENTITY_PATH).read_text());_rows=tuple(_d.get("rows",()))
if _d.get("complete_registered_target_count")!=10 or _d.get("target_definitions_examples_values_outcomes_presence_flags_or_payload_hashes_present") is not False or len(_rows)!=10:raise ValueError("INORG-014 identity boundary changed")
TARGET_REFERENCES=tuple(ChemistryTargetReference(x["target_id"],f"{x['authority']}::{x['source_id']}::{x['source_record_role']}::{x['custody_class']}",x["registered_identity"],x["snapshot_path"],x["snapshot_sha256"]) for x in _rows)
METAL_CLUSTER_BONDING_SPEC=EmpiricalChemistrySpec(claim_id="SFT-CHEM-METAL-CLUSTER-BONDING-014",title="Exact finite connected metal-cluster and metal-bonding law",statement="A metal cluster is one finite complete support of at least two distinct metal centres connected by the generated cluster-relation graph. Direct metal bonds, bridging-ligand paths and held grouping relations are separate support classes; direct or bridging bonding may be structurally absent without destroying a connected cluster. Each class is counted positively or retained as EmptyOne, and a fresh attached centre preserves connectivity.",dependencies=DEPENDENCIES,generation_rule="Generate the literal product of carrier, centres, connectivity, direct, bridge, grouping, count and extension alternatives; decide all 256 forms from admitted graph, bond, composition and coordination dependencies.",grammar_boundary="Every finite connected graph of at least two metal centres with direct, bridging or held grouping relations and explicit bridge occurrences; all ten frozen cluster and iron-sulfur-cluster topology, example and charge-inscription surfaces.",dimensions=DIMENSIONS,exact_result=EXACT_RESULT,induction_base="Two distinct centres joined by one generated direct, bridging or held grouping relation form the first connected cluster support.",induction_step="Appending one fresh centre by exactly one generated relation preserves every prior centre and relation, increments centre count once and preserves connectedness.",exclusions=("no numerical zero; absent relation classes are structural EmptyOne","no negative irrational imaginary signed continuum fitted free or imported parameter","no assumption that every cluster has a direct metal bond or bridge","no external signed charge inscription used as a proof value","no selected cluster catalogue or observed example selecting the law"),operational_witnesses=OPERATIONAL_WITNESSES,experiment_id="SFT-EXP-CHEM-METAL-CLUSTER-BONDING-014",expected_observation_label="complete-cluster-topology-and-iron-sulfur-vector",target_rows=TARGET_REFERENCES,observation_registry_path=TARGET_PATH,falsification_condition="The claim fails if centre support is finite-incomplete, duplicated or disconnected; if direct, bridging and held grouping relations are conflated; if bridge occurrences are implicit; if absent classes use numerical zero; if an observed example or charge inscription selects the law; if any of ten IUPAC surfaces is removed; or if outcomes open before sealing.")
METAL_CLUSTER_BONDING_SPEC.validate()
__all__=("FAMILY_BOUNDARY_PATH","FAMILY_INVENTORY_PATH","FAMILY_REGISTRY_PATH","IDENTITY_HASH","IDENTITY_PATH","METAL_CLUSTER_BONDING_SPEC","PRIMARY_HASH","PRIMARY_PATH","TARGET_HASH","TARGET_PATH","TARGET_REFERENCES")
