"""Fold-native nuclear-electronic composition and scale-separation law."""

from __future__ import annotations

from dataclasses import dataclass

from sft.engine.exact import HeldLabel, InadmissibleExactValue
from sft.physics.generated_empirical_law import LawDimension, dimension


@dataclass(frozen=True)
class NuclearElectronicSupport:
    molecular_carrier: HeldLabel
    nuclear_occurrences: tuple[HeldLabel, ...]
    isotope_labels: tuple[HeldLabel, ...]
    electronic_support: HeldLabel
    electronic_state: HeldLabel
    record: HeldLabel

    def __post_init__(self) -> None:
        if self.molecular_carrier.family != "molecular-carrier":
            raise InadmissibleExactValue("joint support requires one molecular carrier")
        if not self.nuclear_occurrences or len(set(self.nuclear_occurrences)) != len(self.nuclear_occurrences):
            raise InadmissibleExactValue("nuclear occurrences must be positive and distinct")
        if any(label.family != "nuclear-occurrence" for label in self.nuclear_occurrences):
            raise InadmissibleExactValue("nuclear occurrence labels have the wrong family")
        if len(self.isotope_labels) != len(self.nuclear_occurrences) or any(label.family != "molecular-isotope" for label in self.isotope_labels):
            raise InadmissibleExactValue("every nuclear occurrence retains one isotope label")
        if self.electronic_support.family != "molecular-electronic-support" or self.electronic_state.family != "molecular-electronic-state":
            raise InadmissibleExactValue("electronic support and state must both be retained")
        if self.record.family != "nuclear-electronic-record":
            raise InadmissibleExactValue("joint support requires a retained observation record")

    @property
    def nuclear_support_key(self) -> tuple[str, ...]:
        return tuple(label.label for label in self.isotope_labels)

    @property
    def electronic_support_key(self) -> tuple[str, str]:
        return self.electronic_support.label, self.electronic_state.label


def equal_electronic_support_isotopologues(left: NuclearElectronicSupport, right: NuclearElectronicSupport) -> bool:
    if left.molecular_carrier != right.molecular_carrier:
        raise InadmissibleExactValue("isotopologue comparison requires one molecular carrier class")
    return left.electronic_support_key == right.electronic_support_key and left.nuclear_support_key != right.nuclear_support_key


DEPENDENCIES = (
    "SFT-FOUNDATION-FORM-ENFORCEMENT-001", "SFT-MATH-EXACT-ARITHMETIC-001",
    "SFT-MATH-DISCRETE-001", "SFT-MATH-COMBINATORICS-001",
    "SFT-INFO-SYMBOL-DISTINCTION-001", "SFT-INFO-CONSERVATION-LOSS-001",
    "SFT-QUANTUM-STATE-COMPOSITION-001", "SFT-PHYS-NUCLEAR-DEUTERON-DINUCLEON-TERMINAL-006",
    "SFT-CHEM-ELEM-ISOTOPE-001", "SFT-CHEM-ELECTRONIC-STATE-IDENTITY-001",
    "SFT-CHEM-ORBITAL-SUPPORT-OCCUPANCY-003", "SFT-CHEM-CONFIGURATION-ORDER-PATH-011",
)


DIMENSIONS: tuple[LawDimension, ...] = (
    dimension("carrier", "detached-nuclear-and-electronic-records", "Detached records do not identify one molecular state.", "retained-joint-molecular-carrier", "Nuclear and electronic coordinates remain bound to one carrier."),
    dimension("nuclear", "mass-number-without-occurrence-identity", "A magnitude alone erases which nuclear occurrence carries an isotope.", "retained-occurrence-and-isotope-support", "Every occurrence retains one exact isotope label."),
    dimension("electronic", "isotope-replacement-erases-electronic-identity", "Erasing electronic identity prevents lawful equal-support comparison.", "retained-electronic-support-and-state", "Electronic support and state remain held through isotope replacement."),
    dimension("composition", "nuclear-or-electronic-factor-erased", "Either erasure merges empirically distinguishable states.", "finite-nuclear-electronic-joint-product", "The state is the exact finite product of both supports."),
    dimension("scale", "imported-continuum-separation", "A continuum scale approximation is not generated by Fold structure.", "exact-coordinate-partition-without-separation-parameter", "Distinct coordinate families force a finite partition without a fitted scale."),
    dimension("transport", "isotopologue-coordinates-declared-invariant", "Invariant coordinates erase observed isotope transport.", "exact-isotope-labelled-coordinate-transport", "Equal electronic labels retain isotope-specific exact coordinate records."),
    dimension("absence", "numerical-zero-or-signed-proof-value", "Numerical zero and signed magnitudes are outside the SFT proof domain.", "EmptyOne-or-held-external-inscription", "Absence is EmptyOne; external signed inscriptions remain labels only."),
    dimension("record", "selected-common-state-highlights", "A selected intersection hides unmatched and absent source rows.", "complete-isotopologue-and-vibronic-record", "Every registered H2, HD and D2 state and cell remains present."),
)


def _state(isotopes: tuple[str, str], record: str) -> NuclearElectronicSupport:
    return NuclearElectronicSupport(
        HeldLabel("molecular-carrier", "hydrogen-diatomic"),
        (HeldLabel("nuclear-occurrence", "left"), HeldLabel("nuclear-occurrence", "right")),
        tuple(HeldLabel("molecular-isotope", value) for value in isotopes),
        HeldLabel("molecular-electronic-support", "one-sigma-g-two"),
        HeldLabel("molecular-electronic-state", "X-singlet-sigma-g"),
        HeldLabel("nuclear-electronic-record", record),
    )


def _incomplete_rejects() -> bool:
    try:
        NuclearElectronicSupport(
            HeldLabel("molecular-carrier", "hydrogen-diatomic"),
            (HeldLabel("nuclear-occurrence", "left"), HeldLabel("nuclear-occurrence", "right")),
            (HeldLabel("molecular-isotope", "protium"),),
            HeldLabel("molecular-electronic-support", "one-sigma-g-two"),
            HeldLabel("molecular-electronic-state", "X-singlet-sigma-g"),
            HeldLabel("nuclear-electronic-record", "incomplete"),
        )
    except InadmissibleExactValue:
        return True
    return False


H2, HD, D2 = _state(("protium", "protium"), "H2"), _state(("protium", "deuterium"), "HD"), _state(("deuterium", "deuterium"), "D2")
OPERATIONAL_WITNESSES = (
    ("three-nuclear-supports", "H2, HD and D2 retain three distinct nuclear-support keys.", len({H2.nuclear_support_key, HD.nuclear_support_key, D2.nuclear_support_key}) == 3),
    ("equal-electronic-support", "Isotope replacement preserves the held electronic support and state.", equal_electronic_support_isotopologues(H2, HD) and equal_electronic_support_isotopologues(HD, D2)),
    ("incomplete-support-control", "A missing isotope label rejects.", _incomplete_rejects()),
)
EXACT_RESULT = "retained-joint-molecular-carrier__retained-occurrence-and-isotope-support__retained-electronic-support-and-state__finite-nuclear-electronic-joint-product__exact-coordinate-partition-without-separation-parameter__exact-isotope-labelled-coordinate-transport__EmptyOne-or-held-external-inscription__complete-isotopologue-and-vibronic-record"


__all__ = ("DEPENDENCIES", "DIMENSIONS", "EXACT_RESULT", "NuclearElectronicSupport", "OPERATIONAL_WITNESSES", "equal_electronic_support_isotopologues")
