"""Registered ORG-016 exhaustive decomposition/reconstruction law."""
from pathlib import Path
from sft.chemistry.generated_law import ChemistryTargetReference,EmpiricalChemistrySpec
from sft.chemistry.retrosynthetic_reconstruction_law_v1 import DEPENDENCIES,DIMENSIONS,EXACT_RESULT,OPERATIONAL_WITNESSES
from sft.engine.canonical import sha256_identity
from sft.engine.source import hash_file
ROOT=Path(__file__).resolve().parents[2];CLAIM_ID="SFT-CHEM-RETROSYNTHETIC-DECOMPOSITION-RECONSTRUCTION-016";OBLIGATION_ID="SFT-CHEM-OBL-ORG-016";IDENTITY_PATH="experiments/external_sources/chemistry/org_016_target_identities_v1.json";PRESEAL_PATH="experiments/sealed_predictions/chemistry_org_016_retrosynthesis_pre_source_v1.json";MECHANISM_PATH="experiments/external_sources/chemistry/snapshots/org-001-016-family-v1/iupac-m03804.json";PATH_PATH="experiments/external_sources/chemistry/snapshots/org-001-016-family-v1/iupac-r05174.json"
AUTHORITIES=(("audits/CHEMISTRY_ORG_001_016_FAMILY_BOUNDARY_2026-07-27.json","sha256:ccbc91e9873a84f31b50670c9a8f063ee6a6096d3dd216b5e7c3bf86521681b2"),("experiments/external_sources/chemistry/org_001_016_family_source_identity_registry_v1.json","sha256:12c6822a695eb7135081ef8d044a3136c2fee2b0d486c9164b1f1166ef087381"),("sft/chemistry/retrosynthetic_reconstruction_law_v1.py","sha256:b2501e9db8446ca3075146a26adc0f6d3c989286c30d5eef07bd968f46539caf"),(IDENTITY_PATH,"sha256:96e4e13767fc5d890f9402be4352c8181f8af61ac0d9d5393aaff1a85f3fd1dd"),(PRESEAL_PATH,"sha256:e066f0f8ce679b72e215979c0526774f067b4ebd8787976c1db9a24c415c452a"),(MECHANISM_PATH,"sha256:439cff9833c2412ab1801ac36b32c884adfdffbceeda73c370305eb0584cf201"),(PATH_PATH,"sha256:3ea227936feb3b0940dbffb3b76e54f47d9f0bfe06cb8d111343a07737ab85a3"))
for p,h in AUTHORITIES:
 if hash_file(ROOT/p)!=h:raise ValueError(f"ORG-016 authority changed: {p}")
TARGET_REFERENCES=(ChemistryTargetReference("SFT-CHEM-ORG-016-MECH-COMPLETE","IUPAC-M03804","complete mechanism description",MECHANISM_PATH,AUTHORITIES[5][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-MECH-INTERMEDIATES","IUPAC-M03804","intermediates products transition states",MECHANISM_PATH,AUTHORITIES[5][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-MECH-ALTERNATIVES","IUPAC-M03804","alternative mechanisms retained",MECHANISM_PATH,AUTHORITIES[5][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-MECH-INCOMPLETE","IUPAC-M03804","incomplete evidence disclosed",MECHANISM_PATH,AUTHORITIES[5][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-PATH-MECHANISM","IUPAC-R05174","mechanism synonym",PATH_PATH,AUTHORITIES[6][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-PATH-TRAJECTORY","IUPAC-R05174","potential-energy trajectory",PATH_PATH,AUTHORITIES[6][1]),ChemistryTargetReference("SFT-CHEM-ORG-016-PATH-STEPS","IUPAC-R05174","synthetic-step sequence",PATH_PATH,AUTHORITIES[6][1]))
RETROSYNTHESIS_SPEC=EmpiricalChemistrySpec(claim_id=CLAIM_ID,title="Fold exhaustive retrosynthetic decomposition and exact forward reconstruction",statement="Every positive binary decomposition of a complete finite target is generated recursively to One leaves exactly once, and every generated path forward-reconstructs the exact target.",dependencies=DEPENDENCIES,generation_rule="Generate the literal product of eight registered binary decomposition decisions.",grammar_boundary="Eight dimensions exhaust target, cuts, recursion, graph, forward inverse, paths, observation and extension.",dimensions=DIMENSIONS,exact_result=EXACT_RESULT,induction_base="A one-occurrence target is the unique terminal synthesis tree.",induction_step="For a positive-finite successor, generate every positive split and pair every recursively generated left and right tree; concatenation reconstructs the target.",exclusions=("no numerical zero negative irrational imaginary continuum fitted free random or imported native parameter","no named route measured success or external mechanism selects a tree","no successful-path-only filtering"),operational_witnesses=OPERATIONAL_WITNESSES,experiment_id="SFT-EXP-CHEM-RETROSYNTHETIC-DECOMPOSITION-RECONSTRUCTION-016",expected_observation_label="complete-retrosynthetic-graph-observable-and-preservation-vector",target_rows=TARGET_REFERENCES,observation_registry_path=IDENTITY_PATH,falsification_condition="The claim fails if more than one form survives; a split or tree is omitted or duplicated; a path does not exactly reconstruct the target; either complete IUPAC record, alternatives or incomplete-evidence disclosure is omitted; or an external route selects the graph.")
RETROSYNTHESIS_SPEC.validate();COMPLETENESS_CERTIFICATE=sha256_identity((CLAIM_ID,tuple(x.target_id for x in TARGET_REFERENCES),5,14,EXACT_RESULT))
__all__=("AUTHORITIES","CLAIM_ID","COMPLETENESS_CERTIFICATE","IDENTITY_PATH","MECHANISM_PATH","OBLIGATION_ID","PATH_PATH","PRESEAL_PATH","RETROSYNTHESIS_SPEC","TARGET_REFERENCES")
