"""Registered ELEC-013 resolved rovibronic joint-composition specification."""
from __future__ import annotations
import json
from pathlib import Path
from sft.chemistry.generated_law import ChemistryTargetReference,EmpiricalChemistrySpec
from sft.chemistry.rovibronic_joint_law_v1 import DEPENDENCIES,DIMENSIONS,EXACT_RESULT,OPERATIONAL_WITNESSES
from sft.engine.source import hash_file
ROOT=Path(__file__).resolve().parents[2]
IDENTITY_PATH="experiments/external_sources/chemistry/nuclear_electronic_target_identities_v1.json";IDENTITY_HASH="sha256:316d3d94aa9a82a529c574e6029a9c05c5f3814683478bd184205e0b21806680"
TARGET_PATH="experiments/external_sources/chemistry/nuclear_electronic_withheld_targets_v1.json";TARGET_HASH="sha256:b8a3cb16b0fbdc53a01846492e71b38585d0a7c5336b755f3f9ea21ba48d7421"
SOURCE_ID="NIST-CHEMISTRY-WEBBOOK-SRD69-H2-HD-D2-RESOLVED-DIATOMIC-SURFACE-2026"
for p,h in ((IDENTITY_PATH,IDENTITY_HASH),(TARGET_PATH,TARGET_HASH)):
 if hash_file(ROOT/p)!=h:raise ValueError("ELEC-013 registered surface changed: "+p)
d=json.loads((ROOT/IDENTITY_PATH).read_text());rows=d["rows"]
if len(rows)!=95:raise ValueError("ELEC-013 identity surface incomplete")
TARGET_REFERENCES=tuple(ChemistryTargetReference(str(r["target_id"]),SOURCE_ID,str(r["source_url"])+" :: resolved state row "+str(r["state_row_ordinal"]),str(r["snapshot_path"]),str(r["snapshot_hash"])) for r in rows)
ROVIBRONIC_JOINT_SPEC=EmpiricalChemistrySpec(claim_id="SFT-CHEM-RESOLVED-ROVIBRONIC-SPIN-COMPOSITION-013",title="Exact resolved vibronic, rovibronic and spin-state joint-composition law",statement="A resolved molecular spectral state is one finite joint product retaining its isotopologue carrier, electronic designation, positive whole spin multiplicity, exact positive vibrational and rotational coordinates or structural EmptyOne, transition/band record and complete source record. No coordinate may be erased, recombined independently or replaced by a continuum premise.",dependencies=DEPENDENCIES,generation_rule="Generate the literal product of carrier, electronic, vibration, rotation, spin, composition, observation and record forms; decide all 256 only from admitted composition, transition, selection and exact spectroscopy dependencies.",grammar_boundary="Every positive finite resolved molecular state word and every source absence, tested against all 95 state rows and all 1,235 cells in the complete NIST H2, HD and D2 diatomic surface.",dimensions=DIMENSIONS,exact_result=EXACT_RESULT,induction_base="One isotopologue carrier, electronic designation, positive multiplicity, first resolved vibration/rotation coordinates or structural absences, transition record and source record form the least complete state.",induction_step="Appending one positive vibration or rotation recurrence extends that coordinate while preserving carrier, isotope, electronic, spin, transition and all preceding records; appending a state row extends the census without changing prior states.",exclusions=("no numerical zero; external zero is structural EmptyOne","no negative, irrational, imaginary, floating, signed or continuum proof value","no imported wavefunction, Hamiltonian, rigid rotor, harmonic oscillator, differential equation or fitted spectroscopic constant","no NIST state, multiplicity, constant, transition or band outcome before prediction seal","no singlet-only, triplet-only, common-state-only or resolved-value-only subset"),operational_witnesses=OPERATIONAL_WITNESSES,experiment_id="SFT-EXP-CHEM-RESOLVED-ROVIBRONIC-SPIN-COMPOSITION-013",expected_observation_label="complete-resolved-H2-HD-D2-vibronic-rovibronic-spin-correspondence",target_rows=TARGET_REFERENCES,observation_registry_path=TARGET_PATH,falsification_condition="Reject if any carrier, isotope, electronic designation, multiplicity, vibrational coordinate, rotational coordinate, transition, band or source record is erased or recombined; if any of 95 rows or 1,235 cells changes; if the complete surface does not retain 54 singlet and 41 triplet rows, 78 positive vibrational coordinates, 60 positive rotational coordinates, 56 jointly resolved vibronic/rotational rows, 92 transition designations, 83 positive band origins, three source-zero and three absent electronic origins; if a signed inscription becomes an SFT number; or if targets enter before sealing.")
ROVIBRONIC_JOINT_SPEC.validate()
__all__=("IDENTITY_HASH","IDENTITY_PATH","ROVIBRONIC_JOINT_SPEC","SOURCE_ID","TARGET_HASH","TARGET_PATH","TARGET_REFERENCES")
