"""Capability-closed complete resolved-spectrum validation for ELEC-013."""
from __future__ import annotations
from collections import Counter
from fractions import Fraction
import json,platform,re
from pathlib import Path
from sft.chemistry.nuclear_electronic_validation_v1 import _cell_form,_source_rows
from sft.chemistry.rovibronic_joint_batch_v1 import IDENTITY_HASH,IDENTITY_PATH,ROVIBRONIC_JOINT_SPEC,SOURCE_ID,TARGET_HASH,TARGET_PATH
from sft.claim_evidence import CapabilityClosedFoldInterpreter,CrossPlatformCustodyExchange,FoldTable,HostilePackageAuditor,TargetVault,fold_program_from_mapping,snapshot_protected_tree,target_identity_from_release
from sft.engine import EmpiricalValidation,seal_isolation_certificate,seal_target_custody_certificate,unsealed_isolation_certificate,unsealed_target_custody_certificate
from sft.engine.canonical import sha256_identity
from sft.engine.empirical import BlindExperimentBoundary,PredictionEnvelope
from sft.engine.exact import HeldLabel
VALUE_PATTERN=re.compile(r"^[\[\(]?\s*~?\s*([+-]?[0-9]+(?:\.[0-9_]*)?)")
MULTIPLICITY_PATTERN=re.compile(r"\^([1-9][0-9]*)")
def prediction_program_document(root:Path):
 values=(("carrier","retained-molecular-and-isotope-carrier"),("electronic","retained-electronic-state-designation"),("vibration","positive-vibrational-coordinate-or-EmptyOne"),("rotation","positive-rotational-coordinate-or-EmptyOne"),("spin","retained-positive-spin-multiplicity"),("composition","finite-vibronic-rovibronic-spin-product"),("observation","retained-transition-and-band-record"),("record","complete-resolved-spectrum-surface"));ins=[{"opcode":"input","destination":"premise","arguments":["registered-premise"]}];table=[]
 for p,(n,v) in enumerate(values,1):
  k,w="key-%d"%p,"value-%d"%p;ins.extend(({"opcode":"label","destination":k,"arguments":["resolved-state-axis",n]},{"opcode":"label","destination":w,"arguments":["resolved-state-law",v]}));table.extend((k,w))
 ins.extend(({"opcode":"table","destination":"law","arguments":table},{"opcode":"emit","destination":"","arguments":["law"]}));return {"schema":"sft-v3-fold-program/1","program_id":ROVIBRONIC_JOINT_SPEC.experiment_id+"-prediction","instructions":ins}
def experiment_registration_record(root:Path):
 s=ROVIBRONIC_JOINT_SPEC;return {"experiment_id":s.experiment_id,"claim_id":s.claim_id,"provenance":"observational_derivation","frozen_relation":s.exact_result,"identity_registry":(IDENTITY_PATH,IDENTITY_HASH),"withheld_target_registry":(TARGET_PATH,TARGET_HASH),"prediction_program":prediction_program_document(root),"target_references":tuple((r.target_id,r.source_id,r.source_locator,r.snapshot_path,r.snapshot_hash) for r in s.target_rows),"target_content_absent_from_prediction":True,"all_resolved_rows_required":True,"falsification_condition":s.falsification_condition}
def _positive(cell):
 m=VALUE_PATTERN.match(cell or "")
 return bool(m and Fraction(m.group(1).replace("_",""))>0)
class RovibronicJointValidator:
 def __init__(self,root:Path):self.root=root.resolve();self.spec=ROVIBRONIC_JOINT_SPEC
 def validate(self,sealed):
  rows=_source_rows(self.root);registration=experiment_registration_record(self.root);rh=sha256_identity(registration);document=prediction_program_document(self.root);program=fold_program_from_mapping(document);inputs={"registered-premise":HeldLabel("sealed-derivation",sealed.seal_hash)};envelope=PredictionEnvelope(self.spec.experiment_id,{"registered-premise":sha256_identity(inputs["registered-premise"])},tuple(r.target_id for r in self.spec.target_rows),sealed.seal_hash,rh);vault=TargetVault(experiment_id=self.spec.experiment_id,custodian_id=self.spec.experiment_id+"-NIST-custodian",targets={r["target_id"]:HeldLabel("external-resolved-spectrum-row",sha256_identity(r)) for r in rows},custody_nonce=sha256_identity((rh,TARGET_HASH)),expected_envelope_hash=sha256_identity(envelope));before=snapshot_protected_tree(self.root);execution=CapabilityClosedFoldInterpreter().execute(program,inputs);boundary=BlindExperimentBoundary(envelope);ps=boundary.seal_prediction(execution.output,execution.trace);after=snapshot_protected_tree(self.root);audited,audit=HostilePackageAuditor().audit_program_document(document,before,after)
  if sha256_identity(audited)!=execution.program_hash or not audit.passed or not isinstance(execution.output,FoldTable) or len(execution.output.entries)!=8:raise ValueError("ELEC-013 prediction package differs")
  release=vault.release(ps);CrossPlatformCustodyExchange.verify(vault.commitment,release,ps);boundary.measurement_context(release.targets);multiplicity=Counter();comparisons=[]
  for row in rows:
   match=MULTIPLICITY_PATTERN.search(row["state_cells"][0]);
   if match is None:raise ValueError("ELEC-013 multiplicity missing")
   multiplicity[match.group(1)]+=1;comparisons.append({"target_id":row["target_id"],"species":row["species"],"multiplicity":match.group(1),"vibration":_cell_form(row["state_cells"][2])[0],"rotation":_cell_form(row["state_cells"][5])[0],"transition":row["state_cells"][11],"band":_cell_form(row["state_cells"][12])[0],"passed":release.targets[row["target_id"]].label==sha256_identity(row)})
  counts={"rows":len(rows),"cells":sum(len(r["state_cells"]) for r in rows),"singlet":multiplicity["1"],"triplet":multiplicity["3"],"positive_vibration":sum(_positive(r["state_cells"][2]) for r in rows),"positive_rotation":sum(_positive(r["state_cells"][5]) for r in rows),"joint_vibration_rotation":sum(_positive(r["state_cells"][2]) and _positive(r["state_cells"][5]) for r in rows),"transition_designation":sum(bool(r["state_cells"][11]) for r in rows),"positive_band_origin":sum(_positive(r["state_cells"][12]) for r in rows),"source_zero_electronic_origin":sum(r["state_cells"][1]=="0" for r in rows),"absent_electronic_origin":sum(r["state_cells"][1]=="" for r in rows),"held_signed_inscriptions":sum(_cell_form(c)[0]=="held-negative-inscription" for r in rows for c in r["state_cells"])};expected={"rows":95,"cells":1235,"singlet":54,"triplet":41,"positive_vibration":78,"positive_rotation":60,"joint_vibration_rotation":56,"transition_designation":92,"positive_band_origin":83,"source_zero_electronic_origin":3,"absent_electronic_origin":3,"held_signed_inscriptions":8};adverse={"exact_counts":counts==expected,"all_rows":all(r["passed"] for r in comparisons),"omission_rejected":len(rows[:-1])!=95,"multiplicity_erasure_rejected":len(multiplicity)==2,"signed_values_held":counts["held_signed_inscriptions"]==8};passed=all(adverse.values())
  isolation=seal_isolation_certificate(unsealed_isolation_certificate(executor_id=self.spec.experiment_id+"-prediction-executor",host_platform=platform.system() or "registered-host",python_implementation=platform.python_implementation(),interpreter_hash=sha256_identity(CapabilityClosedFoldInterpreter.interpreter_id),program_hash=execution.program_hash,input_manifest_hash=execution.input_manifest_hash,registered_target_identity_hash=vault.commitment.target_identity_hash,comparison_implementation_identity_hash=sha256_identity(("complete-resolved-H2-HD-D2-comparator/1",self.spec.experiment_id)),prediction_seal_hash=ps.seal_hash,output_hash=execution.output_hash,trace_hash=execution.trace_hash));ti=target_identity_from_release(release);custody=seal_target_custody_certificate(unsealed_target_custody_certificate(custodian_id=release.custodian_id,experiment_registration_hash=rh,registered_target_identity_hash=ti,prediction_seal_hash=ps.seal_hash,target_release_manifest_hash=release.release_hash));payload={"comparisons":comparisons,"counts":counts,"adverse":adverse,"trace":execution.trace_hash};measurements=tuple("%s: multiplicity %s; vibration %s; rotation %s; band %s; pass %s"%(r["target_id"],r["multiplicity"],r["vibration"],r["rotation"],r["band"],r["passed"]) for r in comparisons)+tuple("count %s: %s"%(k,v) for k,v in counts.items());return EmpiricalValidation(sealed.seal_hash,rh,isolation,custody,True,True,True,(SOURCE_ID,),measurements,sha256_identity(payload),self.spec.falsification_condition,passed)
__all__=("RovibronicJointValidator","experiment_registration_record","prediction_program_document")
