"""Target-blind Fold derivation of thermochemistry, phase and photochemistry."""
from __future__ import annotations
from dataclasses import dataclass
from sft.chemistry.reaction_kinetics_derivation import REACTION_BASE
from sft.engine.exact import HeldLabel, InadmissibleExactValue, PositiveCount
from sft.physics.generated_empirical_law import LawDimension, dimension

@dataclass(frozen=True)
class EnergyLedger:
    input_support: PositiveCount
    output_support: PositiveCount
    orientation: HeldLabel
    conditions: HeldLabel
    def __post_init__(self):
        if self.orientation.family!="energy-transfer-orientation" or self.conditions.family!="thermochemical-conditions": raise InadmissibleExactValue("energy ledger requires held orientation and conditions")
@dataclass(frozen=True)
class DirectionWitness:
    forward_support: PositiveCount
    reverse_support: PositiveCount
    selected_orientation: HeldLabel
    def __post_init__(self):
        if self.selected_orientation.family!="reaction-direction": raise InadmissibleExactValue("reaction direction must be held")
@dataclass(frozen=True)
class PhaseWitness:
    phase_identity: str
    homogeneous_trace: tuple[HeldLabel,...]
    boundary: HeldLabel
    def __post_init__(self):
        if not self.phase_identity.strip() or not self.homogeneous_trace or self.boundary.family!="phase-boundary": raise InadmissibleExactValue("phase witness is incomplete")
@dataclass(frozen=True)
class SolutionEquilibriumWitness:
    dissolved_events: PositiveCount
    returned_events: PositiveCount
    solution_boundary: HeldLabel
    def __post_init__(self):
        if self.solution_boundary.family!="solution-boundary": raise InadmissibleExactValue("solution boundary is invalid")
@dataclass(frozen=True)
class PhotochemicalWitness:
    photon: HeldLabel
    ground_state: str
    excited_state: str
    reaction_channel: str
    def __post_init__(self):
        if self.photon.family!="photon-carrier" or not all(x.strip() for x in (self.ground_state,self.excited_state,self.reaction_channel)) or self.ground_state==self.excited_state: raise InadmissibleExactValue("photochemical witness is invalid")
@dataclass(frozen=True)
class ThermochemistryBlueprint:
    claim_id:str; title:str; statement:str; dependencies:tuple[str,...]; generation_rule:str; grammar_boundary:str; dimensions:tuple[LawDimension,...]; exact_result:str; induction_base:str; induction_step:str; exclusions:tuple[str,...]; operational_witnesses:tuple[tuple[str,str,bool],...]; experiment_id:str; predicted_observation_label:str; falsification_condition:str
    def validate(self):
        if not self.claim_id.startswith("SFT-CHEM-") or not self.experiment_id.startswith("SFT-EXP-CHEM-") or len(self.dimensions)!=8 or len({d.key for d in self.dimensions})!=8: raise ValueError("thermochemistry blueprint invalid")
        for d in self.dimensions:
            if len(d.choices)!=2: raise ValueError("thermochemistry dimension must be binary")
            d.admitted_choice
        if not all(ok for _,_,ok in self.operational_witnesses): raise ValueError("thermochemistry witness failed")
def _dims(rows): return tuple(dimension(*row) for row in rows)
def _exclude(boundary): return ("no thermochemical table, spontaneity rule, phase diagram, solubility value, photochemical database, measured target or V2 answer may select a candidate","no numerical zero, negative, irrational, imaginary or floating proof quantity","no free, fitted, learned or target-derived parameter","no energy, matter or photon carrier may be created, copied or silently erased","absence is an Empty structural form rather than numerical zero","external target content remains inaccessible until the prediction is sealed",boundary)

THERMO_DEPS=REACTION_BASE+("SFT-CHEM-RXN-IDENTITY-001","SFT-CHEM-RXN-MECHANISM-001","SFT-CHEM-RXN-INTERMEDIATE-001","SFT-CHEM-KIN-ACTIVATION-001","SFT-CHEM-KIN-RATE-001","SFT-CHEM-KIN-ORDER-001","SFT-CHEM-EQ-CHEMICAL-001")

THERMO_BOUNDARY="Every finite closed chemical reaction with complete source-bound energy carriers at reactant and product boundaries, held transfer orientation, phase, conditions and reference state."
THERMO_DIMS=_dims((
 ("reaction","energy-value-without-reaction","No chemical identity is retained.","registered-reaction-trace","The exact reaction is held."),("input","reactant-energy-erased","The ledger cannot close.","complete-reactant-energy-support","Every input carrier is counted."),("output","product-energy-erased","The ledger cannot close.","complete-product-energy-support","Every output carrier is counted."),("conservation","free-energy-creation","It violates closure.","energy-transfer-balanced","System and surroundings pair."),("orientation","signed-heat-number","A signed scalar is unnecessary.","held-absorbed-or-released-orientation","Direction is a fibre label."),("conditions","condition-free-value","Thermochemical quantities are state-bound.","phase-condition-reference-held","All external coordinates remain explicit."),("record","enthalpy-answer-only","It cannot reproduce accounting.","reaction-energy-source-trace","All carriers remain auditable."),("extra","free-calibration-fit","A fit can select any value.","no-extra-rule","Complete energy ledger supplies the law.")))
DIRECTION_BOUNDARY="Every finite pair of forward and reverse reaction paths on one retained condition boundary, compared by complete source, energy-transfer and distinction-production support, selecting an orientation only when one path strictly closes the available transition support."
DIRECTION_DIMS=_dims((
 ("paths","forward-path-only","No directional comparison exists.","forward-and-reverse-paths","Both alternatives are generated."),("energy","energy-change-erased","Available support is unknown.","complete-energy-transfer-ledgers","Both ledgers are held."),("distinctions","entropy-label-only","A label cannot count support.","complete-accessible-distinction-census","All generated states are counted."),("comparison","imported-spontaneity-sign","A sign assumes the answer.","strict-support-order","The complete paths determine preference."),("orientation","negative-Gibbs-primitive","A negative scalar is prohibited.","held-favored-direction","Direction and positive magnitude are separate."),("equilibrium","forced-direction-at-tie","Equal support cannot select.","empty-direction-at-equality","A tie is an Empty orientation."),("record","direction-answer-only","It cannot reproduce comparison.","path-energy-distinction-trace","All premises remain auditable."),("extra","free-temperature-threshold","A parameter can force a target.","no-extra-rule","Complete condition-bound support selects direction.")))
PHASE_BOUNDARY="Every finite maximal connected chemical region whose complete intensive observation trace is homogeneous under the declared resolution, separated from a distinct region by a retained interface; coexistence is paired recurrence at that interface."
PHASE_DIMS=_dims((
 ("region","arbitrary-sample-label","It does not define phase identity.","maximal-connected-region","Every same-trace cell is included."),("homogeneity","single-point-observation","It cannot establish uniformity.","complete-intensive-trace-equivalence","All cells share the registered trace."),("extent","size-dependent-phase","Phase identity is intensive.","extent-independent-class","Replication preserves identity."),("boundary","interface-erased","Distinct phases cannot be separated.","retained-phase-interface","Both sides remain named."),("coexistence","one-phase-only","No coexistence relation exists.","paired-interface-recurrence","Both phases persist at one boundary."),("conditions","condition-free-phase","Phase depends on source conditions.","temperature-pressure-composition-held","The phase record is bounded."),("record","phase-name-only","It cannot reproduce homogeneity.","region-trace-interface-record","All distinctions remain auditable."),("extra","free-phase-diagram","An imported diagram selects the class.","no-extra-rule","Maximal trace equivalence supplies phase identity.")))
SOLUTION_BOUNDARY="Every finite solution boundary containing a retained solvent/solute organization and opposed dissolution/return transitions whose complete event supports pair at saturation while the macroscopic dissolved-composition class recurs."
SOLUTION_DIMS=_dims((
 ("solution","unidentified-mixture","Solute and solvent roles are lost.","retained-solute-solvent-organization","Both identities remain held."),("dissolution","one-way-dissolution-only","No equilibrium can close.","dissolution-and-return-transitions","Both paths are generated."),("balance","unpaired-event-support","Composition would drift.","paired-opposed-event-support","Dissolved and returned carriers pair."),("saturation","free-solubility-number","A measured number imports the target.","source-bounded-capacity-boundary","Capacity is finite and condition-bound."),("composition","microscopic-state-fixed","Individual events may continue.","macroscopic-dissolved-class-recurs","The observed solution remains stable."),("conditions","condition-free-solubility","Solubility changes with conditions.","phase-temperature-pressure-held","All source coordinates remain explicit."),("record","solubility-answer-only","It cannot reproduce the dynamics.","solution-event-composition-trace","All carriers remain auditable."),("extra","free-equilibrium-fit","A fit can select any saturation.","no-extra-rule","Opposed recurrence closure supplies the law.")))
PHOTO_BOUNDARY="Every finite chemical path initiated when one retained radiation carrier is absorbed by a named molecular carrier, producing a distinct excited-state support and a source-bound reaction or relaxation channel with complete energy accounting."
PHOTO_DIMS=_dims((
 ("radiation","anonymous-energy-input","It cannot establish carrier identity.","one-retained-photon-carrier","The absorbed support is named."),("absorption","photon-copied","Copying violates conservation.","carrier-absorbed-once","The radiation support enters one molecule."),("state","ground-state-unchanged","No excitation occurs.","distinct-excited-state-support","The molecular state changes."),("channel","unregistered-outcome","No chemical path is retained.","source-bound-reaction-or-relaxation-channel","Every endpoint is named."),("conservation","energy-erased","The path cannot close.","complete-photon-molecule-energy-ledger","Input and outputs balance."),("selection","free-quantum-yield-fit","A fit can force outcomes.","generated-channel-census","All accessible paths are retained."),("record","photochemical-label-only","It cannot reproduce excitation.","photon-state-channel-trace","Every transition remains auditable."),("extra","free-spectral-rule","An imported rule selects a target.","no-extra-rule","Absorption and closed channels supply the law.")))

_E=EnergyLedger(PositiveCount(3),PositiveCount(2),HeldLabel("energy-transfer-orientation","released"),HeldLabel("thermochemical-conditions","state-one"))
_D=DirectionWitness(PositiveCount(3),PositiveCount(2),HeldLabel("reaction-direction","forward"))
_P=PhaseWitness("phase-a",(HeldLabel("intensive-trace","cell-one"),HeldLabel("intensive-trace","cell-two")),HeldLabel("phase-boundary","a-b"))
_S=SolutionEquilibriumWitness(PositiveCount(2),PositiveCount(2),HeldLabel("solution-boundary","vessel-one"))
_F=PhotochemicalWitness(HeldLabel("photon-carrier","photon-one"),"ground","excited","reaction-channel-one")

THERMOCHEMISTRY_BLUEPRINTS=(
 ThermochemistryBlueprint("SFT-CHEM-THERMO-REACTION-001","Reaction thermochemical accounting","Reaction thermochemistry is the complete source-bound energy ledger across one conserved chemical transformation, with transfer orientation, phase, conditions and reference state retained.",THERMO_DEPS,"Generate the literal product of reaction, input, output, conservation, orientation, condition, record and extension choices.",THERMO_BOUNDARY,THERMO_DIMS,"registered-reaction-trace__complete-reactant-energy-support__complete-product-energy-support__energy-transfer-balanced__held-absorbed-or-released-orientation","One reaction with a closed energy ledger supplies the first thermochemical record.","Appending a carrier preserves prior energy support and adds its paired system/surroundings transfer.",_exclude(THERMO_BOUNDARY),(("inputs","input support is positive",_E.input_support==PositiveCount(3)),("outputs","output support is positive",_E.output_support==PositiveCount(2)),("conditions","conditions remain held",_E.conditions.family=="thermochemical-conditions")),"SFT-EXP-CHEM-THERMO-REACTION-001","reaction-energy-change__products-minus-reactants__absorbed-or-released-transfer__state-and-condition-source-bounded","The claim fails if the authority record lacks reaction energy difference, transfer direction or state/condition boundary, or if a changed row is accepted."),
 ThermochemistryBlueprint("SFT-CHEM-THERMO-DIRECTION-001","Reaction direction under complete energy and distinction accounting","Reaction direction is the held orientation selected by strict complete support order between forward and reverse paths; equality yields no selected direction.",THERMO_DEPS+("SFT-CHEM-THERMO-REACTION-001",),"Generate the literal product of path, energy, distinction, comparison, orientation, equilibrium, record and extension choices.",DIRECTION_BOUNDARY,DIRECTION_DIMS,"forward-and-reverse-paths__complete-energy-transfer-ledgers__complete-accessible-distinction-census__strict-support-order__held-favored-direction","One unequal path-support pair supplies the first direction.","Appending a distinction preserves the comparison and changes direction only when the complete strict order changes.",_exclude(DIRECTION_BOUNDARY),(("comparison","forward support is strictly greater",_D.forward_support.value>_D.reverse_support.value),("orientation","the selected direction is held",_D.selected_orientation.family=="reaction-direction"),("tie","equality admits no arbitrary direction",True)),"SFT-EXP-CHEM-THERMO-DIRECTION-001","forward-or-reverse-spontaneous-tendency__Gibbs-energy-condition__equilibrium-at-no-driving-force__direction-state-bounded","The claim fails if the authority record lacks condition-bound forward/reverse tendency and equilibrium at no driving force, or if a changed row is accepted."),
 ThermochemistryBlueprint("SFT-CHEM-PHASE-CHEMICAL-001","Chemical phase and coexistence identity","A chemical phase is a maximal connected region of complete intensive-trace equivalence; coexistence retains two phase identities and their recurrent interface under fixed conditions.",THERMO_DEPS+("SFT-CHEM-THERMO-REACTION-001","SFT-CHEM-THERMO-DIRECTION-001"),"Generate the literal product of region, homogeneity, extent, boundary, coexistence, condition, record and extension choices.",PHASE_BOUNDARY,PHASE_DIMS,"maximal-connected-region__complete-intensive-trace-equivalence__extent-independent-class__retained-phase-interface__paired-interface-recurrence","One homogeneous connected region supplies the first phase.","Appending an equivalent adjacent cell extends the same maximal phase; a distinct trace creates a retained interface.",_exclude(PHASE_BOUNDARY),(("identity","the phase is named",bool(_P.phase_identity)),("trace","multiple cells share the phase trace",len(_P.homogeneous_trace)==2),("boundary","the interface is held",_P.boundary.family=="phase-boundary")),"SFT-EXP-CHEM-PHASE-CHEMICAL-001","homogeneous-material-region__uniform-intensive-properties__phase-boundary-retained__coexistence-condition-bounded","The claim fails if the authority record lacks homogeneous intensive properties, a phase boundary or condition-bound coexistence, or if a changed row is accepted."),
 ThermochemistryBlueprint("SFT-CHEM-SOLUTION-EQUILIBRIUM-001","Solution and solubility equilibrium","Solubility equilibrium is paired dissolution and return recurrence on a retained solution boundary, preserving a condition-bound macroscopic dissolved-composition class at finite saturation.",THERMO_DEPS+("SFT-CHEM-EQ-CHEMICAL-001","SFT-CHEM-PHASE-CHEMICAL-001"),"Generate the literal product of solution, dissolution, balance, saturation, composition, condition, record and extension choices.",SOLUTION_BOUNDARY,SOLUTION_DIMS,"retained-solute-solvent-organization__dissolution-and-return-transitions__paired-opposed-event-support__source-bounded-capacity-boundary__macroscopic-dissolved-class-recurs","One paired dissolution/return recurrence supplies the first saturated solution equilibrium.","Appending a paired event preserves carrier balance and the same macroscopic dissolved class.",_exclude(SOLUTION_BOUNDARY),(("balance","dissolution and return counts match",_S.dissolved_events==_S.returned_events),("activity","both event supports are positive",_S.dissolved_events==PositiveCount(2)),("boundary","the solution boundary is retained",_S.solution_boundary.family=="solution-boundary")),"SFT-EXP-CHEM-SOLUTION-EQUILIBRIUM-001","dissolution-and-crystallization-continue__rates-balanced-at-saturation__dissolved-composition-constant__solubility-condition-bounded","The claim fails if the authority record lacks opposed dissolution/crystallization, saturation balance or condition-bounded solubility, or if a changed row is accepted."),
 ThermochemistryBlueprint("SFT-CHEM-PHOTOCHEM-001","Photochemical excitation and reaction channel","A photochemical event absorbs one retained photon carrier into a named molecular carrier, produces distinct excited support and closes through a generated reaction or relaxation channel with complete energy accounting.",THERMO_DEPS+("SFT-CHEM-RXN-MECHANISM-001","SFT-CHEM-KIN-ACTIVATION-001","SFT-CHEM-THERMO-REACTION-001"),"Generate the literal product of radiation, absorption, state, channel, conservation, selection, record and extension choices.",PHOTO_BOUNDARY,PHOTO_DIMS,"one-retained-photon-carrier__carrier-absorbed-once__distinct-excited-state-support__source-bound-reaction-or-relaxation-channel__complete-photon-molecule-energy-ledger","One photon absorption and one closed molecular channel supply the first photochemical event.","Appending a channel preserves photon and molecular energy accounting and adds only generated accessible endpoints.",_exclude(PHOTO_BOUNDARY),(("photon","the radiation carrier is retained",_F.photon.family=="photon-carrier"),("state","ground and excited states differ",_F.ground_state!=_F.excited_state),("channel","the outcome path is named",bool(_F.reaction_channel))),"SFT-EXP-CHEM-PHOTOCHEM-001","light-absorption-initiates-chemical-change__molecular-excited-state__reaction-or-relaxation-pathways__photon-energy-accounted","The claim fails if the authority record lacks light absorption, excited molecular state, reaction/relaxation pathways or photon-energy accounting, or if a changed row is accepted."))
for _b in THERMOCHEMISTRY_BLUEPRINTS: _b.validate()
__all__=("THERMOCHEMISTRY_BLUEPRINTS","ThermochemistryBlueprint")
