from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-MULTIMODAL-MOLECULAR-IDENTITY-021'
DOMAINS=(('independent-modality-identities', 'one-held-molecular-carrier'), ('selected-diagnostic-modalities', 'complete-orthogonal-record-family'), ('database-first-answer', 'complete-generated-carrier-candidate-set'), ('fitted-similarity-score', 'exact-record-candidate-incidence'), ('majority-vote-identity', 'exact-complete-support-intersection'), ('best-ranked-candidate', 'one-unique-common-carrier-or-halt'), ('discarded-conflicting-modality', 'complete-conflict-absence-unresolved-custody'), ('refitted-new-modality', 'successor-intersects-without-changing-prior-records'))
SURVIVOR='one-held-molecular-carrier__complete-orthogonal-record-family__complete-generated-carrier-candidate-set__exact-record-candidate-incidence__exact-complete-support-intersection__one-unique-common-carrier-or-halt__complete-conflict-absence-unresolved-custody__successor-intersects-without-changing-prior-records'
DIMENSION_KEYS=('carrier', 'records', 'candidates', 'comparison', 'intersection', 'uniqueness', 'adversity', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
