from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-PHOSPHORESCENCE-INTERSYSTEM-011';DOMAINS=(('detached-phosphorescence-number', 'held-molecular-carrier'), ('phosphorescence-without-spin-path', 'held-distinct-source-and-intersystem-spin-states'), ('single-emission-arrow', 'held-excitation-intersystem-final-state-path'), ('signed-floating-emission-value', 'exact-positive-emission-support-or-EmptyOne'), ('fitted-phosphorescence-yield', 'exact-outcome-over-excitation-ratio-or-EmptyOne'), ('imported-continuous-tail', 'exact-positive-finite-lifetime-or-EmptyOne'), ('selected-long-lived-emissions', 'complete-emission-lifetime-spin-condition-custody'), ('refitted-added-intersystem-path', 'successor-retains-and-appends-complete-paths'));SURVIVOR='held-molecular-carrier__held-distinct-source-and-intersystem-spin-states__held-excitation-intersystem-final-state-path__exact-positive-emission-support-or-EmptyOne__exact-outcome-over-excitation-ratio-or-EmptyOne__exact-positive-finite-lifetime-or-EmptyOne__complete-emission-lifetime-spin-condition-custody__successor-retains-and-appends-complete-paths'
from fractions import Fraction
EMPTY="EmptyOne"
rows=(("molecule-a","excited-a","intersystem-a","ground-a","hand-a","hand-b",Fraction(5,2),1,4,Fraction(7,3)),("molecule-a","excited-b","intersystem-b","ground-a","hand-b","hand-a",EMPTY,EMPTY,4,EMPTY))
native={"carrier":all(x[0]=="molecule-a" for x in rows),"spin":all(x[4]!=x[5] for x in rows),"path":all(x[1]!=x[2] and x[2]!=x[3] for x in rows),"emission":rows[0][6]==Fraction(5,2) and rows[1][6]==EMPTY,"yield":Fraction(rows[0][7],rows[0][8])==Fraction(1,4) and rows[1][7]==EMPTY,"lifetime":rows[0][9]==Fraction(7,3) and rows[1][9]==EMPTY,"custody":len(rows)==2,"extension":tuple(rows)==rows}
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};passed=sealed["claim_id"]==CLAIM_ID and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(item["passed"] for item in sealed["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
