"""Implementation-distinct value-free KIN-013 reconstruction."""
from fractions import Fraction
from itertools import product
import json,sys
CLAIM='SFT-CHEM-REACTION-DYNAMICS-SCATTERING-PRODUCT-STATE-013'
DOMAINS=(('incoming-carriers-erased-or-replaced-by-continuum-beam', 'finite-held-incoming-channel-and-preparation'), ('selected-product-or-continuous-outgoing-distribution', 'complete-finite-distinct-outgoing-product-state-support'), ('coproduct-states-separated-or-marginalized', 'joint-ordered-coproduct-state-word'), ('imported-cross-section-probability-amplitude-or-fitted-density', 'completed-state-events-per-complete-positive-event-support'), ('signed-angle-continuum-or-numerical-zero-direction', 'held-incoming-outgoing-orientation-relation'), ('selected-normalized-or-favorable-product-vector', 'complete-51-record-36-page-14-worksheet-978591-cell-vector'), ('experimental-theoretical-fitted-estimated-and-tentative-records-mixed', 'experiment-theory-fit-estimate-tentative-control-and-review-status-separated'), ('product-values-workbook-or-target-readable-before-seal', 'value-free-51-record-identity-seal-and-depth-independent-scattering-successor'))
SURVIVOR='finite-held-incoming-channel-and-preparation__complete-finite-distinct-outgoing-product-state-support__joint-ordered-coproduct-state-word__completed-state-events-per-complete-positive-event-support__held-incoming-outgoing-orientation-relation__complete-51-record-36-page-14-worksheet-978591-cell-vector__experiment-theory-fit-estimate-tentative-control-and-review-status-separated__value-free-51-record-identity-seal-and-depth-independent-scattering-successor'
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; received=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}
 incoming=("reaction","reactant-a","reactant-b","preparation"); outgoing=((1,"product-a-state-1","product-b-state-1","same-oriented",3),(2,"product-a-state-2","product-b-state-2","transverse-oriented",2),(3,"product-a-state-3","product-b-state-3","opposed-oriented",1)); total=sum(row[-1] for row in outgoing); shares=tuple(Fraction(row[-1],total) for row in outgoing); prior=(("occurrence-a",shares),); extended=prior+(("occurrence-b",shares),)
 witnesses=(len(incoming)==4 and tuple(row[0] for row in outgoing)==(1,2,3) and len({row[1:4] for row in outgoing})==3 and shares==(Fraction(1,2),Fraction(1,3),Fraction(1,6)) and tuple(row[3] for row in outgoing)==("same-oriented","transverse-oriented","opposed-oriented") and extended[:len(prior)]==prior and len(extended)==len(prior)+1)
 passed=(d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={candidate:candidate==SURVIVOR for candidate in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {row["kind"] for row in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(row["passed"] for row in d["controls"]) and witnesses)
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"finite_incoming_and_complete_distinct_outgoing_joint_product_state_support_reconstructed":witnesses,"exact_positive_state_shares_and_all_three_held_orientation_relations_reconstructed":witnesses,"scattering_occurrence_successor_preserves_prior_family":witnesses,"numerical_zero_negative_irrational_imaginary_signed_or_continuum_proof_value_used":False,"scattering_equation_cross_section_law_probability_amplitude_potential_fit_normalization_target_measurement_or_source_file_accessed":False}},sort_keys=True))
if __name__=="__main__":main()
