from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-DOUBLE-LAYER-INTERFACIAL-CHARGE-011';DOMAINS=(('bulk-charge-number', 'one-held-electrode-electrolyte-interface'), ('continuum-profile-premise', 'complete-finite-ordered-interface-layers'), ('anonymous-charge-density', 'held-species-resolved-charge-carriers'), ('signed-interfacial-charge', 'held-opposed-interface-sides'), ('unreferenced-potential', 'exact-positive-interface-potential-separation'), ('fitted-capacitance-parameter', 'exact-carrier-per-potential-ratio'), ('numerical-zero-charge-state', 'structural-EmptyOne-interface-coincidence'), ('selected-capacitance-point', 'complete-interface-potential-capacitance-vector'));SURVIVOR='one-held-electrode-electrolyte-interface__complete-finite-ordered-interface-layers__held-species-resolved-charge-carriers__held-opposed-interface-sides__exact-positive-interface-potential-separation__exact-carrier-per-potential-ratio__structural-EmptyOne-interface-coincidence__complete-interface-potential-capacitance-vector'
from fractions import Fraction
def layer(n,side):return (n,side,side,n)
def double(rows,p):return (rows,None) if p is None else (rows,Fraction(sum(x[3] for x in rows),1)/p)
r=double((layer(1,"electrode"),layer(2,"solution")),Fraction(3,2));z=double((layer(1,"electrode"),),None);native={"layers":len(r[0])==2,"order":tuple(x[0] for x in r[0])==(1,2),"species":len({x[2] for x in r[0]})==2,"sides":len({x[1] for x in r[0]})==2,"potential":Fraction(3,2)>0,"capacitance":r[1]==2,"coincidence":z[1] is None,"interface":True}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
