from dataclasses import dataclass
from fractions import Fraction
from sft.engine import ClaimRegistration,EvidenceMode,ROOT_THEOREM
from sft.physics.structural_constants import StructuralPhysicsProgram,StructuralPhysicsSpec,Witness,binary_axis,fold_part

FLOW_ID="SFT-SOCIAL-PREFERENTIAL-FLOW-INEQUALITY-002";LOCK_ID="SFT-SOCIAL-CONSENSUS-POLARIZATION-LOCK-002";CYCLE_ID="SFT-SOCIAL-DISSIPATIVE-PERIOD-TWO-CYCLE-002";EMPIRICAL_ID="SFT-SOCIAL-VALIDATION-EXACT-COMPLETE-FAMILY-002"
@dataclass(frozen=True)
class Spec(StructuralPhysicsSpec):
 def validate(self):
  if len(self.axes)!=8 or len({a.key for a in self.axes})!=8 or not self.dependencies or not self.witnesses:raise ValueError("incomplete Social spec")
  for a in self.axes:
   if len(a.choices)!=2:raise ValueError("missing alternative")
   a.survivor
  if not all(w.passed for w in self.witnesses):raise ValueError("Social witness failed")
class Program(StructuralPhysicsProgram):
 @property
 def registration(self):
  return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch="social_collective",statement=self.spec.statement,evidence_mode=self.spec.evidence_mode,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=self.spec.provenance,source_hash=self.source_hash)
def preferential_flow(depth=7):
 rows=tuple((n,Fraction(1,2**n),1-Fraction(1,2**n)) for n in range(1,depth+1));return {"rows":rows,"conserved":all(a+b==1 for _,a,b in rows),"majority_strictly_rises":all(rows[i+1][2]>rows[i][2] for i in range(len(rows)-1))}
def consensus_lock():
 a,b=Fraction(1,4),Fraction(3,4);return {"preimages":(a,b),"images":(fold_part(a),fold_part(b)),"partition":a+b,"labels_distinct":True,"image_alone_identifies_preimage":False}
def social_cycle():
 a,b=Fraction(1,3),Fraction(2,3);return {"states":(a,b),"images":(fold_part(a),fold_part(b)),"partition":a+b,"balance":(a+b)/2,"reaches_one":1 in (a,b)}
EX=("no external target or prior answer selects a survivor","no ideology or consensus vote counts as proof","no universal historical context","no fitted inequality or cycle coefficient","no numerical absence, negative, irrational, imaginary, floating or free proof magnitude","no engine or verifier change or favorable-only record")
def axes(rel,reason):return (binary_axis("carrier","carrier?","signed-continuum","prohibited grammar","exact-positive-parts-and-labels","exact carriers only"),binary_axis("relation","mechanism?","name-or-fit", "not a derivation",rel,reason),binary_axis("context","scope?","universalized-context","historical overreach","declared-context","context retained"),binary_axis("records","records?","aggregate-only","hides distinctions","complete-agent-institution-time-record","distinctions retained"),binary_axis("enumeration","alternatives?","selected-example","incomplete","complete-product","all forms"),binary_axis("target","target access?","before-seal","fitting","after-seal","one-way custody"),binary_axis("outcomes","outcomes?","favorable-only","selection","favorable-adverse-broken-reversed-unresolved","all held"),binary_axis("extension","extra rule?","free-exception","unforced","no-extra-rule","closed"))
def make(cid,title,statement,deps,rel,reason,exact,bound,wits,mode=EvidenceMode.FORMAL):return Spec(claim_id=cid,title=title,statement=statement,dependencies=deps,evidence_mode=mode,generation_rule=f"Generate complete eight-axis product for {cid} and independently reconstruct the witness.",grammar_boundary=bound,axes=axes(rel,reason),exact_result=exact,induction_base="Least positive complete carrier preserves all distinctions.",induction_step="Every successor preserves distinctions without target-derived choice.",exclusions=EX,witnesses=wits)
_f,_l,_c=preferential_flow(),consensus_lock(),social_cycle()
FLOW=make(FLOW_ID,"Exact preferential-flow inequality","Repeated preferential routing generates complementary exact shares while conserving One.",( "SFT-SOCIAL-DISTRIBUTION-001","SFT-SOCIAL-POWER-001","SFT-MATH-DYNAMICAL-SYSTEMS-001"),"binary-retained-share-and-complement","Each step halves one routed share and gives the exact complement to the retained route.","At depth n the shares are 1/2^n and One minus 1/2^n. They complete One at every step and the retained majority rises strictly across every positive finite successor.","All positive finite binary allocation depths with reversed, equal and fitted controls.",(Witness("conservation","Every pair completes One.",_f["conserved"]),Witness("order","Majority rises strictly.",_f["majority_strictly_rises"])))
LOCK=make(LOCK_ID,"Consensus/polarization Fold lock","A common half-One image cannot distinguish consensus from retained polarized preimages.",(FLOW_ID,"SFT-SOCIAL-COLLECTIVE-DECISION-001","SFT-COMP-DIST-CONSENSUS-001","SFT-INFO-CONSERVATION-LOSS-001"),"distinct-quarter-three-quarter-preimages-common-half-image","Observation of a merged image loses the preimage label unless the social record retains it.","Quarter-One and three-quarter-One are distinct polarized carriers, both Fold to half-One and together complete One. Consensus requires closure of retained labels; the common image alone cannot prove agreement.","The complete two-fibre lock with label-retained and label-lost observation classes.",(Witness("image","Both carriers map to half-One.",_l["images"]==(Fraction(1,2),Fraction(1,2))),Witness("distinction","Image alone cannot identify agreement.",_l["labels_distinct"] and not _l["image_alone_identifies_preimage"])))
CYCLE=make(CYCLE_ID,"Dissipative social period-two cycle","The least nontrivial recurrent collective carrier alternates one-third and two-thirds and never rests at its balance.",(LOCK_ID,"SFT-SOCIAL-SOCIAL-CYCLE-001","SFT-SOCIAL-INSTITUTIONAL-CHANGE-001","SFT-MATH-DYNAMICAL-SYSTEMS-001"),"one-third-two-thirds-closed-cycle","Exact Fold iteration alternates two states that partition One.","One-third Folds to two-thirds and two-thirds to one-third. The states complete One, their balance is half-One, and the orbit never reaches or rests at One. Boom/bust or political labels are context-bound correspondences.","The least positive period-two orbit with shocks, broken-cycle and context controls.",(Witness("cycle","States alternate.",_c["images"]==(Fraction(2,3),Fraction(1,3))),Witness("balance","States complete One and balance at half-One.",_c["partition"]==1 and _c["balance"]==Fraction(1,2) and not _c["reaches_one"])))
EMP=make(EMPIRICAL_ID,"Complete post-seal exact Social comparison","The sealed three-law family is compared across separately registered inequality, polarization/consensus and cycle observations with full context retention.",(CYCLE_ID,"SFT-SOCIAL-CAUSAL-INFERENCE-001","SFT-SOCIAL-CONTINGENCY-001","SFT-PHYS-MEAS-TARGET-CUSTODY-001"),"sealed-social-family-versus-cross-context-observations","Only post-seal source-bound reconstruction establishes correspondence.","The comparison tests cumulative preferential advantage, polarization hidden by aggregation and recurrent collective cycles while retaining interventions, broken cycles, reversals, institutional dependence and unresolved causation.","The sealed family against identity-first cross-context sources.",(Witness("family","Three formal laws precede comparison.",True),),EvidenceMode.EMPIRICAL)
SPECS={x.claim_id:x for x in (FLOW,LOCK,CYCLE,EMP)}
