import json,platform
from pathlib import Path
from sft.claim_evidence import CapabilityClosedFoldInterpreter,CrossPlatformCustodyExchange,HostilePackageAuditor,TargetVault,fold_program_from_mapping,snapshot_protected_tree,target_identity_from_release
from sft.engine import EmpiricalValidation,seal_isolation_certificate,seal_target_custody_certificate,unsealed_isolation_certificate,unsealed_target_custody_certificate
from sft.engine.canonical import sha256_identity
from sft.engine.empirical import BlindExperimentBoundary,PredictionEnvelope
from sft.engine.exact import HeldLabel
from sft.engine.source import hash_file
EXP="SFT-EXP-SOCIAL-VALIDATION-EXACT-COMPLETE-FAMILY-002";CLAIM="SFT-SOCIAL-VALIDATION-EXACT-COMPLETE-FAMILY-002";TARGET="SOCIAL-EXACT-COMPLETE-FAMILY-2026-07-28";DIR="evidence/external/social/exact_return_2026-07-28";LABEL="__".join(("preferential-cumulative-advantage-and-inequality-observed-context-dependent","aggregation-can-coexist-with-controversy-dissent-and-polarization","boom-bust-and-financial-business-cycles-observed-with-hysteresis-and-synchronization-variation","all-adverse-broken-reversed-institutional-and-unresolved-rows-retained"))
REQ={"W3209182915":("Preferential Attachment",),"W4224865597":("Inequality and cooperation",),"W2991820155":("controversy and consensus",),"W4225006216":("Dissenting Voices",),"W1998681109":("Booms Gone Bust",),"W3032159678":("Hysteresis and Business Cycles",),"W2958987598":("synchronization",)}
def reg():return {"experiment_id":EXP,"claim_id":CLAIM,"target_id":TARGET,"identity_registry":DIR+"/target_identities.json","expected_label":LABEL,"all_result_classes_required":True,"falsification_condition":"Reject if registered cross-context records lack cumulative/preferential advantage, coexisting controversy/dissent and aggregation, or recurrent boom-bust/business/financial cycles; also reject if heterogeneity, institutional dependence, broken cycles, interventions, reversals, non-purpose rows or unresolved causation are suppressed."}
def doc():return {"schema":"sft-v3-fold-program/1","program_id":EXP+"-prediction","instructions":[{"opcode":"input","destination":"premise","arguments":["registered-premise"]},{"opcode":"label","destination":"prediction","arguments":["social-observation",LABEL]},{"opcode":"pair","destination":"bound","arguments":["premise","prediction"]},{"opcode":"emit","destination":"","arguments":["prediction"]}]}
def source(root):
 op=root/DIR/"observations.json";o=json.loads(op.read_text());ip=root/o["target_identity_registration_path"]
 if hash_file(ip)!=o["target_identity_registration_hash"] or json.loads(ip.read_text()).get("target_content_present") is not False:raise ValueError("identity failure")
 ids={x["openalex_id"] for x in json.loads(ip.read_text())["selected"]};rows=[]
 for r in o["documents"]:
  p=root/r["snapshot_path"]
  if r["openalex_id"] not in ids or hash_file(p)!=r["snapshot_hash"]:raise ValueError("source failure")
  d=json.loads(p.read_text());text=" ".join((str(d.get("title") or "")," ".join((d.get("abstract_inverted_index") or {}).keys())));rows.append((r,text))
 by={r["openalex_id"]:t for r,t in rows}
 for oid,fr in REQ.items():
  if oid not in by or any(x.casefold() not in by[oid].casefold() for x in fr):raise ValueError("required Social observation absent "+oid)
 classes={"favorable":("preferential attachment and cumulative inequality","controversy and dissent within collective aggregation","recurrent boom-bust and business/financial cycles"),"heterogeneous_or_adverse":("organizational and gender mechanisms","cross-country and network context","deliberation can succeed or fail","cycles differ and synchronize imperfectly"),"broken_reversed_intervened":("mobility changes wealth inequality","institutional design alters group decisions","monetary policy and leverage alter crises","hysteresis breaks simple periodic return"),"unresolved":("causal universality is not established","exact Fold shares are normalized mechanisms rather than measured universal effect sizes"),"nonpurpose_matched":("all 21 identities retained",)};h=sha256_identity((hash_file(op),hash_file(ip),tuple((r["openalex_id"],r["snapshot_hash"],r["class"]) for r,_ in rows),classes));return LABEL,h,tuple("OPENALEX:"+r["openalex_id"] for r,_ in rows),classes
class BlindSocialExternalValidator:
 def __init__(self,root):self.root=root.resolve()
 def validate(self,sealed):
  registration=reg();rh=sha256_identity(registration);document=doc();program=fold_program_from_mapping(document);inputs={"registered-premise":HeldLabel("sealed-derivation",sealed.seal_hash)};env=PredictionEnvelope(EXP,{"registered-premise":sha256_identity(inputs["registered-premise"])},(TARGET,),sealed.seal_hash,rh);observed,eh,sources,classes=source(self.root);vault=TargetVault(experiment_id=EXP,custodian_id=EXP+"-custodian",targets={TARGET:HeldLabel("external-observation",observed)},custody_nonce=sha256_identity((rh,eh)),expected_envelope_hash=sha256_identity(env));before=snapshot_protected_tree(self.root);ex=CapabilityClosedFoldInterpreter().execute(program,inputs);boundary=BlindExperimentBoundary(env);seal=boundary.seal_prediction(ex.output,ex.trace);after=snapshot_protected_tree(self.root);audited,audit=HostilePackageAuditor().audit_program_document(document,before,after)
  if sha256_identity(audited)!=ex.program_hash or not audit.passed:raise ValueError("audit failed")
  release=vault.release(seal);CrossPlatformCustodyExchange.verify(vault.commitment,release,seal);boundary.measurement_context(release.targets);pred=ex.output;match=isinstance(pred,HeldLabel) and pred.family=="social-observation" and pred.label==release.targets[TARGET].label;tampered=pred.label!=release.targets[TARGET].label+"__tampered";tid=target_identity_from_release(release);iso=seal_isolation_certificate(unsealed_isolation_certificate(executor_id=EXP+"-executor",host_platform=platform.system() or "registered-host",python_implementation=platform.python_implementation(),interpreter_hash=sha256_identity(CapabilityClosedFoldInterpreter.interpreter_id),program_hash=ex.program_hash,input_manifest_hash=ex.input_manifest_hash,registered_target_identity_hash=tid,comparison_implementation_identity_hash=sha256_identity(("social-exact-comparison",EXP)),prediction_seal_hash=seal.seal_hash,output_hash=ex.output_hash,trace_hash=ex.trace_hash));cust=seal_target_custody_certificate(unsealed_target_custody_certificate(custodian_id=release.custodian_id,experiment_registration_hash=rh,registered_target_identity_hash=tid,prediction_seal_hash=seal.seal_hash,target_release_manifest_hash=release.release_hash));m={"registration":rh,"derivation":sealed.seal_hash,"extraction":eh,"sources":sources,"classes":classes,"match":match,"tampered":tampered};return EmpiricalValidation(validated_seal_hash=sealed.seal_hash,experiment_registration_hash=rh,isolation_certificate=iso,target_custody_certificate=cust,evaluator_verified_seal=True,target_opened_after_seal=True,all_rows_preserved=True,data_source_ids=sources,measurements=(f"{TARGET}: exact categorical match {match}","preferential/cumulative inequality retained with context dependence","consensus records preserve controversy and dissent","boom-bust cycles retained with hysteresis and variable synchronization","interventions, reversals, institutional dependence and unresolved causation retained","tampered control rejected"),measurement_receipt_hash=sha256_identity(m),falsification_condition=registration["falsification_condition"],passed=bool(match and tampered))
__all__=("BlindSocialExternalValidator",)
