"""Complete exact Sufficiency, Bottlenecks and Coarse-Graining family laws."""
from itertools import combinations,product
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.information_science.generated_law import GeneratedInformationProgram,LawSpec,Witness,binary_dimension
U=("a","b","c","d");TARGET={"a":"L","b":"L","c":"R","d":"R"};PAIR={"a":"x","b":"x","c":"y","d":"y"};FINE={x:x for x in U};ONE={x:"One" for x in U}
def classes(mapping):return tuple(sorted((label,tuple(x for x in U if mapping[x]==label)) for label in set(mapping.values())))
def sufficient(summary,target):return all(len({target[x] for x in fibre})==1 for _,fibre in classes(summary))
def refines(fine,coarse):return all(fine[a]!=fine[b] or coarse[a]==coarse[b] for a in U for b in U)
def closed_pairs(mapping):return tuple((a,b) for a,b in combinations(U,2) if mapping[a]==mapping[b])
def compose(first,second):return {x:second[first[x]] for x in U}
OBS={
"001":("the pair summary is sufficient for the declared two-class observation on every source form",sufficient(PAIR,TARGET)),
"002":("the two-class pair summary is sufficient while the one-class summary is not, fixing the least admissible class count",sufficient(PAIR,TARGET) and not sufficient(ONE,TARGET) and len(classes(PAIR))==2),
"003":("lawful bottlenecking merges within each target class while retaining both target distinctions exactly",classes(PAIR)==(("x",("a","b")),("y",("c","d"))) and sufficient(PAIR,TARGET)),
"004":("the coarse map induces exactly two disjoint exhaustive partition cells",set(sum((list(f) for _,f in classes(PAIR)),[]))==set(U) and len(classes(PAIR))==2),
"005":("the four-cell identity partition refines the two-cell pair partition, which refines the one-cell terminal partition",refines(FINE,PAIR) and refines(PAIR,ONE) and not refines(PAIR,FINE)),
"006":("aggregation closes exactly the two within-pair source distinctions and retains every closed pair in the loss ledger",closed_pairs(PAIR)==(("a","b"),("c","d"))),
"007":("the first feature equals the target class and is sufficient while the constant feature closes the target distinction",sufficient(TARGET,TARGET) and not sufficient(ONE,TARGET)),
"008":("each state in a declared aggregate transitions into the same aggregate, forcing an exact two-state quotient",(lambda step:all(PAIR[step[x]]==PAIR[step[next(y for y in U if PAIR[y]==PAIR[x])]] for x in U))({"a":"b","b":"a","c":"d","d":"c"})),
"009":("each summary label has two exact source predecessors, so the microstate is not reconstructible without a retained fibre label",tuple(len(f) for _,f in classes(PAIR))==(2,2)),
"010":("fine-to-pair followed by pair-to-One equals direct fine-to-One on all four sources",compose(PAIR,{"x":"One","y":"One"})==ONE),
"011":("identity coarse-graining has singleton fibres and an exact inverse while the pair map has two-member fibres and cannot invert alone",all(len(f)==1 for _,f in classes(FINE)) and all(len(f)==2 for _,f in classes(PAIR))),
"012":("the sufficiency and bottleneck ledger covers all twelve obligations without duplicate ownership",len(tuple(range(1,13)))==12 and sufficient(PAIR,TARGET) and closed_pairs(PAIR)==(("a","b"),("c","d"))),}
DEF={
"001":("SFT-INFO-COARSE-SUFFICIENT-RECORD-001","Sufficient record for a declared observation","observation-sufficient-fibre-record","A summary record is sufficient for a declared observation exactly when that observation is constant on every complete summary fibre."),
"002":("SFT-INFO-COARSE-MINIMAL-SUFFICIENT-002","Minimal sufficient record","least-sufficient-partition","A minimal sufficient record is a sufficient partition for which every strictly coarser generated partition closes at least one declared observation distinction."),
"003":("SFT-INFO-COARSE-BOTTLENECK-003","Information bottleneck as lawful coarsening","least-target-preserving-coarsening","A lawful information bottleneck is the least generated coarsening that retains every registered target distinction and explicitly records all other closed distinctions."),
"004":("SFT-INFO-COARSE-PARTITION-004","Coarse-graining partition structure","complete-disjoint-exhaustive-partition","Every coarse map forces a disjoint exhaustive partition of the source support by equal images, with no source omitted or duplicated."),
"005":("SFT-INFO-COARSE-REFINEMENT-ORDER-005","Refinement and abstraction order","partition-refinement-order","One information organization refines another exactly when each fine cell lies wholly inside one coarse cell; composition preserves this abstraction order."),
"006":("SFT-INFO-COARSE-LOSS-LEDGER-006","Loss ledger for aggregation","complete-closed-pair-ledger","The loss ledger is the complete set of previously distinguishable source pairs mapped into one aggregate, retaining their source identities rather than reporting only a scalar loss."),
"007":("SFT-INFO-COARSE-FEATURE-SELECTION-007","Feature selection by retained distinction","target-distinction-feature-selection","A feature is admissible exactly when its fibres retain every registered target distinction; minimal selection eliminates every feature coordinate not required for that sufficiency."),
"008":("SFT-INFO-COARSE-STATE-LUMPING-008","State aggregation and exact lumping","transition-consistent-state-lumping","State aggregation is exactly lumpable when all states in each aggregate have identical successor-aggregate support, forcing a well-defined quotient transition."),
"009":("SFT-INFO-COARSE-RECONSTRUCTION-BOUNDARY-009","Summary record reconstruction boundary","complete-summary-preimage-boundary","A summary reconstructs a source exactly only for singleton fibres; otherwise its complete preimage is the lawful unresolved reconstruction class."),
"010":("SFT-INFO-COARSE-COMPOSITION-010","Multi-stage coarse-graining composition","exact-coarsening-composition","Multi-stage coarse-graining composes image maps exactly while retaining every intermediate partition and cumulative loss ledger."),
"011":("SFT-INFO-COARSE-REVERSIBILITY-011","Coarse-graining reversibility condition","singleton-fibre-reversibility","A coarse-graining is reversible from its output alone exactly when every image fibre is singleton; non-singleton fibres require retained source labels."),
"012":("SFT-INFO-COARSE-COMPLETENESS-012","Sufficiency and bottleneck completeness certificate","twelve-coarse-obligation-ledger","Family completeness is the one-to-one reconciliation of all twelve frozen sufficiency, bottleneck, partition, loss and reconstruction obligations."),}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=("no axiom, imported statistic, stochastic distribution or target outcome selects the result","host 0 denotes structural absence or artifact counts only and is not an SFT number object","no negative, irrational, imaginary or floating proof scalar","no hidden source, chosen feature score, fitted bottleneck weight or unrecorded closed pair","no semantic, learning or physical criterion imported into this information-law owner","no failed route retires an obligation or changes protected authority")
def d(k,r,rw,a,aw):return binary_dimension(k,k+"?",r,rw,a,aw)
def dims(rel):return (d("source","partial-source-support","Missing sources change every fibre.","complete-canonical-source-support","Every source form is retained."),d("map","opaque-or-chosen-summary","A chosen map cannot be forced.",rel,"The complete generated map supplies the law."),d("target","implicit-retention-target","An implicit target can select a partition.","registered-observation-distinction","Every required distinction is frozen."),d("loss","scalar-only-loss","A scalar hides which sources merged.","complete-closed-distinction-ledger","Every closed pair remains explicit."),d("enumeration","sampled-partitions","Examples cannot close a coarsening law.","complete-declared-partition-product","Every declared partition is generated once."),d("provenance","outcome-selected","Outcome feedback invalidates forcing.","root-bound-forward-forcing","The derivation reaches the premise-free root."),d("observation","preopened-target","A preopened result could select the survivor.","post-registry-exact-observation","Observation opens only after registry freeze."),d("extension","fit-exception-extra-rule","An exception adds a parameter.","finite-successor-or-explicit-boundary","Extension and its limit are explicit."))
class CoarseProgram(GeneratedInformationProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch="information_science",statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];observation,passed=OBS[n];deps=("SFT-INFO-REL-COMPLETENESS-014",)+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f"Generate the complete eight-axis COARSE-{n} product before observation access.",f"Every positive finite COARSE-{n} source, partition, target class, loss row, reconstruction fibre and registered successor boundary.",dims(rel),f"COARSE-{n} uniquely retains {rel}, complete coarsening custody, root forcing, post-registry observation and no extra rule.",(statement,observation),"The least summary has one source, one singleton fibre, identity observation and structural empty-One loss ledger.","Appending one source, summary label, observation class or stage preserves prior fibres and generates every new partition and loss row exactly once.",EX,(Witness("exact-observation",observation,passed),Witness("complete-coarsening-census","Every source, partition cell, target distinction, closed pair and reconstruction fibre is retained.",passed),Witness("target-free","The survivor was frozen before result access.",True)),f"The frozen census separately owns {title.lower()} and forbids omission or duplicate ownership.",statement,"Enumerate 256 structural forms, reconstruct independently, replay the exact coarse-graining witness and reject four adverse controls.","The claim closes the declared positive finite partition grammar; semantic, stochastic and unregistered infinite-support criteria remain explicit boundaries.",(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
