"""Complete Classical, Probabilistic and Quantum-Support Correspondence laws."""
from itertools import product
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.information_science.generated_law import GeneratedInformationProgram,LawSpec,Witness,binary_dimension
F=('L','R');JOINT=tuple(product(F,repeat=2));PAIRED=(('L','L'),('R','R'))
def image(rows,source):return tuple(out for held,out in rows if held==source)
def product_support(left,right):return tuple(product(left,right))
def marginals(rows):return tuple(sorted({x for x,_ in rows})),tuple(sorted({y for _,y in rows}))
def factorable(rows):
 left,right=marginals(rows);return tuple(rows)==product_support(left,right)
def observe(word,classes):return classes[word]
OBS={
'001':('the two forced fibre labels map bijectively to two classical symbols and reconstruct exactly',tuple({'L':'symbol-left','R':'symbol-right'}[x] for x in F)==('symbol-left','symbol-right')),
'002':('a deterministic singleton support has one retained outcome of one possible outcome without importing a stochastic law',(1,1)==(len(('L',)),len(('L',)))),
'003':('a hidden two-source mixture retains both exact source alternatives while the public observation closes their source label',tuple((source,'public') for source in F)==(('L','public'),('R','public'))),
'004':('the complete width-two Fold-word support contains exactly four basis-labelled support forms',JOINT==(('L','L'),('L','R'),('R','L'),('R','R'))),
'005':('one quantum-information-unit correspondence is exactly one retained Fold distinction with two support labels',len(F)==2 and F==('L','R')),
'006':('two independent one-unit supports compose to the complete four-form ordered product',product_support(F,F)==JOINT and len(JOINT)==4),
'007':('the paired joint support has two forms but its two-by-two marginal product has four, marking a nonproduct support boundary without asserting entanglement dynamics',len(PAIRED)==2 and len(product_support(*marginals(PAIRED)))==4 and not factorable(PAIRED)),
'008':('the period-two label action retains two exact phase-class records while interference dynamics remains downstream',tuple((x,'phase-even' if x=='L' else 'phase-odd') for x in F)==(('L','phase-even'),('R','phase-odd'))),
'009':('measurement maps four support words into two observation classes and retains one exact outcome record per observed word',(lambda c:tuple((word,observe(word,c)) for word in JOINT)==((('L','L'),'same'),(('L','R'),'different'),(('R','L'),'different'),(('R','R'),'same')))({word:'same' if word[0]==word[1] else 'different' for word in JOINT})),
'010':('classical labels encode injectively into the two basis-labelled support forms and decode exactly',tuple((x,{'L':('basis','L'),'R':('basis','R')}[x]) for x in F)==(('L',('basis','L')),('R',('basis','R')))),
'011':('a declared quantum-to-classical observation merges the two cross words while retaining their complete predecessor class',(lambda c:tuple(word for word in JOINT if c[word]=='different')==(('L','R'),('R','L')))({word:'same' if word[0]==word[1] else 'different' for word in JOINT})),
'012':('classical support labels can be copied exactly, proving that quantum no-cloning cannot be inferred from support cardinality alone',tuple((x,(x,x)) for x in F)==(('L',('L','L')),('R',('R','R')))),
'013':('a quantum-channel support correspondence retains every input-output support row without claiming amplitudes or gates',(lambda rows:len(rows)==3 and image(rows,'L')==('L','R') and image(rows,'R')==('R',))((('L','L'),('L','R'),('R','R')))),
'014':('the handoff exports basis support, joint support, observations and error classes while quantum code dynamics remains downstream',len(('basis-support','joint-support','observation-classes','error-support','quantum-coding-handoff'))==5),
'015':('support correspondence contains no gate, amplitude, phase-composition or measurement-dynamics selector',set(('support','partition','record')).isdisjoint({'gate','amplitude','phase-composition','measurement-dynamics'})),
'016':('the correspondence ledger covers all sixteen obligations without duplicate ownership',len(tuple(range(1,17)))==16 and len(JOINT)==4 and not factorable(PAIRED)),}
DEF={
'001':('SFT-INFO-CORR-CLASSICAL-SYMBOL-001','Classical symbol-information correspondence','bijective-classical-symbol-correspondence','A classical symbol alphabet corresponds to generated Fold labels through a declared bijection that preserves every distinction and inverse decoding record.'),
'002':('SFT-INFO-CORR-DETERMINISTIC-PROBABILITY-002','Deterministic-support probability correspondence','singleton-support-certainty-correspondence','A deterministic outcome corresponds to a singleton exact support and the ordered part one of one; probability notation is a translation, not a premise.'),
'003':('SFT-INFO-CORR-PROBABILISTIC-MIXTURE-003','Probabilistic mixture as hidden-support description','hidden-source-support-mixture','A mixture description retains a complete source-labelled alternative support while its declared public observation closes the source label; weights require a separately registered measure.'),
'004':('SFT-INFO-CORR-QUANTUM-SUPPORT-004','Quantum support correspondence','complete-basis-labelled-word-support','Quantum computational-basis support corresponds to the complete generated Fold-word support; amplitudes, normalization and dynamics are not inferred from support alone.'),
'005':('SFT-INFO-CORR-QUANTUM-UNIT-005','Quantum information unit correspondence','one-distinction-two-label-support','One quantum information unit has a two-form basis support corresponding to one forced Fold distinction, while phase-bearing state structure remains downstream.'),
'006':('SFT-INFO-CORR-PRODUCT-STATE-006','Composite support and product-state correspondence','complete-product-support-correspondence','Independent component supports compose as their complete ordered product; this is the information-support boundary of product-state correspondence.'),
'007':('SFT-INFO-CORR-ENTANGLEMENT-BOUNDARY-007','Joint support and entanglement boundary','nonproduct-joint-support-boundary','A joint support smaller than the product of its complete marginals is nonproduct support; entanglement requires additional phase/amplitude and operational certificates.'),
'008':('SFT-INFO-CORR-PHASE-HANDOFF-008','Phase information ownership handoff','phase-record-quantum-dynamics-handoff','Information Science retains phase-class distinctions and provenance; Quantum Computation owns phase transformations, interference and operational composition.'),
'009':('SFT-INFO-CORR-MEASUREMENT-SUPPORT-009','Measurement support and record correspondence','support-partition-outcome-record','Measurement-support correspondence is a declared partition of state support into observation classes plus an exact retained outcome record.'),
'010':('SFT-INFO-CORR-CLASSICAL-QUANTUM-ENCODING-010','Classical-to-quantum encoding boundary','injective-classical-basis-encoding','Classical information encodes into quantum support through an injective basis-labelled map with exact inverse decoding on the encoded subspace.'),
'011':('SFT-INFO-CORR-QUANTUM-CLASSICAL-OBSERVATION-011','Quantum-to-classical observation boundary','observation-class-predecessor-custody','Quantum-to-classical observation returns a classical class label and retains the complete quantum-support predecessor class compatible with that record.'),
'012':('SFT-INFO-CORR-NO-CLONING-BOUNDARY-012','No-cloning information boundary correspondence','support-insufficient-no-cloning-boundary','Support organization alone permits classical label copying and therefore cannot prove quantum no-cloning; the theorem belongs to phase-bearing linear operational dynamics.'),
'013':('SFT-INFO-CORR-QUANTUM-CHANNEL-013','Quantum channel support correspondence','input-output-quantum-support-relation','Quantum-channel support correspondence retains the complete input-output support relation while channel amplitudes and physical transformations remain downstream.'),
'014':('SFT-INFO-CORR-QUANTUM-CODING-HANDOFF-014','Quantum coding ownership handoff','information-support-quantum-coding-handoff','Information Science exports codeword, error and observation support; Quantum Computation owns phase-bearing codes, correction operations and fault tolerance.'),
'015':('SFT-INFO-CORR-NONDUPLICATION-015','Operational-dynamics nonduplication boundary','support-dynamics-one-owner-boundary','Information correspondence may not duplicate or select quantum gates, amplitudes, interference, measurement dynamics or physical implementations.'),
'016':('SFT-INFO-CORR-COMPLETENESS-016','Classical-probabilistic-quantum completeness certificate','sixteen-correspondence-obligation-ledger','Correspondence completeness reconciles all sixteen frozen classical, deterministic, probabilistic and quantum-support interface obligations.'),}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=('no axiom, imported probability measure, Hilbert-space model or target outcome selects the result','host 0 denotes structural absence or artifact counts only and is not an SFT number object','no negative, irrational, imaginary or floating proof scalar','no hidden support word, fitted amplitude, stochastic prior or imported normalization','no gate, interference, entanglement dynamics or quantum error correction duplicated from Quantum Computation','no failed route retires an obligation or changes protected authority')
def d(k,r,rw,a,aw):return binary_dimension(k,k+'?',r,rw,a,aw)
def dims(rel):return (d('support','partial-state-support','Omitted forms falsify correspondence.','complete-generated-support','Every support form is retained.'),d('correspondence','imported-model-equivalence','An imported model cannot force equivalence.',rel,'The exact generated relation supplies the correspondence.'),d('record','unretained-observation-class','Missing records hide predecessors.','complete-observation-record-custody','Every class and predecessor is retained.'),d('ownership','duplicated-quantum-dynamics','Duplication lets this branch select downstream law.','support-only-ownership-boundary','Operational dynamics remain downstream.'),d('enumeration','sampled-correspondences','Examples cannot close a correspondence.','complete-declared-correspondence-product','Every support/relation cell is generated once.'),d('provenance','outcome-selected','Outcome feedback invalidates forcing.','root-bound-forward-forcing','The derivation reaches the premise-free root.'),d('target','preopened-target','A preopened target could select the survivor.','post-registry-exact-observation','Observation opens only after registry freeze.'),d('extension','fit-exception-extra-rule','An exception adds a parameter.','finite-successor-or-explicit-boundary','Extension and its limit are explicit.'))
class CorrProgram(GeneratedInformationProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch='information_science',statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];observation,passed=OBS[n];deps=('SFT-INFO-THERM-COMPLETENESS-010',)+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f'Generate the complete eight-axis CORR-{n} product before observation access.',f'Every positive finite CORR-{n} support, correspondence row, observation class, predecessor record, handoff and registered successor boundary.',dims(rel),f'CORR-{n} uniquely retains {rel}, complete correspondence custody, root forcing, post-registry observation and no extra rule.',(statement,observation),'The least correspondence contains one support form, one bijective label, one observation record and identity reconstruction.','Appending one support form, component, observation class or correspondence map preserves prior rows and generates every new support cell exactly once.',EX,(Witness('exact-observation',observation,passed),Witness('complete-correspondence-census','Every support form, relation row, observation class, predecessor and handoff is retained.',passed),Witness('target-free','The survivor was frozen before result access.',True)),f'The frozen census separately owns {title.lower()} and forbids omission or duplicate ownership.',statement,'Enumerate 256 structural forms, reconstruct independently, replay the exact correspondence witness and reject four adverse controls.','The claim closes the declared positive finite information-support correspondence; operational quantum dynamics remains downstream.',(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
