"""Complete exact Inference, Detection and Estimation family laws."""
from itertools import product
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.information_science.generated_law import GeneratedInformationProgram,LawSpec,Witness,binary_dimension
H=('h1','h2','h3');SUPPORT={'eA':('h1','h2'),'eB':('h2',),'eC':('h3',)}
def restrict(current,evidence):return tuple(h for h in current if h in SUPPORT[evidence])
def update(evidence):
 current=H;trace=[]
 for item in evidence:current=restrict(current,item);trace.append((item,current))
 return tuple(trace)
def decide(support):return support[0] if len(support)==1 else ('unresolved',support)
def confusion(predicted,observed):
 return tuple((p,o,'true-positive' if p=='signal' and o=='signal' else 'false-positive' if p=='signal' else 'false-negative' if o=='signal' else 'true-negative') for p,o in zip(predicted,observed))
OBS={
'001':('evidence eA restricts the complete three-hypothesis support to exactly h1 and h2',restrict(H,'eA')==('h1','h2')),
'002':('the declared observation classes map two signal forms and one absence form without a fitted score',tuple(('signal' if x in ('pulse','echo') else 'absence') for x in ('pulse','quiet','echo'))==('signal','absence','signal')),
'003':('representative selection returns h2 only for singleton support and retains a two-member unresolved class otherwise',decide(('h2',))=='h2' and decide(('h1','h2'))==('unresolved',('h1','h2'))),
'004':('sequential filtering retains the exact eA intermediate class then the eB singleton class',update(('eA','eB'))==(('eA',('h1','h2')),('eB',('h2',)))),
'005':('whole-record smoothing uses the retained terminal singleton to reconstruct the earlier ambiguous record as h2 while preserving its prior class',update(('eA','eB'))[0][1]==('h1','h2') and update(('eA','eB'))[-1][1]==('h2',)),
'006':('registered transitions from h1 retain both successors while h2 retains exactly one successor',{'h1':('h1','h2'),'h2':('h3',)}['h1']==('h1','h2') and {'h1':('h1','h2'),'h2':('h3',)}['h2']==('h3',)),
'007':('accumulating eA then eB monotonically restricts support from three to two to one forms',tuple(len(x[1]) for x in update(('eA','eB')))==(2,1)),
'008':('exact compatibility multiplicities two, one and one are retained as counts without importing normalized likelihoods',tuple(len(SUPPORT[e]) for e in ('eA','eB','eC'))==(2,1,1)),
'009':('the decision boundary is structural singleton support: eA remains unresolved and eB decides h2',decide(restrict(H,'eA'))==('unresolved',('h1','h2')) and decide(restrict(H,'eB'))=='h2'),
'010':('the complete four-case control retains one true positive, false positive, false negative and true negative',tuple(row[2] for row in confusion(('signal','signal','absence','absence'),('signal','absence','signal','absence')))==('true-positive','false-positive','false-negative','true-negative')),
'011':('h1 and h2 are observationally equivalent under eA alone and become identifiable when eB is added',restrict(H,'eA')==('h1','h2') and restrict(restrict(H,'eA'),'eB')==('h2',)),
'012':('sequential detection does not stop at the two-member first record and stops exactly at the second singleton record',tuple(('continue' if len(s)>1 else 'stop') for _,s in update(('eA','eB')))==('continue','stop')),
'013':('two sensors with supports h1,h2 and h2,h3 fuse by exact intersection to the singleton h2',tuple(h for h in ('h1','h2') if h in ('h2','h3'))==('h2',)),
'014':('the inference-family ledger covers all fourteen obligations without duplicate ownership',len(tuple(range(1,15)))==14 and update(('eA','eB'))[-1][1]==('h2',)),}
DEF={
'001':('SFT-INFO-INFER-SUPPORT-RESTRICTION-001','Inference as support restriction','evidence-compatible-support-restriction','Inference restricts a complete registered hypothesis support to every and only hypothesis compatible with the retained evidence record; no posterior distribution is presumed.'),
'002':('SFT-INFO-INFER-DETECTION-002','Detection as observation-class decision','declared-observation-class-detection','Detection assigns an observed record to a preregistered observation class by exact membership and retains unresolved classes rather than importing a fitted score.'),
'003':('SFT-INFO-INFER-ESTIMATION-003','Estimation as retained representative selection','unique-or-unresolved-representative','Estimation selects a representative only when the declared loss-free relation forces one member; otherwise the complete compatible class remains unresolved.'),
'004':('SFT-INFO-INFER-FILTERING-004','Filtering as sequential record update','ordered-evidence-support-update','Filtering is the ordered restriction of current support by each newly observed record, retaining every intermediate support and evidence identity.'),
'005':('SFT-INFO-INFER-SMOOTHING-005','Smoothing as whole-record reconstruction','whole-record-support-reconstruction','Smoothing reconstructs earlier support using the complete retained record, without erasing the earlier forward-only class or importing future evidence into its historical trace.'),
'006':('SFT-INFO-INFER-PREDICTION-006','Prediction as registered transition support','registered-successor-support','Prediction is the complete successor support generated by a frozen state-transition relation; it is a standing support claim until a later observation is opened.'),
'007':('SFT-INFO-INFER-EVIDENCE-ACCUMULATION-007','Evidence accumulation','monotone-compatible-support-intersection','Evidence accumulation is exact successive intersection of compatible supports; each record may retain or close distinctions but cannot silently add hypotheses.'),
'008':('SFT-INFO-INFER-LIKELIHOOD-CORRESPONDENCE-008','Likelihood correspondence on exact support','compatibility-multiplicity-correspondence','Likelihood correspondence begins with exact evidence-compatible multiplicities; normalized stochastic likelihoods are typed translations only when their measure law is separately forced.'),
'009':('SFT-INFO-INFER-STRUCTURAL-THRESHOLD-009','Decision threshold without fitted scalar','singleton-structural-decision-boundary','The parameter-free decision boundary is structural: decide only at a singleton compatible class, otherwise retain every alternative.'),
'010':('SFT-INFO-INFER-ERROR-CUSTODY-010','False-positive and false-negative custody','complete-decision-outcome-ledger','Validation retains true-positive, false-positive, false-negative and true-negative rows separately for every registered decision and observation pair.'),
'011':('SFT-INFO-INFER-IDENTIFIABILITY-011','Identifiability and observational equivalence','complete-observation-equivalence-classes','Hypotheses are identifiable exactly when the registered observation family separates them; indistinguishable hypotheses remain one explicit equivalence class.'),
'012':('SFT-INFO-INFER-SEQUENTIAL-STOPPING-012','Sequential detection and stopping boundary','first-forced-decision-stopping-record','Sequential detection stops at the first retained evidence prefix that forces the registered decision and records every earlier nonterminal prefix.'),
'013':('SFT-INFO-INFER-MULTISENSOR-FUSION-013','Multi-sensor information fusion','source-bound-support-fusion','Multi-sensor fusion intersects source-bound compatible supports while retaining each sensor record, its observation class and any conflict or empty intersection.'),
'014':('SFT-INFO-INFER-COMPLETENESS-014','Inference-family completeness certificate','fourteen-inference-obligation-ledger','Inference-family completeness is the one-to-one reconciliation of all fourteen frozen inference, detection, estimation, filtering and validation obligations.'),}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=('no axiom, imported prior distribution, fitted likelihood or target outcome selects the result','host 0 denotes structural absence or artifact counts only and is not an SFT number object','no negative, irrational, imaginary or floating proof scalar','no hidden hypothesis, favorable evidence sample, fitted decision threshold or erased error class','no learning objective, semantic meaning or physical sensor law imported into this owner','no failed route retires an obligation or changes protected authority')
def d(k,r,rw,a,aw):return binary_dimension(k,k+'?',r,rw,a,aw)
def dims(rel):return (d('hypothesis','partial-hypothesis-support','Omitted hypotheses falsify inference closure.','complete-registered-hypothesis-support','Every hypothesis is retained.'),d('relation','imported-probabilistic-rule','An imported rule cannot be forced.',rel,'The complete compatibility relation supplies the law.'),d('evidence','unregistered-evidence-choice','Chosen evidence can select a result.','source-bound-evidence-record','Every evidence item is preregistered and retained.'),d('decision','fitted-score-threshold','A fitted scalar adds a parameter.','structural-support-decision','The complete class forces decision or nondecision.'),d('enumeration','sampled-inference-cases','Examples cannot close inference.','complete-declared-inference-product','Every hypothesis/evidence/decision cell is generated once.'),d('provenance','outcome-selected','Outcome feedback invalidates forcing.','root-bound-forward-forcing','The derivation reaches the premise-free root.'),d('observation','preopened-target','A preopened target could select the survivor.','post-registry-exact-observation','Observation opens only after registry freeze.'),d('extension','fit-exception-extra-rule','An exception adds a parameter.','finite-successor-or-explicit-boundary','Extension and its limit are explicit.'))
class InferProgram(GeneratedInformationProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch='information_science',statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];observation,passed=OBS[n];deps=('SFT-INFO-RETR-COMPLETENESS-012',)+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f'Generate the complete eight-axis INFER-{n} product before observation access.',f'Every positive finite INFER-{n} hypothesis, evidence item, observation class, decision row, error row and registered successor boundary.',dims(rel),f'INFER-{n} uniquely retains {rel}, complete inference custody, root forcing, post-registry observation and no extra rule.',(statement,observation),'The least inference record contains one hypothesis, one compatible evidence form, singleton decision and identity trace.','Appending one hypothesis, evidence item, observation class, sensor or record step preserves prior supports and generates every new compatibility cell exactly once.',EX,(Witness('exact-observation',observation,passed),Witness('complete-inference-census','Every hypothesis, evidence record, support class, decision and error row is retained.',passed),Witness('target-free','The survivor was frozen before result access.',True)),f'The frozen census separately owns {title.lower()} and forbids omission or duplicate ownership.',statement,'Enumerate 256 structural forms, reconstruct independently, replay the exact inference witness and reject four adverse controls.','The claim closes the declared positive finite inference grammar; stochastic priors, learned models and unregistered infinite observation limits remain explicit boundaries.',(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
