"""Complete exact Privacy, Leakage and Disclosure Interface family laws."""
from itertools import combinations,product
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.information_science.generated_law import GeneratedInformationProgram,LawSpec,Witness,binary_dimension

S=('L','R')
def parity(a,b):return 'same' if a==b else 'different'
def fibres(rows):
 labels=tuple(sorted({out for _source,out in rows}))
 return tuple((out,tuple(source for source,image in rows if image==out)) for out in labels)
def distinctions(rows):
 image=dict(rows)
 return tuple((a,b) for a,b in combinations(tuple(image),2) if image[a]!=image[b])
def encrypt_support():return tuple((secret,key,parity(secret,key)) for secret,key in product(S,repeat=2))
def possible_secrets(cipher):return tuple(secret for secret in S if any(s==secret and c==cipher for s,_k,c in encrypt_support()))
U=('a','b','c','d');UTILITY={'a':'L','b':'L','c':'R','d':'R'};PAIR={'a':'x','b':'x','c':'y','d':'y'};IDENTITY={x:x for x in U};ONE={x:'One' for x in U}
OBS={
'001':('identity observation leaks the one secret distinction while constant observation leaks none and retains both predecessors',distinctions((('L','L'),('R','R')))==(('L','R'),) and distinctions((('L','One'),('R','One')))==()),
'002':('for either ciphertext the complete held-key support retains both possible secrets exactly',possible_secrets('same')==S and possible_secrets('different')==S),
'003':('ciphertext alone retains two possible secrets while adding the exact key reveals one, fixing the side-information boundary',possible_secrets('same')==S and tuple(s for s,k,c in encrypt_support() if k=='L' and c=='same')==('L',)),
'004':('a constant public label places three identities in one anonymity class while a role label separates exactly two classes',fibres((('a','member'),('b','member'),('c','member')))==(('member',('a','b','c')),) and len(fibres((('a','reader'),('b','reader'),('c','editor'))))==2),
'005':('least disclosure gives the reader one public field while the editor receives both public and held fields',{'reader':('public',),'editor':('public','held')}['reader']==('public',) and len({'reader':('public',),'editor':('public','held')}['editor'])==2),
'006':('two releases compose by intersecting their fibres and reveal every distinction revealed by either release',distinctions(tuple((x,(PAIR[x],{'a':'u','b':'v','c':'u','d':'v'}[x])) for x in U))==tuple(combinations(U,2))),
'007':('two separately released one-coordinate queries reconstruct all four joint records whereas either query alone leaves two-member fibres',len(set(product(S,repeat=2)))==4 and all(len(tuple(pair for pair in product(S,repeat=2) if pair[i]==label))==2 for i in (0,1) for label in S)),
'008':('among identity, target-pair and constant releases, the target-pair map is the least disclosure that retains both utility classes',all(UTILITY[a]==UTILITY[b] for a,b in combinations(U,2) if PAIR[a]==PAIR[b]) and not all(UTILITY[a]==UTILITY[b] for a,b in combinations(U,2) if ONE[a]==ONE[b]) and len(distinctions(tuple(PAIR.items())))<len(distinctions(tuple(IDENTITY.items())))),
'009':('the privacy owner exports exact public/private classes and leakage ledgers while one-wayness and adversary resource assumptions remain downstream',('public-class','private-class','leakage-ledger','cryptographic-handoff')==('public-class','private-class','leakage-ledger','cryptographic-handoff')),
'010':('the privacy-interface ledger covers all ten obligations without duplicate ownership',len(tuple(range(1,11)))==10 and possible_secrets('same')==S and len(fibres((('a','member'),('b','member'))))==1),}
DEF={
'001':('SFT-INFO-PRIV-LEAKAGE-001','Information leakage as retained adversary distinction','adversary-observation-distinction-ledger','Information leakage is the complete set of protected source distinctions retained by a declared adversary observation, with every still-closed predecessor class preserved.'),
'002':('SFT-INFO-PRIV-PERFECT-SECRECY-002','Perfect secrecy correspondence','secret-independent-observation-support','Perfect-secrecy correspondence holds when every public observation has the same complete secret predecessor support; no probability distribution is required for the support law.'),
'003':('SFT-INFO-PRIV-SIDE-INFORMATION-003','Side-information and disclosure boundary','side-information-refined-predecessor-class','Side information refines adversary predecessor classes by exact intersection; every newly separated protected distinction is entered in the disclosure ledger.'),
'004':('SFT-INFO-PRIV-ANONYMITY-004','Anonymity and indistinguishability classes','complete-adversary-equivalence-classes','An anonymity class is the complete set of identities with one adversary-visible observation; class membership is observation-relative and source identities remain retained.'),
'005':('SFT-INFO-PRIV-LEAST-DISCLOSURE-005','Access observation and least disclosure','role-bound-least-disclosure-map','Least disclosure exposes exactly the fields required by a frozen access observation and retains every withheld field and authorization record.'),
'006':('SFT-INFO-PRIV-COMPOSITION-006','Composition of privacy losses','composed-observation-refinement-ledger','Composed disclosure is the common refinement of all released observations; its privacy loss is the union of exact source distinctions separated by any release.'),
'007':('SFT-INFO-PRIV-QUERY-RECONSTRUCTION-007','Query disclosure and reconstruction risk','complete-query-composition-preimages','Query reconstruction risk is the complete source predecessor class under all released query answers; singleton composition reconstructs while non-singleton classes remain private.'),
'008':('SFT-INFO-PRIV-UTILITY-BOUNDARY-008','Privacy-utility exact trade boundary','least-utility-sufficient-disclosure','The exact privacy-utility boundary is the least generated disclosure partition sufficient for every registered utility distinction, with all additional leaked distinctions rejected.'),
'009':('SFT-INFO-PRIV-CRYPTO-HANDOFF-009','Cryptographic ownership handoff','privacy-law-cryptography-interface','Information Science owns observation classes and leakage ledgers; Cryptography owns adversary resources, one-wayness, computational secrecy and protocol constructions.'),
'010':('SFT-INFO-PRIV-COMPLETENESS-010','Privacy-interface completeness certificate','ten-privacy-obligation-ledger','Privacy-interface completeness is the one-to-one reconciliation of all ten frozen leakage, secrecy-support, anonymity, disclosure and handoff obligations.'),}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=('no axiom, imported privacy metric, stochastic secret prior or target outcome selects the result','host 0 denotes structural absence or artifact counts only and is not an SFT number object','no negative, irrational, imaginary or floating proof scalar','no hidden identity, undeclared side information, fitted privacy weight or favorable adversary','no cryptographic hardness assumption imported into the information-law owner','no failed route retires an obligation or changes protected authority')
def d(k,r,rw,a,aw):return binary_dimension(k,k+'?',r,rw,a,aw)
def dims(rel):return (d('secret','partial-protected-support','Omitted protected forms falsify leakage.','complete-protected-source-support','Every protected form is retained.'),d('observation','implicit-adversary-view','An implicit view hides disclosure.',rel,'The complete adversary observation supplies the law.'),d('side-information','undeclared-side-channel','Hidden side information changes anonymity.','registered-side-information-custody','Every auxiliary record is declared.'),d('loss','scalar-privacy-score','A scalar hides which distinctions leaked.','complete-leaked-distinction-ledger','Every separated pair is retained.'),d('enumeration','sampled-adversaries','Samples cannot close privacy.','complete-declared-observation-product','Every source/view combination is generated once.'),d('provenance','outcome-selected','Outcome feedback invalidates forcing.','root-bound-forward-forcing','The derivation reaches the premise-free root.'),d('target','preopened-target','A preopened target could select the survivor.','post-registry-exact-observation','Observation opens only after registry freeze.'),d('extension','fit-exception-extra-rule','An exception adds a parameter.','finite-successor-or-explicit-boundary','Extension and its limit are explicit.'))
class PrivProgram(GeneratedInformationProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch='information_science',statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];observation,passed=OBS[n];deps=('SFT-INFO-INFER-COMPLETENESS-014',)+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f'Generate the complete eight-axis PRIV-{n} product before observation access.',f'Every positive finite PRIV-{n} protected source, adversary view, side record, disclosure pair, query composition and registered successor boundary.',dims(rel),f'PRIV-{n} uniquely retains {rel}, complete privacy custody, root forcing, post-registry observation and no extra rule.',(statement,observation),'The least privacy relation contains one protected form, one declared view, singleton predecessor support and structural empty-One leakage ledger.','Appending one protected form, public observation, side record or query preserves prior classes and generates every new adversary predecessor and leakage row exactly once.',EX,(Witness('exact-observation',observation,passed),Witness('complete-privacy-census','Every protected source, view, predecessor class, side record and leaked distinction is retained.',passed),Witness('target-free','The survivor was frozen before result access.',True)),f'The frozen census separately owns {title.lower()} and forbids omission or duplicate ownership.',statement,'Enumerate 256 structural forms, reconstruct independently, replay the exact privacy witness and reject four adverse controls.','The claim closes the declared positive finite privacy-interface grammar; computational adversaries and cryptographic constructions remain downstream.',(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
