from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-POLYMER-CONFORMATION-SIZE-010';DOMAINS=(('mass-only-chain', 'complete-ordered-chain-carrier'), ('one-equilibrium-shape', 'complete-generated-finite-conformation-support'), ('continuum-coordinate-field', 'exact-rational-position-word'), ('assumed-origin', 'exact-finite-centroid'), ('root-mean-radius', 'exact-mean-squared-centroid-distance'), ('random-walk-premise', 'explicit-state-and-weight-census'), ('asymptotic-universal-law', 'declared-chain-state-and-resolution-boundary'), ('size-scalar-only', 'positions-centroid-squares-weights-and-boundary-trace'));SURVIVOR='complete-ordered-chain-carrier__complete-generated-finite-conformation-support__exact-rational-position-word__exact-finite-centroid__exact-mean-squared-centroid-distance__explicit-state-and-weight-census__declared-chain-state-and-resolution-boundary__positions-centroid-squares-weights-and-boundary-trace'
from fractions import Fraction
points=((Fraction(1),),(Fraction(3),));centre=sum(p[0] for p in points)/len(points);squared=sum((p[0]-centre)**2 for p in points)/len(points)
native={"chain":len(points)==2,"states":len(set(points))==2,"positions":all(isinstance(p[0],Fraction) for p in points),"centre":centre==2,"size":squared==1,"ensemble":len(points)==2,"scope":len(points)<3,"certificate":squared==Fraction(1,1)}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
