from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-SELECTIVITY-INTERFERENCE-005';DOMAINS=(('response-without-analyte', 'held-analyte-method-condition'), ('selected-interferent', 'complete-declared-interferent-matrix'), ('mixture-only-result', 'analyte-and-interferent-baselines-held'), ('accepted-mixtures-only', 'all-analyte-interferent-mixtures-held'), ('signed-bias-scalar', 'held-side-positive-distance-or-EmptyOne'), ('universal-specificity-label', 'exact-response-distinguishability-class'), ('false-positive-rows-erased', 'favorable-adverse-error-rows-retained'), ('matrix-renormalized', 'successor-retains-and-adds-interferent'));SURVIVOR='held-analyte-method-condition__complete-declared-interferent-matrix__analyte-and-interferent-baselines-held__all-analyte-interferent-mixtures-held__held-side-positive-distance-or-EmptyOne__exact-response-distinguishability-class__favorable-adverse-error-rows-retained__successor-retains-and-adds-interferent'
from fractions import Fraction
def matrix(base,rows):return tuple((i,None if mixed==base else ("raises" if mixed>base else "lowers",abs(mixed-base)),Fraction(mixed,base),pure) for i,pure,mixed in rows)
r=(("i1",Fraction(1),Fraction(5)),("i2",Fraction(2),Fraction(6)));x=matrix(Fraction(5),r)
native={"identity":True,"matrix":len(x)==2,"baselines":tuple(q[3] for q in x)==(1,2),"mixtures":tuple(q[2] for q in x)==(1,Fraction(6,5)),"comparison":x[0][1] is None,"selectivity":x[1][1][0]=="raises","adverse":x[1][1][1]==1,"successor":len(matrix(Fraction(5),r+(("i3",Fraction(1),Fraction(4)),)))==3}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
