from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-COPOLYMER-SEQUENCE-COMPOSITION-007';DOMAINS=(('composition-without-sequence', 'complete-ordered-monomer-word'), ('anonymous-repeat-count', 'held-monomer-identities'), ('selected-monomer-fractions', 'complete-positive-label-count-vector'), ('rounded-percentages', 'exact-label-count-over-word-length'), ('random-sequence-premise', 'every-position-and-neighbour-relation-retained'), ('one-word-replaces-sample', 'word-and-sample-boundaries-separated'), ('retroactive-sequence-fit', 'append-one-held-label-extension'), ('composition-only-output', 'word-counts-ratios-sequence-and-boundary-trace'));SURVIVOR='complete-ordered-monomer-word__held-monomer-identities__complete-positive-label-count-vector__exact-label-count-over-word-length__every-position-and-neighbour-relation-retained__word-and-sample-boundaries-separated__append-one-held-label-extension__word-counts-ratios-sequence-and-boundary-trace'
from fractions import Fraction
word=("a","b","a");counts={x:word.count(x) for x in set(word)};composition={k:Fraction(v,len(word)) for k,v in counts.items()}
native={"word":word==("a","b","a"),"labels":set(word)=={"a","b"},"counts":counts=={"a":2,"b":1},"composition":composition=={"a":Fraction(2,3),"b":Fraction(1,3)},"sequence":word[0]==word[2],"population":len(word)==3,"extension":word+("b",)==("a","b","a","b"),"certificate":sum(composition.values())==1}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
