from itertools import product
import json,sys
CLAIM='SFT-CHEM-MOLECULAR-EXCLUSION-EXCHANGE-006'
DOMAINS=(('cross-molecule-pair', 'one-molecule-electron-pair'), ('named-distinguishable-electrons', 'exchange-equivalent-constituents'), ('free-total-exchange-label', 'alternating-total-word'), ('imported-spin-sign-function', 'complete-one-and-three-spin-sectors'), ('independent-spin-and-space-labels', 'complementary-spin-spatial-fibres'), ('selected-occupancy-cap', 'spatial-exchange-controlled-occupation'), ('selected-favourable-spin-states', 'complete-state-and-exchange-pair-record'), ('species-or-energy-order-exception', 'pairwise-successor-with-no-extra-rule'))
SURVIVOR='one-molecule-electron-pair__exchange-equivalent-constituents__alternating-total-word__complete-one-and-three-spin-sectors__complementary-spin-spatial-fibres__spatial-exchange-controlled-occupation__complete-state-and-exchange-pair-record__pairwise-successor-with-no-extra-rule'
PRODUCT={("preserving","preserving"):"preserving",("preserving","alternating"):"alternating",("alternating","preserving"):"alternating",("alternating","alternating"):"preserving"}
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; registered=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}; law=(PRODUCT[("alternating","preserving")]=="alternating" and PRODUCT[("preserving","alternating")]=="alternating" and PRODUCT[("preserving","preserving")]=="preserving" and 1+3==4); passed=(d["claim_id"]==CLAIM and registered==generated and len(set(registered))==256 and decisions=={row:row==SURVIVOR for row in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and all(row["passed"] for row in d["controls"]) and law); print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"candidate_count":len(generated),"survivor":SURVIVOR if passed else None,"exchange_product":sorted((a,b,c) for (a,b),c in PRODUCT.items())}},sort_keys=True))
if __name__=="__main__":main()
