from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-MECHANISM-SEARCH-PROOF-TRACE-009'
DOMAINS=(('unidentified-intermediate-nodes', 'held-complete-chemical-states'), ('learned-or-named-template-edge', 'admitted-chemical-transition-edge'), ('first-successful-path', 'complete-simple-path-enumeration'), ('net-reaction-only', 'stepwise-carrier-custody'), ('major-route-only', 'all-parallel-route-support'), ('silent-loop-truncation', 'declared-cycle-and-resource-boundary'), ('score-selected-mechanism', 'proof-kernel-stepwise-acceptance'), ('terminal-product-only', 'premise-alternative-step-and-terminal-trace'))
SURVIVOR='held-complete-chemical-states__admitted-chemical-transition-edge__complete-simple-path-enumeration__stepwise-carrier-custody__all-parallel-route-support__declared-cycle-and-resource-boundary__proof-kernel-stepwise-acceptance__premise-alternative-step-and-terminal-trace'
DIMENSION_KEYS=('states', 'transitions', 'search', 'carriers', 'branching', 'cycles', 'acceptance', 'certificate')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
