"""Frozen foundational obligations for Earth and Environmental Sciences.

The rows name the complete Layer-One question surface before external source
identities or outcomes are opened. They do not import conventional Earth-system
models, empirical constants or earlier SFT answers as derivational premises.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EarthEnvironmentObligation:
    claim_id: str
    title: str
    family: str
    carrier: str
    relation: str
    retained_record: str
    evidence_boundary: str
    statement: str
    falsification_condition: str


FAMILY_ORDER = (
    "earth_system_observation",
    "planetary_budgets",
    "geological_material_history",
    "interior_geodynamics",
    "seismic_volcanic",
    "hydrosphere_cryosphere",
    "atmosphere_weather",
    "ocean_coast",
    "climate_system",
    "biogeochemical_ecological",
    "environmental_transport_quality",
    "evidence_hazard_handoffs",
)


def row(
    suffix: str,
    title: str,
    family: str,
    carrier: str,
    relation: str,
    retained_record: str,
    evidence_boundary: str,
    statement: str,
    falsification_condition: str,
) -> EarthEnvironmentObligation:
    return EarthEnvironmentObligation(
        "SFT-EARTH-" + suffix + "-001",
        title,
        family,
        carrier,
        relation,
        retained_record,
        evidence_boundary,
        statement,
        falsification_condition,
    )


EARTH_ENVIRONMENT_OBLIGATIONS = (
    # Earth-system object, reservoirs, boundaries and observations — 6
    row("SYSTEM", "Earth-system identity", "earth_system_observation", "nested-earth-reservoir-interface-carrier", "bounded-joint-state-continuation", "reservoirs-interfaces-time-and-scale-held", "earth-state-observation-bounded", "The Earth system is a declared joint organization of distinguishable reservoirs and interfaces whose state, boundary, scale and observation time remain explicit.", "Reject if system identity is claimed while a participating reservoir, interface, spatial boundary, timescale or observation class is silently erased."),
    row("RESERVOIR", "Earth-system reservoir", "earth_system_observation", "bounded-stock-membership-carrier", "membership-storage-and-transfer-relation", "members-stock-units-boundary-and-time-held", "reservoir-definition-bounded", "An Earth reservoir is a source- and time-bounded carrier with explicit membership, stored quantity, interfaces and observation units.", "Reject if membership or boundary changes without record, or if an unobserved remainder is treated as absent."),
    row("BOUNDARY", "Earth-system boundary and interface", "earth_system_observation", "two-reservoir-interface-carrier", "cross-boundary-transfer-relation", "orientation-area-route-and-time-held", "interface-resolution-bounded", "An Earth-system boundary distinguishes adjacent carriers while retaining every registered cross-boundary transfer, orientation and observation limit.", "Reject if a transfer is counted on only one side, if orientation is lost, or if the interface is replaced by an ungenerated continuum."),
    row("STATE", "Earth-system state", "earth_system_observation", "time-indexed-complete-reservoir-carrier", "stock-relation-state-assignment", "stocks-relations-missingness-and-time-held", "registered-state-vector-bounded", "An Earth-system state is the complete registered assignment of stocks, relations and observation status at one declared time and scale.", "Reject if favorable variables alone define the state or if missing and outside-scope entries are collapsed into absence."),
    row("OBSERVATION", "Earth observation", "earth_system_observation", "source-instrument-processing-result-carrier", "source-to-record-trace", "location-time-calibration-processing-and-quality-held", "method-validity-bounded", "An Earth observation is a reconstructible source-to-instrument-to-processing-to-result trace with calibration, uncertainty, exclusions and quality flags retained.", "Reject if a model output, interpolated field or uncalibrated reading is silently relabelled as direct observation."),
    row("ABSENCE-MISSINGNESS", "Absence, non-detection and missingness", "earth_system_observation", "complete-observation-status-carrier", "status-class-distinction", "detected-absent-censored-missing-outside-scope-held", "detection-boundary-declared", "Observed absence, non-detection, censoring, missing data and outside-scope status are distinct Earth evidence classes and may not be merged.", "Reject if any unavailable or unresolved observation is converted into ordinary numerical zero or favorable absence."),

    # Planetary energy, matter and information budgets — 6
    row("ENERGY-BUDGET", "Earth-system energy budget", "planetary_budgets", "bounded-energy-stock-transfer-carrier", "source-storage-transfer-loss-balance", "all-terms-units-boundaries-and-times-held", "budget-resolution-bounded", "An Earth energy budget retains every registered source, storage change, transfer and export across a declared boundary before testing closure.", "Reject if closure is asserted after omitting a flux, changing units, mixing timescales or fitting a residual away."),
    row("MATTER-BUDGET", "Earth-system matter budget", "planetary_budgets", "species-resolved-stock-transfer-carrier", "source-storage-transformation-export-balance", "species-phase-location-time-and-uncertainty-held", "matter-domain-bounded", "An Earth matter budget follows distinguishable material carriers through storage, transformation, transfer and export without permitting disappearance.", "Reject if chemical identity, phase, location, boundary transfer or unresolved stock is erased."),
    row("INFORMATION-BUDGET", "Earth-system information budget", "planetary_budgets", "distinction-observation-transformation-carrier", "retention-loss-and-reconstruction-relation", "source-resolution-processing-and-lost-labels-held", "observation-process-bounded", "An Earth information budget records which environmental distinctions are retained, merged, reconstructed or lost by observation and transformation.", "Reject if increased resolution is claimed without a source distinction or if merged histories are treated as uniquely recoverable without a record."),
    row("STOCK-FLOW", "Stock and flow distinction", "planetary_budgets", "reservoir-stock-interface-flow-carrier", "time-integrated-transfer-relation", "stock-basis-flow-interval-and-boundary-held", "quantity-and-interval-bounded", "A stock is retained occupancy within a boundary; a flow is a counted transfer across an interface during a declared interval, and neither may substitute for the other.", "Reject if an instantaneous rate is added to a stock without an interval or if cumulative transfer is presented as simultaneous occupancy."),
    row("SOURCE-SINK-STORAGE", "Source, sink and storage roles", "planetary_budgets", "process-reservoir-role-carrier", "boundary-relative-role-assignment", "direction-duration-capacity-and-reversal-held", "system-boundary-bounded", "Source, sink and storage are boundary- and interval-relative roles assigned from the complete transfer record rather than permanent labels attached to an object.", "Reject if a role is assigned without direction and interval or retained after the measured transfer reverses."),
    row("BUDGET-CLOSURE", "Budget closure and residual", "planetary_budgets", "complete-registered-ledger-carrier", "independent-route-balance-comparison", "measurement-uncertainty-missing-terms-and-residual-held", "declared-ledger-bounded", "Budget closure is exact agreement of independently reconstructed registered routes; any unexplained residual remains evidence rather than being distributed by fit.", "Reject if a residual is deleted, reallocated by tuning or called closure outside the declared uncertainty and source boundary."),

    # Geological material, layers, cycles and historical records — 6
    row("GEOLOGICAL-MATERIAL", "Geological material identity", "geological_material_history", "specimen-composition-phase-texture-carrier", "material-class-equivalence", "provenance-mineralogy-chemistry-structure-and-scale-held", "specimen-method-bounded", "A geological material is a source-bound specimen class retaining chemical composition, material phases, texture, structure, provenance and observation scale.", "Reject if a hand specimen name erases heterogeneous phases, alteration, provenance or measurement resolution."),
    row("GEOLOGICAL-LAYER", "Geological layer", "geological_material_history", "bounded-spatial-material-carrier", "adjacency-continuity-and-contact-relation", "extent-thickness-contacts-facies-and-uncertainty-held", "mapping-resolution-bounded", "A geological layer is a mapped material body whose extent, contacts, continuity, internal variation and uncertainty are retained.", "Reject if continuity is inferred across an unobserved gap without recording the correlation rule and alternatives."),
    row("STRATIGRAPHIC-ORDER", "Stratigraphic order", "geological_material_history", "ordered-layer-event-carrier", "before-after-and-correlation-relation", "contacts-unconformities-intrusions-faults-and-dates-held", "section-and-correlation-bounded", "Stratigraphic order is a partial order over observed layers and events that retains unconformities, faults, intrusions and unresolved correlations.", "Reject if one local sequence is silently promoted to a global total order or if a contradictory contact is discarded."),
    row("GEOLOGICAL-CYCLE", "Geological transformation cycle", "geological_material_history", "material-state-transition-network", "weathering-transport-deposition-transformation-relation", "inputs-products-paths-losses-and-times-held", "process-network-bounded", "A geological cycle is a reconstructible network of material-state transitions whose carriers, paths, transfers, losses and recurrence boundary remain explicit.", "Reject if a named cycle implies that every carrier returns or if intermediate transformations and exports are omitted."),
    row("GEOLOGICAL-PROVENANCE", "Geological provenance", "geological_material_history", "source-path-deposit-carrier", "source-to-observed-material-reconstruction", "composition-age-route-alteration-and-alternatives-held", "method-and-basin-bounded", "Geological provenance is a source-to-path-to-deposit reconstruction supported by retained composition, age, alteration and competing-source evidence.", "Reject if one matching property uniquely identifies a source while generated alternatives remain viable."),
    row("EARTH-HISTORY", "Earth historical record", "geological_material_history", "time-ordered-multi-proxy-carrier", "event-state-reconstruction", "dating-provenance-gaps-resolution-and-alternatives-held", "dated-record-bounded", "An Earth-history claim is a source-dated reconstruction over preserved records with temporal uncertainty, gaps, resolution and alternative histories retained.", "Reject if absence of record becomes proof of absence, if dating uncertainty is erased, or if a universal law is inferred from one contingent history alone."),

    # Interior structure and geodynamics — 6
    row("INTERIOR-COMPARTMENT", "Earth interior compartments", "interior_geodynamics", "nested-interior-region-carrier", "boundary-and-property-contrast-relation", "depth-composition-state-observation-and-uncertainty-held", "geophysical-inference-bounded", "An inferred Earth-interior compartment requires a reproducible property contrast across a declared boundary with its observation and inversion limits retained.", "Reject if an inversion model is presented as direct access or if incompatible observations and nonunique interiors are erased."),
    row("INTERNAL-HEAT", "Earth internal heat sources", "interior_geodynamics", "source-reservoir-thermal-carrier", "production-storage-transfer-relation", "source-identity-location-rate-history-and-uncertainty-held", "thermal-ledger-bounded", "Earth internal heat is a complete source, storage and transport ledger distinguishing inherited, transformation and internally generated contributions.", "Reject if present surface flux is assigned to a unique interior source without a registered transport history."),
    row("INTERIOR-HEAT-TRANSPORT", "Interior heat transport", "interior_geodynamics", "temperature-material-motion-carrier", "conduction-advection-and-transition-relation", "geometry-properties-boundaries-time-and-flux-held", "interior-scale-bounded", "Interior heat transport composes admitted material conduction with counted carrier motion and phase transitions under explicit geometry and boundaries.", "Reject if a fitted effective parameter replaces the missing carrier path or if distinct transport modes are silently merged."),
    row("CRUST-MANTLE-BOUNDARY", "Crust-mantle boundary", "interior_geodynamics", "solid-earth-interface-carrier", "composition-structure-and-wave-contrast", "depth-lateral-variation-method-and-uncertainty-held", "regional-observation-bounded", "The crust-mantle boundary is an observation-bounded interface identified through retained composition, structure and propagation contrasts, not a globally uniform surface by premise.", "Reject if local depth is generalized globally without evidence or if method-dependent alternatives are discarded."),
    row("PLATE-BOUNDARY", "Tectonic plate boundary", "interior_geodynamics", "moving-region-interface-carrier", "relative-motion-and-deformation-relation", "orientation-rate-strain-events-and-uncertainty-held", "geodetic-geologic-window-bounded", "A tectonic plate boundary is a zone of measured relative motion and deformation whose geometry, rate, distributed strain and observation interval are retained.", "Reject if a sharp line replaces an observed deformation zone or if motion is inferred without a time-indexed reference frame."),
    row("TECTONIC-MOTION", "Tectonic motion and deformation", "interior_geodynamics", "time-indexed-solid-earth-position-carrier", "relative-displacement-strain-transition", "reference-frame-path-rate-events-and-errors-held", "spatial-temporal-window-bounded", "Tectonic motion is a reference-frame-bound history of relative displacement and deformation reconstructed from complete geodetic and geological records.", "Reject if reference-frame change creates the claimed motion or if episodic and unresolved intervals are smoothed away."),

    # Seismic, volcanic and geophysical processes — 6
    row("STRESS-STRAIN", "Geophysical stress and strain", "seismic_volcanic", "material-load-deformation-carrier", "load-to-deformation-relation", "orientation-path-rate-history-and-material-state-held", "specimen-and-scale-bounded", "Geophysical stress and strain retain load orientation, deformation, material state, path, rate and scale rather than reducing both to an unsigned scalar.", "Reject if orientation or loading history is lost or if a laboratory relation is applied across scale without an admitted handoff."),
    row("RUPTURE", "Earth rupture process", "seismic_volcanic", "fault-state-transition-carrier", "stored-deformation-to-slip-transition", "geometry-loading-nucleation-propagation-and-arrest-held", "event-and-network-bounded", "Rupture is a source-bound transition from stored deformation to propagating and arrested slip with fault geometry, loading history and unresolved segments retained.", "Reject if catalog time alone is treated as the rupture mechanism or if unobserved nucleation is asserted as measured fact."),
    row("SEISMIC-WAVE", "Seismic propagation record", "seismic_volcanic", "source-medium-receiver-carrier", "source-to-receiver-propagation-relation", "phase-path-time-instrument-and-uncertainty-held", "network-resolution-bounded", "A seismic record is a source-medium-receiver propagation trace with phase identity, path, timing, calibration and alternative source or medium explanations retained.", "Reject if a processed arrival is treated as a direct interior image or if missing stations and phase ambiguity are erased."),
    row("EARTHQUAKE-CATALOG", "Earthquake catalog", "seismic_volcanic", "event-detection-location-magnitude-carrier", "catalog-membership-and-equivalence-relation", "network-threshold-method-duplicates-errors-and-time-held", "catalog-completeness-bounded", "An earthquake catalog is a method- and interval-bounded event set retaining detection threshold, location, magnitude scale, duplicates, uncertainty and completeness changes.", "Reject if catalogs with different thresholds or magnitude scales are pooled without a registered translation."),
    row("QUAKE-MAGNITUDE-FREQUENCY", "Earthquake magnitude-frequency law", "seismic_volcanic", "complete-catalog-size-count-carrier", "scale-to-frequency-recurrence", "magnitude-scale-threshold-region-time-and-residuals-held", "catalog-completeness-bounded", "An earthquake magnitude-frequency claim is an exact size-count relation over a complete declared catalog, with its exponent derived before blind comparison and all departures retained.", "Reject if the catalog selects the exponent, if incomplete small events are treated as absent, or if one fitted line erases scale-dependent departures."),
    row("VOLCANIC-PROCESS", "Volcanic process and eruption record", "seismic_volcanic", "magma-pathway-eruption-carrier", "generation-storage-transport-release-transition", "composition-pressure-geometry-time-products-and-failures-held", "volcanic-system-bounded", "A volcanic process is a complete material and state-transition record from generation through storage, transport and release, including failed and non-eruptive paths.", "Reject if surface products uniquely determine an unobserved pathway without alternative reconstructions."),

    # Hydrosphere and cryosphere — 6
    row("WATER-RESERVOIR", "Water reservoir identity", "hydrosphere_cryosphere", "phase-location-bounded-water-carrier", "storage-membership-and-exchange-relation", "amount-phase-composition-boundary-and-time-held", "hydrological-domain-bounded", "A water reservoir retains amount, phase, composition, location, boundary, residence interval and exchanges as distinct registered properties.", "Reject if water outside the observation boundary is treated as absent or if phase and chemical composition are erased."),
    row("WATER-PHASE-HANDOFF", "Environmental water phase handoff", "hydrosphere_cryosphere", "water-state-interface-carrier", "phase-transition-and-transfer-relation", "source-destination-energy-solutes-and-time-held", "interface-condition-bounded", "An environmental water phase handoff cites admitted physical and chemical phase laws while retaining source, destination, energy, solutes, boundary and time.", "Reject if universal phase behavior is reowned by Earth Science or if environmental carriers and impurities are omitted."),
    row("HYDROLOGIC-CYCLE", "Hydrologic cycle", "hydrosphere_cryosphere", "water-reservoir-transfer-network", "evaporation-transport-precipitation-runoff-infiltration-relation", "stocks-flows-phases-boundaries-and-losses-held", "basin-and-time-bounded", "The hydrologic cycle is a bounded reservoir-transfer network whose stocks, phase changes, atmospheric transport, precipitation, runoff, infiltration and exports remain counted.", "Reject if the name cycle implies closure while storage change, groundwater exchange or boundary export remains unregistered."),
    row("GROUNDWATER", "Groundwater system", "hydrosphere_cryosphere", "subsurface-water-material-carrier", "storage-gradient-path-and-exchange-relation", "porosity-composition-boundaries-recharge-discharge-and-time-held", "aquifer-observation-bounded", "A groundwater system is a material-bounded storage and transfer organization with recharge, paths, composition, residence and discharge observations retained.", "Reject if hydraulic head or a model surface is substituted for direct water identity, path and source evidence."),
    row("SURFACE-WATER", "Rivers, lakes and surface-water networks", "hydrosphere_cryosphere", "surface-water-node-edge-carrier", "storage-routing-and-exchange-relation", "network-geometry-flow-quality-boundaries-and-time-held", "catchment-window-bounded", "Surface-water organization is a directed storage and transfer network over rivers, lakes, wetlands and interfaces with complete catchment and observation boundaries.", "Reject if ungauged reaches, diversions, floodplain storage or groundwater exchange are silently omitted."),
    row("CRYOSPHERE", "Cryosphere state and transition", "hydrosphere_cryosphere", "snow-ice-frozen-ground-carrier", "accumulation-transport-phase-and-loss-relation", "extent-thickness-mass-motion-age-and-uncertainty-held", "method-region-time-bounded", "A cryosphere state retains snow, ice and frozen-ground identities, mass, extent, thickness, motion, age, phase transitions and measurement uncertainty.", "Reject if area alone is substituted for mass, if unavailable thickness becomes absence, or if distinct ice reservoirs are pooled without record."),

    # Atmosphere, circulation, weather and the Earth-ionosphere system — 7
    row("ATMOSPHERE", "Atmospheric system identity", "atmosphere_weather", "bounded-gas-aerosol-energy-carrier", "layered-composition-motion-and-exchange-relation", "composition-state-height-boundaries-and-time-held", "atmospheric-observation-bounded", "The atmosphere is a layered, moving material and energy carrier whose composition, state, boundaries and exchanges with other Earth reservoirs remain explicit.", "Reject if a global mean erases vertical, regional or temporal structure required by the claim."),
    row("ATMOSPHERIC-COMPOSITION", "Atmospheric composition", "atmosphere_weather", "species-aerosol-mixture-carrier", "amount-fraction-and-transformation-relation", "species-units-altitude-location-time-and-method-held", "sampling-network-bounded", "Atmospheric composition is a source- and method-bound mixture record retaining species, amount basis, altitude, location, time, transformation and uncertainty.", "Reject if dry, wet, local and global composition bases are mixed or if below-detection values become ordinary zero."),
    row("ATMOSPHERIC-RADIATIVE-BUDGET", "Atmospheric radiative budget", "atmosphere_weather", "spectral-source-layer-boundary-carrier", "absorption-emission-scattering-transfer-relation", "spectrum-direction-cloud-aerosol-surface-and-time-held", "spectral-spatial-window-bounded", "An atmospheric radiative budget is a directional and spectral transfer ledger through atmosphere and surface with clouds, aerosols, storage and unresolved terms retained.", "Reject if a bulk fitted parameter substitutes for the registered carriers or if incoming and outgoing quantities use incompatible boundaries."),
    row("MOISTURE-CLOUD", "Atmospheric moisture and cloud organization", "atmosphere_weather", "water-vapour-droplet-ice-air-carrier", "transport-phase-nucleation-and-precipitation-relation", "phase-size-location-time-aerosol-and-uncertainty-held", "cloud-observation-bounded", "Atmospheric moisture and clouds are phase-resolved water organizations coupled to air motion, particles and radiation under explicit observation limits.", "Reject if cloud occurrence alone fixes its microphysics or if unresolved sub-grid structure is treated as absent."),
    row("ATMOSPHERIC-CIRCULATION", "Atmospheric circulation", "atmosphere_weather", "time-indexed-air-mass-motion-carrier", "transport-recurrence-and-exchange-network", "position-orientation-moisture-energy-boundaries-and-time-held", "spatial-temporal-window-bounded", "Atmospheric circulation is a time-indexed network of air-mass motion and exchange retaining orientation, transported carriers, boundaries and unresolved scales.", "Reject if one averaged velocity field is treated as the complete carrier history or if opposite orientations are encoded as negative proof magnitudes."),
    row("WEATHER", "Weather state and forecast boundary", "atmosphere_weather", "finite-time-atmospheric-state-carrier", "state-transition-and-observation-relation", "initial-state-forcing-resolution-ensemble-and-outcomes-held", "forecast-horizon-bounded", "Weather is the observed atmospheric state and its finite-time transition record; a forecast is a sealed conditional consequence, not an observation or natural law.", "Reject if forecast skill selects the governing law, if adverse forecasts are dropped, or if a model trajectory is relabelled as measured weather."),
    row("EARTH-IONOSPHERE-RESONANCE", "Earth-ionosphere resonant cavity", "atmosphere_weather", "earth-surface-atmosphere-ionosphere-boundary-carrier", "bounded-propagation-mode-recurrence", "geometry-medium-source-spectrum-time-and-uncertainty-held", "earth-cavity-observation-bounded", "Earth-ionosphere resonance composes the admitted bounded-wave relation with the measured Earth-atmosphere cavity geometry and retains the complete source spectrum and uncertainty.", "Reject if the observed resonant frequency selects the cavity law, if a universal wave law is reowned, or if engineering transmission claims are inferred from resonance alone."),

    # Ocean and coastal systems — 6
    row("OCEAN", "Ocean system identity", "ocean_coast", "bounded-seawater-basin-interface-carrier", "storage-motion-composition-and-exchange-relation", "basin-depth-composition-state-boundaries-and-time-held", "ocean-observation-bounded", "The ocean is a basin- and boundary-resolved seawater organization retaining composition, state, depth, motion and exchanges with atmosphere, land, ice and seabed.", "Reject if a surface observation is generalized through depth or if basin and global records are mixed without weighting and provenance."),
    row("OCEAN-COMPOSITION", "Ocean composition and salinity", "ocean_coast", "water-dissolved-particulate-gas-carrier", "composition-fraction-and-transformation-relation", "species-basis-depth-location-time-and-method-held", "sample-program-bounded", "Ocean composition retains dissolved, particulate and gaseous carriers, amount basis, depth, location, time, method and transformations rather than salinity as an answer-only scalar.", "Reject if practical and absolute composition bases are silently mixed or if missing species are treated as absent."),
    row("OCEAN-STRATIFICATION", "Ocean stratification", "ocean_coast", "depth-indexed-water-mass-carrier", "property-contrast-and-layer-stability-relation", "temperature-composition-pressure-mixing-and-time-held", "profile-network-bounded", "Ocean stratification is a depth- and time-resolved organization of water masses defined by retained property contrasts, interfaces, mixing and observation uncertainty.", "Reject if a single profile fixes a persistent layer globally or if density is imported without its admitted physical and compositional dependencies."),
    row("OCEAN-CIRCULATION", "Ocean circulation", "ocean_coast", "water-mass-pathway-network", "transport-overturning-and-mixing-relation", "mass-properties-direction-depth-time-and-boundaries-held", "basin-time-window-bounded", "Ocean circulation is a carrier-resolved transport network retaining water-mass identity, direction, depth, mixing, exchange and observation interval.", "Reject if a streamfunction or inferred path is treated as direct parcel history or if unresolved recirculation is erased."),
    row("AIR-SEA-EXCHANGE", "Air-sea exchange", "ocean_coast", "atmosphere-ocean-interface-carrier", "two-way-material-energy-transfer-relation", "species-energy-area-direction-state-and-time-held", "interface-method-bounded", "Air-sea exchange is a two-way, interface-bounded transfer ledger retaining carrier identity, direction, area, state, time and method uncertainty.", "Reject if a transfer coefficient is fitted to close the budget and then presented as a forced Earth law."),
    row("COAST-TIDE", "Coastal and tidal Earth-system response", "ocean_coast", "ocean-land-orbital-forcing-interface-carrier", "periodic-forcing-propagation-and-dissipation-relation", "geometry-water-level-current-sediment-time-and-handoff-held", "coastal-region-bounded", "A coastal tidal response consumes Astronomy-owned orbital forcing and Physics-owned wave laws while Earth Science owns the measured water, current, sediment and boundary response.", "Reject if planetary tidal locking is reowned, if a local response is generalized globally, or if shoreline change is inferred from water level alone."),

    # Climate dynamics, forcing, feedback, variability, attribution and tipping — 7
    row("CLIMATE", "Climate state", "climate_system", "distribution-of-earth-state-histories-carrier", "time-window-recurrence-and-change-relation", "variables-distributions-extremes-boundaries-and-methods-held", "declared-climate-window-bounded", "Climate is a source- and interval-bounded distribution of Earth-system states, variations and extremes rather than one instantaneous weather state or mean.", "Reject if the averaging interval, distribution, extremes, spatial support or observation changes are omitted."),
    row("WEATHER-CLIMATE-TIMESCALE", "Weather-climate timescale distinction", "climate_system", "nested-time-indexed-state-carrier", "short-transition-to-long-distribution-relation", "sampling-window-memory-forcing-and-variability-held", "timescale-explicit", "Weather and climate are distinct evidence classes linked by declared aggregation and memory relations; neither may be inferred from an unlabeled timescale.", "Reject if one event proves a climate law or if a long-term distribution is used as a deterministic event forecast."),
    row("CLIMATE-FORCING", "Climate forcing", "climate_system", "external-or-boundary-driver-carrier", "driver-to-energy-or-matter-budget-change", "identity-magnitude-timing-spectrum-location-and-uncertainty-held", "system-boundary-bounded", "A climate forcing is a registered driver that changes a declared Earth-system boundary ledger while retaining identity, timing, spectrum, location and uncertainty.", "Reject if an internal response is relabelled as forcing or if the forcing is inferred solely from the response it is meant to explain."),
    row("CLIMATE-FEEDBACK", "Climate feedback", "climate_system", "state-response-return-path-carrier", "response-modifies-driver-or-budget-relation", "sign-as-orientation-gain-path-delay-and-boundaries-held", "process-timescale-bounded", "A climate feedback is a closed response path that modifies a registered driver or budget; its orientation, path, delay and boundary must remain structural labels rather than negative proof scalars.", "Reject if correlation substitutes for a closed path or if the feedback magnitude is fitted from the same target used to validate it."),
    row("CLIMATE-VARIABILITY", "Internal climate variability", "climate_system", "coupled-state-history-carrier", "recurrent-and-nonrecurrent-transition-partition", "modes-phases-forcing-record-length-and-missingness-held", "record-and-scale-bounded", "Internal climate variability is the source-bounded state-transition structure remaining after registered external drivers are retained, with recurrence and nonrecurrence both recorded.", "Reject if unexplained change is automatically labeled internal or if a short record establishes a depth-independent cycle."),
    row("CLIMATE-ATTRIBUTION", "Climate detection and attribution", "climate_system", "observation-driver-response-alternative-carrier", "generated-alternative-elimination-relation", "forcings-internal-variation-methods-controls-and-uncertainty-held", "question-and-period-bounded", "Climate attribution requires a preregistered observation, candidate driver set, complete alternatives, controls and source-bound uncertainty; detection of change alone is not attribution.", "Reject if the tested driver set omits a viable alternative, if a model ensemble selects its own target, or if disagreement and failed transport rows are removed."),
    row("EARTH-SYSTEM-TIPPING", "Earth-system tipping boundary", "climate_system", "multi-basin-state-forcing-carrier", "threshold-crossing-hysteresis-and-return-relation", "state-variable-driver-path-rate-controls-and-time-held", "system-proxy-and-timescale-bounded", "An Earth-system tipping claim requires observed or independently reconstructed basins, forcing path, threshold crossing, hysteresis or return behavior and ordinary-variability controls; no universal physical half-One threshold is assumed.", "Reject if abrupt change alone establishes tipping, if the threshold is read from the validation target, or if reversible and ordinary-variable alternatives survive."),

    # Biogeochemical and ecological coupling — 6
    row("CARBON-CYCLE", "Earth carbon cycle", "biogeochemical_ecological", "carbon-species-reservoir-network", "transformation-storage-and-transfer-relation", "species-isotopes-stocks-flows-boundaries-and-time-held", "earth-carbon-domain-bounded", "The Earth carbon cycle is a species- and reservoir-resolved transformation and transfer network with isotopic, stock, flow, boundary and uncertainty records retained.", "Reject if chemically distinct carriers are merged, if an unmeasured sink closes the budget by assumption, or if biological uptake is rederived rather than cited."),
    row("NITROGEN-CYCLE", "Earth nitrogen cycle", "biogeochemical_ecological", "nitrogen-species-reservoir-network", "transformation-storage-and-transfer-relation", "species-isotopes-organisms-stocks-flows-and-time-held", "earth-nitrogen-domain-bounded", "The Earth nitrogen cycle retains each chemical species, abiotic and biological transformation, reservoir, transfer and observation boundary.", "Reject if oxidation states, biological processes or atmospheric and aquatic boundaries are silently merged."),
    row("PHOSPHORUS-CYCLE", "Earth phosphorus cycle", "biogeochemical_ecological", "phosphorus-species-rock-soil-water-biota-network", "weathering-uptake-transfer-return-relation", "species-stocks-flows-organisms-sediment-and-time-held", "earth-phosphorus-domain-bounded", "The Earth phosphorus cycle composes geological, chemical and biological carriers while retaining weathering, uptake, transfer, burial, return and boundary exports.", "Reject if a named cycle asserts atmospheric equivalence or complete return without evidence."),
    row("BIOSPHERE-EXCHANGE", "Biosphere-Earth exchange", "biogeochemical_ecological", "organism-community-abiotic-interface-carrier", "two-way-resource-waste-and-state-transfer", "biological-owner-reservoir-carrier-rate-time-and-controls-held", "ecosystem-boundary-bounded", "Biosphere-Earth exchange cites Biology-owned organismal processes while Earth Science owns their measured coupling to atmosphere, water, soil and rock reservoirs.", "Reject if Earth Science reowns biological mechanism or if an ecosystem observation is generalized without organism and environmental boundaries."),
    row("COUPLED-ECOSYSTEM", "Coupled ecosystem-Earth organization", "biogeochemical_ecological", "community-abiotic-reservoir-joint-carrier", "biotic-abiotic-transfer-and-feedback-network", "species-resources-disturbance-boundaries-effort-and-time-held", "ecosystem-observation-bounded", "A coupled ecosystem-Earth claim retains Biology-owned communities together with abiotic stocks, transfers, disturbances, observation effort and missing links.", "Reject if ecological recurrence alone establishes planetary stability or if absent observations become absent interactions."),
    row("BIODIVERSITY-ENVIRONMENT", "Biodiversity-environment boundary", "biogeochemical_ecological", "taxon-trait-habitat-pressure-carrier", "environmental-condition-to-biological-response-comparison", "sampling-taxonomy-space-time-confounders-and-missingness-held", "study-design-bounded", "A biodiversity-environment relation is a sampling- and design-bounded comparison retaining taxonomic identity, habitat, pressure, response, confounders and missingness.", "Reject if correlation becomes causation or if unequal observation effort is treated as biological difference."),

    # Pollution, transport, accumulation and environmental quality — 6
    row("POLLUTANT-IDENTITY", "Pollutant identity and boundary", "environmental_transport_quality", "substance-form-source-context-carrier", "harm-relevant-exposure-classification", "chemical-form-source-medium-dose-time-and-endpoint-held", "environment-health-handoff-bounded", "A pollutant is a source- and context-bound material form associated with a declared exposure and adverse endpoint; substance identity alone does not establish harm.", "Reject if chemical forms, exposure, dose, endpoint or Medicine-owned health evidence are omitted."),
    row("SOURCE-PATH-RECEPTOR", "Environmental source-path-receptor chain", "environmental_transport_quality", "source-medium-path-receptor-carrier", "causal-transfer-chain", "identity-route-timing-transformation-exposure-and-controls-held", "system-and-study-bounded", "An environmental exposure claim requires a reconstructible source-to-path-to-receptor chain retaining carrier identity, transformations, timing, alternatives and controls.", "Reject if co-location or correlation substitutes for the transfer chain."),
    row("ENVIRONMENTAL-TRANSPORT", "Environmental contaminant transport", "environmental_transport_quality", "material-medium-pathway-network", "advection-dispersion-partition-and-transfer-relation", "species-phase-direction-boundaries-time-and-uncertainty-held", "site-and-medium-bounded", "Environmental transport is a carrier-resolved pathway network that cites upstream physical and material laws and retains phase, direction, boundaries, transformations and uncertainty.", "Reject if a fitted transport coefficient replaces missing path evidence or if unavailable downstream observations become absence."),
    row("ENVIRONMENTAL-TRANSFORMATION", "Environmental transformation and persistence", "environmental_transport_quality", "substance-condition-product-carrier", "condition-dependent-transition-network", "precursors-products-pathways-rates-controls-and-time-held", "medium-condition-bounded", "Environmental transformation is a condition-bounded chemical or biological transition network with precursors, products, alternatives, rates and persistence observations retained.", "Reject if disappearance of the measured precursor is treated as destruction of matter or proof of harmless products."),
    row("ENVIRONMENTAL-ACCUMULATION", "Environmental accumulation", "environmental_transport_quality", "input-storage-output-history-carrier", "retention-and-release-ledger", "carrier-reservoir-input-output-transformation-and-time-held", "reservoir-and-interval-bounded", "Environmental accumulation is an input-storage-output ledger over a declared reservoir and interval, including transformation, remobilization and unresolved stock.", "Reject if concentration alone establishes accumulation without volume, input, output and time records."),
    row("ENVIRONMENTAL-QUALITY", "Environmental quality state", "environmental_transport_quality", "multi-measurement-environmental-state-carrier", "standard-purpose-and-ecological-comparison", "variables-methods-threshold-provenance-missingness-and-time-held", "medium-purpose-jurisdiction-bounded", "Environmental quality is a purpose- and medium-specific evidence vector retaining measurement methods, thresholds, provenance, uncertainty and missing components; no single index may erase them.", "Reject if a weighted index imports fitted choices, hides an adverse component or silently becomes a universal natural law."),

    # Evidence, reconstruction, models, forecasts, hazards and handoffs — 6
    row("FIELD-OBSERVATION", "Field observation and sampling", "evidence_hazard_handoffs", "site-specimen-instrument-result-carrier", "sampling-to-population-relation", "design-location-time-effort-calibration-and-exclusions-held", "representativeness-declared", "A field observation retains site selection, sampling design, effort, calibration, processing, exclusions and representativeness limits.", "Reject if convenience samples establish a global Earth relation or if failed and below-detection samples are removed."),
    row("REMOTE-SENSING", "Remote-sensing observation", "evidence_hazard_handoffs", "source-path-sensor-retrieval-carrier", "signal-to-geophysical-record-relation", "geometry-spectrum-calibration-processing-validation-and-cloud-held", "sensor-product-bounded", "Remote sensing is a source-to-path-to-sensor-to-retrieval trace whose geophysical interpretation retains calibration, geometry, processing, validation and unavailable pixels.", "Reject if a retrieval product is called direct ground truth or if cloud, saturation and algorithm changes are erased."),
    row("PROXY-RECONSTRUCTION", "Proxy and Earth-history reconstruction", "evidence_hazard_handoffs", "archive-proxy-calibration-target-carrier", "proxy-to-past-state-inference", "archive-formation-dating-calibration-resolution-and-alternatives-held", "proxy-region-period-bounded", "A proxy reconstruction preserves archive formation, dating, calibration, resolution, uncertainty and competing environmental controls and remains distinct from direct observation.", "Reject if one modern calibration is assumed invariant through untested history or if proxy disagreement is discarded."),
    row("MODEL-DATA-ASSIMILATION", "Earth model and data-assimilation boundary", "evidence_hazard_handoffs", "law-state-observation-update-carrier", "conditional-simulation-and-state-update-relation", "equations-as-correspondence-inputs-parameters-observations-errors-and-outputs-held", "model-purpose-bounded", "An Earth model is a declared conditional simulation and data assimilation is a traceable state update; neither can select an SFT law or become an observation.", "Reject if tuned performance is offered as structural proof, if observations leak into a sealed prediction, or if model and observation errors are conflated."),
    row("FORECAST-VALIDATION", "Earth forecast validation", "evidence_hazard_handoffs", "sealed-forecast-outcome-carrier", "predeclared-comparison-relation", "targets-metrics-baselines-adverse-cases-missingness-and-time-held", "forecast-question-bounded", "Forecast validation compares a sealed forecast with later source-bound outcomes using preregistered targets, metrics, baselines and complete adverse and missing rows.", "Reject if the target or score enters before sealing, if unfavorable forecasts are omitted, or if accuracy is treated as proof of an opaque law."),
    row("HAZARD-RISK-HANDOFF", "Hazard, risk, resilience and disciplinary handoff", "evidence_hazard_handoffs", "process-exposure-vulnerability-consequence-carrier", "hazard-to-impact-and-recovery-chain", "event-probability-exposure-vulnerability-capacity-time-and-ownership-held", "decision-context-bounded", "Earth Science owns the physical or environmental hazard record; risk composes exposure and vulnerability at explicit Social, Medicine and Engineering handoffs, while resilience retains recovery capacities and failures.", "Reject if hazard is equated with impact, if a probability is asserted without a reference class, or if Earth Science reowns social, clinical or engineered consequences."),
)


OBLIGATIONS = EARTH_ENVIRONMENT_OBLIGATIONS


def validate_inventory() -> None:
    if len(EARTH_ENVIRONMENT_OBLIGATIONS) != 74:
        raise ValueError("Earth foundational question decomposition must contain its 74 explicit rows")
    if len({item.claim_id for item in EARTH_ENVIRONMENT_OBLIGATIONS}) != len(EARTH_ENVIRONMENT_OBLIGATIONS):
        raise ValueError("Earth inventory contains duplicate claim identities")
    observed = tuple(dict.fromkeys(item.family for item in EARTH_ENVIRONMENT_OBLIGATIONS))
    if observed != FAMILY_ORDER:
        raise ValueError("Earth inventory is not in declared dependency order")
    for item in EARTH_ENVIRONMENT_OBLIGATIONS:
        if not all((item.title.strip(), item.carrier.strip(), item.relation.strip(), item.retained_record.strip(), item.evidence_boundary.strip(), item.statement.strip(), item.falsification_condition.strip())):
            raise ValueError(f"Earth obligation has an empty field: {item.claim_id}")


validate_inventory()


__all__ = ("EarthEnvironmentObligation", "EARTH_ENVIRONMENT_OBLIGATIONS", "OBLIGATIONS", "FAMILY_ORDER", "validate_inventory")
