"""Force arrangements, selections and duplicate-free finite enumeration."""

from __future__ import annotations

from sft.mathematics.generated_law import LawSpec, Witness, binary_dimension


CLAIM_ID = "SFT-MATH-COMBINATORICS-001"
EMPTY_ONE = ("empty-One",)


def arrangements(items: tuple[str, ...]) -> tuple[tuple[str, ...], ...]:
    if not items or len(set(items)) != len(items):
        raise ValueError("arrangements require a nonempty unique generated carrier")
    if len(items) == 1:
        return (items,)
    result = []
    for held in items:
        remainder = tuple(item for item in items if item != held)
        result.extend((held,) + suffix for suffix in arrangements(remainder))
    return tuple(result)


def selections(items: tuple[str, ...]) -> tuple[tuple[str, ...], ...]:
    if not items or len(set(items)) != len(items):
        raise ValueError("selections require a nonempty unique generated carrier")
    result: list[tuple[str, ...]] = [()]
    for item in items:
        result += [selection + (item,) for selection in tuple(result)]
    return tuple(EMPTY_ONE if not selection else selection for selection in result)


def disjoint_class_ledger(items: tuple[str, ...], classifier) -> tuple[tuple[str, tuple[str, ...]], ...]:
    labels: list[str] = []
    classes: dict[str, list[str]] = {}
    for item in items:
        label = str(classifier(item))
        if label not in classes:
            labels.append(label)
            classes[label] = []
        classes[label].append(item)
    return tuple((label, tuple(classes[label])) for label in labels)


def recurrence_extend(previous: tuple[tuple[str, ...], ...], fresh: str) -> tuple[tuple[str, ...], ...]:
    if any(fresh in form for form in previous):
        raise ValueError("recurrence extension requires a fresh label")
    return previous + tuple((fresh,) if form == EMPTY_ONE else form + (fresh,) for form in previous)


_items = ("a", "b", "c")
_arrangements = arrangements(_items)
_selections = selections(_items)


SPEC = LawSpec(
    claim_id=CLAIM_ID,
    title="Exact finite combinatorial generation",
    statement=(
        "Every admitted finite combinatorial family is generated by an explicit held-choice recurrence over a "
        "complete canonical carrier, preserves construction order and provenance, removes duplicates only by "
        "canonical form identity, and counts the resulting complete trace; selections include the structural "
        "empty One form rather than numerical zero."
    ),
    dependencies=(
        "SFT-FOUNDATION-FOLD-ASSEMBLY-001",
        "SFT-MATH-EXACT-ARITHMETIC-001",
        "SFT-MATH-DISCRETE-001",
    ),
    generation_rule=(
        "Generate the complete product of carrier coverage, choice rule, provenance, duplication policy, symmetry "
        "identity, class accounting, recurrence closure and extra-formula status."
    ),
    grammar_boundary=(
        "All arrangement, selection and finite classification families produced from a registered canonical "
        "finite carrier by held choice, remainder and successor recurrence."
    ),
    dimensions=(
        binary_dimension("carrier", "Is the source carrier complete and canonical?", "partial-carrier", "A partial carrier silently omits possible generated choices.", "complete-canonical-carrier", "Every distinct generated source member is present once."),
        binary_dimension("choice", "How are combinatorial forms generated?", "sampled-choices", "Sampling does not exhaust the registered choice positions.", "held-choice-recurrence", "Each available member is held once at the next position and recursion continues on the exact remainder."),
        binary_dimension("provenance", "Are construction choices retained?", "erased-origin", "Erasing origin prevents reconstruction and duplicate diagnosis.", "complete-choice-trace", "Every result retains the ordered held-choice construction trace."),
        binary_dimension("duplicates", "How are repeated outputs treated?", "presentation-deduplication", "Presentation equality can merge structurally distinct results.", "canonical-identity-deduplication", "Only identical canonical construction traces are identified."),
        binary_dimension("symmetry", "How are symmetric forms compared?", "assumed-symmetry", "An assumed quotient may remove distinguishable held labels.", "generated-bijection-witness", "A declared label-preserving bijection is required before forms share a symmetry class."),
        binary_dimension("accounting", "How are overlapping predicates counted?", "signed-inclusion-subtraction", "Signed subtraction imports negative quantities.", "disjoint-provenance-classes", "Each generated form is assigned once to a held disjoint class before counts are joined."),
        binary_dimension("generality", "What closes every finite carrier size?", "finite-size-table", "A table of small sizes does not force the next recurrence.", "carrier-successor-recurrence", "Adding one fresh carrier member partitions new forms by whether and where it is held."),
        binary_dimension("addition", "Is an imported counting formula used?", "imported-formula", "A stored factorial, binomial or inclusion formula selects the conventional answer.", "no-imported-formula", "Counts are identities of the complete generated output traces."),
    ),
    exact_result=(
        "The combinatorial kernel is complete canonical carrier generation by held-choice recurrence with complete "
        "choice provenance, canonical deduplication, witnessed symmetry, disjoint class accounting, successor "
        "generality and no imported formula."
    ),
    laws=(
        "every arrangement holds each carrier member exactly once",
        "every selection is produced once by the fresh-member absent/held recurrence",
        "canonical trace equality is the only duplicate-elimination rule",
        "disjoint class ledgers conserve the complete generated family",
        "enumerated count is the identity of the complete output trace",
    ),
    induction_base="A one-member carrier has one complete arrangement and two structural selection forms: empty One and held member.",
    induction_step=(
        "For a fresh carrier member, arrangements partition by its held position and recurse on the prior remainder; "
        "selections partition into prior forms and the same forms with the fresh member held. These disjoint generated "
        "classes exhaust the successor carrier without an imported formula."
    ),
    boundary_exclusions=(
        "no random sampling as completeness evidence",
        "no factorial or binomial answer table",
        "no negative inclusion-exclusion proof value",
        "no completed infinite combinatorial family",
    ),
    witnesses=(
        Witness("arrangement-completeness", "Three distinct held labels generate six unique ordered arrangements.", len(_arrangements) == 6 and len(set(_arrangements)) == 6),
        Witness("arrangement-coverage", "Every arrangement holds every carrier label exactly once.", all(set(form) == set(_items) and len(form) == len(_items) for form in _arrangements)),
        Witness("selection-recurrence", "Three held labels generate the structural empty One and every absent/held combination once.", len(_selections) == 8 and len(set(_selections)) == 8 and EMPTY_ONE in _selections),
        Witness("disjoint-accounting", "Parity-named witness classes partition the carrier without overlap or omission.", tuple(item for _, group in disjoint_class_ledger(_items, lambda item: "a-class" if item == "a" else "other-class") for item in group) == _items),
        Witness("fresh-extension", "Fresh-member recurrence creates a disjoint absent/held copy of every prior selection.", len(recurrence_extend(selections(("a", "b")), "c")) == len(_selections)),
    ),
    why=(
        "Counting arrangements by quoting familiar formulas would import their answers. The generated family itself "
        "must be primary so every count, symmetry reduction and recurrence remains inspectable."
    ),
    derivation=(
        "Discrete canonical collections provide the carrier and held selection; Fold words provide exact choice "
        "traces; arithmetic counts the complete result. Exhausting the eight assembly choices forces explicit "
        "held-choice recurrence and provenance-preserving class accounting."
    ),
    check=(
        "Execute all 256 kernels, exhaust arrangements and selections on small unfavorable controls, verify trace "
        "uniqueness and successor partitioning, then independently regenerate the candidate product and survivor."
    ),
    limitations=(
        "The law closes the generative foundation of finite combinatorics. Named advanced enumerations require "
        "their own derived generators; none may be admitted by quoting a conventional closed-form answer."
    ),
    correspondence_terms=("permutation", "combination", "recurrence", "symmetry class", "pigeonhole counting", "inclusion-exclusion"),
)
