from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-OVERPOTENTIAL-POLARIZATION-010';DOMAINS=(('reference-free-voltage', 'one-held-equilibrium-reference'), ('signed-potential-offset', 'held-anodic-cathodic-equilibrium-side'), ('continuum-difference-premise', 'exact-positive-potential-distance'), ('anonymous-current', 'held-current-direction-positive-magnitude'), ('numerical-zero-origin', 'structural-EmptyOne-equilibrium-point'), ('selected-polarization-point', 'complete-ordered-finite-polarization-curve'), ('mixed-condition-curve', 'common-electrode-reference-condition'), ('fitted-tafel-line', 'complete-raw-potential-current-vector'));SURVIVOR='one-held-equilibrium-reference__held-anodic-cathodic-equilibrium-side__exact-positive-potential-distance__held-current-direction-positive-magnitude__structural-EmptyOne-equilibrium-point__complete-ordered-finite-polarization-curve__common-electrode-reference-condition__complete-raw-potential-current-vector'
from fractions import Fraction
def point(n,side):return (n,side,None,None) if side=="equilibrium" else (n,side,Fraction(n,2),Fraction(n,3))
def curve(rows):return tuple(x[0] for x in rows)==tuple(range(1,len(rows)+1))
rows=(point(1,"equilibrium"),point(2,"anodic"),point(3,"cathodic"));native={"ordered":curve(rows),"reference":True,"equilibrium":rows[0][2:] == (None,None),"anodic":rows[1][1]=="anodic","cathodic":rows[2][1]=="cathodic","positive":rows[1][3]>0,"condition":True,"omission":not curve((point(1,"anodic"),point(3,"cathodic")))}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
