"""Frozen foundational question surface for Biology and Life Sciences.

The inventory names biological questions without importing biological answers.
Every row states the distinctions that a lawful Fold reconstruction must retain.
External observations may test these rows only after the complete inventory and
its generated candidate space have been sealed.
"""

from __future__ import annotations

from dataclasses import dataclass


SUBBRANCH_ORDER = (
    "life_boundary",
    "compartment_identity",
    "metabolism_resource",
    "inheritance_replication",
    "variation_evolution",
    "gene_genome_regulation",
    "protein_structure_function",
    "cell_process",
    "multicellular_development",
    "organism_physiology",
    "population_ecology",
    "observation_handoffs",
)


@dataclass(frozen=True)
class BiologyObligation:
    claim_id: str
    title: str
    subbranch: str
    carrier: str
    relation: str
    organization: str
    observation: str
    statement: str


def row(
    suffix: str,
    title: str,
    subbranch: str,
    carrier: str,
    relation: str,
    organization: str,
    observation: str,
    statement: str,
) -> BiologyObligation:
    return BiologyObligation(
        f"SFT-BIO-{suffix}-001", title, subbranch, carrier, relation,
        organization, observation, statement,
    )


BIOLOGY_OBLIGATIONS = (
    # Life boundary — 6
    row("LIFE-ORGANIZATION", "Living organization", "life_boundary", "bounded-process-carrier", "self-maintaining-transition-relation", "identity-through-turnover", "viability-window-declared", "Living organization is a bounded process network that retains its identity by regulated material and energy turnover within a declared viability window."),
    row("LIFE-CHEMICAL-BOUNDARY", "Living and nonliving chemical-network boundary", "life_boundary", "complete-reaction-network-carrier", "network-to-maintenance-comparison", "closure-and-inheritance-retained", "condition-bounded-life-class", "A chemical network is biologically living only when compartment, maintenance, heritable continuation and regulated resource exchange are jointly retained; chemistry alone does not supply that classification."),
    row("LIFE-AUTOCATALYTIC-CLOSURE", "Autocatalytic closure and origin-of-life boundary", "life_boundary", "complete-catalytic-network", "product-to-required-catalyst-recurrence", "boundary-and-resource-input-retained", "finite-network-closure-test", "Autocatalytic closure is the least complete finite reaction support in which every required catalytic role is regenerated by the network while resources and boundary conditions remain explicit."),
    row("LIFE-MAINTENANCE", "Biological maintenance", "life_boundary", "living-state-and-repair-carrier", "damage-to-restoration-transition", "identity-defining-relations-retained", "time-and-condition-bounded", "Maintenance is the generated set of transitions that restores identity-defining biological relations faster than incompatible distinctions accumulate at the declared boundary."),
    row("LIFE-IDENTITY-TURNOVER", "Identity through constituent turnover", "life_boundary", "lineage-bound-organization-carrier", "replacement-with-relation-preservation", "organization-and-provenance-retained", "scale-and-time-declared", "Biological identity persists through constituent replacement exactly when the lineage-bound organization and its required transition relations remain reconstructible."),
    row("LIFE-DEATH", "Loss of living closure", "life_boundary", "formerly-living-process-carrier", "irrecoverable-closure-loss", "material-remains-process-identity-not-retained", "recovery-boundary-declared", "Biological death is the condition-bounded loss of the jointly required maintenance, regulation and integrated continuation relations, not numerical zero or disappearance of material."),

    # Compartment and identity — 6
    row("COMPARTMENT", "Biological compartment", "compartment_identity", "boundary-and-content-carrier", "boundary-separates-content-classes", "inside-outside-distinction-held", "resolution-declared", "A biological compartment is a connected boundary that retains distinguishable internal and external content classes together with every permitted transfer path."),
    row("INSIDE-OUTSIDE", "Inside/outside orientation", "compartment_identity", "oriented-boundary-carrier", "opposed-side-label-relation", "two-sides-never-merged", "observer-orientation-declared", "A retained compartment boundary forces two held side labels, inside and outside, whose distinction cannot be erased by a lawful transfer description."),
    row("MEMBRANE", "Membrane organization", "compartment_identity", "complete-membrane-component-carrier", "component-adjacency-and-orientation", "continuous-boundary-support", "state-and-scale-bounded", "A membrane is a continuous oriented component organization that maintains a compartment while retaining composition, adjacency, state and interruption records."),
    row("SELECTIVE-PERMEABILITY", "Selective permeability", "compartment_identity", "boundary-species-state-carrier", "species-specific-transition-permission", "allowed-and-rejected-paths-retained", "condition-bounded-transport-test", "Selective permeability is the complete partition of candidate boundary crossings into permitted and rejected species-state paths under declared conditions."),
    row("NESTED-COMPARTMENT", "Nested biological compartments", "compartment_identity", "finite-compartment-tree-carrier", "parent-child-containment", "each-boundary-and-transfer-retained", "nesting-depth-declared", "Nested biological organization is a finite containment tree in which every compartment boundary, side label and cross-boundary transfer remains separately reconstructible."),
    row("COMPARTMENT-PROVENANCE", "Compartment lineage provenance", "compartment_identity", "source-bound-compartment-carrier", "predecessor-to-successor-boundary-map", "division-fusion-and-transfer-recorded", "lineage-window-declared", "Compartment identity claims require an unbroken predecessor-to-successor record across division, fusion, growth and component turnover."),

    # Metabolism, maintenance and resource closure — 6
    row("METABOLISM", "Metabolic network", "metabolism_resource", "complete-transformation-network", "resource-to-product-transition", "catalyst-content-and-boundary-ledger", "condition-and-time-bounded", "Metabolism is a compartment-bound transformation network that records every resource, product, catalyst, transfer and retained constituent relation required for maintenance."),
    row("RESOURCE-UPTAKE", "Biological resource uptake", "metabolism_resource", "external-resource-and-boundary-carrier", "external-to-internal-transfer", "source-identity-and-path-retained", "availability-and-time-bounded", "Resource uptake is a source-bound permitted transition from an external support into a biological compartment with identity, amount, route and condition retained."),
    row("METABOLIC-TRANSFORMATION", "Metabolic transformation conservation", "metabolism_resource", "complete-reactant-product-carrier", "balanced-transformation-relation", "atom-and-held-label-ledger-retained", "reaction-boundary-declared", "A metabolic transformation is admissible only when the complete constituent ledger balances and catalysts, resources and products remain separately identified."),
    row("ENERGY-COUPLING", "Metabolic process coupling", "metabolism_resource", "joint-uphill-downhill-process-carrier", "shared-transition-coupling", "complete-transfer-record-retained", "condition-and-direction-bounded", "Biological process coupling joins otherwise nonpersistent and resource-releasing transitions through one retained transfer record; an unrecorded gain is rejected."),
    row("WASTE-EXPORT", "Metabolic by-product and waste export", "metabolism_resource", "byproduct-and-boundary-carrier", "internal-to-external-transfer", "mass-identity-and-impact-retained", "system-boundary-declared", "Waste export is a recorded transfer of nonretained metabolic products across the compartment boundary; no product may disappear from the constituent ledger."),
    row("RESOURCE-CLOSURE", "Finite biological resource closure", "metabolism_resource", "organism-environment-joint-carrier", "uptake-transformation-export-cycle", "all-required-inputs-and-losses-retained", "finite-window-closure-test", "Resource closure is always relative to a declared organism-environment boundary and finite interval and requires every necessary input, transformation, storage, export and loss path to be recorded."),

    # Inheritance and replication — 6
    row("INHERITANCE", "Information-bearing inheritance", "inheritance_replication", "lineage-and-carrier-state", "predecessor-successor-retention", "heritable-distinction-and-context-held", "generation-boundary-declared", "Inheritance is the reconstructible retention of a biological distinction from predecessor to successor through an identified carrier and generation relation."),
    row("TEMPLATE", "Template-directed copying", "inheritance_replication", "template-and-product-carrier", "positionwise-complement-or-copy-relation", "template-product-distinction-retained", "finite-word-boundary", "Template copying generates a product word through a declared positionwise relation while retaining template, product, direction and every mismatch."),
    row("REPLICATION", "Biological replication", "inheritance_replication", "complete-replicator-and-resource-carrier", "one-predecessor-to-distinct-successors", "copy-lineage-and-resource-ledger", "generation-and-capacity-bounded", "Replication is a resource-bounded process that generates at least one distinct successor carrying the declared hereditary relation while retaining predecessor and copy provenance."),
    row("COPY-FIDELITY", "Replication fidelity and error", "inheritance_replication", "aligned-template-product-words", "positionwise-agreement-census", "matches-mismatches-and-unread-positions-held", "assay-and-length-declared", "Copy fidelity is the exact part-to-whole count of agreed positions over a declared aligned word; every mismatch and unobserved position remains in the record."),
    row("HERITABLE-VARIATION", "Heritable copy variation", "inheritance_replication", "variant-product-and-lineage-carrier", "copy-difference-retained-across-generation", "location-state-and-origin-held", "observation-window-declared", "A copy difference is heritable variation only when its exact state and location persist through a registered successor relation rather than appearing only as transient damage or observation error."),
    row("REPLICATION-LINEAGE", "Replication lineage", "inheritance_replication", "finite-predecessor-successor-graph", "parent-child-generation-edges", "branch-merger-and-sample-history-retained", "depth-and-sampling-declared", "A replication lineage is a finite directed predecessor-successor graph with every sampled branch, merger, missing observation and generation boundary explicit."),

    # Variation, selection and evolution — 6
    row("VARIATION", "Biological variation", "variation_evolution", "population-state-carrier", "within-class-distinction-relation", "individual-lineage-and-state-held", "sampling-boundary-declared", "Variation is the complete retained set of distinguishable biological states within a declared population and sampling boundary."),
    row("HERITABILITY", "Heritability relation", "variation_evolution", "related-generation-carrier", "predecessor-successor-covariation", "environment-and-carrier-context-retained", "population-and-generation-bounded", "Heritability is a population- and condition-bounded relation between predecessor and successor distinctions and does not by itself identify a molecular cause."),
    row("DIFFERENTIAL-REPRODUCTION", "Differential reproduction", "variation_evolution", "typed-lineage-carrier", "type-specific-successor-count", "exposure-survival-and-fecundity-ledger", "generation-window-declared", "Differential reproduction is an exact comparison of retained successor counts among biological types under one declared environment and generation window."),
    row("SELECTION", "Selection", "variation_evolution", "heritable-variant-population", "variant-linked-differential-continuation", "competing-lineages-and-environment-held", "finite-generation-test", "Selection is the recurrence of a heritable variant together with reproducible differential continuation relative to registered alternatives under a declared environment."),
    row("FIXATION", "Fixation and loss boundary", "variation_evolution", "complete-population-support", "variant-count-to-population-count", "all-sampled-lineages-retained", "finite-population-generation-bounded", "Fixation is whole support of one retained variant in the declared population; loss is structural absence of that variant from the same support, never a universal guarantee from benefit alone."),
    row("DRIFT-BOUNDARY", "Selection and drift distinction", "variation_evolution", "replicate-population-carrier", "state-change-to-fitness-association", "sampling-and-randomizer-provenance-held", "finite-replicate-boundary", "A change is attributed to selection only when the registered variant-continuation relation survives the declared controls; otherwise finite sampling recurrence remains an explicit drift-compatible alternative."),

    # Gene, genome, expression and regulation — 6
    row("NUCLEOTIDE-ALPHABET", "Nucleic-acid symbol alphabet", "gene_genome_regulation", "two-distinction-symbol-carrier", "ordered-pair-label-generation", "four-code-symbols-retained", "DNA-alphabet-boundary", "Two independent held distinctions generate exactly four nucleic-acid symbol labels at the DNA coding boundary."),
    row("CODON", "Triplet codon word space", "gene_genome_regulation", "four-symbol-word-carrier", "three-position-ordered-composition", "position-and-symbol-identities-retained", "complete-word-census", "Three ordered positions over four generated symbols force exactly sixty-four distinguishable codon words."),
    row("CODON-BOX", "First-two-position codon boxes", "gene_genome_regulation", "complete-codon-support", "prefix-equivalence-partition", "third-position-variation-retained", "complete-partition-census", "The sixty-four codons partition by their first two positions into exactly sixteen boxes of exactly four third-position words each."),
    row("GENE", "Gene as expression-bearing hereditary interval", "gene_genome_regulation", "source-bound-sequence-interval", "interval-to-product-or-regulatory-relation", "orientation-context-and-provenance-retained", "annotation-boundary-declared", "A gene is a source-bound hereditary interval whose expression or regulatory relation is demonstrated with orientation, context and evidence boundary retained."),
    row("GENOME", "Genome organization", "gene_genome_regulation", "complete-hereditary-carrier-support", "ordered-and-linked-locus-relation", "chromosomal-compartment-and-copy-state-held", "assembly-and-sample-declared", "A genome is the complete declared hereditary carrier support of an organism or cell with order, linkage, compartment, copy state, gaps and assembly provenance retained."),
    row("EXPRESSION-REGULATION", "Expression and regulation", "gene_genome_regulation", "gene-product-condition-carrier", "condition-dependent-production-transition", "regulator-context-time-and-output-held", "assay-bounded", "Gene expression is a recorded transition from a hereditary interval to a product; regulation is a reproducible condition-dependent difference in that transition with regulator, context and time retained."),

    # Protein sequence, structure, function and interaction — 7
    row("PROTEIN-SEQUENCE", "Protein sequence identity", "protein_structure_function", "ordered-residue-word-carrier", "peptide-linked-position-relation", "residue-modification-and-provenance-held", "sequence-boundary-declared", "A protein sequence is an ordered residue word with every position, linkage, modification, ambiguity and source record retained."),
    row("PROTEIN-FOLD", "Protein folding relation", "protein_structure_function", "sequence-condition-conformation-carrier", "transition-to-recurrent-structure-class", "path-ensemble-and-condition-held", "resolution-and-time-bounded", "Protein folding is a condition-bounded transition from sequence support to a recurrent structural class; it is a generated descent relation, not exhaustive random search or an imported unique-shape premise."),
    row("PROTEIN-ENSEMBLE", "Protein conformational ensemble", "protein_structure_function", "complete-observed-conformation-support", "interconversion-recurrence", "populations-times-and-conditions-held", "method-resolution-bounded", "A protein state is an observed recurrence class over a conformational ensemble; one structure may not erase retained alternate conformations or intrinsically disordered support."),
    row("PROTEIN-FUNCTION", "Protein function", "protein_structure_function", "protein-context-process-carrier", "protein-dependent-process-difference", "sequence-structure-context-and-controls-held", "assay-and-organism-bounded", "Protein function is a reproducible protein-dependent difference in a declared biological process under explicit context and controls, not a label inferred from shape alone."),
    row("PROTEIN-INTERACTION", "Protein interaction", "protein_structure_function", "two-protein-context-carrier", "specific-joint-state-recurrence", "alternatives-stoichiometry-and-condition-held", "interaction-assay-bounded", "A protein interaction is a reproducible specific joint-state relation whose alternatives, stoichiometry, condition and observation method are retained."),
    row("PROTEIN-QUATERNARY", "Quaternary protein assembly", "protein_structure_function", "multi-chain-labelled-carrier", "interface-compatible-composition", "chain-identity-symmetry-and-contact-held", "structure-method-bounded", "Quaternary assembly is a generated multi-chain joint state that retains chain identities, stoichiometry, symmetry, interface contacts and adverse steric alternatives; no fitted docking score may select it."),
    row("BIOLOGICAL-HOMOCHIRALITY", "Biological homochirality", "protein_structure_function", "chiral-biopolymer-carrier", "same-hand-recurrence-along-chain", "opposed-hand-controls-retained", "organism-and-polymer-bounded", "Biological homochirality is a source-bound recurrence of one molecular hand across a declared biopolymer class; Chemistry supplies chirality while Biology owns its lineage-maintained selection."),

    # Cells — 6
    row("CELL", "Cell identity", "cell_process", "compartmented-living-process-carrier", "integrated-maintenance-inheritance-relation", "membrane-metabolism-and-lineage-held", "cell-cycle-window-declared", "A cell is the least compartmented living organization jointly retaining boundary, maintenance, hereditary continuation and regulated process integration."),
    row("CELL-TRANSPORT", "Cellular transport", "cell_process", "cell-boundary-species-carrier", "directed-cross-boundary-transition", "route-gradient-resource-and-fate-held", "time-condition-bounded", "Cellular transport is a counted species-state transition through a declared membrane route with direction, driving relation and intracellular fate retained."),
    row("CELL-SIGNALLING", "Cell signalling", "cell_process", "source-signal-receptor-response-carrier", "source-to-response-causal-chain", "intermediates-controls-and-time-held", "assay-bounded", "Cell signalling is a reconstructible source-to-receptor-to-response transition chain whose intermediates, controls, timing and alternative routes remain explicit."),
    row("EXCITABLE-THRESHOLD", "Excitable-cell threshold transition", "cell_process", "resting-excitable-state-carrier", "threshold-crossing-to-regenerative-transition", "subthreshold-and-refractory-controls-held", "cell-condition-bounded", "An excitable-cell event is a regenerative state transition after a declared threshold is crossed, distinguished from subthreshold and refractory responses; no universal voltage is imported."),
    row("CELL-DIVISION", "Cell division", "cell_process", "one-cell-lineage-carrier", "one-predecessor-to-partitioned-successors", "genome-cytoplasm-boundary-and-errors-held", "division-cycle-bounded", "Cell division partitions one lineage-bound cell into successor compartments while retaining the complete hereditary, cytoplasmic, boundary and error-allocation record."),
    row("DYSREGULATED-DIVISION", "Dysregulated cell continuation and cancer boundary", "cell_process", "lineage-control-state-carrier", "division-death-differentiation-control-comparison", "mutations-context-and-clonal-history-held", "tissue-and-time-bounded", "Dysregulated cellular continuation is a lineage-supported failure of normal division, death or differentiation control under a declared tissue context; cycling alone is not sufficient to identify cancer."),

    # Multicellular composition and development — 6
    row("MULTICELLULAR-COMPOSITION", "Multicellular organismal composition", "multicellular_development", "connected-cell-lineage-carrier", "coordinated-cell-composition", "cell-identities-boundaries-and-shared-processes-held", "organism-stage-bounded", "Multicellular organization is a connected lineage-related cell composition with retained cellular identities and regulated shared processes."),
    row("CELL-ADHESION", "Cell adhesion and tissue boundary", "multicellular_development", "cell-interface-carrier", "specific-persistent-contact-relation", "adhesion-components-mechanics-and-controls-held", "tissue-condition-bounded", "Cell adhesion is a specific persistent intercellular or cell-matrix relation that retains component identity, contact geometry, mechanical context and adverse controls."),
    row("DIFFERENTIATION", "Cell differentiation", "multicellular_development", "common-lineage-cell-state-carrier", "stable-state-divergence", "genome-identity-expression-and-function-held", "developmental-window-declared", "Differentiation is a stable lineage-related divergence of cellular state and function while hereditary carrier identity and transition provenance remain reconstructible."),
    row("DEVELOPMENT", "Developmental lineage", "multicellular_development", "zygote-to-organism-lineage-carrier", "ordered-division-differentiation-transition", "branching-time-position-and-state-held", "stage-boundary-declared", "Development is an ordered lineage of division, movement and differentiation transitions from an initiating cell to a multicellular organization with every branch and stage boundary retained."),
    row("MORPHOGENESIS", "Morphogenesis", "multicellular_development", "cell-state-spatial-carrier", "local-transition-to-global-form", "neighbour-boundary-force-and-time-held", "scale-and-stage-bounded", "Morphogenesis is the reconstruction of global biological form from local cell-state, adjacency, movement and boundary transitions over a declared developmental interval."),
    row("REGENERATION", "Biological regeneration", "multicellular_development", "damaged-organization-lineage-carrier", "loss-to-restored-organization-transition", "residual-source-path-and-function-held", "extent-and-time-bounded", "Regeneration is a lineage-supported transition from a recorded loss state to restored organization and function, with residual source, path, extent and failures retained."),

    # Organism and physiology — 6
    row("ORGANISM", "Organism identity", "organism_physiology", "integrated-living-lineage-carrier", "part-to-whole-functional-integration", "boundaries-life-cycle-and-environment-held", "taxon-stage-condition-bounded", "An organism is an integrated lineage-bound living whole whose parts participate in coordinated maintenance, development, reproduction or continuation within a declared life cycle."),
    row("PHYSIOLOGY", "Physiological process", "organism_physiology", "organ-system-state-carrier", "coordinated-function-transition", "parts-flows-controls-and-time-held", "organism-condition-bounded", "Physiology is the complete coordinated transition record by which organismal parts maintain or change a biological function under declared conditions."),
    row("HOMEOSTASIS", "Homeostatic regulation", "organism_physiology", "regulated-variable-control-carrier", "departure-sensing-response-return-relation", "set-range-delay-and-failure-held", "condition-and-time-bounded", "Homeostasis is a closed sensing-and-response recurrence that returns a biological variable to a declared viable range while preserving delays, overshoot and failure cases."),
    row("REPRODUCTION", "Organismal reproduction", "organism_physiology", "parent-offspring-lineage-carrier", "generation-of-new-organism", "carrier-contributions-development-and-errors-held", "life-cycle-bounded", "Organismal reproduction generates a new lineage-bound organism through declared parental carrier contributions and development, with variation and failures retained."),
    row("LIFE-CYCLE", "Biological life cycle", "organism_physiology", "stage-transition-carrier", "ordered-recurrent-stage-relation", "development-reproduction-and-death-held", "taxon-environment-bounded", "A biological life cycle is the complete ordered recurrence of organismal stages including development, reproductive continuation and terminal loss at a declared taxonomic boundary."),
    row("SENESCENCE", "Senescence and longevity", "organism_physiology", "lineage-maintenance-history-carrier", "age-linked-maintenance-loss-relation", "survival-repair-reproduction-and-censoring-held", "population-condition-bounded", "Senescence is an age-linked change in maintenance or continuation measured on a declared lineage and population; longevity requires survival and censoring records and is not forced by denominator parity alone."),

    # Population and ecology — 6
    row("POPULATION", "Biological population", "population_ecology", "individual-set-space-time-carrier", "membership-and-interaction-relation", "identities-lineages-and-sampling-held", "taxon-place-time-bounded", "A population is a declared set of organismal individuals connected by place, time and relevant biological interaction, with membership and sampling rules explicit."),
    row("SPECIES-BOUNDARY", "Species and reproductive boundary", "population_ecology", "population-lineage-carrier", "within-between-continuation-comparison", "gene-flow-history-and-method-held", "species-concept-declared", "A species claim is an explicitly chosen, evidence-bound equivalence class over populations; reproductive, phylogenetic and ecological criteria may not be silently merged."),
    row("COMMUNITY", "Ecological community", "population_ecology", "co-located-population-carrier", "interpopulation-interaction-network", "species-identities-and-observation-effort-held", "place-time-scale-bounded", "A community is a place- and time-bounded network of distinguishable populations and their observed interactions, including absent and unresolved links."),
    row("TROPHIC-NETWORK", "Trophic and resource network", "population_ecology", "population-resource-directed-network", "consumption-and-transfer-edge", "amount-direction-loss-and-provenance-held", "ecosystem-window-declared", "A trophic network is a directed resource-transfer graph retaining source, consumer, amount basis, direction, loss and observation boundary for every edge."),
    row("ECOSYSTEM", "Ecosystem organization", "population_ecology", "community-environment-joint-carrier", "biotic-abiotic-transfer-network", "stocks-flows-boundaries-and-history-held", "spatial-temporal-boundary", "An ecosystem is a bounded joint organization of communities and abiotic supports with complete registered stocks, transfers, losses and observation history."),
    row("ECOLOGICAL-RECURRENCE", "Ecological recurrence and stability", "population_ecology", "time-indexed-ecosystem-state-carrier", "state-return-and-perturbation-relation", "species-resources-disturbance-and-effort-held", "finite-series-boundary", "Ecological recurrence is a return of a complete declared state class; stability is persistence or recovery under registered perturbations and cannot be inferred from one bounded-denominator orbit alone."),
    row("ECOLOGICAL-NETWORK", "Ecological network topology", "population_ecology", "complete-population-interaction-graph", "degree-path-and-clustering-census", "nodes-edges-effort-and-missing-links-held", "sampling-scale-declared", "Ecological network topology is the exact degree, path and clustering census of a declared interaction graph; scale-free or small-world labels require whole-graph and unfavorable-model comparison."),
    row("BIOLOGICAL-ALLOMETRY", "Biological allometric relation", "population_ecology", "organism-trait-size-carrier", "trait-to-size-scaling-comparison", "taxon-stage-condition-and-residuals-held", "range-and-sample-bounded", "A biological allometric claim is a population-bounded comparison of trait and body-size recurrence with taxa, stages, conditions, residuals and alternative exponents retained; no universal exponent is imported."),

    # Observation and handoffs — 6
    row("BIO-SPECIMEN", "Biological specimen and sampling", "observation_handoffs", "source-bound-biological-part", "specimen-to-source-provenance", "collection-preservation-and-subselection-held", "representativeness-declared", "A biological specimen is a finite source-bound part with collection, preservation, preparation, subsampling and representativeness boundaries explicit."),
    row("BIO-CONDITION", "Biological condition and control", "observation_handoffs", "experimental-unit-condition-carrier", "condition-to-outcome-comparison", "controls-exposure-time-and-context-held", "design-boundary-declared", "A biological comparison requires experimental units, conditions, controls, timing and context to be registered before the outcome is opened."),
    row("BIO-ASSAY", "Biological assay", "observation_handoffs", "specimen-method-result-carrier", "method-to-observation-relation", "calibration-detection-and-processing-held", "method-validity-bounded", "A biological assay is a specimen-bound observation process with calibration, detection, processing, exclusions and method-validity boundaries retained."),
    row("BIO-UNCERTAINTY", "Biological uncertainty and missingness", "observation_handoffs", "complete-observation-record", "result-to-uncertainty-partition", "variation-error-missing-and-censored-held", "inference-boundary-declared", "Biological evidence must retain biological variation, measurement error, missingness, censoring and unresolved states rather than collapsing them into one favorable estimate."),
    row("BIO-CAUSALITY", "Biological causal and associative boundary", "observation_handoffs", "intervention-exposure-outcome-carrier", "counterfactual-control-comparison", "confounders-timing-and-selection-held", "design-specific-causal-scope", "A biological causal claim requires a registered intervention or adequate control structure that eliminates generated alternatives; association alone remains explicitly noncausal."),
    row("BIO-HANDOFF", "Cross-branch biological handoff", "observation_handoffs", "source-law-interface-carrier", "upstream-to-biological-composition", "ownership-assumptions-and-losses-held", "discipline-boundary-declared", "A Biology claim cites upstream mathematical, informational, physical, chemical and material laws without reowning them and exports organismal consequences without claiming medical efficacy, consciousness or engineering implementation."),
)


OBLIGATIONS = BIOLOGY_OBLIGATIONS


def validate_inventory() -> None:
    if len(BIOLOGY_OBLIGATIONS) != 75:
        raise ValueError("Biology foundational inventory must contain exactly 75 frozen obligations")
    if len({item.claim_id for item in BIOLOGY_OBLIGATIONS}) != len(BIOLOGY_OBLIGATIONS):
        raise ValueError("Biology inventory contains duplicate claim identities")
    observed = tuple(dict.fromkeys(item.subbranch for item in BIOLOGY_OBLIGATIONS))
    if observed != SUBBRANCH_ORDER:
        raise ValueError("Biology inventory is not in declared dependency order")
    if any(not item.statement.strip() for item in BIOLOGY_OBLIGATIONS):
        raise ValueError("Biology inventory contains an empty statement")


validate_inventory()

__all__ = ("BiologyObligation", "BIOLOGY_OBLIGATIONS", "OBLIGATIONS", "SUBBRANCH_ORDER", "validate_inventory")
