from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-MOLECULAR-GRAPH-ISOMORPHISM-002'
DOMAINS=(('formula-only-comparison', 'complete-graph-domain'), ('partial-or-many-to-one-map', 'complete-atom-bijection'), ('element-only-match', 'all-atom-state-labels-preserved'), ('connectivity-only-match', 'all-bond-order-labels-preserved'), ('stereo-isotope-charge-erasure', 'all-held-fibres-preserved'), ('one-heuristic-labelling', 'complete-unresolved-cell-permutation-census'), ('database-id-equality', 'canonical-word-and-witness-equivalence'), ('near-match-accepted', 'every-single-distinction-tamper-rejected'))
SURVIVOR='complete-graph-domain__complete-atom-bijection__all-atom-state-labels-preserved__all-bond-order-labels-preserved__all-held-fibres-preserved__complete-unresolved-cell-permutation-census__canonical-word-and-witness-equivalence__every-single-distinction-tamper-rejected'
DIMENSION_KEYS=('domain', 'mapping', 'atoms', 'bonds', 'orientation', 'enumeration', 'decision', 'adverse')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
