"""Complete Optimization and Operations Research family laws and witnesses."""
from fractions import Fraction
from itertools import combinations,product
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.mathematics.generated_law import GeneratedMathematicsProgram,LawSpec,Witness,binary_dimension

def subsets(values):
 values=tuple(values)
 return tuple(tuple(values[i] for i in range(len(values)) if i in chosen) for n in range(len(values)+1) for chosen in combinations(range(len(values)),n))
def pareto(points):return tuple(p for p in points if not any(q!=p and q[0]<=p[0] and q[1]<=p[1] for q in points))
def compositions(total,width):return tuple(x for x in product(range(1,total+1),repeat=width) if sum(x)==total)
OBS={
"001":("the declared feasible labels two three four retain an exact objective order with minimum two",min(x for x in (1,2,3,4) if x>=2)==2),
"002":("complete enumeration of values four one three two gives exact minimum one and maximum four",min((4,1,3,2))==1 and max((4,1,3,2))==4),
"003":("complete two-objective minimization retains exactly the three nondominated points one-four two-two four-one",pareto(((1,4),(2,2),(4,1),(3,3)))==((1,4),(2,2),(4,1))),
"004":("complete positive grid enumeration under the linear bound x-plus-y at most four has optimum value four",max(x+y for x,y in product(range(1,4),repeat=2) if x+y<=4)==4),
"005":("complete knapsack subset enumeration under weight three uniquely selects the first two items with value five",(lambda rows:max(rows,key=lambda x:x[1]))(tuple((s,sum((2,3,4)[i] for i in s)) for s in subsets(range(3)) if sum((1,2,3)[i] for i in s)<=3))==((0,1),5)),
"006":("the exact convex held-distance-square objective on labels one through five has unique minimizer three",tuple(x for x in range(1,6) if (max(x,3)-min(x,3))**2==min((max(y,3)-min(y,3))**2 for y in range(1,6)))==(3,)),
"007":("the finite linear primal optimum four equals the complete dual certificate minimum four",max(x+y for x,y in product(range(1,4),repeat=2) if x+y<=4)==min(4*z for z in range(1,5))==4),
"008":("among every positive three-part path totaling six the unique least squared action is two-two-two",tuple(x for x in compositions(6,3) if sum(v*v for v in x)==min(sum(v*v for v in y) for y in compositions(6,3)))==((2,2,2),)),
"009":("complete path enumeration and backward compositional recurrence agree on shortest cost three",min((2+1,1+1+1,1+5))==3),
"010":("the complete generated control paths from state one to state five have unique least-step control two-two",tuple(p for n in range(1,5) for p in product((1,2),repeat=n) if 1+sum(p)==5 and n==min(m for m in range(1,5) if any(1+sum(q)==5 for q in product((1,2),repeat=m))))==((2,2),)),
"011":("complete best-response enumeration of the two-action game has unique mutual equilibrium at the second-second action",(lambda pay:tuple((r,c) for r,c in product((1,2),repeat=2) if pay[(r,c)][0]==max(pay[(x,c)][0] for x in (1,2)) and pay[(r,c)][1]==max(pay[(r,y)][1] for y in (1,2))))({(1,1):(2,2),(1,2):(1,3),(2,1):(3,1),(2,2):(2,2)})==((2,2),)),
"012":("exact equal-support loss accumulation orders action A before B before C",(Fraction(1+2,2),Fraction(2+2,2),Fraction(3+2,2))==(Fraction(3,2),2,Fraction(5,2))),
"013":("the complete two-route network carries maximum flow three and the one-machine schedule has exact makespan three",min(2,2)+min(1,1)==3 and sum((2,1))==3),
"014":("complete bounded-scenario enumeration uniquely selects action B with least worst-case loss four",min((("A",5),("B",4),("C",6)),key=lambda x:x[1])==("B",4)),
"015":("a candidate value eight against certified optimum ten retains exact four-fifths ratio and gap two",Fraction(8,10)==Fraction(4,5) and 8+2==10),
"016":("opposed bounds at-most-two and at-least-three have no positive feasible label while every supplied bound is exceeded by its successor",not any(x<=2 and x>=3 for x in range(1,6)) and all(b+1>b for b in range(1,9))),
}
DEF={
"001":("SFT-MATH-OPT-FEASIBLE-OBJECTIVE-ORDER-001","Feasible set and objective-order structure","feasible-objective-order","Optimization begins with a completely generated feasible support and an exact objective preorder; no preferred candidate is imported."),
"002":("SFT-MATH-OPT-FINITE-EXTREMA-002","Exact minimum and maximum on finite support","complete-finite-extrema","Finite extrema are the objective-equivalent classes surviving complete comparison across every feasible candidate."),
"003":("SFT-MATH-OPT-PARETO-DOMINANCE-003","Pareto dominance and multiobjective order","complete-pareto-frontier","The Pareto frontier contains exactly those feasible candidates not dominated in every registered objective coordinate."),
"004":("SFT-MATH-OPT-LINEAR-PROGRAM-004","Linear-program correspondence","exact-linear-feasible-enumeration","Linear-program correspondence is exact affine feasibility and objective ordering over a generated rational support, with relaxation boundaries explicit."),
"005":("SFT-MATH-OPT-INTEGER-COMBINATORIAL-005","Integer and combinatorial optimization","complete-discrete-feasible-search","Integer and combinatorial optimization is complete exact enumeration or a separately certified structure-preserving reduction over discrete feasible forms."),
"006":("SFT-MATH-OPT-CONVEX-CORRESPONDENCE-006","Convex optimization correspondence","held-distance-convex-minimum","Convex correspondence is exact midpoint or held-distance ordering over generated rational supports, not an imported continuum theorem."),
"007":("SFT-MATH-OPT-DUAL-CERTIFICATE-007","Duality and certificate structure","matching-primal-dual-certificate","A dual certificate is an independently checkable exact bound matching a feasible primal value; equality closes optimality."),
"008":("SFT-MATH-OPT-VARIATIONAL-CORRESPONDENCE-008","Variational optimization correspondence","complete-path-action-minimum","Variational correspondence compares the exact action of every generated finite path and retains all boundary records."),
"009":("SFT-MATH-OPT-DYNAMIC-PROGRAMMING-009","Dynamic programming as compositional optimization","subproblem-optimum-composition","Dynamic programming is lawful when locally retained subproblem optima compose to the same result as complete path enumeration."),
"010":("SFT-MATH-OPT-GENERATED-STATE-CONTROL-010","Optimal control on generated state paths","complete-control-path-optimum","Optimal control is exact ordering of every generated admissible state-action path under fixed dynamics and boundary custody."),
"011":("SFT-MATH-OPT-GAME-EQUILIBRIUM-011","Game equilibrium finite correspondence","mutual-best-response-census","A finite game equilibrium is a complete action profile whose every unilateral alternative fails to improve the acting participant's exact order."),
"012":("SFT-MATH-OPT-DECISION-LOSS-012","Decision theory and loss ordering","exact-decision-loss-order","Decision theory orders complete action-state loss records under declared exact support weights without importing utility scales or priors."),
"013":("SFT-MATH-OPT-FLOW-SCHEDULING-013","Operations-research flow and scheduling","flow-schedule-conservation","Flow and scheduling retain capacity, conservation, precedence and resource custody across every generated route or schedule."),
"014":("SFT-MATH-OPT-ROBUST-BOUNDED-UNCERTAINTY-014","Robust optimization under bounded uncertainty","complete-worst-case-scenario-order","Robust optimization orders each candidate by its complete declared scenario family, with no hidden distribution or fitted uncertainty radius."),
"015":("SFT-MATH-OPT-APPROXIMATION-GAP-015","Approximation guarantees and gaps","exact-certified-approximation-gap","An approximation guarantee requires an exact candidate value and independent optimum bound whose ratio or additive gap is explicitly certified."),
"016":("SFT-MATH-OPT-INFEASIBLE-UNBOUNDED-BOUNDARY-016","Infeasibility and unboundedness boundaries","complete-infeasible-or-successor-unbounded-certificate","Infeasibility requires elimination of every feasible candidate; unboundedness requires a successor construction exceeding every supplied finite bound."),
}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=("no axiom, fitted objective, imported optimizer answer or target outcome selects the result","host 0 denotes structural absence or counts artifacts only and is not an SFT number object","no negative, irrational, imaginary or floating proof scalar","no opaque solver, sampled feasible subset or unregistered tie breaker","no unrestricted continuum optimum without a separate exact successor or enclosure certificate","no failed route retires an obligation or changes protected authority")
def d(k,b,bw,g,gw):return binary_dimension(k,k+"?",b,bw,g,gw)
def dims(rel):return (d("feasibility","selected-feasible-candidates","Selected candidates may hide alternatives.","complete-generated-feasible-support","Every feasible form is generated."),d("objective","imported-optimum-answer","An imported optimum cannot select the law.",rel,"The exact order follows from the declared objective."),d("orientation","negative-cost-scalar","Negative proof scalars violate the domain.","positive-cost-held-orientation","Magnitude stays positive and direction is structural."),d("enumeration","sampled-search","Samples cannot close optimality.","complete-declared-candidate-census","Every declared candidate is compared."),d("provenance","outcome-selected","Outcome feedback invalidates forcing.","root-bound-forward-forcing","The law reaches the premise-free root."),d("observation","preopened-result","A preopened result may choose the law.","post-registry-exact-observation","Observation opens after freeze."),d("generality","fixed-instance-only","One instance lacks a successor boundary.","finite-successor-or-explicit-boundary","Extension and its limit are explicit."),d("extension","fit-exception-extra-rule","An exception adds a parameter.","dated-complete-no-extra-rule","Only lawful versioned extension is admitted."))
class OptimizationProgram(GeneratedMathematicsProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch="mathematics",statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];text,passed=OBS[n];deps=("SFT-MATH-PROB-IDENTIFIABILITY-016","SFT-MATH-ORDER-MONOTONE-MAP-010","SFT-MATH-GRAPH-CONNECTIVITY-CUT-FLOW-003")+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f"Generate the complete eight-axis OPT-{n} product before observation access.",f"Every supplied positive finite OPT-{n} feasible support, objective, path, scenario and registered successor boundary.",dims(rel),f"OPT-{n} uniquely retains {rel}, complete candidate custody, root forcing, post-registry observation and no extra rule.",(statement,text),"The least nonempty feasible support and exact objective generate a complete order and retained optimum class.","Appending one feasible form, objective coordinate, path step or scenario preserves all prior comparisons and tests every new relation exactly once.",EX,(Witness("exact-observation",text,passed),Witness("complete-feasible-census","Every declared candidate, path or scenario is compared.",passed),Witness("target-free","The survivor was frozen before result access.",True)),f"The frozen census separately owns {title.lower()}.",statement,"Enumerate 256 forms, reconstruct independently, replay the exact optimization witness and reject four controls.","The claim closes the declared finite candidate and successor grammar; unrestricted continuum claims require separate certificates.",(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
