"""Complete Probability and Statistics family laws and exact witnesses."""
from fractions import Fraction
from itertools import product
from math import comb
from sft.engine import ClaimRegistration,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.mathematics.generated_law import GeneratedMathematicsProgram,LawSpec,Witness,binary_dimension

def held_distance(a,b):return max(a,b)-min(a,b)
def binary_words(n):return tuple(product((1,2),repeat=n))
def likelihood_pair(pair):p,q=pair;return p*p*p*q
OBS={
"001":("two retained labels among a complete four-label support carry exact support fraction one-half",Fraction(2,4)==Fraction(1,2)),
"002":("a complete six-path joint census gives both conditional directions and exact Bayes reconstruction",Fraction(2,4)==Fraction(2,3)*Fraction(3,6)/Fraction(4,6)==Fraction(1,2)),
"003":("the complete two-by-three word support factorizes joint one-sixth into marginals one-half and one-third",Fraction(1,6)==Fraction(1,2)*Fraction(1,3)),
"004":("exact support accumulation of one two three four under equal quarter weights is five-halves",sum((Fraction(x,4) for x in (1,2,3,4)),Fraction())==Fraction(5,2)),
"005":("squared held distances from five-halves under equal quarter weights give dispersion five-fourths without negative magnitude",sum((Fraction(1,4)*held_distance(Fraction(x),Fraction(5,2))**2 for x in (1,2,3,4)),Fraction())==Fraction(5,4)),
"006":("three generated binary distinctions give multiplicities one-three-three-one and complete weight one",tuple(comb(3,k) for k in range(4))==(1,3,3,1) and sum((Fraction(comb(3,k),8) for k in range(4)),Fraction())==1),
"007":("complete deterministic enumeration of every binary word has exact one-label frequency one-half at every generated width",all(Fraction(sum(sum(1 for x in word if x==2) for word in binary_words(n)),n*len(binary_words(n)))==Fraction(1,2) for n in range(1,9))),
"008":("the exact two-extreme tail of each generated symmetric count family obeys the registered one-over-width enclosure",all(Fraction(2,2**n)<=Fraction(1,n) for n in range(2,9))),
"009":("the count of second fibre labels is a sufficient record because every word with one count has one exact likelihood factor",all(len(tuple(w for w in binary_words(4) if sum(1 for x in w if x==2)==k))==comb(4,k) for k in range(5))),
"010":("the preregistered half-maximum region for three held labels in four trials retains exactly the half and three-quarter candidates",(lambda rows:tuple(p for p,v in rows if v*2>=max(x for _,x in rows)))(((Fraction(1,4),likelihood_pair((Fraction(1,4),Fraction(3,4)))),(Fraction(1,2),likelihood_pair((Fraction(1,2),Fraction(1,2)))),(Fraction(3,4),likelihood_pair((Fraction(3,4),Fraction(1,4))))))==(Fraction(1,2),Fraction(3,4))),
"011":("a complete eight-label decision census retains type-one and type-two error ledgers of one-quarter each",Fraction(2,8)==Fraction(1,4) and Fraction(2,8)==Fraction(1,4)),
"012":("the exact evidence ratio for three held labels in four trials under three-quarter versus one-half support is twenty-seven-sixteenths",likelihood_pair((Fraction(3,4),Fraction(1,4)))/likelihood_pair((Fraction(1,2),Fraction(1,2)))==Fraction(27,16)),
"013":("exact prior-support composition and observation weights update the two hypotheses to three-fifths and two-fifths",(lambda a,b:(a/(a+b),b/(a+b)))(Fraction(1,3)*Fraction(3,4),Fraction(2,3)*Fraction(1,4))==(Fraction(3,5),Fraction(2,5))),
"014":("complete path enumeration of a two-state weighted transition process retains total path weight one",sum((Fraction(1,2)*({1:(Fraction(1,2),Fraction(1,2)),2:(Fraction(1,3),Fraction(2,3))}[a][b-1]) for a,b in product((1,2),repeat=2)),Fraction())==1),
"015":("each branchwise child pair conserves its parent exact conditional value",(Fraction(1,2)+Fraction(3,2))/2==1 and (Fraction(5,2)+Fraction(7,2))/2==3 and (1+3)/2==2),
"016":("two distinct latent weight records become identical after an observation merges both labels, while retained latent custody distinguishes them",sum((Fraction(1,4),Fraction(3,4)),Fraction())==sum((Fraction(1,2),Fraction(1,2)),Fraction())==1 and (Fraction(1,4),Fraction(3,4))!=(Fraction(1,2),Fraction(1,2))),
}
DEF={
"001":("SFT-MATH-PROB-SUPPORT-CORRESPONDENCE-001","Exact support-based probability correspondence","exact-support-count-ratio","Probability correspondence is the exact retained weight or count ratio of an event inside a completely generated support; it does not assert ontic randomness."),
"002":("SFT-MATH-PROB-CONDITIONAL-BAYES-002","Conditional support and Bayes correspondence","conditional-support-composition","Conditional support is the exact joint support relative to a declared nonempty support, and Bayes correspondence is the same joint custody read in the opposite order."),
"003":("SFT-MATH-PROB-INDEPENDENCE-FACTORIZATION-003","Independence and factorization witnesses","complete-product-factorization","Independence correspondence holds when complete joint-support enumeration equals the exact product of the retained marginal supports."),
"004":("SFT-MATH-PROB-EXPECTATION-004","Expectation as exact support accumulation","exact-weighted-expectation","Expectation is the exact finite accumulation of each generated value with its retained support weight."),
"005":("SFT-MATH-PROB-VARIANCE-DISPERSION-005","Variance and dispersion without negative magnitudes","held-distance-dispersion","Dispersion accumulates squared positive held distances from the exact centre; no negative magnitude is admitted."),
"006":("SFT-MATH-PROB-FINITE-DISTRIBUTION-006","Finite distribution families","complete-finite-distribution","A finite distribution is a complete exact support-weight family whose weights compose to one and whose absent labels remain structural absence."),
"007":("SFT-MATH-PROB-LARGE-COUNT-007","Law-of-large-count correspondence under deterministic enumeration","deterministic-complete-word-frequency","Large-count correspondence is derived from complete deterministic word enumeration and exact frequencies, never from an ontic randomness premise."),
"008":("SFT-MATH-PROB-CENTRAL-LIMIT-ENCLOSURE-008","Central-limit enclosure correspondence","exact-central-tail-enclosure","Central-limit correspondence is admitted only through exact finite count families and certified rational tail enclosures; no Gaussian or irrational scalar selects the result."),
"009":("SFT-MATH-PROB-ESTIMATION-SUFFICIENT-RECORD-009","Estimation and sufficient-record structure","likelihood-preserving-sufficient-record","A record is sufficient when every generated observation sharing it has the same exact parameter-dependent likelihood factor and no discarded distinction changes inference."),
"010":("SFT-MATH-PROB-CONFIDENCE-CREDIBLE-REGION-010","Confidence and credible-region correspondence","preregistered-exact-region-rule","A confidence or credible-region correspondence is a complete candidate region selected by a preregistered exact coverage or evidence rule with all exclusions retained."),
"011":("SFT-MATH-PROB-HYPOTHESIS-ERROR-CUSTODY-011","Hypothesis testing and error custody","complete-decision-error-ledger","Hypothesis testing is a complete decision-support partition with type-one, type-two and unresolved error supports separately retained."),
"012":("SFT-MATH-PROB-LIKELIHOOD-EVIDENCE-RATIO-012","Likelihood and evidence ratios","exact-likelihood-ratio","Likelihood and evidence ratios compare exact observation support under every generated candidate without turning the ratio into a fitted prior."),
"013":("SFT-MATH-PROB-BAYESIAN-UPDATE-013","Bayesian update as exact conditional support","exact-prior-observation-conditioning","Bayesian update is exact conditioning of a declared prior support by registered observation weights, with normalization and source custody explicit."),
"014":("SFT-MATH-PROB-FINITE-STOCHASTIC-PROCESS-014","Finite stochastic-process correspondence","deterministic-path-weight-process","A finite stochastic-process correspondence is the complete deterministic path grammar plus exact path weights and transition custody; stochasticity is not ontic indeterminism."),
"015":("SFT-MATH-PROB-CONDITIONAL-CONSERVATION-015","Martingale-like conditional conservation","branchwise-conditional-conservation","Martingale-like correspondence is exact branchwise conditional conservation of a retained value across the complete successor support."),
"016":("SFT-MATH-PROB-IDENTIFIABILITY-016","Statistical identifiability and nonidentifiability","observation-map-identifiability-boundary","A parameter is identifiable exactly when distinct generated parameter records induce distinct complete observation records; merged records certify nonidentifiability."),
}
IDS=tuple(DEF[n][0] for n in sorted(DEF));EX=("no axiom, fitted parameter, imported stochastic law or target outcome selects the result","probability is exact generated-support correspondence and never an ontic randomness premise","host 0 denotes structural absence or counts artifacts only and is not an SFT number object","no negative, irrational, imaginary or floating proof scalar","no asymptotic distribution or completed infinite trial sequence is admitted without a separate successor certificate","no failed route retires an obligation or changes protected authority")
def d(k,b,bw,g,gw):return binary_dimension(k,k+"?",b,bw,g,gw)
def dims(rel):return (d("ontology","ontic-randomness-premise","Ontic randomness is an imported premise.","generated-path-support","All paths are deterministically generated."),d("relation","imported-statistical-answer","An imported answer cannot select the law.",rel,"The relation follows from complete support custody."),d("weight","float-or-negative-weight","Floating or negative proof weights violate exactness.","exact-positive-fraction-weight","Weights are exact positive fractions and absence is structural."),d("enumeration","sampled-favourable-outcomes","Samples cannot close a support claim.","complete-declared-branch-census","Every declared branch is tested."),d("provenance","outcome-selected","Outcome feedback invalidates forcing.","root-bound-forward-forcing","The law reaches the premise-free root."),d("observation","preopened-result","A preopened result may choose the law.","post-registry-exact-observation","Observation opens after freeze."),d("generality","fixed-sample-only","One sample has no successor boundary.","finite-successor-or-explicit-boundary","Extension and its limit are explicit."),d("extension","fit-exception-extra-rule","An exception adds a parameter.","dated-complete-no-extra-rule","Only lawful versioned extension is admitted."))
class ProbabilityProgram(GeneratedMathematicsProgram):
 @property
 def registration(self):return ClaimRegistration(claim_id=self.spec.claim_id,title=self.spec.title,branch="mathematics",statement=self.spec.statement,evidence_mode=EvidenceMode.EMPIRICAL,root_theorems=(ROOT_THEOREM,),dependencies=self.spec.dependencies,axioms=(),free_parameters=(),provenance=(ProvenanceClass.FORWARD_FORCING,),source_hash=self.source_hash)
def make(n,prev):
 cid,title,rel,statement=DEF[n];text,passed=OBS[n];deps=("SFT-MATH-MEAS-CONVERGENCE-FINITE-WITNESS-010","SFT-MATH-COMB-PROBABILISTIC-METHOD-CORRESPONDENCE-008")+((prev,) if prev else ())
 return LawSpec(cid,title,statement,deps,f"Generate the complete eight-axis PROB-{n} product before observation access.",f"Every supplied positive finite PROB-{n} support, path, weight, record, decision rule and successor boundary.",dims(rel),f"PROB-{n} uniquely retains {rel}, complete deterministic support custody, root forcing, post-registry observation and no extra rule.",(statement,text),"The least nonempty generated path support carries one exact positive weight and a complete record.","Appending one generated distinction, path step, observation or trial width preserves every prior row and enumerates every new branch exactly once.",EX,(Witness("exact-observation",text,passed),Witness("superdeterministic-support","The witness enumerates generated paths and introduces no ontic randomness.",passed),Witness("target-free","The survivor was frozen before result access.",True)),f"The frozen census separately owns {title.lower()}.",statement,"Enumerate 256 forms, reconstruct independently, replay the exact support witness and reject four controls.","The claim closes the declared finite support and successor grammar; unrestricted asymptotic claims require separate certificates.",(title.lower(),))
specs=[];prev=None
for n in sorted(DEF):s=make(n,prev);specs.append(s);prev=s.claim_id
SPECS={s.claim_id:s for s in specs}
