from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-DETECTION-QUANTIFICATION-004';DOMAINS=(('unidentified-signal', 'held-analyte-method-condition'), ('single-numerical-zero-blank', 'complete-positive-blank-support'), ('selected-low-result', 'complete-positive-ordered-level-support'), ('declared-limit-number', 'exact-blank-sample-distinguishability'), ('false-results-erased', 'false-positive-negative-custody'), ('detection-equals-quantification', 'repeatability-and-recovery-required'), ('negative-undetected-value', 'detected-quantified-label-or-EmptyOne'), ('threshold-refitted', 'successor-retains-and-recomputes-levels'));SURVIVOR='held-analyte-method-condition__complete-positive-blank-support__complete-positive-ordered-level-support__exact-blank-sample-distinguishability__false-positive-negative-custody__repeatability-and-recovery-required__detected-quantified-label-or-EmptyOne__successor-retains-and-recomputes-levels'
from fractions import Fraction
def classify(blanks,levels):
 u=max(blanks);return tuple((a,all(x>u for x in r),all(x>u for x in r) and len(r)>1 and max(r)!=min(r)) for a,r in levels)
b=(Fraction(1),Fraction(2));levels=((Fraction(1),(Fraction(2),Fraction(3))),(Fraction(2),(Fraction(4),Fraction(5))));x=classify(b,levels)
native={"identity":True,"blank":len(b)==2,"levels":len(levels)==2,"detection":x[0][1] is False,"errors":levels[0][1][0]==max(b),"quantification":x[1][2] is True,"absence":x[0][1] is False,"successor":len(classify(b,levels+((Fraction(3),(Fraction(6),Fraction(7))),)))==3}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
