from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CHROMATOGRAPHIC-RETENTION-RESOLUTION-018'
DOMAINS=(('retention-number-without-analyte', 'held-analyte-and-matrix'), ('phase-free-retention', 'held-mobile-and-stationary-phases'), ('floating-retention-value', 'exact-positive-retention-coordinate-or-EmptyOne'), ('apex-only-peak', 'complete-positive-peak-support'), ('named-separated-or-not', 'exact-pairwise-resolution-relation'), ('unconditioned-retention-index', 'held-temperature-flow-column-condition'), ('selected-resolved-analytes', 'complete-coelution-error-absence-custody'), ('refitted-added-analyte', 'successor-retains-and-appends-complete-peaks'))
SURVIVOR='held-analyte-and-matrix__held-mobile-and-stationary-phases__exact-positive-retention-coordinate-or-EmptyOne__complete-positive-peak-support__exact-pairwise-resolution-relation__held-temperature-flow-column-condition__complete-coelution-error-absence-custody__successor-retains-and-appends-complete-peaks'
DIMENSION_KEYS=('analyte', 'phases', 'coordinate', 'peak', 'resolution', 'condition', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
