from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-MASS-WEIGHTED-MOLECULAR-SIZE-003';DOMAINS=(('selected-heavy-chains', 'complete-resolved-chain-population'), ('nominal-class-labels', 'exact-positive-chain-sizes'), ('frequency-erased', 'positive-multiplicity-per-size'), ('free-statistical-weight', 'one-held-mass-copy-per-carrier-mass'), ('first-moment-only', 'complete-second-size-moment'), ('chain-count-denominator', 'complete-first-size-moment'), ('floating-moment-ratio', 'exact-positive-rational-moment-ratio'), ('weighted-mean-only-output', 'all-rows-moments-ratio-and-boundary-trace'));SURVIVOR='complete-resolved-chain-population__exact-positive-chain-sizes__positive-multiplicity-per-size__one-held-mass-copy-per-carrier-mass__complete-second-size-moment__complete-first-size-moment__exact-positive-rational-moment-ratio__all-rows-moments-ratio-and-boundary-trace'
from fractions import Fraction
rows=((2,3),(5,2));first=sum(m*n for m,n in rows);second=sum(m*m*n for m,n in rows);result=Fraction(second,first)
native={"population":len(rows)==2,"sizes":all(m>0 for m,_ in rows),"multiplicity":all(n>0 for _,n in rows),"weight":second==62,"numerator":second==62,"denominator":first==16,"arithmetic":result==Fraction(31,8),"certificate":result*first==second}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
