from itertools import product
import json,sys
CLAIM_ID="SFT-CHEM-RETROSYNTHETIC-DECOMPOSITION-RECONSTRUCTION-016";DOMAINS=(("selected-target-fragment","complete-held-target-carrier"),("chosen-disconnection-only","every-positive-binary-split-generated"),("one-step-retrosynthetic-story","recursive-decomposition-to-One-leaves"),("cyclic-or-duplicate-search","finite-acyclic-unique-tree-census"),("unverified-plausible-route","every-edge-has-exact-forward-inverse"),("successful-route-only","all-generated-paths-forward-reconstruct-target"),("external-mechanism-selects-tree","value-free-graph-sealed-before-comparison"),("fixed-depth-exception","fresh-occurrence-successor-generates-all-new-splits"));SURVIVOR="__".join(x[1] for x in DOMAINS)
def trees(word):
 if len(word)==1:return ((word,None,None),)
 return tuple((word,l,r) for cut in range(1,len(word)) for l in trees(word[:cut]) for r in trees(word[cut:]))
def forward(t):return t[0] if t[1] is None else forward(t[1])+forward(t[2])
def main():
 s=json.load(open(sys.argv[1]));g=["__".join(x) for x in product(*DOMAINS)];d={x["candidate_id"]:x["survives"] for x in s["decisions"]};four,five=trees(("a","b","c","d")),trees(("a","b","c","d","e"));native={"four_tree_count":len(four)==5,"five_tree_count":len(five)==14,"every_tree_unique":len(set(four))==5 and len(set(five))==14,"all_forward_reconstruct":all(forward(x)==x[0] for x in (*four,*five)),"all_root_splits":{len(x[1][0]) for x in four}=={1,2,3}};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==g and d=={x:x==SURVIVOR for x in g} and sum(d.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(g),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_route_or_measurement_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
