"""Implementation-distinct validator for SFT-SOCIAL-COMMUNICATION-NOISE-001."""
from itertools import product
import json,sys
CLAIM_ID='SFT-SOCIAL-COMMUNICATION-NOISE-001'; DOMAINS=(('answer-only-or-decontextualized-carrier', 'message-channel-context-interpretation-carrier'), ('population-time-or-context-erased', 'channel-and-audience-bounded'), ('imported-fitted-or-status-selected-relation', 'distortion-ambiguity-and-loss-relation'), ('aggregate-or-favourable-output-only', 'source-versions-audiences-interpretations-and-missingness-held'), ('observation-report-model-value-conflated', 'evidence-and-normative-class-explicit'), ('prestige-prior-answer-or-target-selected', 'root-bound-forward-forcing'), ('one-group-one-period-universalized', 'positive-finite-extension-retains-all-contexts'), ('free-weight-exception-or-opaque-oracle', 'no-extra-rule')); SURVIVOR='message-channel-context-interpretation-carrier__channel-and-audience-bounded__distortion-ambiguity-and-loss-relation__source-versions-audiences-interpretations-and-missingness-held__evidence-and-normative-class-explicit__root-bound-forward-forcing__positive-finite-extension-retains-all-contexts__no-extra-rule'
def main():
    sealed=json.load(open(sys.argv[1],encoding="utf-8")); generated=["__".join(x) for x in product(*DOMAINS)]; received=[x["candidate_id"] for x in sealed["census"]["candidates"]]; decisions={x["candidate_id"]:x["survives"] for x in sealed["decisions"]}
    passed=(sealed["claim_id"]==CLAIM_ID and received==generated and sealed["census"]["expected_cardinality"]==len(generated) and len(set(received))==len(generated) and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and sealed["closure"]["minimality_passed"] is True and sealed["closure"]["named_shape_uniqueness_passed"] is True and {x["kind"] for x in sealed["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] is True for x in sealed["controls"]))
    print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"candidate_count":len(generated),"survivor":SURVIVOR if passed else None}},sort_keys=True))
if __name__=="__main__": main()
