"""Implementation-distinct validator for SFT-ENG-AVAILABILITY-001."""
from itertools import product
import json,sys
CLAIM_ID='SFT-ENG-AVAILABILITY-001'; DOMAINS=(('answer-only-or-unversioned-artifact', 'system-service-time-state-carrier'), ('operating-test-or-lifecycle-boundary-erased', 'availability-window-bounded'), ('target-fitted-status-or-application-selected-relation', 'serviceable-time-relation'), ('successful-output-only', 'uptime-downtime-cause-maintenance-demand-and-window-held'), ('law-design-test-simulation-demonstration-conflated', 'science-design-test-and-decision-classes-explicit'), ('opaque-build-prior-output-or-authority-selected', 'root-bound-forward-translation'), ('single-platform-prototype-or-favourable-run-universalized', 'positive-finite-extension-preserves-platforms-failures-and-versions'), ('free-weight-exception-or-silent-dependency', 'no-extra-rule')); SURVIVOR='system-service-time-state-carrier__availability-window-bounded__serviceable-time-relation__uptime-downtime-cause-maintenance-demand-and-window-held__science-design-test-and-decision-classes-explicit__root-bound-forward-translation__positive-finite-extension-preserves-platforms-failures-and-versions__no-extra-rule'
def main():
    sealed=json.load(open(sys.argv[1],encoding="utf-8")); generated=["__".join(x) for x in product(*DOMAINS)]; received=[x["candidate_id"] for x in sealed["census"]["candidates"]]; decisions={x["candidate_id"]:x["survives"] for x in sealed["decisions"]}
    passed=(sealed["claim_id"]==CLAIM_ID and received==generated and sealed["census"]["expected_cardinality"]==len(generated) and len(set(received))==len(generated) and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and sealed["closure"]["minimality_passed"] is True and sealed["closure"]["named_shape_uniqueness_passed"] is True and {x["kind"] for x in sealed["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] is True for x in sealed["controls"]))
    print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"candidate_count":len(generated),"survivor":SURVIVOR if passed else None}},sort_keys=True))
if __name__=="__main__": main()
