from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ROTATIONAL-SPECTRUM-LINE-015'
DOMAINS=(('detached-microwave-line', 'held-molecule-geometry-isotopologue'), ('line-without-rotational-states', 'held-initial-final-rotational-states'), ('axis-free-rotational-number', 'held-molecular-axis-and-symmetry'), ('floating-frequency', 'exact-positive-frequency-or-EmptyOne'), ('arbitrary-line-strength', 'exact-positive-line-response-or-EmptyOne'), ('unconditioned-catalog-line', 'held-energy-temperature-unit-condition'), ('selected-detected-lines', 'complete-frequency-error-intensity-state-custody'), ('refitted-catalog-extension', 'successor-appends-without-changing-prior-lines'))
SURVIVOR='held-molecule-geometry-isotopologue__held-initial-final-rotational-states__held-molecular-axis-and-symmetry__exact-positive-frequency-or-EmptyOne__exact-positive-line-response-or-EmptyOne__held-energy-temperature-unit-condition__complete-frequency-error-intensity-state-custody__successor-appends-without-changing-prior-lines'
DIMENSION_KEYS=('carrier', 'states', 'axis', 'coordinate', 'response', 'condition', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
