from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-PERFORMANCE-BUDGET-022'
DOMAINS=(('detached-final-number', 'held-result-sample-measurand-method'), ('untraced-reference', 'complete-reference-traceability-chain'), ('precision-as-trueness', 'exact-trueness-relation-or-EmptyOne'), ('single-observation-precision', 'complete-replicate-precision-relation'), ('sensitivity-without-domain', 'exact-sensitivity-selectivity-domain'), ('single-detection-threshold', 'separate-detection-quantification-custody'), ('single-combined-error-number', 'complete-component-dependency-uncertainty-budget'), ('replaced-validation-study', 'successor-retains-and-appends-validation-records'))
SURVIVOR='held-result-sample-measurand-method__complete-reference-traceability-chain__exact-trueness-relation-or-EmptyOne__complete-replicate-precision-relation__exact-sensitivity-selectivity-domain__separate-detection-quantification-custody__complete-component-dependency-uncertainty-budget__successor-retains-and-appends-validation-records'
DIMENSION_KEYS=('result', 'traceability', 'trueness', 'precision', 'response', 'decision', 'uncertainty', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
