from itertools import product
import json,sys
CLAIM='SFT-CHEM-STATE-SYMMETRY-DEGENERACY-005'
DOMAINS=(('cross-carrier-equivalence', 'one-molecule-equivalence'), ('energy-only-equivalence', 'complete-symmetry-signature'), ('unsigned-or-absent-multiplicity', 'positive-spin-multiplicity'), ('continuum-or-zero-projection', 'empty-One-or-positive-axis-rank'), ('free-degeneracy-number', 'one-or-complementary-orientation-support'), ('erased-sign-labels', 'held-symmetry-label-composition'), ('unbounded-anonymous-members', 'complete-positive-component-class'), ('term-table-exception', 'no-extra-rule'))
SURVIVOR='one-molecule-equivalence__complete-symmetry-signature__positive-spin-multiplicity__empty-One-or-positive-axis-rank__one-or-complementary-orientation-support__held-symmetry-label-composition__complete-positive-component-class__no-extra-rule'
LAW={"sigma_orientation":1,"positive_axis_orientation":2,"degeneracy":"positive-spin-times-positive-orientation","absence":"structural-empty-One"}
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; registered=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}; witnesses=(LAW["sigma_orientation"]==1 and LAW["positive_axis_orientation"]==2 and 1*1==1 and 2*2==4 and LAW["absence"]=="structural-empty-One"); passed=(d["claim_id"]==CLAIM and registered==generated and len(set(registered))==256 and decisions=={row:row==SURVIVOR for row in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and all(row["passed"] for row in d["controls"]) and witnesses); print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"candidate_count":len(generated),"survivor":SURVIVOR if passed else None,"independent_law":LAW}},sort_keys=True))
if __name__=="__main__":main()
