from itertools import product
import json,sys
CLAIM="SFT-CHEM-INSERTION-ELIMINATION-PATHWAY-013"
DOMAINS=(("anonymous-products","complete-retained-carrier-support"),("endpoint-only-reaction","complete-before-after-adjacency-difference"),("imported-product-formula","xz-plus-y-to-x-y-z-adjacency-law"),("named-migratory-step","migration-plus-insertion-composition"),("insertion-elimination-conflation","extrusion-exact-insertion-inverse"),("selected-leaving-group","complete-two-eliminand-centre-trace"),("imported-unsaturation-name","held-unsaturation-ring-or-carbene-boundary"),("mechanism-specific-exception","adjacency-trace-composition-no-extra-rule"))
SURVIVOR="complete-retained-carrier-support__complete-before-after-adjacency-difference__xz-plus-y-to-x-y-z-adjacency-law__migration-plus-insertion-composition__extrusion-exact-insertion-inverse__complete-two-eliminand-centre-trace__held-unsaturation-ring-or-carbene-boundary__adjacency-trace-composition-no-extra-rule"
def main():
 d=json.load(open(sys.argv[1],encoding="utf-8"));g=["__".join(x) for x in product(*DOMAINS)];r=[x["candidate_id"] for x in d["census"]["candidates"]];dec={x["candidate_id"]:x["survives"] for x in d["decisions"]};before={("X","Z")};after={("X","Y"),("Y","Z")};removed=before-after;added=after-before;reconstructed=(len(before),len(after),len(removed),len(added))==(1,2,1,2)
 passed=d["claim_id"]==CLAIM and r==g and len(g)==256 and len(set(r))==256 and dec=={x:x==SURVIVOR for x in g} and sum(dec.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {x["kind"] for x in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] for x in d["controls"]) and reconstructed
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(g),"unique_survivor":SURVIVOR if passed else None,"insertion_counts":[1,2,1,2],"external_product_or_mechanism_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_or_free_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
