from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-ACCURACY-TRUENESS-001';DOMAINS=(('nominal-value-premise', 'traceable-reference-identity'), ('result-without-measurand', 'held-sample-measurand-method'), ('selected-result', 'complete-ordered-result-support'), ('signed-error-scalar', 'held-side-positive-distance-or-EmptyOne'), ('declared-accurate-label', 'exact-observed-reference-relation'), ('single-certain-value', 'complete-exact-uncertainty-support'), ('universal-method-accuracy', 'registered-material-method-boundary'), ('renormalized-new-results', 'successor-retains-and-recomputes-all-results'));SURVIVOR='traceable-reference-identity__held-sample-measurand-method__complete-ordered-result-support__held-side-positive-distance-or-EmptyOne__exact-observed-reference-relation__complete-exact-uncertainty-support__registered-material-method-boundary__successor-retains-and-recomputes-all-results'
from fractions import Fraction
def compare(o,r):return None if o==r else ("above" if o>r else "below",abs(o-r))
rows=((1,Fraction(101,10),Fraction(10)),(2,Fraction(10),Fraction(10)))
native={"reference":all(x[2]>0 for x in rows),"measurand":True,"support":tuple(x[0] for x in rows)==(1,2),"comparison":compare(rows[0][1],rows[0][2])==("above",Fraction(1,10)),"trueness":compare(rows[1][1],rows[1][2]) is None,"uncertainty":all(isinstance(x[1],Fraction) for x in rows),"boundary":True,"successor":len(rows+((3,Fraction(10),Fraction(10)),))==3}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
