"""Frozen Layer-One obligations for Astronomy and Cosmology."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AstronomyObligation:
    claim_id: str
    title: str
    family: str
    carrier: str
    relation: str
    retained_record: str
    evidence_boundary: str
    statement: str
    falsification_condition: str


FAMILY_ORDER = (
    "observation_geometry", "object_identity_classification", "radiation_motion_time",
    "stellar_systems", "planetary_small_body", "interstellar_enrichment_formation",
    "galaxies_populations", "compact_high_energy_multimessenger", "large_scale_expansion",
    "early_background_abundance", "dark_horizon_unobserved", "inference_prediction_handoffs",
)


def row(suffix, title, family, carrier, relation, record, boundary, statement, falsification):
    return AstronomyObligation("SFT-ASTRO-" + suffix + "-001", title, family, carrier, relation, record, boundary, statement, falsification)


DATA = (
    # Source-observer-signal geometry — 6
    ("SOURCE", "Astronomical source", "observation_geometry", "emitting-or-interacting-source-carrier", "source-state-to-signal-relation", "identity-direction-distance-time-and-state-held", "source-resolution-bounded", "An astronomical source is a bounded carrier whose state produces or alters a registered signal along a declared path.", "Reject if source identity, direction, distance, time or state is erased."),
    ("OBSERVER", "Astronomical observer", "observation_geometry", "site-platform-instrument-observer-carrier", "observer-to-record-relation", "site-platform-clock-calibration-and-frame-held", "observer-frame-bounded", "An observer is a source-located site, platform, instrument and clock relation, not an unlocated view.", "Reject if frame, clock, site or calibration changes without record."),
    ("SIGNAL", "Astronomical signal", "observation_geometry", "source-path-detector-signal-carrier", "propagation-and-detection-relation", "emission-path-band-arrival-and-quality-held", "signal-channel-bounded", "A signal retains source, path, band, arrival, detector response and quality status.", "Reject if propagation, detector response or non-detection is omitted."),
    ("ANGULAR-POSITION", "Angular position and reference frame", "observation_geometry", "direction-coordinate-frame-carrier", "frame-transformation-relation", "epoch-origin-basis-motion-and-uncertainty-held", "astrometric-frame-bounded", "Angular position is a direction in a named frame and epoch with motion and uncertainty retained.", "Reject an unframed coordinate or an epoch-free moving position."),
    ("DISTANCE", "Astronomical distance", "observation_geometry", "source-observer-separation-carrier", "method-specific-distance-inference", "method-calibration-ladder-range-and-uncertainty-held", "distance-method-bounded", "Distance is a method-bound source-observer relation whose ladder, calibration and range remain explicit.", "Reject if one distance method silently substitutes for another."),
    ("SELECTION", "Survey selection and non-detection", "observation_geometry", "target-opportunity-detection-status-carrier", "selection-and-detection-relation", "footprint-cadence-threshold-masks-and-missingness-held", "survey-selection-bounded", "Selection, detection, upper limit, non-detection, missing and outside-footprint status remain distinct.", "Reject if a non-detection or missing row becomes ordinary zero or confirmed absence."),
    # Object/classification — 6
    ("OBJECT", "Astronomical object identity", "object_identity_classification", "cross-epoch-object-carrier", "observation-association-relation", "positions-times-signals-links-and-alternatives-held", "association-bounded", "Object identity is a reconstructible association of observations across epochs and channels.", "Reject if blended or ambiguous detections are forced into one object."),
    ("CLASSIFICATION", "Astronomical classification", "object_identity_classification", "feature-evidence-class-carrier", "feature-to-class-relation", "features-method-probability-alternatives-and-version-held", "classifier-and-taxonomy-bounded", "Classification retains measured features, method, alternatives and taxonomy version.", "Reject if a label replaces its evidence or an uncertain class becomes certain."),
    ("POPULATION", "Astronomical population", "object_identity_classification", "selection-bounded-object-set-carrier", "membership-and-distribution-relation", "selection-volume-time-weights-and-censoring-held", "population-sampling-bounded", "A population is a selection-bounded set with membership, volume, time, weights and censoring retained.", "Reject population inference from favorable detections alone."),
    ("MORPHOLOGY", "Astronomical morphology", "object_identity_classification", "resolved-structure-carrier", "component-adjacency-shape-relation", "resolution-band-orientation-distance-and-uncertainty-held", "morphology-method-bounded", "Morphology is a resolution- and band-bound organization of distinguishable components.", "Reject if resolution or projection is erased."),
    ("COMPOSITION", "Astronomical composition inference", "object_identity_classification", "species-feature-source-carrier", "spectral-or-particle-composition-relation", "species-lines-model-boundary-abundance-and-errors-held", "composition-method-bounded", "Composition inference retains species evidence, excitation, method and alternatives.", "Reject if a line identification or abundance is detached from its method."),
    ("CATALOG", "Astronomical catalogue", "object_identity_classification", "versioned-row-provenance-carrier", "source-to-catalogue-transformation", "query-version-columns-flags-crossmatches-and-missingness-held", "catalogue-release-bounded", "A catalogue is a versioned transformation with row provenance, flags, crossmatches and missingness.", "Reject if catalogue version, query or quality filtering is hidden."),
    # Radiation/motion/time — 6
    ("FLUX-LUMINOSITY", "Flux and luminosity", "radiation_motion_time", "source-path-received-radiation-carrier", "flux-distance-luminosity-relation", "band-distance-geometry-extinction-and-time-held", "radiometric-boundary-declared", "Received flux and source luminosity remain distinct through distance, geometry, band and attenuation records.", "Reject if apparent brightness is relabelled intrinsic luminosity."),
    ("SPECTRUM", "Astronomical spectrum", "radiation_motion_time", "ordered-band-signal-carrier", "wavelength-frequency-energy-feature-relation", "resolution-response-calibration-lines-and-continuum-held", "spectral-method-bounded", "A spectrum is an ordered calibrated signal with resolution, response, features and continuum retained.", "Reject an uncalibrated or selectively cropped feature set."),
    ("REDSHIFT", "Astronomical redshift", "radiation_motion_time", "emitted-observed-feature-carrier", "feature-displacement-relation", "feature-identity-frame-motion-gravity-expansion-and-error-held", "redshift-cause-bounded", "Redshift is an emitted-to-observed feature relation; motion, gravity and expansion causes remain distinguishable.", "Reject if measured redshift alone is treated as a unique distance or cause."),
    ("MOTION", "Astrometric and radial motion", "radiation_motion_time", "time-indexed-position-spectrum-carrier", "position-or-feature-change-relation", "frame-epochs-baseline-components-and-errors-held", "motion-observation-bounded", "Motion retains frame, epochs, baseline, components and uncertainties.", "Reject if apparent and physical motion are conflated."),
    ("VARIABILITY", "Astronomical variability", "radiation_motion_time", "time-series-source-carrier", "state-to-signal-change-relation", "cadence-window-band-errors-and-nondetections-held", "time-series-bounded", "Variability is source change observed through a declared cadence and window with gaps retained.", "Reject if sampling aliases or missing intervals are erased."),
    ("PERIOD-TRANSIENT", "Periodicity and transient distinction", "radiation_motion_time", "time-ordered-event-or-cycle-carrier", "recurrence-or-one-event-relation", "epochs-phase-window-baseline-and-alternatives-held", "temporal-class-bounded", "Periodic recurrence, quasi-periodicity and one-time transience remain distinct temporal classes.", "Reject if a finite window manufactures a period or erases recurrence."),
    # Stars — 6
    ("STAR-FORMATION", "Stellar formation", "stellar_systems", "bound-collapsing-gas-dust-carrier", "assembly-heating-cooling-ignition-relation", "environment-mass-flow-time-and-evidence-held", "formation-history-bounded", "Stellar formation is a source-dated assembly history from bound material to sustained stellar state.", "Reject if a final star is used as its own formation record."),
    ("STELLAR-STRUCTURE", "Stellar structure", "stellar_systems", "layered-stellar-state-carrier", "gravity-pressure-energy-transport-balance", "mass-radius-composition-temperature-luminosity-and-age-held", "stellar-model-observation-bounded", "A stellar state retains layers, mass, radius, composition, energy transport and observation boundary.", "Reject if model state is relabelled direct interior observation."),
    ("STELLAR-ENERGY", "Stellar energy generation", "stellar_systems", "fuel-reaction-product-radiation-carrier", "reaction-network-to-output-ledger", "species-rates-losses-time-and-neutrino-photon-record-held", "nuclear-network-bounded", "Stellar energy follows species through a complete reaction and loss ledger.", "Reject if missing energy or species is fitted away."),
    ("STELLAR-EVOLUTION", "Stellar evolution", "stellar_systems", "time-ordered-stellar-state-carrier", "fuel-structure-transition-relation", "initial-mass-composition-environment-loss-and-time-held", "evolution-track-bounded", "Stellar evolution is a causal state sequence with initial conditions and mass loss retained.", "Reject if a population ordering is silently treated as one star's history."),
    ("STELLAR-POPULATION", "Stellar population", "stellar_systems", "selection-bounded-star-set-carrier", "age-metallicity-mass-distribution-relation", "selection-distance-extinction-binaries-and-completeness-held", "population-synthesis-bounded", "A stellar population retains selection, distance, extinction, binaries and completeness.", "Reject if unresolved binaries or selection effects are ignored."),
    ("STELLAR-ENDPOINT", "Stellar terminal state", "stellar_systems", "progenitor-transition-remnant-carrier", "mass-composition-loss-collapse-relation", "progenitor-event-remnant-ejecta-and-uncertainty-held", "endpoint-class-bounded", "Terminal state links progenitor, transition, remnant and ejecta without erasing alternatives.", "Reject if remnant class is inferred without progenitor and event boundaries."),
    # Planetary — 6
    ("PLANETARY-SYSTEM", "Planetary-system identity", "planetary_small_body", "host-orbiting-body-joint-carrier", "bound-orbit-and-interaction-relation", "host-bodies-orbits-masses-epochs-and-errors-held", "system-detection-bounded", "A planetary system is a host-and-body organization with orbits, interactions and detection limits retained.", "Reject if candidates or unseen completeness are treated as confirmed bodies."),
    ("ORBIT", "Astronomical orbit", "planetary_small_body", "body-primary-state-sequence-carrier", "bounded-recurrent-motion-relation", "frame-epoch-state-elements-perturbations-and-errors-held", "orbit-solution-bounded", "An orbit is a frame- and epoch-bound recurrent state sequence with perturbations and uncertainty.", "Reject if fitted elements replace observations or an open trajectory is called bound."),
    ("RESONANCE-TIDE", "Orbital resonance and tidal state", "planetary_small_body", "coupled-orbit-spin-carrier", "integer-recurrence-and-dissipation-relation", "periods-phases-bodies-history-and-errors-held", "resonance-baseline-bounded", "Resonance is joint recurrence; tidal locking additionally retains dissipative history.", "Reject a near ratio without phase recurrence or a lock without history."),
    ("PLANET", "Planet and satellite classification", "planetary_small_body", "body-orbit-mass-shape-context-carrier", "feature-and-dynamical-class-relation", "host-orbit-mass-radius-composition-and-method-held", "classification-version-bounded", "Planet, satellite and dwarf classifications retain dynamical context and measured features.", "Reject if taxonomy supplies a physical law or uncertain mass is hidden."),
    ("EXOPLANET", "Exoplanet observation", "planetary_small_body", "host-signal-planet-candidate-carrier", "transit-radial-imaging-or-timing-inference", "method-selection-host-activity-period-and-errors-held", "detection-method-bounded", "An exoplanet claim retains host, method, signal, selection, stellar activity and alternatives.", "Reject if an instrumental or stellar signal is silently promoted to a planet."),
    ("SMALL-BODY", "Small-body population", "planetary_small_body", "selection-bounded-comet-asteroid-carrier", "orbit-size-composition-population-relation", "survey-selection-orbits-activity-and-completeness-held", "small-body-survey-bounded", "Small-body inference retains survey selection, orbit, activity, composition and completeness.", "Reject if detected objects are treated as the complete population."),
    # ISM/enrichment/star formation — 6
    ("ISM", "Interstellar-medium identity", "interstellar_enrichment_formation", "multiphase-gas-dust-field-carrier", "phase-and-transfer-network", "location-phase-species-field-scale-and-time-held", "ism-observation-bounded", "The interstellar medium is a multiphase carrier with species, dust, fields and transfers retained.", "Reject if phases or unseen components are collapsed into one medium."),
    ("DUST", "Astronomical dust", "interstellar_enrichment_formation", "grain-composition-size-temperature-carrier", "absorption-emission-scattering-relation", "composition-size-band-temperature-and-geometry-held", "dust-model-bounded", "Dust inference retains grain properties, temperature, geometry and radiative method.", "Reject if extinction and emission models are conflated."),
    ("MOLECULAR-CLOUD", "Molecular cloud", "interstellar_enrichment_formation", "molecule-gas-dust-bound-region-carrier", "chemistry-cooling-collapse-relation", "species-density-temperature-motion-and-boundary-held", "tracer-method-bounded", "A molecular cloud retains tracer, chemistry, density, motion and boundary.", "Reject if one tracer is assumed to equal total material without a bridge."),
    ("CHEMICAL-ENRICHMENT", "Cosmic chemical enrichment", "interstellar_enrichment_formation", "source-ejecta-medium-generation-carrier", "nucleosynthesis-transfer-mixing-relation", "species-yields-sources-time-mixing-and-losses-held", "enrichment-history-bounded", "Enrichment is a source-to-ejecta-to-medium history retaining species, mixing and losses.", "Reject if abundance similarity proves unique provenance."),
    ("STAR-FORMATION-ENVIRONMENT", "Environment-to-star-formation relation", "interstellar_enrichment_formation", "cloud-environment-young-star-carrier", "condition-to-formation-rate-comparison", "mass-area-time-tracer-selection-and-controls-held", "region-and-tracer-bounded", "Star-formation relations retain region, tracer, time, selection and controls.", "Reject a universal rate from one tracer or region."),
    ("FEEDBACK", "Stellar feedback", "interstellar_enrichment_formation", "star-output-medium-response-carrier", "radiation-wind-ejecta-transfer-relation", "source-energy-momentum-species-geometry-and-time-held", "feedback-domain-bounded", "Feedback follows source outputs into medium response with energy, momentum and species ledgers.", "Reject if correlation alone establishes direction or conserved transfer."),
    # Galaxies — 6
    ("GALAXY", "Galaxy identity", "galaxies_populations", "stars-gas-dust-dark-joint-carrier", "bound-structure-and-history-relation", "components-distance-frame-environment-and-time-held", "galaxy-observation-bounded", "A galaxy is a bound multi-component organization with environment and history retained.", "Reject if morphology alone supplies identity or causal history."),
    ("GALACTIC-STRUCTURE", "Galactic structure", "galaxies_populations", "resolved-component-network-carrier", "spatial-kinematic-component-relation", "band-resolution-orientation-distance-and-errors-held", "structure-method-bounded", "Galactic structure retains components, projection, kinematics and resolution.", "Reject if projected light is treated as complete mass structure."),
    ("GALACTIC-DYNAMICS", "Galactic dynamics", "galaxies_populations", "tracer-potential-motion-carrier", "mass-distribution-to-motion-relation", "tracers-distance-inclination-baryons-dark-and-errors-held", "dynamical-model-bounded", "Galactic dynamics retain tracers, baryons, unseen inference, geometry and alternatives.", "Reject if a rotation curve uniquely identifies an untested mass model."),
    ("TULLY-FISHER", "Luminosity-rotation scaling", "galaxies_populations", "galaxy-luminosity-velocity-carrier", "rank-four-dilution-scaling-test", "band-distance-inclination-baryonic-choice-and-residuals-held", "sample-and-regression-bounded", "The pre-source rank-four relation is tested against complete source-bound galaxy rows and residuals.", "Reject if regression choice, selection or adverse rows are erased."),
    ("GALAXY-EVOLUTION", "Galaxy evolution", "galaxies_populations", "time-ordered-galaxy-population-carrier", "assembly-transformation-quenching-relation", "selection-redshift-mass-environment-and-progenitors-held", "population-history-bounded", "Galaxy evolution distinguishes population sequence from individual causal history.", "Reject progenitor bias or redshift selection erasure."),
    ("CLUSTER-LARGE-ENVIRONMENT", "Groups, clusters and environment", "galaxies_populations", "member-galaxy-gas-potential-carrier", "membership-binding-environment-relation", "selection-redshift-membership-mass-method-and-errors-held", "cluster-definition-bounded", "Cluster inference retains membership, gas, potential, selection and mass method.", "Reject if projection or one mass proxy is treated as exact membership and mass."),
    # Compact/high-energy — 6
    ("COMPACT-OBJECT", "Compact-object identity", "compact_high_energy_multimessenger", "source-field-matter-signal-carrier", "compact-state-to-observable-relation", "position-mass-spin-environment-method-and-errors-held", "compact-inference-bounded", "Compact-object identity retains source, environment, signals, method and alternatives.", "Reject if one signature uniquely fixes an unobserved interior."),
    ("WHITE-DWARF-NEUTRON-STAR", "Degenerate remnant classes", "compact_high_energy_multimessenger", "progenitor-degenerate-remnant-carrier", "mass-composition-pressure-endpoint-relation", "mass-radius-composition-field-rotation-and-errors-held", "remnant-class-bounded", "White-dwarf and neutron-star claims retain mass, radius, composition, rotation and field evidence.", "Reject if a theoretical limit replaces measurement."),
    ("BLACK-HOLE", "Black-hole candidate and horizon evidence", "compact_high_energy_multimessenger", "source-orbit-accretion-wave-carrier", "compactness-and-horizon-consequence-relation", "mass-spin-environment-messenger-and-alternatives-held", "horizon-evidence-bounded", "A black-hole claim retains dynamical mass, compactness, environment, messenger and alternatives.", "Reject if darkness alone proves a horizon or interior ontology."),
    ("TRANSIENT", "High-energy transient", "compact_high_energy_multimessenger", "source-event-multiband-carrier", "progenitor-to-transient-relation", "localization-time-bands-selection-afterglow-and-errors-held", "transient-class-bounded", "A transient links source, event, localization, time, bands and afterglow with alternatives.", "Reject if one light-curve feature fixes a unique progenitor."),
    ("MULTIMESSENGER", "Multi-messenger association", "compact_high_energy_multimessenger", "photon-wave-neutrino-particle-event-carrier", "space-time-source-association-relation", "localizations-clocks-selection-background-and-errors-held", "association-window-bounded", "Multi-messenger association retains localization, clocks, selection and background coincidence.", "Reject if temporal proximity alone proves common origin."),
    ("COMPACT-POPULATION", "Compact-object population", "compact_high_energy_multimessenger", "selection-bounded-remnant-set-carrier", "formation-merger-population-relation", "survey-volume-selection-masses-spins-and-censoring-held", "population-model-bounded", "Compact populations retain detection selection, censoring and source history.", "Reject if detected events are treated as an unbiased population."),
    # Large-scale/expansion — 6
    ("COSMIC-HOMOGENEITY", "Large-scale statistical organization", "large_scale_expansion", "survey-volume-tracer-field-carrier", "scale-dependent-distribution-relation", "selection-mask-redshift-distance-and-errors-held", "survey-scale-bounded", "Large-scale organization is a survey- and scale-bound tracer distribution.", "Reject if finite-volume uniformity is asserted without scale and selection."),
    ("COSMIC-WEB", "Cosmic-web structure", "large_scale_expansion", "tracer-node-filament-void-carrier", "adjacency-density-history-relation", "tracer-selection-scale-redshift-method-and-errors-held", "web-extraction-bounded", "Web structure retains tracer, scale, method, selection and redshift.", "Reject if a visualization substitutes for a generated structure criterion."),
    ("EXPANSION-RECORD", "Cosmic expansion record", "large_scale_expansion", "source-redshift-distance-time-carrier", "distance-redshift-comparison-relation", "standardization-calibration-selection-covariance-and-era-held", "expansion-probe-bounded", "Expansion is a multi-probe distance-redshift record with calibration and covariance retained.", "Reject if one rung or probe silently sets the law."),
    ("DISTANCE-LADDER", "Distance-ladder composition", "large_scale_expansion", "anchor-rung-source-carrier", "calibration-composition-relation", "anchors-rungs-populations-zero-points-and-covariance-held", "ladder-version-bounded", "A distance ladder is an explicit composition of anchors and rungs with covariance.", "Reject if a terminal value is detached from its ladder."),
    ("LENSING", "Gravitational-lensing observation", "large_scale_expansion", "source-lens-observer-image-carrier", "multiple-path-distortion-relation", "redshifts-geometry-selection-mass-model-and-errors-held", "lensing-model-bounded", "Lensing retains source, lens, observer, geometry, mass model and degeneracies.", "Reject if an image distortion uniquely identifies mass without alternatives."),
    ("EXPANSION-HISTORY", "Expansion-history inference", "large_scale_expansion", "multi-probe-epoch-carrier", "ordered-expansion-state-reconstruction", "probes-calibration-covariance-model-boundary-and-time-held", "historical-inference-bounded", "Expansion history is an ordered reconstruction from independently retained probes.", "Reject if a fitted curve is relabelled direct cosmic history."),
    # Early/background/abundance — 6
    ("THERMAL-HISTORY", "Cosmic thermal history", "early_background_abundance", "ordered-radiation-matter-state-carrier", "dilution-interaction-transition-relation", "temperature-scale-species-epoch-and-evidence-held", "thermal-reconstruction-bounded", "Thermal history retains species, interaction, scale, temperature and evidence class by epoch.", "Reject if a present background uniquely supplies all earlier states."),
    ("CMB", "Cosmic microwave background", "early_background_abundance", "all-sky-frequency-temperature-polarization-carrier", "background-anisotropy-spectrum-relation", "frequency-calibration-mask-beam-foregrounds-and-covariance-held", "cmb-release-bounded", "CMB evidence retains frequency, calibration, beam, masks, foregrounds and covariance.", "Reject if a component-separated map is called raw observation."),
    ("ACOUSTIC-STRUCTURE", "Background acoustic structure", "early_background_abundance", "angular-spectrum-feature-carrier", "bounded-harmonic-recurrence-relation", "multipoles-peaks-covariance-foregrounds-and-model-boundary-held", "spectrum-analysis-bounded", "Acoustic structure retains harmonic features, covariance and extraction boundary.", "Reject if a selected peak or harmonic fit erases adverse multipoles."),
    ("PRIMORDIAL-ABUNDANCE", "Primordial abundance record", "early_background_abundance", "species-environment-abundance-carrier", "reaction-history-to-abundance-relation", "species-sites-methods-depletion-and-errors-held", "abundance-inference-bounded", "Primordial abundance inference retains species, sites, methods, depletion and stellar processing.", "Reject if current abundance is silently relabelled primordial."),
    ("RECOMBINATION", "Recombination and photon release", "early_background_abundance", "matter-radiation-interaction-state-carrier", "binding-opacity-release-relation", "species-temperature-redshift-optical-depth-and-evidence-held", "recombination-model-bounded", "Recombination links matter state, opacity and photon release with evidence boundaries.", "Reject if a model epoch is relabelled direct observation."),
    ("INITIAL-PERTURBATION", "Early perturbation record", "early_background_abundance", "background-anisotropy-seed-carrier", "initial-distinction-to-later-structure-relation", "scale-spectrum-phase-covariance-and-transfer-held", "seed-inference-bounded", "An early perturbation record retains scale, spectrum, covariance and transfer to later tracers.", "Reject if later structure uniquely reconstructs an unrecorded initial state."),
    # dark/horizon/multiverse — 6
    ("DARK-MATTER-EVIDENCE", "Dark-matter evidence class", "dark_horizon_unobserved", "visible-tracer-gravitational-residual-carrier", "observed-motion-lensing-growth-comparison", "baryons-geometry-selection-alternatives-and-errors-held", "dark-inference-bounded", "Dark-matter evidence is a cross-probe residual with baryons and alternatives retained.", "Reject if one anomaly or prior preference uniquely selects a carrier."),
    ("DARK-ENERGY-EVIDENCE", "Dark-energy evidence class", "dark_horizon_unobserved", "distance-growth-expansion-residual-carrier", "multi-probe-acceleration-comparison", "calibration-covariance-model-boundary-and-alternatives-held", "dark-energy-inference-bounded", "Dark-energy evidence retains distance, growth, calibration, covariance and alternatives.", "Reject if acceleration data alone fixes ontology or an equation of state."),
    ("COSMIC-HORIZON", "Cosmic horizon", "dark_horizon_unobserved", "observer-signal-reach-carrier", "finite-history-causal-access-relation", "observer-epoch-propagation-law-and-boundary-held", "horizon-definition-bounded", "A horizon is an observer- and epoch-bound causal access limit under admitted propagation.", "Reject if unobserved beyond-horizon state is relabelled observed absence."),
    ("TOPOLOGY", "Cosmic topology claim", "dark_horizon_unobserved", "observable-pattern-identification-carrier", "global-identification-consequence-relation", "survey-mask-scale-pattern-controls-and-alternatives-held", "observable-domain-bounded", "Topology claims require observable repeated-pattern consequences and controls.", "Reject if mathematical possibility is counted as observation."),
    ("MULTIVERSE", "Multiverse admissibility boundary", "dark_horizon_unobserved", "declared-domain-hypothesis-carrier", "observable-consequence-or-nonadmission-relation", "premises-domain-predictions-controls-and-access-held", "observable-consequence-bounded", "A multiverse claim enters empirical science only through a distinct observable consequence sealed before data.", "Reject if unobservability, anthropic selection or possibility is treated as confirmation."),
    ("ULTIMATE-FATE", "Cosmic ultimate-fate inference", "dark_horizon_unobserved", "current-state-law-history-carrier", "conditional-future-continuation-relation", "state-laws-uncertainty-alternatives-and-domain-held", "future-inference-bounded", "Ultimate fate is conditional continuation from current records and admitted laws, not an observed terminal state.", "Reject if extrapolation uncertainty or alternative lawful continuation is erased."),
    # inference/predictions/handoffs — 6
    ("LAW-HISTORY", "Universal law and cosmic history distinction", "inference_prediction_handoffs", "law-initial-condition-observation-carrier", "lawful-history-generation-relation", "law-receipts-initial-records-and-observations-held", "ownership-boundary-declared", "Universal law, contingent initial condition and source-dated history remain separate.", "Reject if a catalogue regularity is promoted to premise-free law."),
    ("MODEL-OBSERVATION", "Astronomical model-observation boundary", "inference_prediction_handoffs", "law-state-instrument-model-output-carrier", "conditional-simulation-comparison-relation", "inputs-parameters-observations-errors-and-output-held", "model-purpose-bounded", "A model output remains a conditional result compared with, not substituted for, observation.", "Reject opaque prediction or parameter fitting as derivation."),
    ("STANDING-PREDICTION", "Standing astronomical prediction", "inference_prediction_handoffs", "sealed-premise-prediction-outcome-carrier", "predeclared-comparison-relation", "targets-metrics-baselines-adverse-and-missing-rows-held", "prediction-question-bounded", "A standing prediction is sealed before outcome and retains every adverse and missing row.", "Reject post-outcome target changes or favorable-row selection."),
    ("UNEXPLAINED", "Unexplained astronomical observation", "inference_prediction_handoffs", "observation-controls-alternative-carrier", "residual-after-tested-explanations-relation", "data-method-controls-alternatives-and-failures-held", "residual-evidence-bounded", "Unexplained means a source-bound residual after declared controls, not evidence for a preferred unknown cause.", "Reject argument from ignorance or hidden adverse controls."),
    ("ASTROBIOLOGY", "Astrobiology and technosignature boundary", "inference_prediction_handoffs", "environment-signal-life-hypothesis-carrier", "biosignature-or-technosignature-comparison", "abiotic-controls-selection-contamination-and-replication-held", "life-evidence-bounded", "Life or technology claims require replicated signals and complete abiotic, instrumental and contamination controls.", "Reject an ambiguous signal or habitability proxy as life detection."),
    ("ASTRO-HANDOFF", "Astronomy scientific handoffs", "inference_prediction_handoffs", "law-instrument-earth-life-social-boundary-carrier", "typed-branch-handoff-relation", "source-owner-dependency-evidence-and-use-held", "branch-ownership-bounded", "Astronomy consumes universal laws and exports source-dated constraints through explicit Physics, Engineering, Earth, Biology and Social boundaries.", "Reject if an instrument selects a law or another branch's object is silently reowned."),
)


ASTRONOMY_OBLIGATIONS = tuple(row(*item) for item in DATA)


def validate_inventory() -> None:
    if len(ASTRONOMY_OBLIGATIONS) != 72 or len({row.claim_id for row in ASTRONOMY_OBLIGATIONS}) != 72:
        raise ValueError("Astronomy obligation surface must contain 72 unique rows")
    if tuple(dict.fromkeys(row.family for row in ASTRONOMY_OBLIGATIONS)) != FAMILY_ORDER:
        raise ValueError("Astronomy family order changed")


validate_inventory()
OBLIGATIONS = ASTRONOMY_OBLIGATIONS
__all__ = ("AstronomyObligation", "ASTRONOMY_OBLIGATIONS", "OBLIGATIONS", "FAMILY_ORDER", "validate_inventory")
