from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-RADIOACTIVE-BRANCHING-CHEMICAL-YIELD-004';DOMAINS=(('unlabelled-yield', 'held-decay-channel'), ('anonymous-product-amount', 'held-daughter-chemical-species'), ('continuum-branch-probability', 'positive-counted-branch-events'), ('fitted-chemical-recovery', 'positive-counted-recovered-events'), ('percentage-premise', 'exact-recovered-per-branch-ratio'), ('independent-branch-fractions', 'complete-branch-partition-sums-to-One'), ('selected-favorable-daughter', 'complete-daughter-yield-vector'), ('renormalize-after-omission', 'new-branch-repartitions-complete-total'));SURVIVOR='held-decay-channel__held-daughter-chemical-species__positive-counted-branch-events__positive-counted-recovered-events__exact-recovered-per-branch-ratio__complete-branch-partition-sums-to-One__complete-daughter-yield-vector__new-branch-repartitions-complete-total'
from fractions import Fraction
def partition(events):
 total=sum(events);return tuple(Fraction(x,total) for x in events)
rows=(("one","d1",3,2),("two","d2",1,1));parts=partition(tuple(x[2] for x in rows))
native={"channel":len({x[0] for x in rows})==2,"daughter":len({x[1] for x in rows})==2,"events":rows[0][2]>0,"recovery":rows[0][3]>0,"yield":Fraction(rows[0][3],rows[0][2])==Fraction(2,3),"partition":sum(parts)==1,"complete":len(rows)==2,"successor":partition((3,1,2))[0]==Fraction(1,2)}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
