from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-NUMBER-AVERAGE-MOLECULAR-SIZE-002';DOMAINS=(('selected-representative-chains', 'complete-resolved-chain-population'), ('binned-or-rounded-sizes', 'exact-positive-chain-sizes'), ('duplicate-carriers-collapsed', 'positive-multiplicity-per-size'), ('unweighted-size-total', 'multiplicity-weighted-size-total'), ('mass-total-denominator', 'complete-chain-count-denominator'), ('floating-average', 'exact-positive-rational-average'), ('unbounded-population-claim', 'sample-and-method-boundary-retained'), ('mean-only-output', 'all-rows-sums-ratio-and-boundary-trace'));SURVIVOR='complete-resolved-chain-population__exact-positive-chain-sizes__positive-multiplicity-per-size__multiplicity-weighted-size-total__complete-chain-count-denominator__exact-positive-rational-average__sample-and-method-boundary-retained__all-rows-sums-ratio-and-boundary-trace'
from fractions import Fraction
rows=((2,3),(5,2));count=sum(n for _,n in rows);total=sum(m*n for m,n in rows);result=Fraction(total,count)
native={"population":len(rows)==2,"sizes":len({m for m,_ in rows})==2,"multiplicity":all(n>0 for _,n in rows),"numerator":total==16,"denominator":count==5,"arithmetic":result==Fraction(16,5),"scope":sum(n for _,n in rows)==5,"certificate":result*count==total}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
