from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-FLUORESCENCE-YIELD-LIFETIME-010';DOMAINS=(('detached-fluorescence-number', 'held-molecular-carrier-and-excitation'), ('emission-peak-without-states', 'held-initial-and-final-molecular-states'), ('radiative-channel-only', 'complete-radiative-nonradiative-partition'), ('signed-floating-emission-value', 'exact-positive-emission-support-or-EmptyOne'), ('fitted-quantum-yield', 'exact-outcome-over-excitation-ratio'), ('imported-continuous-decay-law', 'exact-positive-observation-lifetime-or-EmptyOne'), ('selected-bright-favorable-records', 'complete-emission-yield-lifetime-condition-custody'), ('refitted-added-channel', 'successor-retains-and-repartitions-complete-counts'));SURVIVOR='held-molecular-carrier-and-excitation__held-initial-and-final-molecular-states__complete-radiative-nonradiative-partition__exact-positive-emission-support-or-EmptyOne__exact-outcome-over-excitation-ratio__exact-positive-observation-lifetime-or-EmptyOne__complete-emission-yield-lifetime-condition-custody__successor-retains-and-repartitions-complete-counts'
from fractions import Fraction
EMPTY="EmptyOne"
excitation=5
rows=(("molecule-a","excited-a","ground-a","radiative",Fraction(7,3),3,Fraction(2,3)),("molecule-a","excited-a","other-a","nonradiative",EMPTY,2,EMPTY))
native={"carrier":all(x[0]=="molecule-a" and x[1]=="excited-a" for x in rows),"transition":len({x[2] for x in rows})==2,"channels":sum(x[5] for x in rows)==excitation,"emission":rows[0][4]==Fraction(7,3) and rows[1][4]==EMPTY,"yield":Fraction(rows[0][5],excitation)==Fraction(3,5),"lifetime":rows[0][6]==Fraction(2,3),"custody":rows[1][6]==EMPTY,"extension":tuple(rows)==rows}
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};passed=sealed["claim_id"]==CLAIM_ID and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(item["passed"] for item in sealed["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
