from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-NMR-RELAXATION-EXCHANGE-008';DOMAINS=(('detached-relaxation-or-exchange-number', 'held-molecular-carrier-and-site'), ('single-state-decay-label', 'held-source-and-destination-states'), ('generic-dynamics-label', 'held-relaxation-or-exchange-process'), ('continuous-time-premise', 'finite-positive-observation-interval'), ('imported-exponential-or-fitted-rate', 'exact-positive-time-or-counted-transition-rate'), ('unconditioned-universal-dynamics', 'held-condition-unit-and-uncertainty'), ('missing-or-unfavorable-rows-erased', 'measured-bounded-unavailable-unresolved-custody'), ('refitted-added-timescale', 'successor-retains-and-appends-complete-transitions'));SURVIVOR='held-molecular-carrier-and-site__held-source-and-destination-states__held-relaxation-or-exchange-process__finite-positive-observation-interval__exact-positive-time-or-counted-transition-rate__held-condition-unit-and-uncertainty__measured-bounded-unavailable-unresolved-custody__successor-retains-and-appends-complete-transitions'
from fractions import Fraction
EMPTY="EmptyOne"
rows=(("site-a","longitudinal-relaxation","state-a","state-a",Fraction(3,2),"seconds","measured"),("site-b","hydrogen-exchange","state-a","state-b",Fraction(5,3),"per-second","measured"),("site-a","rotating-frame-relaxation","state-a","state-a",EMPTY,"seconds","unavailable"))
native={"carrier":len({x[0] for x in rows})==2,"states":rows[1][2]!=rows[1][3],"process":len({x[1] for x in rows})==3,"resource":rows[0][4]==Fraction(3,2),"relation":Fraction(5,1)/Fraction(3,1)==Fraction(5,3),"observation":rows[0][5]=="seconds","adversity":rows[2][4]==EMPTY and rows[2][6]=="unavailable","extension":len(rows+(("site-b","transverse-relaxation","state-b","state-b",Fraction(4,3),"seconds","bounded"),))==4}
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};passed=sealed["claim_id"]==CLAIM_ID and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(item["passed"] for item in sealed["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
