from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ELECTRON-NEUTRON-DIFFRACTION-017'
DOMAINS=(('diffraction-without-material', 'held-material-phase-and-composition'), ('probe-agnostic-pattern', 'held-electron-or-neutron-probe'), ('chemistry-invents-probe-law', 'explicit-physics-scattering-handoff'), ('peaks-without-reciprocal-state', 'held-reciprocal-and-site-support'), ('floating-diffraction-coordinate', 'exact-positive-diffraction-coordinate-or-EmptyOne'), ('same-response-for-both-probes', 'probe-specific-structure-response-correspondence'), ('selected-agreeing-reflections', 'complete-probe-reflection-error-custody'), ('refitted-mixed-probe-pattern', 'successor-appends-probe-records-without-conflation'))
SURVIVOR='held-material-phase-and-composition__held-electron-or-neutron-probe__explicit-physics-scattering-handoff__held-reciprocal-and-site-support__exact-positive-diffraction-coordinate-or-EmptyOne__probe-specific-structure-response-correspondence__complete-probe-reflection-error-custody__successor-appends-probe-records-without-conflation'
DIMENSION_KEYS=('carrier', 'probe', 'handoff', 'support', 'coordinate', 'correspondence', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
