from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CONSTITUTIONAL-ISOMER-ENUMERATION-004'
DOMAINS=(('unheld-formula-total', 'held-element-multiplicity-support'), ('catalogued-bond-patterns', 'complete-generated-incidence-support'), ('disconnected-fragment-admission', 'one-connected-molecular-carrier'), ('unbounded-edge-placement', 'admitted-element-capacity-bound'), ('drawing-name-identity', 'canonical-graph-equivalence-quotient'), ('known-isomer-list', 'complete-bounded-candidate-census'), ('count-without-members', 'every-member-and-rejection-witness'), ('retroactive-recount', 'new-support-appends-new-census'))
SURVIVOR='held-element-multiplicity-support__complete-generated-incidence-support__one-connected-molecular-carrier__admitted-element-capacity-bound__canonical-graph-equivalence-quotient__complete-bounded-candidate-census__every-member-and-rejection-witness__new-support-appends-new-census'
DIMENSION_KEYS=('composition', 'edges', 'connectedness', 'valence', 'identity', 'enumeration', 'certificate', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
