from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CORROSION-REACTION-NETWORK-012';DOMAINS=(('material-free-rate', 'held-material-environment-custody'), ('single-reaction-answer', 'complete-anodic-cathodic-network'), ('continuum-loss-rate', 'positive-counted-path-events'), ('unbounded-corrosion-rate', 'exact-events-per-resource-ratio'), ('independent-fitted-rates', 'exact-synchronized-path-rate'), ('signed-net-current', 'held-excess-path-orientation'), ('numerical-zero-corrosion-current', 'structural-EmptyOne-balanced-excess'), ('selected-corrosion-rate', 'complete-potential-current-rate-mass-loss-vector'));SURVIVOR='held-material-environment-custody__complete-anodic-cathodic-network__positive-counted-path-events__exact-events-per-resource-ratio__exact-synchronized-path-rate__held-excess-path-orientation__structural-EmptyOne-balanced-excess__complete-potential-current-rate-mass-loss-vector'
from fractions import Fraction
def network(a,c):
 s=min(a,c);return (s,"balanced",None) if a==c else ((s,"anodic-excess",a-c) if a>c else (s,"cathodic-excess",c-a))
b=network(Fraction(4,2),Fraction(4,2));a=network(Fraction(6,2),Fraction(4,2));native={"paths":True,"material":True,"environment":True,"rate":b[0]==2,"balance":b[2] is None,"orientation":a[1]=="anodic-excess","positive":a[2]==1,"network":True}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
