from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CANONICAL-MOLECULAR-GRAPH-ENCODING-001'
DOMAINS=(('detached-symbol-string', 'held-finite-molecular-carrier'), ('unlabelled-vertex-count', 'complete-held-atom-identities'), ('adjacency-without-bond-state', 'complete-held-bond-identities'), ('discarded-isotope-charge-stereo', 'retained-isotope-charge-stereo-fibres'), ('input-order-dependent-word', 'exhaustive-equivalence-class-canonical-word'), ('one-way-text-token', 'exact-word-to-graph-reconstruction'), ('source-free-identifier', 'held-source-and-translation-custody'), ('renumbered-prior-graph', 'append-only-new-carrier-registration'))
SURVIVOR='held-finite-molecular-carrier__complete-held-atom-identities__complete-held-bond-identities__retained-isotope-charge-stereo-fibres__exhaustive-equivalence-class-canonical-word__exact-word-to-graph-reconstruction__held-source-and-translation-custody__append-only-new-carrier-registration'
DIMENSION_KEYS=('carrier', 'atoms', 'bonds', 'orientation', 'canonicality', 'decoding', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
