from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-REACTION-GRAPH-GENERATION-007'
DOMAINS=(('reaction-name-without-reactants', 'complete-held-reactant-graphs'), ('imported-template-library', 'registered-identity-conserving-graph-transitions'), ('untracked-atom-creation-loss', 'complete-carrier-conservation'), ('product-only-connectivity', 'complete-bond-change-trace'), ('major-product-search', 'all-reachable-product-support'), ('string-product-deduplication', 'canonical-product-graph-quotient'), ('favorable-products-only', 'all-products-absence-and-rejection-custody'), ('unbounded-reaction-claim', 'declared-depth-and-transition-resource'))
SURVIVOR='complete-held-reactant-graphs__registered-identity-conserving-graph-transitions__complete-carrier-conservation__complete-bond-change-trace__all-reachable-product-support__canonical-product-graph-quotient__all-products-absence-and-rejection-custody__declared-depth-and-transition-resource'
DIMENSION_KEYS=('source', 'moves', 'carriers', 'bonds', 'generation', 'identity', 'custody', 'resource')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
