"""Implementation-distinct, value-free INORG-002 reconstruction."""
from itertools import product
import json,sys
CLAIM="SFT-CHEM-COORDINATION-NUMBER-INCIDENCE-COUNT-002"
DOMAINS=(("formula-or-central-name-only","admitted-complete-coordination-entity"),("nearby-or-selected-ligands","every-distinct-direct-central-incidence"),("imported-coordination-number-table","positive-count-of-generated-incidence-traces"),("repeated-ligand-labels-merged","occurrence-distinct-incidences-counted-once"),("numerical-zero-or-negative-vacancy","structural-EmptyOne-outside-positive-support"),("observed-counts-readable-before-seal","complete-23-record-value-free-identity-seal"),("general-crystal-pi-and-sigma-senses-mixed","direct-inorganic-incidence-sense-held"),("next-ligand-recounts-or-replaces-support","next-incidence-preserves-prior-and-adds-one"))
SURVIVOR="admitted-complete-coordination-entity__every-distinct-direct-central-incidence__positive-count-of-generated-incidence-traces__occurrence-distinct-incidences-counted-once__structural-EmptyOne-outside-positive-support__complete-23-record-value-free-identity-seal__direct-inorganic-incidence-sense-held__next-incidence-preserves-prior-and-adds-one"
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; received=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}
 def direct_count(width):
  central="M-one"; occurrences=tuple(f"L-{n}" for n in range(1,width+1)); traces=tuple((central,occurrence) for occurrence in occurrences); return len(traces),traces
 c3,t3=direct_count(3);c4,t4=direct_count(4);c5,t5=direct_count(5); witnesses=(c3,c4,c5)==(3,4,5) and t4[:len(t3)]==t3 and t5[:len(t4)]==t4 and len(set(t5))==5
 passed=d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={candidate:candidate==SURVIVOR for candidate in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {row["kind"] for row in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(row["passed"] for row in d["controls"]) and witnesses
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"generated_three_four_five_counts_reconstructed":witnesses,"successor_preserves_prior_and_adds_one":witnesses,"numerical_zero_negative_irrational_imaginary_signed_or_continuum_proof_value_used":False,"coordination_table_valence_geometry_ligand_field_bonding_model_target_measurement_or_source_file_accessed":False}},sort_keys=True))
if __name__=="__main__":main()
