"""Implementation-distinct validator for SFT-ASTRO-COSMIC-HORIZON-001."""
from itertools import product
import json,sys
CLAIM_ID='SFT-ASTRO-COSMIC-HORIZON-001'; DOMAINS=(('answer-only-or-unbounded-carrier', 'observer-signal-reach-carrier'), ('frame-time-or-selection-erased', 'horizon-definition-bounded'), ('imported-fitted-or-missing-relation', 'finite-history-causal-access-relation'), ('favourable-output-incomplete-record', 'observer-epoch-propagation-law-and-boundary-held'), ('observation-model-forecast-conflated', 'evidence-class-explicit'), ('prior-answer-or-target-selected', 'root-bound-forward-forcing'), ('one-favourable-object-erases-population', 'positive-finite-extension-retains-all-rows'), ('free-parameter-exception-or-opaque-oracle', 'no-extra-rule')); SURVIVOR='observer-signal-reach-carrier__horizon-definition-bounded__finite-history-causal-access-relation__observer-epoch-propagation-law-and-boundary-held__evidence-class-explicit__root-bound-forward-forcing__positive-finite-extension-retains-all-rows__no-extra-rule'
def main():
    sealed=json.load(open(sys.argv[1],encoding="utf-8")); generated=["__".join(x) for x in product(*DOMAINS)]; received=[x["candidate_id"] for x in sealed["census"]["candidates"]]; decisions={x["candidate_id"]:x["survives"] for x in sealed["decisions"]}
    passed=(sealed["claim_id"]==CLAIM_ID and received==generated and sealed["census"]["expected_cardinality"]==len(generated) and len(set(received))==len(generated) and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and sealed["closure"]["minimality_passed"] is True and sealed["closure"]["named_shape_uniqueness_passed"] is True and {x["kind"] for x in sealed["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(x["passed"] is True for x in sealed["controls"]))
    print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"candidate_count":len(generated),"survivor":SURVIVOR if passed else None}},sort_keys=True))
if __name__=="__main__": main()
