"""Implementation-distinct value-free KIN-009 reconstruction."""
from itertools import product
import json,sys
CLAIM='SFT-CHEM-REVERSIBLE-KINETIC-EQUILIBRIUM-CORRESPONDENCE-009'
DOMAINS=(('selected-forward-or-reverse-direction', 'both-held-directional-transition-occurrences'), ('separate-unrelated-forward-and-reverse-graphs', 'same-exact-two-state-closed-transition-graph'), ('endpoint-rate-fit-or-aggregate-only', 'exact-ordered-directed-transition-word'), ('imported-equilibrium-constant-steady-state-or-balance-law', 'closed-graph-recurrence-support'), ('terminal-compositions-collapsed-or-averaged', 'every-initial-terminal-composition-retained-separately'), ('direction-label-disagreement-or-adverse-row-omitted', 'all-favorable-adverse-and-disagreement-records-retained'), ('selected-kinetic-pages-or-answer-table', 'complete-article-supplement-movie-and-archive-ledger'), ('state-time-composition-energy-or-target-readable-before-seal', 'value-free-164-record-identity-seal-and-depth-independent-pair-successor'))
SURVIVOR='both-held-directional-transition-occurrences__same-exact-two-state-closed-transition-graph__exact-ordered-directed-transition-word__closed-graph-recurrence-support__every-initial-terminal-composition-retained-separately__all-favorable-adverse-and-disagreement-records-retained__complete-article-supplement-movie-and-archive-ledger__value-free-164-record-identity-seal-and-depth-independent-pair-successor'
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; received=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}
 states=("state-a","state-b"); forward=(states[0],states[1],"first-to-second"); reverse=(states[1],states[0],"second-to-first"); recurrence=states; next_pair=("state-c","state-d"); prior=((states,forward,reverse,recurrence),); extended=prior+((next_pair,(next_pair[0],next_pair[1],"first-to-second"),(next_pair[1],next_pair[0],"second-to-first"),next_pair),)
 witnesses=(len(states)==2 and states[0]!=states[1] and forward[0]==reverse[1] and forward[1]==reverse[0] and forward[2]!=reverse[2] and recurrence==states and extended[:len(prior)]==prior and len(extended)==len(prior)+1)
 passed=(d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={candidate:candidate==SURVIVOR for candidate in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {row["kind"] for row in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(row["passed"] for row in d["controls"]) and witnesses)
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"same_two_state_graph_reconstructed":witnesses,"directed_kinetic_word_and_recurrence_support_reconstructed":witnesses,"pair_successor_preserves_complete_prior_family":witnesses,"numerical_zero_negative_irrational_imaginary_logarithmic_signed_or_continuum_proof_value_used":False,"rate_equation_equilibrium_constant_stochastic_weight_fit_target_measurement_or_source_file_accessed":False}},sort_keys=True))
if __name__=="__main__":main()
