from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-FISSION-PRODUCT-CHEMICAL-DISTRIBUTION-011';DOMAINS=(('chemistry-selects-fission-products', 'explicit-physics-product-handoff'), ('mass-chain-only', 'held-nuclide-and-chemical-species'), ('bulk-release-fraction', 'complete-phase-location-support'), ('expected-yield-premise', 'positive-species-resolved-events'), ('renormalized-selected-products', 'exact-complete-partition-of-One'), ('fixed-chemical-form-assumption', 'explicit-chemical-redistribution-network'), ('silent-decay-inside-chemistry', 'nuclide-change-requires-physics-handoff'), ('selected-terminal-sample', 'successor-retains-complete-time-sample-vector'));SURVIVOR='explicit-physics-product-handoff__held-nuclide-and-chemical-species__complete-phase-location-support__positive-species-resolved-events__exact-complete-partition-of-One__explicit-chemical-redistribution-network__nuclide-change-requires-physics-handoff__successor-retains-complete-time-sample-vector'
from fractions import Fraction
def distribution(rows):
 if not rows:return None
 total=sum(r[4] for r in rows);return tuple((*r[:4],Fraction(r[4],total)) for r in rows)
def redistribute(a,b):return distribution(b) if {r[0] for r in a}=={r[0] for r in b} and sum(r[4] for r in a)==sum(r[4] for r in b) else None
a=(("Cs","fluoride","salt","bulk",3),("Xe","elemental","gas","headspace",1));b=(("Cs","fluoride","salt","wall",2),("Xe","elemental","gas","headspace",2))
native={"handoff":{r[0] for r in a}=={"Cs","Xe"},"identity":a[0][1]=="fluoride","support":len({r[2:4] for r in a})==2,"events":min(r[4] for r in a)>0,"partition":sum(r[-1] for r in distribution(a))==1,"chemistry":redistribute(a,b)[0][3]=="wall","boundary":{r[0] for r in a}=={r[0] for r in b},"successor":len(redistribute(a,b))==2}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
