from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-MASS-ISOTOPE-FRAGMENT-VECTOR-014'
DOMAINS=(('mass-peaks-without-molecule', 'held-molecular-parent-and-ion-carriers'), ('nominal-mass-only', 'held-isotope-and-charge-composition'), ('floating-mass-to-charge', 'exact-positive-mass-charge-ratio'), ('peak-without-fragment-path', 'held-parent-fragment-transition-path'), ('normalized-major-peak-only', 'exact-event-over-reference-event-ratio'), ('unconditioned-ionization', 'held-ionization-and-acquisition-condition'), ('selected-diagnostic-peaks', 'complete-peak-isotope-error-absence-custody'), ('refitted-added-fragment', 'successor-retains-and-appends-complete-fragments'))
SURVIVOR='held-molecular-parent-and-ion-carriers__held-isotope-and-charge-composition__exact-positive-mass-charge-ratio__held-parent-fragment-transition-path__exact-event-over-reference-event-ratio__held-ionization-and-acquisition-condition__complete-peak-isotope-error-absence-custody__successor-retains-and-appends-complete-fragments'
DIMENSION_KEYS=('carrier', 'composition', 'coordinate', 'fragmentation', 'response', 'condition', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
