from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-STEP-GROWTH-POLYMERIZATION-NETWORK-006';DOMAINS=(('mean-chain-only', 'complete-molecule-and-reactive-group-population'), ('conversion-without-bond', 'one-explicit-intermolecular-bond-transition'), ('component-count-untracked', 'each-bond-merges-two-components'), ('reactive-groups-erased', 'every-reactive-group-identity-retained'), ('selected-chain-products', 'all-connected-component-products'), ('cycle-bond-counts-as-merge', 'cycle-and-intermolecular-bonds-distinguished'), ('imported-conversion-equation', 'exact-initial-minus-merge-count'), ('degree-only-output', 'groups-bonds-components-products-and-boundary-trace'));SURVIVOR='complete-molecule-and-reactive-group-population__one-explicit-intermolecular-bond-transition__each-bond-merges-two-components__every-reactive-group-identity-retained__all-connected-component-products__cycle-and-intermolecular-bonds-distinguished__exact-initial-minus-merge-count__groups-bonds-components-products-and-boundary-trace'
def remaining(initial,bonds):return initial-bonds if initial>bonds else None
r=remaining(5,3)
native={"population":5>0,"reaction":3>0,"components":r==2,"groups":6==2*3,"products":r>0,"cycles":remaining(5,4)==1,"arithmetic":r==2,"certificate":r+3==5}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
