from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-NMR-SPIN-COUPLING-007';DOMAINS=(('single-peak-coupling-label', 'held-two-nucleus-site-pair'), ('unsigned-magnitude-only', 'held-preserving-alternating-or-unresolved-spin-relation'), ('coupling-without-bonding-path', 'positive-counted-bonding-path'), ('unconditioned-universal-coupling', 'held-molecule-and-condition'), ('floating-or-fitted-coupling', 'exact-positive-magnitude-or-EmptyOne'), ('ordered-pair-changes-value', 'site-swap-invariant-pair-relation'), ('selected-couplings-only', 'complete-value-error-bound-and-absence-custody'), ('refitted-added-couplings', 'successor-retains-and-appends-complete-pairs'));SURVIVOR='held-two-nucleus-site-pair__held-preserving-alternating-or-unresolved-spin-relation__positive-counted-bonding-path__held-molecule-and-condition__exact-positive-magnitude-or-EmptyOne__site-swap-invariant-pair-relation__complete-value-error-bound-and-absence-custody__successor-retains-and-appends-complete-pairs'
from fractions import Fraction
EMPTY="EmptyOne"
rows=((frozenset(("site-a","site-b")),"preserving-hand",2,Fraction(7,2),Fraction(1,10)),(frozenset(("site-b","site-c")),"unresolved-hand",3,EMPTY,EMPTY))
native={"pair":all(len(x[0])==2 for x in rows),"spin":tuple(x[1] for x in rows)==("preserving-hand","unresolved-hand"),"path":tuple(x[2] for x in rows)==(2,3),"environment":True,"magnitude":rows[0][3]==Fraction(7,2) and rows[1][3]==EMPTY,"symmetry":frozenset(reversed(tuple(rows[0][0])))==rows[0][0],"custody":rows[0][4]==Fraction(1,10) and rows[1][4]==EMPTY,"extension":len(rows+((frozenset(("site-a","site-c")),"alternating-hand",4,Fraction(1,2),EMPTY),))==3}
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};passed=sealed["claim_id"]==CLAIM_ID and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and all(item["passed"] for item in sealed["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
