#!/usr/bin/env python3
"""Submit the terminal particle-mode and generation-transport law."""

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sft.engine import EngineRepository  # noqa: E402
from sft.physics.particle_mode_generation_terminal_law_v1 import CLAIM_ID, SPEC  # noqa: E402


def write(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine():
    result = subprocess.run((sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"), cwd=ROOT, text=True, capture_output=True)
    if result.returncode or json.loads(result.stdout).get("status") != "VALID_CANONICAL_ENGINE":
        raise SystemExit(result.stdout + result.stderr + "\nparticle-mode admission halted")


def execution():
    path = ROOT / "claims" / CLAIM_ID / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_particle_mode_generation", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load particle-mode execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def registration():
    return {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": SPEC.grammar_boundary,
            "completeness_certificate": "generated by the admission engine from the complete declared product",
            "generator": SPEC.generation_rule,
        },
        "claim_id": CLAIM_ID,
        "dependencies": list(SPEC.dependencies),
        "excluded_inputs": list(SPEC.exclusions),
        "intended_certificate": "Complete 1,024-form law census, general m-fibre and fixed-mode induction, four generation-coordinate systems, 27-state cover, finite particle-mode injection, terminal mass transport, dual/reach/transition witnesses and hostile controls.",
        "provenance_classes": [item.value for item in SPEC.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-25",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": SPEC.exact_result,
        "status": "independently_replicated_formal_external_empirical_comparison_separate",
        "title": SPEC.title,
    }


def main():
    verify_engine()
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    existing = {row["claim_id"]: row for row in census["claims"]}
    if CLAIM_ID in existing:
        print(f"retained admitted {CLAIM_ID}: {existing[CLAIM_ID]['receipt_hash']}")
    else:
        claim_execution = execution()
        receipt = EngineRepository(ROOT).execute_official(claim_execution.program, claim_execution.independent_validator, claim_execution.source_files)
        print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")
    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append({"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"})
        write(manifest_path, manifest)
    materialized = subprocess.run((sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), CLAIM_ID, SPEC.exact_result), cwd=ROOT, text=True, capture_output=True)
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)
    package = ROOT / "claims" / CLAIM_ID
    write(package / "registration.json", registration())
    row = next(item for item in json.loads(census_path.read_text(encoding="utf-8"))["claims"] if item["claim_id"] == CLAIM_ID)
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}",
        "",
        "Status: `independently_replicated_formal_external_empirical_comparison_separate`",
        "",
        "- Every positive finite m-Fold has exactly m positive preimages and m-2 interior fixed modes.",
        "- Four complete generation coordinate systems carry one ordered three-label set and are not masses.",
        "- The 27-cell state volume forces binary depth five and colour depth three.",
        "- Every finite recurrent particle class injects into internal Fold modes without extra spatial dimensions.",
        "- Terminal lepton, quark and neutrino polynomial carriers replace superseded site-as-mass readings.",
        "- Dual seeds, subtraction reach and structural transition multiplicity close exactly.",
        "- External mass, mixing, generation-count and lifetime comparisons remain a separate sealed successor.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Engine receipt: `{row['receipt_hash']}`",
        "",
    )), encoding="utf-8")
    verify_engine()
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
