#!/usr/bin/env python3
"""Admit the joined gravitational-wave sequence through the frozen engine."""

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine() -> None:
    result = subprocess.run(
        (sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"),
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if result.returncode:
        raise SystemExit(result.stdout + result.stderr + "\nchirp/ringdown admission halted")
    payload = json.loads(result.stdout)
    if payload.get("status") != "VALID_CANONICAL_ENGINE":
        raise SystemExit(result.stdout + "\nchirp/ringdown admission halted")


def load_execution(claim_id: str):
    path = ROOT / "claims" / claim_id / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_gravitational_wave_chirp_ringdown_073", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load gravitational-wave sequence execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def main() -> None:
    verify_engine()
    from sft.engine import EngineRepository
    from sft.physics.gravitational_wave_chirp_ringdown_terminal_law_v1 import CLAIM_ID, SPEC

    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    existing = {row["claim_id"]: row for row in census["claims"]}
    missing = [claim_id for claim_id in SPEC.dependencies if claim_id not in existing]
    if missing:
        raise SystemExit("gravitational-wave sequence dependencies are not admitted: " + ", ".join(missing))
    if CLAIM_ID in existing:
        print(f"retained admitted {CLAIM_ID}: {existing[CLAIM_ID]['receipt_hash']}")
    else:
        execution = load_execution(CLAIM_ID)
        receipt = EngineRepository(ROOT).execute_official(
            execution.program,
            execution.independent_validator,
            execution.source_files,
        )
        print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")

    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append({
            "claim_id": CLAIM_ID,
            "execution_file": f"claims/{CLAIM_ID}/execution.py",
        })
        write_json(manifest_path, manifest)

    materialized = subprocess.run(
        (sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), CLAIM_ID, SPEC.exact_result),
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)

    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": SPEC.grammar_boundary,
            "completeness_certificate": "generated by the untouched admission engine from the complete declared product",
            "generator": SPEC.generation_rule,
        },
        "claim_id": CLAIM_ID,
        "dependencies": list(SPEC.dependencies),
        "excluded_inputs": list(SPEC.exclusions),
        "intended_certificate": "Complete 4096-form census; depth-independent exact chirp ordering, first-contact two-to-one merger and positive finite half-One ringdown.",
        "provenance_classes": [item.value for item in SPEC.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-26",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": SPEC.exact_result,
        "status": "independently_replicated_formal_empirical_comparison_separate",
        "title": SPEC.title,
    })

    row = next(
        item for item in json.loads(census_path.read_text(encoding="utf-8"))["claims"]
        if item["claim_id"] == CLAIM_ID
    )
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}",
        "",
        "Status: `independently_replicated_formal_empirical_comparison_separate`",
        "",
        "- Positive quadrupole radiation and source conservation force shrinking separation.",
        "- Inverse-square balance forces rising exact squared frequency; the quadrupole cycles twice per orbit.",
        "- First horizon contact joins two sources to one remnant with the ledger retained.",
        "- Held remnant labels fix the tone class and half-One contraction forces damped finite ringdown.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Engine receipt: `{row['receipt_hash']}`",
        "",
    )), encoding="utf-8")
    verify_engine()
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
