#!/usr/bin/env python3
"""Admit one requested Tesla-resonance family member through the frozen engine."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_seals() -> None:
    checks = (
        ("verify_engine_seal.py", "VALID_CANONICAL_ENGINE"),
        ("verify_verification_authority_seal.py", "VALID_CANONICAL_VERIFICATION_AUTHORITY"),
    )
    for tool, expected in checks:
        completed = subprocess.run(
            (sys.executable, str(ROOT / "tools" / tool), "--json"),
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if completed.returncode:
            raise SystemExit(completed.stdout + completed.stderr + "\nTesla-family admission halted")
        if json.loads(completed.stdout).get("status") != expected:
            raise SystemExit(completed.stdout + "\nTesla-family admission halted")


def load_execution(claim_id: str):
    version = "execution_v3.py" if claim_id == "SFT-PHYS-TESLA-RESONANT-TRANSFER-081" else "execution_v2.py"
    path = ROOT / "claims" / claim_id / version
    definition = importlib.util.spec_from_file_location(
        "sft_physics_tesla_resonance_family_submission", path
    )
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load Tesla-resonance execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: admit_physics_tesla_resonance_family_v1.py CLAIM_ID")
    claim_id = sys.argv[1]
    verify_seals()

    from sft.engine import EngineRepository
    from sft.physics.tesla_resonance_family_law_v1 import SPECS
    from sft.physics.tesla_resonant_transfer_law_v2 import SPEC as TRANSFER_SPEC

    if claim_id not in SPECS:
        raise SystemExit(f"unregistered Tesla-resonance claim: {claim_id}")
    spec = TRANSFER_SPEC if claim_id == TRANSFER_SPEC.claim_id else SPECS[claim_id]
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    admitted_ids = {row["claim_id"] for row in census["claims"]}
    missing = tuple(dependency for dependency in spec.dependencies if dependency not in admitted_ids)
    if missing:
        raise SystemExit("Tesla-resonance dependencies are not admitted: " + ", ".join(missing))
    if claim_id in admitted_ids:
        raise SystemExit(f"{claim_id} already has an admitted receipt")

    execution = load_execution(claim_id)
    receipt = EngineRepository(ROOT).execute_official(
        execution.program,
        execution.independent_validator,
        execution.source_files,
    )
    if not receipt.model_admitted:
        raise RuntimeError(f"{claim_id} did not enter the model")

    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    execution_name = "execution_v3.py" if claim_id == TRANSFER_SPEC.claim_id else "execution_v2.py"
    manifest["claims"].append({
        "claim_id": claim_id,
        "execution_file": f"claims/{claim_id}/{execution_name}",
    })
    write_json(manifest_path, manifest)

    materialized = subprocess.run(
        (
            sys.executable,
            str(ROOT / "tools/materialize_claim_evidence_execution_path_v1.py"),
            claim_id,
            f"claims/{claim_id}/{execution_name}",
            spec.exact_result,
        ),
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)

    package = ROOT / "claims" / claim_id
    registration_path = package / "registration.json"
    registration = {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": spec.grammar_boundary,
            "completeness_certificate": "generated by the untouched admission engine from the complete declared product",
            "generator": spec.generation_rule,
        },
        "claim_id": claim_id,
        "dependencies": list(spec.dependencies),
        "excluded_inputs": list(spec.exclusions),
        "intended_certificate": "Complete 256-form depth-independent structural census with exact witnesses.",
        "provenance_classes": [item.value for item in spec.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-28",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": spec.exact_result,
        "status": "independently_replicated",
        "title": spec.title,
    }
    write_json(registration_path, registration)
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    admitted_row = next(
        row
        for row in json.loads(census_path.read_text(encoding="utf-8"))["claims"]
        if row["claim_id"] == claim_id
    )
    (package / "STATUS.md").write_text("\n".join((
        f"# {claim_id}",
        "",
        "Status: `independently_replicated`",
        "",
        f"- {spec.exact_result}",
        "- The V1/V2 corpus supplied the question only; no historical result selected the survivor.",
        "- No measurement value, fitted frequency, continuum wave equation or apparatus efficiency entered the formal derivation.",
        "- Every one of the 256 registered alternatives was enumerated once and exactly one survived.",
        "- All four unfavorable controls passed and an implementation-distinct validator reconstructed the exact witnesses.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Engine receipt: `{admitted_row['receipt_hash']}`",
        "",
    )), encoding="utf-8")
    verify_seals()
    print(f"admitted {claim_id}: {receipt.receipt_hash}")
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
