#!/usr/bin/env python3
"""Submit the collective-radiation response law to the canonical engine."""

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sft.engine import EngineRepository  # noqa: E402
from sft.physics.collective_radiation_response_terminal_law_v1 import CLAIM_ID, SPEC  # noqa: E402


def write_json(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine():
    result = subprocess.run((sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"), cwd=ROOT, text=True, capture_output=True)
    if result.returncode or json.loads(result.stdout).get("status") != "VALID_CANONICAL_ENGINE":
        raise SystemExit(result.stdout + result.stderr + "\ncollective-radiation admission halted")


def load_execution():
    path = ROOT / "claims" / CLAIM_ID / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_collective_radiation_response", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load collective-radiation execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def registration():
    return {
        "$schema": "../../governance/claim.schema.json", "branch": "physics",
        "candidate_grammar": {"boundary": SPEC.grammar_boundary, "completeness_certificate": "generated by the admission engine from the complete declared product", "generator": SPEC.generation_rule},
        "claim_id": CLAIM_ID, "dependencies": list(SPEC.dependencies), "excluded_inputs": list(SPEC.exclusions),
        "intended_certificate": "Complete 256-form census; finite boson-word enumeration; exact radiation, acoustic, laser, plasma and Alfvén identities; implementation-distinct reconstruction; and hostile controls.",
        "provenance_classes": [item.value for item in SPEC.provenance], "registered_by": "Maria Smith", "registration_date": "2026-07-25",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": SPEC.exact_result, "status": "independently_replicated_formal_empirical_comparison_separate", "title": SPEC.title,
    }


def main():
    verify_engine()
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    existing = {row["claim_id"]: row for row in census["claims"]}
    if CLAIM_ID in existing:
        print(f"retained admitted {CLAIM_ID}: {existing[CLAIM_ID]['receipt_hash']}")
    else:
        execution = load_execution()
        receipt = EngineRepository(ROOT).execute_official(execution.program, execution.independent_validator, execution.source_files)
        print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")
    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append({"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"})
        write_json(manifest_path, manifest)
    result = subprocess.run((sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), CLAIM_ID, SPEC.exact_result), cwd=ROOT, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(result.stdout + result.stderr)
    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", registration())
    row = next(item for item in json.loads(census_path.read_text(encoding="utf-8"))["claims"] if item["claim_id"] == CLAIM_ID)
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}", "", "Status: `independently_replicated_formal_empirical_comparison_separate`", "",
        "- Complete finite boson occupation words close ultraviolet support and preserve exact scale covariance.",
        "- Stable three-space forces fourth-power radiation; doubling temperature forces factor 16.",
        "- Acoustic modes are positive-whole harmonics; laser inversion is above 1/2 and threshold is gain=loss.",
        "- Plasma frequency, Debye length and Alfvén speed are closed as exact squared carriers.",
        f"- Closure: `{certificate['closure_scope']}`", f"- Derivation seal: `{certificate['derivation_seal_hash']}`",
        f"- Independent validation: `{certificate['external_validation_hash']}`", f"- Engine receipt: `{row['receipt_hash']}`",
        f"- Receipt path: `{row['receipt_path']}`", "",
    )), encoding="utf-8")
    verify_engine()
    print(result.stdout.strip())


if __name__ == "__main__": main()
