#!/usr/bin/env python3
"""Admit the terminal Physics Grand Lock through the untouched engine."""

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine() -> None:
    result = subprocess.run(
        (sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"),
        cwd=ROOT, text=True, capture_output=True,
    )
    if result.returncode:
        raise SystemExit(result.stdout + result.stderr + "\nGrand Lock admission halted")
    if json.loads(result.stdout).get("status") != "VALID_CANONICAL_ENGINE":
        raise SystemExit(result.stdout + "\nGrand Lock admission halted")


def load_execution(claim_id: str):
    path = ROOT / "claims" / claim_id / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_physics_grand_lock_075", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load Grand Lock execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def main() -> None:
    verify_engine()
    from sft.engine import EngineRepository
    from sft.physics.grand_lock_terminal_law_v1 import CLAIM_ID, SPEC

    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    existing = {row["claim_id"]: row for row in census["claims"]}
    missing = [claim_id for claim_id in SPEC.dependencies if claim_id not in existing]
    if missing:
        raise SystemExit("Grand Lock dependencies are not admitted: " + ", ".join(missing))
    if CLAIM_ID in existing:
        print(f"retained admitted {CLAIM_ID}: {existing[CLAIM_ID]['receipt_hash']}")
    else:
        execution = load_execution(CLAIM_ID)
        receipt = EngineRepository(ROOT).execute_official(
            execution.program,
            execution.independent_validator,
            execution.source_files,
        )
        print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")

    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append({
            "claim_id": CLAIM_ID,
            "execution_file": f"claims/{CLAIM_ID}/execution.py",
        })
        write_json(manifest_path, manifest)

    materialized = subprocess.run(
        (sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), CLAIM_ID, SPEC.exact_result),
        cwd=ROOT, text=True, capture_output=True,
    )
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)

    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": SPEC.grammar_boundary,
            "completeness_certificate": "generated by the untouched admission engine from the complete declared product",
            "generator": SPEC.generation_rule,
        },
        "claim_id": CLAIM_ID,
        "dependencies": list(SPEC.dependencies),
        "excluded_inputs": list(SPEC.exclusions),
        "intended_certificate": "Complete 4096-form branch ownership, root-trace, perturbation and extension-open no-omission census.",
        "provenance_classes": [item.value for item in SPEC.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-26",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": SPEC.exact_result,
        "status": "independently_replicated_current_evidence_closed_extension_open",
        "title": SPEC.title,
    })

    row = next(item for item in json.loads(census_path.read_text(encoding="utf-8"))["claims"] if item["claim_id"] == CLAIM_ID)
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}", "",
        "Status: `independently_replicated_current_evidence_closed_extension_open`", "",
        "- Every pre-lock Physics claim is uniquely owned and immutable-evidence bound.",
        "- The complete dependency dictionary is acyclic and every Physics route reaches the foundational One.",
        "- The current exact headline vector independently cross-locks at generator three.",
        "- The three-to-four adverse census moves every declared generator-dependent value and only those values.",
        "- Every empirical receipt, unfavorable result and scope boundary remains bound.",
        "- Completion is relative to the declared current evidence surface; lawful extensions remain open.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Engine receipt: `{row['receipt_hash']}`", "",
    )), encoding="utf-8")
    verify_engine()
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
