#!/usr/bin/env python3
"""Admit the preregistered recurrence-work successors through frozen V3."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

ORDER = (
    "SFT-PHYS-VACUUM-FOLD-RECURRENCE-WORK-CYCLE-096",
    "SFT-PHYS-VACUUM-RECURRENCE-CYCLE-BOUNDARY-097",
    "SFT-ENG-VACUUM-RECURRENCE-CYCLE-PROTOCOL-003",
)


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_seals() -> None:
    for tool, expected in (
        ("verify_engine_seal.py", "VALID_CANONICAL_ENGINE"),
        ("verify_verification_authority_seal.py", "VALID_CANONICAL_VERIFICATION_AUTHORITY"),
    ):
        run = subprocess.run((sys.executable, str(ROOT / "tools" / tool), "--json"), cwd=ROOT, text=True, capture_output=True)
        payload = json.loads(run.stdout)
        if run.returncode or payload.get("status") != expected:
            raise SystemExit("recurrence-work admission halted: protected seal invalid")


def load_execution(claim_id: str):
    path = ROOT / "claims" / claim_id / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_recurrence_submission_" + claim_id.replace("-", "_"), path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load recurrence-work execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def spec_for(claim_id: str):
    if claim_id.startswith("SFT-PHYS-"):
        from sft.physics.vacuum_recurrence_work_cycle_law_v1 import SPECS
        return SPECS[claim_id], "physics"
    from sft.engineering.vacuum_recurrence_cycle_protocol_v1 import SPEC
    return SPEC, "engineering_translation"


def final_registration(spec, branch: str) -> dict[str, object]:
    preregistration = json.loads((ROOT / "claims" / spec.claim_id / "preregistration.json").read_text(encoding="utf-8"))
    return {
        **preregistration,
        "branch": branch,
        "candidate_grammar": {
            "boundary": spec.grammar_boundary,
            "completeness_certificate": "generated by the untouched admission engine from the complete declared product",
            "generator": spec.generation_rule,
        },
        "dependencies": list(spec.dependencies),
        "excluded_inputs": list(spec.exclusions),
        "statement": spec.exact_result,
        "status": "independently_replicated",
    }


def main() -> None:
    verify_seals()
    from sft.engine import EngineRepository

    census_path = ROOT / "census/claims.json"
    manifest_path = ROOT / "census/execution_manifest.json"
    admitted = {row["claim_id"] for row in json.loads(census_path.read_text(encoding="utf-8"))["claims"]}
    for index, claim_id in enumerate(ORDER, 1):
        if claim_id in admitted:
            raise SystemExit("already admitted: " + claim_id)
        spec, branch = spec_for(claim_id)
        preregistration = json.loads((ROOT / "claims" / claim_id / "preregistration.json").read_text(encoding="utf-8"))
        if preregistration.get("status") != "registered" or preregistration.get("claim_id") != claim_id:
            raise SystemExit("frozen preregistration missing or changed: " + claim_id)
        missing = tuple(dependency for dependency in spec.dependencies if dependency not in admitted)
        if missing:
            raise SystemExit(f"missing dependencies for {claim_id}: {missing}")
        execution = load_execution(claim_id)
        receipt = EngineRepository(ROOT).execute_official(execution.program, execution.independent_validator, execution.source_files)
        if not receipt.model_admitted:
            raise SystemExit("untouched engine halted: " + claim_id)

        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["claims"].append({"claim_id": claim_id, "execution_file": f"claims/{claim_id}/execution.py"})
        write_json(manifest_path, manifest)
        materialized = subprocess.run(
            (sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), claim_id, spec.exact_result),
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if materialized.returncode:
            raise RuntimeError(materialized.stdout + materialized.stderr)
        package = ROOT / "claims" / claim_id
        write_json(package / "registration.json", final_registration(spec, branch))
        (package / "STATUS.md").write_text(
            "\n".join((
                f"# {claim_id}",
                "",
                "Status: `independently_replicated`",
                "",
                f"- {spec.exact_result}",
                "- The candidate grammar and independent validator were frozen before engine execution.",
                "- V2 supplied the reconstruction target only and selected no candidate.",
                "- The prior direct-repayment receipt remains immutable and valid inside its declared grammar.",
                "- No physical apparatus outcome or useful dimensional power is claimed without a source-custodied run.",
                "- Every one of 256 forms was enumerated once; one survived; all four mandatory controls passed.",
                f"- Engine receipt: `{receipt.receipt_hash}`",
                "",
            )),
            encoding="utf-8",
        )
        verify_seals()
        admitted.add(claim_id)
        print(f"[{index}/{len(ORDER)}] admitted {claim_id}: {receipt.receipt_hash}", flush=True)


if __name__ == "__main__":
    main()
