#!/usr/bin/env python3
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0, str(ROOT))

from sft.engine import EngineRepository  # noqa: E402
from sft.engine.canonical import sha256_identity  # noqa: E402
from sft.physics.collective_radiation_empirical_v1 import CLAIM_ID, EXPERIMENT_ID, SOURCE_FILES, SOURCE_HASH, SOURCE_IDS, SOURCE_PATH, SPEC  # noqa: E402
from sft.physics.collective_radiation_validation_v1 import TARGET_IDS  # noqa: E402
from sft.physics.generated_empirical_law import prediction_program_document  # noqa: E402

def write_json(path, payload): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
def verify_engine():
    r = subprocess.run((sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"), cwd=ROOT, text=True, capture_output=True)
    if r.returncode or json.loads(r.stdout).get("status") != "VALID_CANONICAL_ENGINE": raise SystemExit(r.stdout + r.stderr + "\ncollective empirical admission halted")
def load_execution():
    path = ROOT / "claims" / CLAIM_ID / "execution.py"; d = importlib.util.spec_from_file_location("sft_collective_empirical", path)
    if d is None or d.loader is None: raise RuntimeError("cannot load execution")
    m = importlib.util.module_from_spec(d); d.loader.exec_module(m); return m.build_execution(ROOT)
def experiment_registration():
    record = json.loads((ROOT / SOURCE_PATH).read_text(encoding="utf-8")); program = prediction_program_document(SPEC)
    return {"$schema": "../../../governance/experiment.schema.json", "experiment_id": EXPERIMENT_ID, "claim_id": CLAIM_ID, "evidence_mode": "observational-data-informed_target-inaccessible_sealed-comparison", "development_observations": [record["historical_boundary"], "Formal Claim 041 preceded all bound snapshots.", "Normalized relations remain distinct from absolute dimensional coefficients."], "external_measurement_sources": [{"source_id": s["source_id"], "measurement_body": s["title"], "source_uri": s["url"], "snapshot_hash": s["snapshot_hash"], "source_pages": [s.get("source_page", 1)], "custody_role": s["role"]} for s in record["sources"]], "frozen_relation": {"statement": SPEC.exact_result, "relation_hash": sha256_identity(SPEC.exact_result), "dependency_hashes": [sha256_identity(x) for x in SPEC.dependencies], "candidate_grammar": SPEC.generation_rule, "exact_domain": SPEC.grammar_boundary, "target_did_not_select_law": True}, "withheld_targets": [{"target_id": x, "source_ids": list(SOURCE_IDS), "content_withheld_from_prediction": True} for x in TARGET_IDS], "prediction_protocol": {"interpreter_id": "sft-v3-capability-closed-fold-interpreter/1", "program_id": program["program_id"], "program_hash": sha256_identity(program), "forbidden_capabilities": ["clock", "dynamic_import", "environment", "filesystem_read", "filesystem_write", "foreign_function", "network", "subprocess"]}, "evaluation_protocol": {"evaluator_id": EXPERIMENT_ID + "-post-seal-evaluator", "comparison_implementation_hash": sha256_identity(("exact-collective-radiation-comparator/1", SPEC.falsification_condition)), "acceptance_condition": "All five typed relation/value records and the adverse exponent control pass.", "falsification_condition": SPEC.falsification_condition}, "controls": [{"control_id": k.upper(), "kind": k, "expected_rejection": "Any premise, source, artifact, boundary or unfavorable target violation halts."} for k in ("false_premise", "tampered_source", "tampered_artifact", "boundary", "unfavorable_measurement")], "custody_protocol": {"exchange_id": "sft-v3-portable-target-exchange/1", "custodian_distinct_from_executor": True, "target_commitment_hash": sha256_identity((SOURCE_HASH, SOURCE_FILES, TARGET_IDS)), "release_requires_matching_seal": True}, "target_access_policy": "structurally-denied-before-seal", "row_retention_policy": "retain all five sources and every numeric, qualitative and limitation row", "source_hashes": {SOURCE_PATH: SOURCE_HASH, **dict(SOURCE_FILES)}, "registration_date": "2026-07-25", "registered_by": "Maria Smith", "status": "registered"}
def claim_registration():
    return {"$schema": "../../governance/claim.schema.json", "branch": "physics", "candidate_grammar": {"boundary": SPEC.grammar_boundary, "completeness_certificate": "generated by the admission engine from the complete declared product", "generator": SPEC.generation_rule}, "claim_id": CLAIM_ID, "dependencies": list(SPEC.dependencies), "excluded_inputs": list(SPEC.exclusions), "empirical_protocol": f"experiments/physics/{EXPERIMENT_ID}/registration.json", "intended_certificate": "Complete 256-form census, independent reconstruction, capability-closed custody and exact typed evaluation of all five source families.", "provenance_classes": ["observational_derivation"], "registered_by": "Maria Smith", "registration_date": "2026-07-25", "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary", "unfavorable_measurement"], "statement": SPEC.exact_result, "status": "empirically_tested_and_independently_replicated", "title": SPEC.title}
def main():
    verify_engine(); exp = ROOT / "experiments/physics" / EXPERIMENT_ID / "registration.json"; write_json(exp, experiment_registration())
    census_path = ROOT / "census/claims.json"; census = json.loads(census_path.read_text(encoding="utf-8")); existing = {x["claim_id"]: x for x in census["claims"]}
    if CLAIM_ID in existing: print(f"retained admitted {CLAIM_ID}: {existing[CLAIM_ID]['receipt_hash']}")
    else:
        e = load_execution(); receipt = EngineRepository(ROOT).execute_official(e.program, e.independent_validator, e.source_files, e.empirical_validator); print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")
    manifest_path = ROOT / "census/execution_manifest.json"; manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {x["claim_id"] for x in manifest["claims"]}: manifest["claims"].append({"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"}); write_json(manifest_path, manifest)
    r = subprocess.run((sys.executable, str(ROOT / "tools/materialize_empirical_claim_evidence.py"), CLAIM_ID, SPEC.exact_result), cwd=ROOT, text=True, capture_output=True)
    if r.returncode: raise RuntimeError(r.stdout + r.stderr)
    package = ROOT / "claims" / CLAIM_ID; write_json(package / "registration.json", claim_registration()); er = json.loads(exp.read_text(encoding="utf-8")); er["status"] = "measured"; write_json(exp, er)
    row = next(x for x in json.loads(census_path.read_text(encoding="utf-8"))["claims"] if x["claim_id"] == CLAIM_ID); cert = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((f"# {CLAIM_ID}", "", "Status: `empirically_tested_and_independently_replicated`", "", "- Measured blackbody exponent 4 matches and forces the exact doubling ratio 16.", "- Historical coefficient agreement is within 1/100; spectrum-shape agreement is retained.", "- NIST/NBS acoustic and laser records retain positive finite resonances and at least twenty-fold linewidth narrowing.", "- NASA plasma-frequency density tracking and the 2007-2014 Alfvén observation interval pass.", "- No normalized relation is relabelled as an absolute dimensional coefficient.", f"- Closure: `{cert['closure_scope']}`", f"- Post-seal empirical validation: `{cert['empirical_validation_hash']}`", f"- Engine receipt: `{row['receipt_hash']}`", "")), encoding="utf-8")
    verify_engine(); print(r.stdout.strip())

if __name__ == "__main__": main()
