#!/usr/bin/env python3
"""Admit the complete Tesla-family observational successor through the frozen engine."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_seals() -> None:
    for tool, expected in (
        ("verify_engine_seal.py", "VALID_CANONICAL_ENGINE"),
        ("verify_verification_authority_seal.py", "VALID_CANONICAL_VERIFICATION_AUTHORITY"),
    ):
        completed = subprocess.run(
            (sys.executable, str(ROOT / "tools" / tool), "--json"),
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if completed.returncode or json.loads(completed.stdout).get("status") != expected:
            raise SystemExit(completed.stdout + completed.stderr + "\nTesla empirical admission halted")


def load_execution():
    path = ROOT / "claims/SFT-PHYS-VALIDATION-TESLA-RESONANCE-FAMILY-082/execution.py"
    definition = importlib.util.spec_from_file_location("sft_tesla_family_empirical_submission", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load Tesla-family empirical execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def experiment_registration(spec, source_files, source_hash, preregistration_hash):
    return {
        "$schema": "../../../governance/experiment.schema.json",
        "experiment_id": spec.experiment_id,
        "claim_id": spec.claim_id,
        "evidence_mode": "observational_derivation_post_formal_seal",
        "historical_access_disclosed": True,
        "blind_numerical_prediction_claimed": False,
        "formal_predecessors_sealed_before_combined_source_record": list(spec.dependencies[:4]),
        "source_identity_preregistration_hash": preregistration_hash,
        "source_record_path": spec.source_snapshot_path,
        "source_record_hash": source_hash,
        "source_hashes": dict(source_files),
        "target_ids": [row.target_id for row in spec.target_rows],
        "complete_row_policy": "retain all five sources and every favorable, adverse, absent, limitation and delivery-type row",
        "formal_relation": spec.exact_result,
        "falsification_condition": spec.falsification_condition,
        "controls": [
            {"kind": kind, "expected": "halt or reject on any changed source, omitted row, altered formal predecessor or unsupported power inference"}
            for kind in ("false_premise", "tampered_source", "tampered_artifact", "boundary", "unfavorable_measurement")
        ],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-28",
        "status": "registered",
    }


def claim_registration(spec):
    return {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": spec.grammar_boundary,
            "completeness_certificate": "generated by the untouched admission engine from the complete declared product",
            "generator": spec.generation_rule,
        },
        "claim_id": spec.claim_id,
        "dependencies": list(spec.dependencies),
        "excluded_inputs": list(spec.exclusions),
        "empirical_protocol": f"experiments/physics/{spec.experiment_id}/registration.json",
        "intended_certificate": "Complete 256-form comparison census, implementation-distinct reconstruction, five direct source checks, custody evidence and all adverse-boundary retention.",
        "provenance_classes": ["observational_derivation"],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-28",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary", "unfavorable_measurement"],
        "statement": spec.exact_result,
        "status": "empirically_tested_and_independently_replicated",
        "title": spec.title,
    }


def main() -> None:
    verify_seals()
    from sft.engine import EngineRepository
    from sft.engine.source import hash_file
    from sft.physics.tesla_resonance_family_empirical_v1 import (
        CLAIM_ID,
        PREREGISTRATION_HASH,
        PREREGISTRATION_PATH,
        SOURCE_FILES,
        SOURCE_HASH,
        SOURCE_PATH,
        SPEC,
    )
    from sft.physics.tesla_resonance_family_empirical_validation_v1 import TeslaResonanceFamilyMeasurementValidator

    if hash_file(ROOT / SOURCE_PATH) != SOURCE_HASH:
        raise SystemExit("Tesla-family source record hash mismatch")
    if hash_file(ROOT / PREREGISTRATION_PATH) != PREREGISTRATION_HASH:
        raise SystemExit("Tesla-family source preregistration hash mismatch")
    for path, expected in SOURCE_FILES:
        if hash_file(ROOT / path) != expected:
            raise SystemExit(f"Tesla-family source hash mismatch: {path}")
    direct = TeslaResonanceFamilyMeasurementValidator(ROOT).direct_source_certificate()
    if not direct["all_passed"] or not direct["unsupported_power_inference_rejected"]:
        raise SystemExit("Tesla-family direct source reconstruction failed")

    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    admitted = {row["claim_id"] for row in census["claims"]}
    missing = tuple(dependency for dependency in SPEC.dependencies if dependency not in admitted)
    if missing:
        raise SystemExit("Tesla-family empirical dependencies absent: " + ", ".join(missing))
    if CLAIM_ID in admitted:
        raise SystemExit(f"{CLAIM_ID} already has an admitted receipt")

    experiment_path = ROOT / "experiments" / "physics" / SPEC.experiment_id / "registration.json"
    write_json(experiment_path, experiment_registration(SPEC, SOURCE_FILES, SOURCE_HASH, PREREGISTRATION_HASH))
    execution = load_execution()
    receipt = EngineRepository(ROOT).execute_official(
        execution.program,
        execution.independent_validator,
        execution.source_files,
        execution.empirical_validator,
    )
    if not receipt.model_admitted:
        raise RuntimeError("Tesla-family empirical successor did not enter the model")

    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["claims"].append({"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"})
    write_json(manifest_path, manifest)
    materialized = subprocess.run(
        (sys.executable, str(ROOT / "tools/materialize_empirical_claim_evidence.py"), CLAIM_ID, SPEC.exact_result),
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)

    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", claim_registration(SPEC))
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}",
        "",
        "Status: `empirically_tested_and_independently_replicated`",
        "",
        "- Four formal resonance laws were sealed before the complete five-source record was assembled.",
        "- NBS measured quarter-wave third and other odd-harmonic response.",
        "- NIST evaluated one longitudinal plus two transverse modes and their distinct velocities.",
        "- NIST measured resonant state transfer, cavity storage and endpoint retrieval with decay and fidelity limits retained.",
        "- NASA measured the Earth-ionosphere cavity mode family; its non-odd sequence is retained as a scope control.",
        "- Proposed wireless/free-energy applications are not relabelled as measured source-free power extraction.",
        "- The legacy NASA PDF locator's HTML delivery mismatch is retained.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Empirical validation: `{certificate['empirical_validation_hash']}`",
        f"- Engine receipt: `{receipt.receipt_hash}`",
        "",
    )), encoding="utf-8")
    verify_seals()
    print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
