#!/usr/bin/env python3
"""Admit one formal vacuum/inertia-drive family member through the frozen engine."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_seals() -> None:
    for tool, expected in (
        ("verify_engine_seal.py", "VALID_CANONICAL_ENGINE"),
        ("verify_verification_authority_seal.py", "VALID_CANONICAL_VERIFICATION_AUTHORITY"),
    ):
        completed = subprocess.run((sys.executable, str(ROOT / "tools" / tool), "--json"), cwd=ROOT, text=True, capture_output=True)
        if completed.returncode or json.loads(completed.stdout).get("status") != expected:
            raise SystemExit(completed.stdout + completed.stderr + "\nVacuum/inertia admission halted")


def load_execution(claim_id: str):
    path = ROOT / "claims" / claim_id / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_vacuum_inertia_drive_submission", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load vacuum/inertia execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: admit_physics_vacuum_inertia_drive_family_v1.py CLAIM_ID")
    claim_id = sys.argv[1]
    verify_seals()
    from sft.engine import EngineRepository
    from sft.physics.vacuum_inertia_drive_family_law_v1 import SPECS

    if claim_id not in SPECS:
        raise SystemExit(f"unregistered vacuum/inertia claim: {claim_id}")
    spec = SPECS[claim_id]
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    admitted = {row["claim_id"] for row in census["claims"]}
    missing = tuple(dependency for dependency in spec.dependencies if dependency not in admitted)
    if missing:
        raise SystemExit("Vacuum/inertia dependencies absent: " + ", ".join(missing))
    if claim_id in admitted:
        raise SystemExit(f"{claim_id} already has an admitted receipt")

    execution = load_execution(claim_id)
    receipt = EngineRepository(ROOT).execute_official(execution.program, execution.independent_validator, execution.source_files)
    if not receipt.model_admitted:
        raise RuntimeError(f"{claim_id} did not enter the model")
    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["claims"].append({"claim_id": claim_id, "execution_file": f"claims/{claim_id}/execution.py"})
    write_json(manifest_path, manifest)
    materialized = subprocess.run(
        (sys.executable, str(ROOT / "tools/materialize_claim_evidence.py"), claim_id, spec.exact_result),
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if materialized.returncode:
        raise RuntimeError(materialized.stdout + materialized.stderr)
    package = ROOT / "claims" / claim_id
    write_json(package / "registration.json", {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {"boundary": spec.grammar_boundary, "completeness_certificate": "generated by the untouched admission engine from the complete declared product", "generator": spec.generation_rule},
        "claim_id": claim_id,
        "dependencies": list(spec.dependencies),
        "excluded_inputs": list(spec.exclusions),
        "intended_certificate": "Complete 256-form depth-independent census with exact witnesses and implementation-distinct reconstruction.",
        "provenance_classes": [item.value for item in spec.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-28",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": spec.exact_result,
        "status": "independently_replicated",
        "title": spec.title,
    })
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {claim_id}",
        "",
        "Status: `independently_replicated`",
        "",
        f"- {spec.exact_result}",
        "- V1/V2 supplied the reconstruction question only and selected no candidate.",
        "- No patent equation, device result, field strength, efficiency or measured magnitude entered the formal law.",
        "- Every one of 256 forms was enumerated once; one survived; all controls passed.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Engine receipt: `{receipt.receipt_hash}`",
        "",
    )), encoding="utf-8")
    verify_seals()
    print(f"admitted {claim_id}: {receipt.receipt_hash}")
    print(materialized.stdout.strip())


if __name__ == "__main__":
    main()
