#!/usr/bin/env python3
"""Admit and materialize terminal cosmic component transport."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sft.engine import EngineRepository  # noqa: E402
from sft.engine.canonical import sha256_identity  # noqa: E402
from sft.physics.cosmic_component_transport_terminal_law_v1 import CLAIM_ID, SPEC  # noqa: E402
from sft.physics.cosmic_component_transport_terminal_validation_v1 import (  # noqa: E402
    COMPARISON_SPEC,
    EXPERIMENT_ID,
    SOURCE_HASH,
    SOURCE_PATH,
)
from sft.physics.generated_empirical_law import experiment_registration_record, prediction_program_document  # noqa: E402


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine() -> None:
    completed = subprocess.run(
        (sys.executable, str(ROOT / "tools/verify_engine_seal.py"), "--json"),
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(completed.stdout + completed.stderr)
    if json.loads(completed.stdout)["status"] != "VALID_CANONICAL_ENGINE":
        raise SystemExit("runtime engine seal changed; cosmic transport admission halted")


def load_execution():
    path = ROOT / "claims" / CLAIM_ID / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_cosmic_component_transport", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load cosmic transport execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def claim_registration() -> dict[str, object]:
    return {
        "$schema": "../../governance/claim.schema.json",
        "branch": "physics",
        "candidate_grammar": {
            "boundary": SPEC.grammar_boundary,
            "completeness_certificate": "generated by the admission engine from the complete declared product",
            "generator": SPEC.generation_rule,
        },
        "claim_id": CLAIM_ID,
        "dependencies": list(SPEC.dependencies),
        "empirical_protocol": f"experiments/physics/{EXPERIMENT_ID}/registration.json",
        "excluded_inputs": list(SPEC.exclusions),
        "intended_certificate": (
            "Complete 4,096-form structural census, implementation-distinct reconstruction, all 32 CCH rows, "
            "Planck ratio thresholds, q0 and transition measurements, constant-vacuum interval, adverse DESI "
            "DR2 retention, capability-closed target custody and all engine controls."
        ),
        "provenance_classes": [item.value for item in SPEC.provenance],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-25",
        "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"],
        "statement": SPEC.exact_result,
        "status": "empirically_tested_and_independently_replicated",
        "title": SPEC.title,
    }


def experiment_registration() -> dict[str, object]:
    source = json.loads((ROOT / SOURCE_PATH).read_text(encoding="utf-8"))
    base = experiment_registration_record(COMPARISON_SPEC)
    program = prediction_program_document(COMPARISON_SPEC)
    return {
        "$schema": "../../../governance/experiment.schema.json",
        "experiment_id": EXPERIMENT_ID,
        "claim_id": CLAIM_ID,
        "evidence_mode": "observational-data-informed_target-inaccessible_sealed-comparison",
        "development_observations": [
            "V1/V2 and the external cosmology measurements were known before reconstruction; no historical-blindness claim is made.",
            "The terminal 11/16 and 5/16 shares were independently admitted before this successor law and replace the adverse earlier 2/3 and 1/3 curve.",
        ],
        "external_measurement_sources": [
            {
                "source_id": row["source_id"],
                "measurement_body": row["title"],
                "source_uri": row["source_uri"],
                "snapshot_hash": row["snapshot_hash"],
                "retrieved_date": source["retrieval_date"],
                "custody_role": "withheld_external_target_or_adverse_row",
            }
            for row in source["sources"]
        ],
        "frozen_relation": {
            "statement": SPEC.exact_result,
            "relation_hash": sha256_identity(SPEC.exact_result),
            "dependency_hashes": [sha256_identity(item) for item in SPEC.dependencies],
            "candidate_grammar": SPEC.generation_rule,
            "exact_domain": SPEC.grammar_boundary,
            "target_did_not_select_law": True,
        },
        "inputs": [{"input_id": "registered-premise", "value_kind": "held-sealed-derivation", "content_hash": sha256_identity(SPEC.dependencies)}],
        "withheld_targets": [
            {"target_id": row.target_id, "source_id": row.source_id, "content_withheld_from_prediction": True}
            for row in COMPARISON_SPEC.target_rows
        ],
        "dimension_unit_boundary": {
            "derived_dimension_carriers": ["SFT-PHYS-MEAS-DIMENSION-COMPOSITION-001", "SFT-PHYS-SCALE-COMMON-AXIS-TERMINAL-030"],
            "external_reference_protocol": "The exact dimensionless curve seals before the external H0 interval transports it into H-squared measurement records.",
            "proof_value_policy": "positive-exact-wholes-fractions-typed-empty-and-held-orientation-only",
            "measurement_record_policy": "conventional signs and decimal intervals remain post-seal source-bound records",
        },
        "prediction_protocol": {
            "interpreter_id": "sft-v3-capability-closed-fold-interpreter/1",
            "program_id": program["program_id"],
            "program_hash": sha256_identity(program),
            "executor_id": EXPERIMENT_ID + "-prediction-executor",
            "complete_trace_required": True,
            "forbidden_capabilities": ["clock", "dynamic_import", "environment", "filesystem_read", "filesystem_write", "foreign_function", "network", "subprocess"],
        },
        "evaluation_protocol": {
            "evaluator_id": EXPERIMENT_ID + "-post-seal-evaluator",
            "comparison_implementation_hash": sha256_identity(("exact-positive-squared-cosmic-transport-comparator/1", COMPARISON_SPEC.falsification_condition)),
            "metrics": [
                {"metric_id": "complete-32-row-CCH-vector", "definition": "Exact overlap of squared positive predicted and reported two-uncertainty intervals.", "all_rows": True},
                {"metric_id": "complete-threshold-and-state-vector", "definition": "Equality, onset, q magnitude, tension magnitude and adverse DESI row are all retained.", "all_rows": True},
            ],
            "acceptance_condition": "Every registered row passes its exact boundary and the deliberately changed control fails.",
            "falsification_condition": COMPARISON_SPEC.falsification_condition,
        },
        "controls": [
            {"control_id": "FALSE-PREMISE", "kind": "false_premise", "expected_rejection": "A component law lacking generated support is rejected."},
            {"control_id": "TAMPERED-SOURCE", "kind": "tampered_source", "expected_rejection": "Any changed nested source or source record is rejected."},
            {"control_id": "TAMPERED-ARTIFACT", "kind": "tampered_artifact", "expected_rejection": "A changed curve, census, prediction or trace is rejected."},
            {"control_id": "BOUNDARY", "kind": "boundary", "expected_rejection": "Target access, signed proof scalars, irrational roots or fitted normalization are rejected."},
            {"control_id": "UNFAVORABLE-MEASUREMENT", "kind": "unfavorable_measurement", "expected_rejection": "A failed CCH row or omitted DESI adverse result rejects the comparison."},
        ],
        "custody_protocol": {
            "exchange_id": "sft-v3-portable-target-exchange/1",
            "custodian_id": EXPERIMENT_ID + "-external-target-custodian",
            "custodian_distinct_from_executor": True,
            "target_commitment_hash": sha256_identity((SOURCE_HASH, tuple((row.target_id, row.source_id, row.source_locator) for row in COMPARISON_SPEC.target_rows))),
            "release_requires_matching_seal": True,
        },
        "target_access_policy": "structurally-denied-before-seal",
        "row_retention_policy": "retain-all-favorable-unfavorable-model-extension-and-tampered-rows",
        "stop_condition": "Halt after every registered target and adverse-control row is evaluated once, or immediately on any violation.",
        "source_hashes": {SOURCE_PATH: SOURCE_HASH, "experiment-registration-record": sha256_identity(base)},
        "registration_date": "2026-07-25",
        "registered_by": "Maria Smith",
        "status": "registered",
    }


def main() -> None:
    verify_engine()
    experiment_path = ROOT / "experiments" / "physics" / EXPERIMENT_ID / "registration.json"
    write_json(experiment_path, experiment_registration())
    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", claim_registration())
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    existing = {row["claim_id"]: row for row in census["claims"]}
    if CLAIM_ID in existing:
        row = existing[CLAIM_ID]
        receipt_hash = row["receipt_hash"]
        print(f"retained admitted {CLAIM_ID}: {receipt_hash}")
    else:
        execution = load_execution()
        receipt = EngineRepository(ROOT).execute_official(
            execution.program,
            execution.independent_validator,
            execution.source_files,
            execution.empirical_validator,
        )
        receipt_hash = receipt.receipt_hash
        print(f"admitted {CLAIM_ID}: {receipt_hash}")
    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append({"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"})
        write_json(manifest_path, manifest)
    completed = subprocess.run(
        (sys.executable, str(ROOT / "tools/materialize_empirical_claim_evidence.py"), CLAIM_ID, SPEC.exact_result),
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stdout + completed.stderr)
    experiment = json.loads(experiment_path.read_text(encoding="utf-8"))
    experiment["status"] = "measured"
    write_json(experiment_path, experiment)
    row = next(item for item in json.loads(census_path.read_text(encoding="utf-8"))["claims"] if item["claim_id"] == CLAIM_ID)
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "STATUS.md").write_text("\n".join((
        f"# {CLAIM_ID}", "", "Status: `empirically_tested_and_independently_replicated`", "",
        "- Matter, radiation and vacuum transport are forced as third-power, fourth-power and invariant-One forms.",
        "- Terminal late expansion is `E²(r)=(11+5r³)/16`; the superseded two-thirds curve remains adverse evidence.",
        "- Equality is `r³=11/5`; acceleration onset is `r³=22/5`; present accelerating magnitude is `17/32`.",
        "- All 32 cosmic-chronometer rows pass the exact positive squared two-uncertainty comparison.",
        "- The constant-vacuum interval passes and the DESI DR2 evolving-dark-energy preference remains explicit adverse evidence.",
        f"- Closure: `{certificate['closure_scope']}`",
        f"- Derivation seal: `{certificate['derivation_seal_hash']}`",
        f"- Independent validation: `{certificate['external_validation_hash']}`",
        f"- Post-seal empirical validation: `{certificate['empirical_validation_hash']}`",
        f"- Measurement receipt: `{certificate['measurement_receipt_hash']}`",
        f"- Engine receipt: `{row['receipt_hash']}`",
        f"- Receipt path: `{row['receipt_path']}`", "",
    )), encoding="utf-8")
    verify_engine()
    print(completed.stdout.strip())


if __name__ == "__main__":
    main()
