#!/usr/bin/env python3
import importlib.util,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from sft.engine import EngineRepository  # noqa:E402
from sft.physics.thermal_equilibrium_response_terminal_law_v1 import CLAIM_ID,SPEC  # noqa:E402
def write(path,payload):path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def verify():
 r=subprocess.run((sys.executable,str(ROOT/"tools/verify_engine_seal.py"),"--json"),cwd=ROOT,text=True,capture_output=True)
 if r.returncode or json.loads(r.stdout).get("status")!="VALID_CANONICAL_ENGINE":raise SystemExit(r.stdout+r.stderr+"\nthermal equilibrium admission halted")
def execution():
 p=ROOT/"claims"/CLAIM_ID/"execution.py";d=importlib.util.spec_from_file_location("sft_thermal_equilibrium",p)
 if d is None or d.loader is None:raise RuntimeError("cannot load execution")
 m=importlib.util.module_from_spec(d);d.loader.exec_module(m);return m.build_execution(ROOT)
def registration():return {"$schema":"../../governance/claim.schema.json","branch":"physics","candidate_grammar":{"boundary":SPEC.grammar_boundary,"completeness_certificate":"generated by the admission engine from the complete declared product","generator":SPEC.generation_rule},"claim_id":CLAIM_ID,"dependencies":list(SPEC.dependencies),"excluded_inputs":list(SPEC.exclusions),"intended_certificate":"Complete 256-form census; exact mean/total identity; binomial equilibrium census; fixed-count/fixed-throw multinomial enumeration; fluctuation-response orbit; independent reconstruction and hostile controls.","provenance_classes":[x.value for x in SPEC.provenance],"registered_by":"Maria Smith","registration_date":"2026-07-25","required_controls":["false_premise","tampered_source","tampered_artifact","boundary"],"statement":SPEC.exact_result,"status":"independently_replicated_formal_empirical_comparison_separate","title":SPEC.title}
def main():
 verify();cp=ROOT/"census/claims.json";c=json.loads(cp.read_text(encoding="utf-8"));e={x["claim_id"]:x for x in c["claims"]}
 if CLAIM_ID in e:print(f"retained admitted {CLAIM_ID}: {e[CLAIM_ID]['receipt_hash']}")
 else:
  x=execution();r=EngineRepository(ROOT).execute_official(x.program,x.independent_validator,x.source_files);print(f"admitted {CLAIM_ID}: {r.receipt_hash}")
 mp=ROOT/"census/execution_manifest.json";m=json.loads(mp.read_text(encoding="utf-8"))
 if CLAIM_ID not in {x["claim_id"] for x in m["claims"]}:m["claims"].append({"claim_id":CLAIM_ID,"execution_file":f"claims/{CLAIM_ID}/execution.py"});write(mp,m)
 r=subprocess.run((sys.executable,str(ROOT/"tools/materialize_claim_evidence.py"),CLAIM_ID,SPEC.exact_result),cwd=ROOT,text=True,capture_output=True)
 if r.returncode:raise RuntimeError(r.stdout+r.stderr)
 p=ROOT/"claims"/CLAIM_ID;write(p/"registration.json",registration());row=next(x for x in json.loads(cp.read_text(encoding="utf-8"))["claims"] if x["claim_id"]==CLAIM_ID);cert=json.loads((p/"certificate.json").read_text(encoding="utf-8"))
 (p/"STATUS.md").write_text("\n".join((f"# {CLAIM_ID}","","Status: `independently_replicated_formal_empirical_comparison_separate`","","- Temperature is the exact positive mean; total throw is count times mean.","- Every complete paired binary population uniquely maximizes at half-One.","- The normalized dyadic level ladder is the unique fixed-count/fixed-throw multinomial maximum.","- Fluctuation 3/4 and response 1/4 have equal 1/4 departure from equilibrium 1/2.",f"- Closure: `{cert['closure_scope']}`",f"- Engine receipt: `{row['receipt_hash']}`","")),encoding="utf-8");verify();print(r.stdout.strip())
if __name__=="__main__":main()
