#!/usr/bin/env python3
"""Officially admit and materialize Chemistry THERMO-007 exactly once."""
from __future__ import annotations
from dataclasses import asdict
import importlib.util,json
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from sft.chemistry.free_energy_equivalent_direction_batch_v1 import FREE_ENERGY_EQUIVALENT_DIRECTION_SPEC  # noqa:E402
from sft.chemistry.free_energy_equivalent_direction_validation_v1 import _source_rows,exact_reaction_direction_analysis  # noqa:E402
from sft.engine import EngineRepository  # noqa:E402
def write_json(path,payload):path.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def load_execution():
    path=ROOT/"claims"/FREE_ENERGY_EQUIVALENT_DIRECTION_SPEC.claim_id/"execution.py";definition=importlib.util.spec_from_file_location("sft_chemistry_thermo_007",path)
    if definition is None or definition.loader is None:raise RuntimeError("cannot load THERMO-007 execution package")
    module=importlib.util.module_from_spec(definition);definition.loader.exec_module(module);return module.build_execution(ROOT)
def main():
    spec=FREE_ENERGY_EQUIVALENT_DIRECTION_SPEC;census_path=ROOT/"census/claims.json";existing={r["claim_id"] for r in json.loads(census_path.read_text())["claims"]}
    if spec.claim_id in existing:raise SystemExit("claim already admitted; immutable receipt preserved")
    execution=load_execution();captured={}
    class CaptureIndependent:
        def validate(self,sealed):captured["sealed"]=sealed;result=execution.independent_validator.validate(sealed);captured["external"]=result;return result
    class CaptureEmpirical:
        def validate(self,sealed):result=execution.empirical_validator.validate(sealed);captured["empirical"]=result;return result
    receipt=EngineRepository(ROOT).execute_official(execution.program,CaptureIndependent(),execution.source_files,CaptureEmpirical())
    if not receipt.model_admitted:raise SystemExit(f"claim halted at {receipt.halted_stage}; preserved receipt {receipt.receipt_hash}")
    sealed,external,empirical=captured["sealed"],captured["external"],captured["empirical"];manifest_path=ROOT/"census/execution_manifest.json";manifest=json.loads(manifest_path.read_text())
    if spec.claim_id not in {r["claim_id"] for r in manifest["claims"]}:manifest["claims"].append({"claim_id":spec.claim_id,"execution_file":f"claims/{spec.claim_id}/execution.py"});write_json(manifest_path,manifest)
    census=json.loads(census_path.read_text());census_row=next(r for r in census["claims"] if r["claim_id"]==spec.claim_id);package=ROOT/"claims"/spec.claim_id;rows=_source_rows(ROOT);analysis=exact_reaction_direction_analysis(rows)
    vector=tuple({"target_id":row["target_id"],"temperature_kelvin":str(analysis["temperatures_kelvin"][index]),"reaction_gibbs_external_signed_inscription":str(analysis["reaction_gibbs_signed_external_inscriptions"][index]),"reaction_gibbs_exact_positive_separation_kilojoule_per_mole":str(analysis["reaction_gibbs_exact_positive_separations"][index]),"reaction_log10K_external_signed_inscription":str(analysis["reaction_log10K_signed_external_inscriptions"][index]),"held_direction":analysis["held_direction_vector"][index],"complete_target_payload_hash":row["target_payload_hash"]} for index,row in enumerate(rows))
    payloads={"candidate_census.json":{"claim_id":spec.claim_id,**asdict(sealed.census)},"elimination_receipt.json":{"claim_id":spec.claim_id,"decisions":asdict(sealed)["decisions"],"closure":asdict(sealed.closure)},"controls.json":{"claim_id":spec.claim_id,"controls":asdict(sealed)["controls"]},"empirical_validation.json":{"claim_id":spec.claim_id,**asdict(empirical)},"certificate.json":{"claim_id":spec.claim_id,"chemistry_obligation":"SFT-CHEM-OBL-THERMO-007","status":"model_admitted_observationally_derived_empirically_tested_and_independently_replicated","source_manifest_hash":execution.program.registration.source_hash,"derivation_seal_hash":sealed.seal_hash,"independent_implementation_hash":external.implementation_hash,"independent_certificate_hash":external.certificate_hash,"external_validation_hash":receipt.external_validation_hash,"empirical_validation_hash":receipt.empirical_validation_hash,"measurement_receipt_hash":empirical.measurement_receipt_hash,"engine_receipt_hash":receipt.receipt_hash,"engine_receipt_path":census_row["receipt_path"],"closure_scope":receipt.closure_status,"exact_result":spec.exact_result,"candidate_count":len(sealed.census.candidates),"unique_survivor_count":sum(x.survives for x in sealed.decisions),"direction_law":"strict exact product order over complete positive retained-energy and closed-distinction accounts","equilibrium_law":"equal complete accounts yield held equilibrium and structural EmptyOne separations","incomparability_law":"crossed accounts halt; no fitted scalar trade-off","successor_law":"common exact positive account addition preserves order","complete_external_target_count":64,"complete_species_column_count_each":8,"reverse_direction_row_count":5,"forward_direction_row_count":59,"equilibrium_observation":"single measured direction crossing bracket; 300 K reverse and 350 K forward","complete_reaction_direction_vector":vector,"all_Gibbs_logK_signs_opposed":analysis["all_Gibbs_logK_signs_opposed"],"all_external_rows_preserved":empirical.all_rows_preserved,"external_data_source_ids":list(empirical.data_source_ids),"all_temperature_Gibbs_logK_and_direction_values_released_after_identity_seal":True,"external_signed_inscriptions_not_used_as_SFT_proof_values":True,"external_value_in_derivation_or_prediction":False,"fitted_weight_imported_Gibbs_equation_or_interpolation_used":False,"numerical_zero_used":False,"negative_irrational_imaginary_logarithmic_or_continuum_proof_value_used":False,"observational_development_disclosed":True,"falsification_condition":empirical.falsification_condition}}
    for name,payload in payloads.items():write_json(package/name,payload)
    registration_path=package/"registration.json";registration=json.loads(registration_path.read_text());registration["status"]="empirically_tested";write_json(registration_path,registration);experiment_path=ROOT/"experiments/chemistry"/spec.experiment_id/"registration.json";experiment=json.loads(experiment_path.read_text());experiment["status"]="complete_64_row_two_direction_crossing_vector_opened_postseal";write_json(experiment_path,experiment)
    status=f"# {spec.claim_id}\n\nStatus: `model_admitted_observationally_derived_empirically_tested_and_independently_replicated`\n\n- Chemistry obligation: `SFT-CHEM-OBL-THERMO-007`\n- Closure: `{receipt.closure_status}`\n- Exact law: strict product order over complete retained-energy and distinction accounts; equality is structural equilibrium.\n- Direct NIST-JANAF vector: `64` complete paired rows; `5` reverse and `59` forward.\n- Equilibrium boundary: exact direction crossing bracket `300–350 K`, without interpolation.\n- Derivation seal: `{sealed.seal_hash}`\n- Independent validation: `{receipt.external_validation_hash}`\n- Empirical validation: `{receipt.empirical_validation_hash}`\n- Engine receipt: `{receipt.receipt_hash}`\n";(package/"STATUS.md").write_text(status)
    print(f"admitted {spec.claim_id}: {receipt.receipt_hash}");print(f"derivation seal: {sealed.seal_hash}");print(f"candidates: {len(sealed.census.candidates)}; survivors: {sum(x.survives for x in sealed.decisions)}");print("NIST-JANAF reaction direction: 64 rows; 5 reverse; 59 forward; crossing bracket 300-350 K")
if __name__=="__main__":main()
