#!/usr/bin/env python3
"""Admit and materialize only the SFT scientific-calculator extension."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sft.engine import EngineRepository  # noqa: E402
from sft.mathematics.calculator.law import SPEC  # noqa: E402


ENGINE_TREE = "ad30f4866c18b2adbade95a0b2de40d5caa61308"
CLAIM_ID = SPEC.claim_id


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_engine() -> None:
    actual = subprocess.run(
        ("git", "rev-parse", "HEAD:sft/engine"),
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    dirty = subprocess.run(("git", "diff", "--quiet", "--", "sft/engine"), cwd=ROOT).returncode
    if actual != ENGINE_TREE or dirty != 0:
        raise SystemExit("frozen engine identity changed; calculator admission halted")


def load_execution():
    path = ROOT / "claims" / CLAIM_ID / "execution.py"
    definition = importlib.util.spec_from_file_location("sft_math_calculator_admission", path)
    if definition is None or definition.loader is None:
        raise RuntimeError("cannot load calculator execution")
    module = importlib.util.module_from_spec(definition)
    definition.loader.exec_module(module)
    return module.build_execution(ROOT)


def registration() -> dict[str, object]:
    return {
        "$schema": "../../governance/claim.schema.json",
        "branch": "mathematics",
        "candidate_grammar": {
            "boundary": SPEC.grammar_boundary,
            "completeness_certificate": "generated by the admission engine from the complete declared product",
            "generator": SPEC.generation_rule,
        },
        "claim_id": CLAIM_ID,
        "dependencies": list(SPEC.dependencies),
        "empirical_protocol": None,
        "excluded_inputs": list(SPEC.boundary_exclusions),
        "intended_certificate": (
            "Complete 1,024-form semantic census, exact operational witnesses, four adverse controls, "
            "implementation-distinct regeneration and cross-platform command-line execution."
        ),
        "provenance_classes": ["forward_forcing"],
        "registered_by": "Maria Smith",
        "registration_date": "2026-07-25",
        "required_controls": [
            "false_premise",
            "tampered_source",
            "tampered_artifact",
            "boundary",
        ],
        "statement": SPEC.statement,
        "status": "independently_replicated",
        "title": SPEC.title,
    }


def main() -> None:
    verify_engine()
    execution = load_execution()
    census_path = ROOT / "census/claims.json"
    census = json.loads(census_path.read_text(encoding="utf-8"))
    rows = {row["claim_id"]: row for row in census["claims"]}
    if CLAIM_ID not in rows:
        receipt = EngineRepository(ROOT).execute_official(
            execution.program,
            execution.independent_validator,
            execution.source_files,
            execution.empirical_validator,
        )
        print(f"admitted {CLAIM_ID}: {receipt.receipt_hash}")
    else:
        row = rows[CLAIM_ID]
        retained = json.loads((ROOT / row["receipt_path"]).read_text(encoding="utf-8"))
        print(f"retained admitted {CLAIM_ID}: {retained['receipt_hash']}")

    manifest_path = ROOT / "census/execution_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if CLAIM_ID not in {row["claim_id"] for row in manifest["claims"]}:
        manifest["claims"].append(
            {"claim_id": CLAIM_ID, "execution_file": f"claims/{CLAIM_ID}/execution.py"}
        )
        write_json(manifest_path, manifest)

    completed = subprocess.run(
        (
            sys.executable,
            str(ROOT / "tools/materialize_claim_evidence.py"),
            CLAIM_ID,
            SPEC.exact_result,
        ),
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stdout + completed.stderr)

    package = ROOT / "claims" / CLAIM_ID
    write_json(package / "registration.json", registration())
    census = json.loads(census_path.read_text(encoding="utf-8"))
    row = next(item for item in census["claims"] if item["claim_id"] == CLAIM_ID)
    receipt = json.loads((ROOT / row["receipt_path"]).read_text(encoding="utf-8"))
    certificate = json.loads((package / "certificate.json").read_text(encoding="utf-8"))
    (package / "WHY_DERIVATION_CHECK.md").write_text(
        "# Why this is a derivation check\n\n"
        "The claim does not assume a conventional signed real or complex calculator. It exhausts the declared "
        "representation and execution choices, admits only the sole form preserving every upstream Mathematics "
        "constraint, and separately executes exact arithmetic, enclosure, orthogonal-fibre, trace and halt witnesses.\n\n"
        "## WHY\n\n" + SPEC.why + "\n\n## DERIVATION\n\n" + SPEC.derivation + "\n\n## CHECK\n\n" + SPEC.check + "\n",
        encoding="utf-8",
    )
    (package / "STATUS.md").write_text(
        "\n".join(
            (
                f"# {CLAIM_ID}",
                "",
                "Status: `independently_replicated`",
                "",
                "- Mathematical status: closed for the declared scientific-calculator grammar and resource boundary.",
                "- Empirical status: not applicable to this formal executable theorem.",
                "- Exact values: rational Fold parts, empty-One and held orientation.",
                "- Non-rational values: exact rational enclosures with replayable certificates.",
                "- Orthogonal values: typed two-fibre composition; no imaginary proof scalar.",
                "- Invalid or unclosed operations: mandatory halt.",
                f"- Closure: `{certificate['closure_scope']}`",
                f"- Derivation seal: `{certificate['derivation_seal_hash']}`",
                f"- Independent validation: `{certificate['external_validation_hash']}`",
                f"- Engine receipt: `{receipt['receipt_hash']}`",
                f"- Receipt path: `{row['receipt_path']}`",
                "",
            )
        ),
        encoding="utf-8",
    )
    verify_engine()
    print(completed.stdout.strip())


if __name__ == "__main__":
    main()
