#!/usr/bin/env python3
"""Open and freeze exact NOISE observations after registry freeze."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"census/information_science_noise_001_012_target_registry_v1.json";OUT=ROOT/"experiments/external_sources/information_science/noise_001_012_observation_vector_v1.json"
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
 if OUT.exists():raise SystemExit("NOISE vector already frozen")
 r=json.loads(REGISTRY.read_text());b=dict(r);ri=b.pop("registry_identity")
 if canonical(b)!=ri or r["target_content_present"] is not False:raise SystemExit("NOISE registry changed")
 values=(("distinction_closure",{"source_predecessors":2,"received_images":1,"closed_class_size":2,"all_predecessors_retained":True}),("source_output_mismatch",{"word_positions":3,"changed_positions":[1],"old_new_labels_retained":True,"identity_trace":"empty-One"}),("pattern_support",{"width":3,"budget":1,"mask_count":3,"distinct_images":3}),("composition",{"actions":[[1],[3]],"terminal_changed_positions":[1,3],"intermediate_actions_retained":True}),("detection",{"codewords":2,"one-change_images":6,"all_outside_code":True,"threshold_used":False}),("localization",{"masks":3,"localized_positions":[1,2,3],"all_unique":True}),("estimation",{"received_images_checked":6,"singleton_predecessors":6,"likelihood_prior_used":False}),("erasure_substitution",{"action_types":["erasure","substitution"],"erasure_received":"absent","substitution_received":"opposed label","types_distinct":True}),("burst_correlation",{"width_two_masks":3,"contiguous_bursts":2,"separated_correlated_masks":1}),("adversarial_support",{"width":4,"budget":1,"complete_masks":4,"stochastic_prior_used":False}),("budget_ledger",{"within_budget_masks":4,"over_budget_control":[1,3],"over_budget_rejected":True}),("noise_completeness",{"registered_obligations":12,"observation_rows":12,"duplicate_owners":0,"omitted_owners":0}))
 rows=[{"number":f"{i:03d}","claim_id":r["claim_ids"][i-1],"obligation_id":r["obligation_ids"][i-1],"observation_name":name,"exact_observation":value,"expected_label":f"complete-noise-{i:03d}-observation-retained","source_ids":["SFT-V3-INDEPENDENT-EXACT-DETERMINISTIC-NOISE-OBSERVER","SFT-V1-V2-INFORMATION-OBSERVATION-CORPUS"],"all_rows_preserved":True} for i,(name,value) in enumerate(values,1)]
 p={"schema":"sft-v3-information-science-noise-observation-vector/1","date":"2026-07-29","authority":"Maria Smith","registry_identity":ri,"outcomes_opened_only_after_registry_freeze":True,"records":rows,"record_count":12,"all_rows_preserved":True,"protected_engine_or_verifier_edit_made":False};p["vector_identity"]=canonical(p);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(p,indent=2,sort_keys=True)+"\n");print(json.dumps({"records":12,"identity":p["vector_identity"]},indent=2))
if __name__=="__main__":main()
