#!/usr/bin/env python3
"""Open the final INORG-014--017 outcomes after their value-free identity seals."""
import html,json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from sft.engine.canonical import sha256_identity  # noqa:E402
from sft.engine.source import hash_file  # noqa:E402
IDENTITY_HASHES={"014":"sha256:9fb4f98fd0946c187bb0e02e700d4f18e2df7455a445b2030d7a768f826db287","015":"sha256:722ac10d9508014abddb474ce7db24dba5386a9e41127d2454c6eb87e88feb37","016":"sha256:f2f97dc76295f1007d6cc6868080129839ff0e1b9d5e3f0b757092e0086f3328","017":"sha256:acea6aaf9593095e596338040d0ff44eb83b2f2658a09224da3002c6af53ea85"}
SURFACES={
"multiple-metal-centre-support":(1,"number of metal centres"),"direct-metal-bond-interaction":(1,"direct metal bonding interactions"),"bridging-ligand-interaction":(1,"interactions through a bridging ligand"),"interaction-not-necessary-for-cluster-grouping":(1,"not necessarily held together by these interactions"),"two-or-more-iron-support":(1,"two or more iron atoms"),"bridging-sulfur-ligand-support":(1,"bridging sulfur ligands"),"iron-sulfur-content-designation":(1,"iron and sulfur content"),"two-iron-two-sulfur-example":(1,"[2\\! Fe-2\\! S]"),"three-iron-four-sulfur-example":(1,"[3\\! Fe-4\\! S]"),"external-oxidation-level-charge-inscriptions":(1,"possible oxidation levels"),
"repeating-coordination-entity-support":(1,"repeating coordination entities"),"one-dimensional-crosslinked-network":(1,"one dimension"),"chain-loop-spiro-crosslink-classes":(1,"chains, loops, or spiro-links"),"two-dimensional-extension":(1,"two or three dimensions"),"three-dimensional-extension":(1,"two or three dimensions"),"registered-solid-solution-returned-mixed-crystal":(1,"mixed crystal"),"second-constituent-support":(1,"second constituent"),"constituent-fits-host-lattice":(1,"fits into"),"constituent-distributed-in-host-lattice":(1,"distributed in the lattice of the host crystal"),"amorphous-solid-solution-use-not-recommended":(1,"amorphous materials is not recommended"),"amorphous-use-boundary":(1,"amorphous materials is not recommended"),
"regular-atomic-arrangement-interruption":(1,"Interruption to the regular pattern of atomic arrangement"),"crystallographic-defect-synonym":(1,"crystallographic defect"),"pattern-formation-imperfection":(1,"Imperfection introduced during pattern formation"),"noncrystal-image-defect-scope-mismatch":(1,"image defect"),"extrinsic-chemical-unit-relative-to-formula":(1,"extrinsic chemical units in relation to the chemical formula"),"adsorbed-species-example":(1,"adsorbed species"),"surface-and-near-surface-bulk-role":(1,"bulk defects located in the near-surface region"),"no-extrinsic-chemical-unit-relative-to-formula":(1,"not including extrinsic chemical units in relation to the chemical formula"),"point-linear-square-dimensional-defect-classes":(1,"zero-dimensional"),"vacancy-interstitial-edge-corner-kink-examples":(1,"Surface vacancies"),
"electron-pair-acceptor":(1,"electron-pair acceptor"),"acid-reacts-with-base":(1,"react with a Lewis base"),"shared-base-pair-forms-adduct":(1,"sharing the electron pair furnished by the Lewis base"),"acid-example-introduced-rendered-structure-absent":(1,"For example:"),"electron-pair-provider":(1,"provide a pair of electrons"),"base-coordinates-acid":(1,"coordination to a Lewis acid"),"base-produces-adduct":(1,"producing a Lewis adduct"),"acid-base-adduct-composition":(1,"formed between a Lewis acid and a Lewis base"),"complete-net-electron-removal":(1,"complete, net removal of one or more electrons"),"external-oxidation-number-increase":(1,"increase in the oxidation number"),"oxygen-gain-hydrogen-loss-criterion":(1,"Gain of oxygen and/or loss of hydrogen"),"all-oxidations-meet-first-two-criteria":(1,"All oxidations meet criteria 1 and 2"),"primitive-change-pathway-description":(1,"primitive changes"),"complete-electron-transfer-to-entity":(1,"complete transfer of one or more electrons to a molecular entity"),"reverse-of-oxidation-processes":(1,"reverse of the processes described under oxidation")}
def html_record(raw):
 title=html.unescape(re.search(r"<title>IUPAC - (.*?) \(",raw,re.S).group(1)).strip();block=re.search(r"<div class='deftext'>(.*?)<div class='sources'",raw,re.S).group(1);text=html.unescape(re.sub(r"<[^>]+>","",block));text=re.sub(r"\s+"," ",text).strip();citation=html.unescape(re.search(r"<b>Citation:</b>(.*?)<a ",raw,re.S).group(1));citation=re.sub(r"<[^>]+>","",citation).strip();return {"title":title,"code":"M03940","status":"current-returned-html","definitions":[{"text":text}],"citation":citation,"license":"complete frozen HTML retained"}
def main():
 ext=ROOT/"experiments/external_sources/chemistry";snap=ext/"snapshots/inorg-004-017-family-v1"
 for num,ih in IDENTITY_HASHES.items():
  ip=ext/f"inorg_{num}_target_identities_v1.json"
  if hash_file(ip)!=ih:raise SystemExit(f"INORG-{num} identity changed")
  identity=json.loads(ip.read_text());cache={};rows=[]
  for ident in identity["rows"]:
   path=ROOT/ident["snapshot_path"]
   if hash_file(path)!=ident["snapshot_sha256"]:raise SystemExit(f"source changed: {path}")
   if str(path) not in cache:
    raw=path.read_text();cache[str(path)]=html_record(raw) if raw.lstrip().startswith("<!DOCTYPE") else json.loads(raw)["term"]
   term=cache[str(path)];ordinal,phrase=SURFACES[ident["source_record_role"]];definition=term["definitions"][ordinal-1]["text"];search_space=" ".join((term.get("title",""),term.get("synonym",""),definition));outcome={"source_title":term["title"],"source_code":term["code"],"source_status":term["status"],"definition_ordinal":ordinal,"complete_definition_text":definition,"registered_surface_phrase":phrase,"registered_surface_present":phrase.casefold() in search_space.casefold(),"citation":term.get("citation"),"licence":term.get("license"),"disclaimer":term.get("disclaimer")}
   if ident["source_record_role"]=="acid-example-introduced-rendered-structure-absent":outcome["introduced_example_structure_present_after_colon"]=bool(definition.split("For example:",1)[1].strip())
   row={**ident,"source_outcome":outcome};row["target_payload_hash"]=sha256_identity((ident["target_id"],ident["source_record_role"],outcome));rows.append(row)
  target={"schema":"sft-v3-postseal-complete-target-vector/1","claim_id":identity["claim_id"],"identity_registry":(str(ip.relative_to(ROOT)),ih),"release_requires_prediction_seal":True,"complete_registered_target_count":len(rows),"all_favourable_adverse_absent_scope_and_unresolved_rows_preserved":True,"rows":rows};tp=ext/f"inorg_{num}_withheld_targets_v1.json";tp.write_text(json.dumps(target,indent=2,sort_keys=True,ensure_ascii=False)+"\n")
  a={"complete_target_count":len(rows),"complete_source_count":len({x["source_id"] for x in rows}),"all_registered_surfaces_present":all(x["source_outcome"]["registered_surface_present"] for x in rows),"development_observed_target_count":sum("development-observed" in x["custody_class"] for x in rows),"identity_only_unopened_target_count":sum("identity-only-unopened" in x["custody_class"] for x in rows),"scope_mismatch_or_distinction_count":sum("scope" in x["source_record_role"] or "returned" in x["source_record_role"] for x in rows),"rendered_structure_absence_count":sum(x["source_outcome"].get("introduced_example_structure_present_after_colon") is False for x in rows),"complete_target_vector_hash":sha256_identity(tuple((x["target_id"],x["source_outcome"]) for x in rows)),"source_recapture_count":0,"all_rows_preserved":True};primary={"schema":"sft-v3-postseal-primary-analysis/1","claim_id":identity["claim_id"],"identity_registry":(str(ip.relative_to(ROOT)),ih),"target_registry":(str(tp.relative_to(ROOT)),hash_file(tp)),"exact_postseal_analysis":a};pp=snap/f"inorg-{num}-primary-records-v1.json";pp.write_text(json.dumps(primary,indent=2,sort_keys=True,ensure_ascii=False)+"\n");print(tp.relative_to(ROOT),hash_file(tp));print(pp.relative_to(ROOT),hash_file(pp),a)
if __name__=="__main__":main()
