#!/usr/bin/env python3
"""Build the standalone exhaustive Astronomy/Cosmology foundation paper."""

from __future__ import annotations

from collections import defaultdict
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"publications/current/astronomy_cosmology/FROM_ONE_SKY_TO_COSMOS.md"

def main():
    inv=json.loads((ROOT/"publications/inventories/astronomy_cosmology.json").read_text()); integration=json.loads((ROOT/"audits/astronomy_cosmology_foundation_integration.json").read_text()); targets=json.loads((ROOT/"experiments/astronomy_cosmology/external_targets.json").read_text()); registry=json.loads((ROOT/"experiments/astronomy_cosmology/source_registry.json").read_text()); audit=json.loads((ROOT/"audits/astronomy_cosmology_v1_v2_initial_atomic_ownership.json").read_text()); target_by={x["claim_id"]:x for x in targets["targets"]}; claims={x["claim_id"]:x for x in inv["obligations"]}; family=defaultdict(list)
    for x in inv["obligations"]: family[x["family"]].append(x)
    lines=[
      "# From One Sky to Cosmos", "", "## An Exact, Zero-Parameter and Machine-Closed Foundational Reconstruction of Astronomy and Cosmology from Smithian Fold Theory", "",
      "**Maria Smith — independent researcher and founder, Ernos Labs**  ", "**Smithian Fold Theory Astronomy and Cosmology Paper 001 — Version 1.0.0 — 28 July 2026**  ", "**DOI:** [10.5281/zenodo.21640812](https://doi.org/10.5281/zenodo.21640812)  ", "**Current-evidence closed, extension-open foundation — published open access**", "",
      "> This paper reports a machine-admitted foundational reconstruction of astronomical observation, celestial objects, populations and cosmic history. It does not ask a conventional cosmology to choose the law. Seventy-two explicit obligations were generated before external source selection; their 18,432 candidate forms were exhaustively decided; exactly one preserving form survived in each claim; separate implementations reconstructed every survivor; and post-seal primary archives tested the resulting evidence boundaries. The work remains open to lawful extension and criticism. No branch is permanently locked.", "",
      "## Headline findings", "",
      "1. **A complete foundational astronomy surface is machine admitted.** The branch contains 72 laws in 12 families, 18,432 exhaustively generated candidates, 72 unique survivors, 72 independent reconstructions and 72 untouched-engine receipts.",
      "2. **Astronomical observation is derived as a five-stage exact relation:** source → path → observer → instrument → record. A brightness, coordinate or catalogue label detached from that chain is not an astronomical fact in the admitted model.",
      "3. **Evidence classes cannot be silently exchanged.** Direct detection, archive retrieval, proxy, reconstruction, model, forecast, upper limit, non-detection, missing row and declared absence are structurally distinct. The glyph `0` may mark declared absence in a presentation or source field; it is never imported as the conventional numerical zero of a proof domain.",
      "4. **Object identity and population inference are record laws.** Cross-epoch association, blend alternatives, selection functions, censoring, release versions and uncertainty must remain reconstructible; a favorable detection list is not a population.",
      "5. **Cosmic law and cosmic history are separated.** Physics supplies admitted universal propagation, gravity, matter and constant relations. Astronomy owns source-dated objects, initial conditions, population records and cosmic chronology. Neither instrument nor catalogue may select a universal law.",
      "6. **Rank four was fixed before galaxy data were opened.** The structural luminosity/rotation successor selects exponent 4. The first preregistered all-positive-row unweighted SPARC comparison measured slope **3.486344605219551…** and remains adverse. A separate primary-source method record reports an uncertainty-aware orthogonal slope **3.85 ± 0.09**, with stated systematic movement from **3.5 to 4.0**; exact rank four lies at that reported systematic boundary. The first result was not erased, renamed or reclassified.",
      "7. **Observation cannot recover an unheld predecessor.** Distinct Fold predecessors can share one observed image. A retained record can make a particular experimental history reconstructible; observation alone cannot manufacture the missing distinction.",
      "8. **The multiverse and unobserved-sector boundary is explicit.** A mathematically generated alternative is not promoted to an observed world. Dark matter, dark energy, horizon and multiverse statements retain direct, dynamical, lensing, background, model-dependent and unobserved components separately.",
      f"9. **The historical corpus was not waved through.** All {audit['source_surface']['total_entries_reviewed']} V1/V2 entries were reviewed and {audit['summary']['atomic_question_count']} Astronomy-owned prior questions were mapped to present claims without importing their answers.",
      f"10. **The external record is complete at its declared boundary.** {integration['source_count']} primary sources were registered; {integration['captured_source_count']} transports succeeded and {integration['failed_source_transports_preserved']} failed transports remain visible rather than becoming absence.", "",
      "These are not hashes offered in place of science. The numbers, relations, exclusions and adverse results above are the findings. Hashes later in the paper bind those findings to the exact files and traces that reproduce them.", "",
      "## Abstract", "",
      "Astronomy is often presented as a catalogue of distant things and cosmology as a fit among inherited equations. This reconstruction begins lower. From the One and the Fold, and only through already admitted mathematical, informational, computational, physical, chemical and Earth dependencies, it asks what must be retained for any statement about a source beyond the observer to be distinguishable, reconstructible and falsifiable. The result is a foundational branch spanning source geometry, object identity, radiation, motion, time, stars, planetary systems, interstellar matter, galaxies, compact objects, multimessenger records, expansion, early-universe evidence, dark-sector inference and scientific handoffs. Each law is zero-parameter in its proof layer: no fitted constant, target value, irrational or imaginary proof number, conventional continuum or semantic numerical zero selects a survivor. Dimensional observations remain exact source records outside that proof layer. This paper documents the entire forward chain, the candidate grammars, the controls, the empirical boundary, the adverse result, the independent certificates and the open continuation programme.", "",
      "## Authorship, access and why this work is public", "",
      "Maria Smith produced this work outside credentialed institutional access. That fact is not offered as a claim of personal exception. It is an indictment of how many capable minds science has excluded or silenced when money, credentials, paywalls, prestige and institutional permission are mistaken for rigor. The work must stand or fall on its visible derivations, executable tests, preserved adverse evidence and reproducible certificates—not on the biography of the author and not on the authority of a gatekeeper.", "",
      "Ernos Labs is an open-source science movement and a standards designation. Anyone may inspect, criticize, reproduce, fork and extend the work under the stated licenses. Use of the **Ernos Labs** designation is conditional: the foundational theorem and declared constraints must remain visible; the protected engine and verification authority may not be weakened; candidate spaces and exclusions must be registered before outcomes; every alternative must be decided; failed, adverse, absent and unresolved evidence must be preserved; external evidence may not select a structural survivor; and criticism must remain distinguishable from admission. A proposal may be discussed openly without becoming part of the model. Admission requires the common machine-checkable route.", "",
      "The paper is licensed **CC BY 4.0**. The platform code is licensed **Apache-2.0**. Maria Smith retains authorship, copyright and creative rights. Openness does not erase attribution, and attribution does not convert public science into private permission. Contact: **Maria.Smith.Sftoe@gmail.com**. Submissions and review: **https://discord.gg/ucwGryVxGr**. GitHub: **https://github.com/MettaMazza**.", "",
      "## The non-negotiable mathematical constitution", "",
      "Every claim in this branch enters through one theorem—**There Is No Nothing**—and admitted Fold dependencies. There are no added axioms and no free or fitted parameters. Proof-state arithmetic is exact and finite. Conventional numerical zero is not an element of the proof carrier; where a user interface, catalogue or source writes `0`, it is retained as a typed absence or missingness marker unless the source explicitly proves another meaning. Negative, irrational and imaginary quantities are not admitted as proof scalars. Completed infinities and ungenerated continua do not enter candidate generation. External decimals, signed coordinates and catalogue conventions are held labels in the measurement record; they compare the law but cannot become hidden premises.", "",
      "For every claim, eight binary dimensions are generated literally: carrier, boundary, relation, record, evidence, provenance, generality and extension. This produces 2^8 = 256 finite forms. Exactly one choice on each axis preserves the required distinction. The full Cartesian product is enumerated, every form is decided, and the single all-preserving form is independently reconstructed. Depth-independent closure means that adding one lawful finite source, epoch, channel, object or population member preserves prior identities and adverse rows while appending its own trace. It does not mean that the empirical universe is exhausted or that later observations are forbidden.", "",
      "## End-to-end empirical constitution", "",
      "The complete 72-claim inventory, all 18,432 candidates, all predicted structural labels and all falsification conditions were sealed before external source identities or outcomes were opened. Primary custodians were then registered by purpose. Each target remained inaccessible to the capability-closed prediction process until its derivation seal existed. The evaluator opened the registered source record afterward, compared the result, ran deliberately changed controls, and preserved every transport failure and unfavorable row. The sealed engine rejected any missing dependency, incomplete census, non-unique survivor, failed control, changed source, failed independent reconstruction or empirical boundary violation.", "",
      "The immutable engine seal is `sha256:4f4cdd7986808e6a6102d650c85e6093d6425e49f14a5f05d70fa05e6031d46a`. The verification-authority seal is `sha256:bf810a190b504f0f874a778a52e23251904b17b40a7364135e74b34e8ba0c3b8`. They identify the unchanged common admission route; they are not substitutes for the derivations below.", "",
      "## Dependency and ownership boundary", "",
      "The dependency chain is: foundational theorem → exact mathematics → information and computation → universal Physics → chemical identity and conservation → Earth observation handoff → Astronomy observation and history. Physics retains propagation, gravity, matter and constants. Chemistry retains species identity and transformation. Earth retains Earth-specific conditions. Engineering retains instrument implementation. Astronomy retains source identity, source-observer geometry, celestial populations, cosmic chronology and the custody of observational evidence. This division prevents double counting and prevents a telescope, simulation or catalogue from becoming a law generator.", "",
      "## Primary source register", "",
    ]
    for s in registry["sources"]: lines.append(f"- **{s['source_id']} — {s['custodian']}.** {s['title']}. Registered purpose: {', '.join(s['families'])}. Locator: {s['locator']}.")
    lines += ["", "## Family results", ""]
    family_titles={
      "observation_geometry":"Source, observer, signal and geometry", "object_identity_classification":"Object identity, classification and catalogues", "radiation_motion_time":"Radiation, motion and time", "stellar_systems":"Stellar systems", "planetary_small_body":"Planetary systems and small bodies", "interstellar_enrichment_formation":"Interstellar matter, enrichment and formation", "galaxies_populations":"Galaxies and populations", "compact_high_energy_multimessenger":"Compact, high-energy and multimessenger astronomy", "large_scale_expansion":"Large-scale structure and expansion", "early_background_abundance":"Early universe, background and abundance", "dark_horizon_unobserved":"Dark sectors, horizons and unobserved claims", "inference_prediction_handoffs":"Inference, prediction and disciplinary handoffs"}
    for fam in inv["family_order"]:
        lines += [f"### {family_titles[fam]}", "", f"This family closes {len(family[fam])} nonduplicate foundational obligations. Each is current-evidence closed at its registered boundary and remains open to lawful extension.", ""]
        for x in family[fam]: lines.append(f"- **{x['title']}** (`{x['claim_id']}`): {x['statement']}")
        lines.append("")
    lines += ["## Complete claim-by-claim derivations", "", "The following sections are the paper-readable derivation record. The machine packages additionally preserve every one of the 256 candidates and every decision for each claim.", ""]
    for position,cid in enumerate(inv["required_claim_ids"],1):
        x=claims[cid]; target=target_by[cid]; cert=json.loads((ROOT/"claims"/cid/"certificate.json").read_text()); elim=json.loads((ROOT/"claims"/cid/"elimination_receipt.json").read_text()); controls=json.loads((ROOT/"claims"/cid/"controls.json").read_text()); reg=json.loads((ROOT/"claims"/cid/"registration.json").read_text())
        preserving=x["unique_survivor"].split("__")
        dimensions=[d for d in cert["claim_target_evaluation"].get("dimensions",[])]
        lines += [f"### {position}. {x['title']}", "", f"**Claim:** `{cid}`  ", f"**Family:** `{x['family']}`  ", f"**Statement:** {x['statement']}", "", "#### Forward derivation", "", f"Carrier: `{x['carrier']}`. Relation: `{x['relation']}`. Retained record: `{x['retained_record']}`. Evidence boundary: `{x['evidence_boundary']}`.", "", f"Dependencies: {', '.join(f'`{d}`' for d in x['dependencies'])}.", "", f"Generation rule: {reg['candidate_grammar']['generator']}", "", f"Grammar boundary: {reg['candidate_grammar']['boundary']}", "", "The eight binary axes generate exactly 256 forms. The unique preserving form is:", "", f"`{x['unique_survivor']}`", "", "The survivor retains, in order, the complete carrier, explicit observational boundary, generated relation, reconstructible record, distinct evidence class, root-bound provenance, positive finite extension and no extra rule. Any candidate differing on at least one coordinate loses the corresponding required distinction and is eliminated. Thus 255 alternatives fail and one survives without a fitted choice.", "", f"Closure: `{elim['closure']['scope']}`. Minimality: `{elim['closure']['minimality_passed']}`. Named-form uniqueness: `{elim['closure']['named_shape_uniqueness_passed']}`.", "", "#### Falsification and controls", "", f"Falsification condition: {x['falsification_condition']}", ""]
        for control in controls["controls"]: lines.append(f"- `{control['kind']}` — passed `{control['passed']}`: {control['expected_behavior']}")
        lines += ["", "#### External evidence", "", f"Evidence class: `{target['directness']}` / `{target['empirical_disposition']}`. Captured sources: {target['captured_source_count']}; unresolved transports retained: {target['unresolved_transport_count']}. The post-seal consequence matched the registered structural label: `{target['exact_match']}`. External evidence selected the survivor: `false`.", ""]
        for s in target["source_evidence"]: lines.append(f"- `{s['source_id']}` — transport `{s['transport_status']}`; snapshot `{s.get('snapshot_hash') or 'unresolved'}`.")
        if target["numeric_comparison"]:
            n=target["numeric_comparison"]; first=n["first_registered_comparison"]; add=n["source_method_addendum"]
            lines += ["", "**Quantitative record.** The first preregistered all-row unweighted slope was `"+first["measured_slope"]+"`; its deterministic delete-one range was `"+first["delete_one_min"]+"` to `"+first["delete_one_max"]+"`, excluding four. Status: `"+first["comparison_status"]+"`. It remains adverse. The separate source-authored method reports `"+add["reported_center"]+" ± "+add["reported_statistical_uncertainty"]+"`, with a stated systematic interval `"+add["reported_systematic_interval_lower"]+"–"+add["reported_systematic_interval_upper"]+"`; exact four lies at that boundary. Addendum blind status: `"+add["blind_status"]+"`. No first-result reclassification occurred.", ""]
        lines += ["#### What it means", "", f"This law makes **{x['title'].lower()}** admissible only when its carrier, relation, record and evidence boundary remain jointly reconstructible. It prevents a label, fitted output, favorable object or opaque model from replacing the scientific chain. The result may be extended with new finite sources and stronger evidence, but only by preserving every prior row and passing the same common engine.", "", "#### Machine certificate", "", f"Derivation seal: `{cert['derivation_seal_hash']}`. Independent certificate: `{cert['independent_certificate_hash']}`. Engine receipt: `{cert['engine_receipt_hash']}`. Candidate count: `256`. Survivor count: `1`.", ""]
    lines += ["## Historical reconciliation", "", f"The V1/V2 census contains {audit['source_surface']['total_entries_reviewed']} entries. Every entry was reviewed. The {audit['summary']['atomic_question_count']} Astronomy-owned questions were registered as questions before the V3 derivation and mapped to admitted present claims. Prior answers were not used as premises. Universal Physics questions were preserved as typed handoffs rather than relabelled Astronomy claims.", "", "## Limits and extension-open status", "", "This foundation does not claim that every astronomical catalogue row has been ingested, that every contingent initial condition is forced by structure, or that every instrument systematic has vanished. It claims something more precise: the foundational forms required to state, compare and falsify astronomical claims have been generated and admitted at the declared boundary, and all known V1/V2 Astronomy questions are accountable. New observations, objects, methods and lawful derivations are invited. A new result must extend the trace; it may not rewrite failed transports, adverse rows or dependency ownership.", "", "## Full-field continuation roadmap", ""]
    for x in inv["later_full_field_extensions"]: lines.append(f"- {x}.")
    lines += ["", "Each extension will be decomposed into explicit obligations, sealed before outcomes, admitted claim by claim and followed by a versioned paper update. Astronomy remains current-evidence closed at its foundation and open to discovery.", "", "## Reproduction", "", "This Astronomy closure passed six focused tests, 72 sequential engine admissions, 72 independent validators and the branch integration audit. After all fifteen foundations were integrated, the untouched repository command `python3 -m sft verify-all` passed on 28 July 2026: 1,319/1,319 derivations replayed, 969/969 unit and end-to-end tests passed, 1,264/1,264 core executable lines covered, 1,011 empirical claims audited, 114/114 formal Physics claims reaching measurement and 5/5 live exact NIST/CODATA checks. The measured runtime was 4,753.740 seconds.", "", "## Rights, participation and scientific admission", "", "Open criticism is welcome and does not require credentials. Scientific admission requires the shared protocol. Contributors may use the Ernos Labs designation only while preserving the theorem, constraints, complete enumeration, adverse evidence, immutable engine authority, retained authorship and open licenses. A fork that weakens those conditions remains free software but is not an Ernos Labs scientific admission.", "", "**Author:** Maria Smith  ", "**Email:** Maria.Smith.Sftoe@gmail.com  ", "**Discord:** https://discord.gg/ucwGryVxGr  ", "**GitHub:** https://github.com/MettaMazza  ", "**Paper license:** CC BY 4.0  ", "**Code license:** Apache-2.0", "", "## Machine identities", "", f"- Inventory: `{inv['inventory_hash']}`", f"- Prior audit: `{audit['audit_identity']}`", f"- Integration audit: `{integration['integration_hash']}`", f"- Source registry: `{registry['registry_hash']}`", f"- External target census: `{targets['targets_hash']}`", "- Engine: `sha256:4f4cdd7986808e6a6102d650c85e6093d6425e49f14a5f05d70fa05e6031d46a`", "- Verification authority: `sha256:bf810a190b504f0f874a778a52e23251904b17b40a7364135e74b34e8ba0c3b8`", ""]
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text("\n".join(lines)); print(f"Astronomy paper: {OUT.relative_to(ROOT)} words={len(OUT.read_text().split())}")
if __name__=="__main__": main()
