#!/usr/bin/env python3
"""Open and freeze exact COMP observations after registry freeze."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"census/information_science_comp_001_014_target_registry_v1.json";OUT=ROOT/"experiments/external_sources/information_science/comp_001_014_observation_vector_v1.json"
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
 if OUT.exists():raise SystemExit("COMP vector already frozen")
 r=json.loads(REGISTRY.read_text());b=dict(r);ri=b.pop("registry_identity")
 if canonical(b)!=ri or r["target_content_present"] is not False:raise SystemExit("COMP registry changed")
 values=(("lossless_reconstruction",{"source_symbols":4,"encoded_units":6,"parse_count":1,"exact_reconstruction":True}),("prefix_tree",{"leaves":3,"prefix_collisions":0,"instantaneous":True}),("dictionary",{"dictionary_entries":2,"tokens":3,"reconstructed_symbols":9,"exact":True}),("run_recurrence",{"run_rows":3,"source_symbols":6,"recurrence_rows":5,"both_invertible":True}),("transform",{"source_symbols":4,"transform_rows":4,"bijective":True,"reconstruction":True}),("source_model_boundary",{"models":2,"code_lengths":[8,6],"all_models_preserved":True,"target_selected_model":False}),("redundancy",{"long_length":8,"least_length":6,"held_excess":2,"negative_scalar_used":False}),("minimum_description",{"grammar_candidates":3,"target_descriptions":2,"unique_least":"prefix","least_units":6}),("lossy_coarsening",{"microforms":4,"representative_classes":2,"microforms_retained":4}),("distortion",{"positions":4,"mismatches":1,"exact_distortion":"1/4","exact-reconstruction-distortion":"structural absence displayed 0"}),("rate_distortion",{"frontier_rows":[[4,"1/4"],[3,"1/2"],[2,"3/4"]],"rows":3,"continuum_optimum_claimed":False}),("successive_refinement",{"base_labels":4,"detail_labels":4,"reconstructed_forms":4,"exact":True}),("side_information",{"side_positions":4,"relation_labels":4,"reconstructed_positions":4,"independence_prior_used":False}),("compression_completeness",{"registered_obligations":14,"observation_rows":14,"duplicate_owners":0,"omitted_owners":0}))
 rows=[{"number":f"{i:03d}","claim_id":r["claim_ids"][i-1],"obligation_id":r["obligation_ids"][i-1],"observation_name":name,"exact_observation":value,"expected_label":f"complete-comp-{i:03d}-observation-retained","source_ids":["SFT-V3-INDEPENDENT-EXACT-COMPRESSION-OBSERVER","SFT-V1-V2-INFORMATION-OBSERVATION-CORPUS"],"all_rows_preserved":True} for i,(name,value) in enumerate(values,1)]
 p={"schema":"sft-v3-information-science-comp-observation-vector/1","date":"2026-07-29","authority":"Maria Smith","registry_identity":ri,"outcomes_opened_only_after_registry_freeze":True,"records":rows,"record_count":14,"all_rows_preserved":True,"protected_engine_or_verifier_edit_made":False};p["vector_identity"]=canonical(p);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(p,indent=2,sort_keys=True)+"\n");print(json.dumps({"records":14,"identity":p["vector_identity"]},indent=2))
if __name__=="__main__":main()
