#!/usr/bin/env python3
"""Open and freeze exact SIGNAL observations after registry freeze."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"census/information_science_signal_001_014_target_registry_v1.json";OUT=ROOT/"experiments/external_sources/information_science/signal_001_014_observation_vector_v1.json"
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
 if OUT.exists():raise SystemExit("SIGNAL vector already frozen")
 r=json.loads(REGISTRY.read_text());b=dict(r);ri=b.pop("registry_identity")
 if canonical(b)!=ri or r["target_content_present"] is not False:raise SystemExit("SIGNAL registry changed")
 values=(("ordered_signal",{"positions":4,"exact_amplitudes":["1/4","1/2","3/4","1/1"],"complete":True}),("support_amplitude",{"support_positions":[1,2,3,4],"amplitude_rows":4,"separate_and_linked":True}),("sampling",{"selected_positions":[1,3],"retained_amplitudes":["1/4","3/4"],"provenance_retained":True}),("finite_sufficiency",{"grammar":"two-label alternating length six","generated_signals":4,"samples_required":2,"all_reconstructed":True}),("aliasing",{"distinct_sources":2,"selected_positions":[1,3],"sample_records_equal":True,"predecessors_retained":2}),("quantization_partition",{"amplitude_support":4,"classes":2,"overlap":0,"omissions":0}),("quantization_error",{"examples":2,"magnitude_each":"1/8","orientations":["opposed","held"],"negative_scalar_used":False}),("reconstruction",{"samples":4,"source_rows":4,"unique_reconstruction":True}),("interpolation_boundary",{"candidate_values":["1/4","1/2","3/4","1/1"],"candidate_count":4,"continuum_claimed":False}),("finite_transform",{"support_forms":4,"image_forms":4,"bijective":True,"independent_inverse":True}),("time_frequency",{"positions":4,"change_rows":2,"same_rows":2,"joint_record_complete":True}),("spatial_support",{"axis_sizes":[2,3],"coordinate_count":6,"all_coordinates_once":True}),("signal_provenance",{"steps":["capture","sample","quantize"],"step_count":3,"ordered":True}),("signal_completeness",{"registered_obligations":14,"observation_rows":14,"duplicate_owners":0,"omitted_owners":0}))
 records=[{"number":f"{i:03d}","claim_id":r["claim_ids"][i-1],"obligation_id":r["obligation_ids"][i-1],"observation_name":name,"exact_observation":value,"expected_label":f"complete-signal-{i:03d}-observation-retained","source_ids":["SFT-V3-INDEPENDENT-EXACT-FINITE-SIGNAL-OBSERVER","SFT-V1-V2-INFORMATION-OBSERVATION-CORPUS"],"all_rows_preserved":True} for i,(name,value) in enumerate(values,1)]
 p={"schema":"sft-v3-information-science-signal-observation-vector/1","date":"2026-07-29","authority":"Maria Smith","registry_identity":ri,"outcomes_opened_only_after_registry_freeze":True,"records":records,"record_count":14,"all_rows_preserved":True,"protected_engine_or_verifier_edit_made":False};p["vector_identity"]=canonical(p);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(p,indent=2,sort_keys=True)+"\n");print(json.dumps({"records":14,"identity":p["vector_identity"]},indent=2))
if __name__=="__main__":main()
