#!/usr/bin/env python3
"""Open and freeze exact Classical Computation handoff outcomes after registry freeze."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"census/computation_hand_001_006_target_registry_v1.json";RECON=ROOT/"census/computation_discipline_current_reconciliation_v11.json";OUT=ROOT/"experiments/external_sources/computation/hand_001_006_observation_vector_v1.json"
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
 if OUT.exists():raise SystemExit("computation HAND observation vector already frozen")
 registry=json.loads(REGISTRY.read_text());body=dict(registry);registry_identity=body.pop("registry_identity")
 if canonical(body)!=registry_identity or registry["target_content_present"] is not False:raise SystemExit("HAND registry changed")
 recon=json.loads(RECON.read_text());body=dict(recon);recon_identity=body.pop("reconciliation_identity")
 if canonical(body)!=recon_identity or recon["current_closed_count"]!=363 or recon["current_open_count"]!=6 or len(recon["completed_families"]["VALID"])!=12:raise SystemExit("computation v11 reconciliation changed")
 owners=[{"subject":"quantum states, gates, channels and fault tolerance","owner":"quantum-computation"},{"subject":"software, hardware, platforms and side channels","owner":"engineering-translation"},{"subject":"domain measurements","owner":"owning-domain-science"},{"subject":"Unison AI, Fold Chess, Fold Go and Fold Protein experiments","owner":"frontier-application-rebuild"}]
 values=(("one_owner",{"owner_rows":owners,"duplicate_subjects":0,"orphan_subjects":0}),("measurement_boundary",{"computational_owner":"classical-computation","measurement_owner":"owning-domain-science","return_route":"sealed-external-comparison"}),("formal_empirical",{"ordered_stages":["formal-law","value-free-registry","sealed-prediction","custodied-observation","complete-comparison"],"suppressed_outcome_rows":0}),("classical_quantum",{"classical_owner":"classical-computation","quantum_owner":"quantum-computation","transferred_records":["state-composition-interface","trace-interface","resource-interface"],"silent_transfer":False}),("open_extension",{"status":"dated-complete-against-frozen-census","extension_policy":"new obligations and receipts without rewriting prior identities","permanent_lock":False}),("cross_branch_completeness",{"frozen_obligations":369,"pre_handoff_closed":363,"handoff_obligations":6,"post_handoff_expected":369,"owner_rows":4,"duplicate_owners":0,"omitted_owners":0,"predecessor_reconciliation_identity":recon_identity,"protected_authority_changed":False}))
 records=[{"number":f"{i:03d}","claim_id":registry["claim_ids"][i-1],"obligation_id":registry["obligation_ids"][i-1],"observation_name":name,"exact_observation":value,"expected_label":f"complete-hand-{i:03d}-execution-retained","source_ids":["SFT-V3-COMPUTATION-RECONCILIATION-V11","SFT-V3-BRANCH-OWNERSHIP-TREE","SFT-V3-OPEN-EXTENSION-POLICY"],"all_rows_preserved":True} for i,(name,value) in enumerate(values,1)]
 payload={"schema":"sft-v3-classical-computation-hand-observation-vector/1","date":"2026-07-29","authority":"Maria Smith","registry_identity":registry_identity,"outcomes_opened_only_after_registry_freeze":True,"predecessor_reconciliation_identity":recon_identity,"records":records,"record_count":len(records),"all_rows_preserved":True,"protected_engine_or_verifier_edit_made":False};payload["vector_identity"]=canonical(payload);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n");print(json.dumps({"records":len(records),"identity":payload["vector_identity"]},indent=2))
if __name__=="__main__":main()
