#!/usr/bin/env python3
"""Open and freeze exact CHAN observations after registry freeze."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"census/information_science_chan_001_018_target_registry_v1.json";OUT=ROOT/"experiments/external_sources/information_science/chan_001_018_observation_vector_v1.json"
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
 if OUT.exists():raise SystemExit("CHAN vector already frozen")
 r=json.loads(REGISTRY.read_text());b=dict(r);ri=b.pop("registry_identity")
 if canonical(b)!=ri or r["target_content_present"] is not False:raise SystemExit("CHAN registry changed")
 values=(("channel_relation",{"inputs":3,"outputs":2,"relation_rows":4,"all_inputs_covered":True}),("deterministic_transport",{"inputs":3,"outputs_per_input":1,"single_valued":True}),("observation_equivalence",{"fine_classes":3,"coarse_classes":2,"source_microforms":3}),("single_user_capacity",{"channel_inputs":3,"distinguishable_code_forms":3,"unit":"forms per one registered use"}),("resource_capacity",{"admissible_inputs":2,"distinguishable_code_forms":2,"resource":"registered two-input codebook"}),("noiseless_composition",{"inputs":3,"component_channels":2,"terminal_images":3,"trace_retained":True}),("cascade_boundary",{"upstream_forms":3,"terminal_distinguishable_forms":2,"boundary_met":True}),("parallel_composition",{"left_forms":2,"right_forms":3,"joint_forms":6,"all_cross_pairs":True}),("feedback",{"uses":2,"histories":4,"distinct_terminal_words":4,"hidden_forms_added":False}),("multiple_access",{"sender_forms":[2,2],"joint_inputs":4,"output_classes":2}),("broadcast",{"source_forms":2,"receivers":2,"joint_output_rows":2}),("relay",{"relay_nodes":2,"source_terminal_paths":2,"all_routes_retained":True}),("interference",{"joint_inputs":4,"joint_outputs":4,"cross_dependency":True}),("bidirectional",{"directional_alphabets":[2,2],"exchange_states":4,"both_histories_retained":True}),("network_cut",{"edge_disjoint_paths":2,"source_cut_edges":2,"cut_closes_transport":True}),("finite_use",{"single_use_forms":2,"uses":2,"word_forms":4,"unit_retained":True}),("channel_simulation",{"target_inputs":2,"encoder_rows":2,"base_rows":2,"decoder_rows":2,"relations_equal":True}),("channel_completeness",{"registered_obligations":18,"observation_rows":18,"duplicate_owners":0,"omitted_owners":0}))
 rows=[{"number":f"{i:03d}","claim_id":r["claim_ids"][i-1],"obligation_id":r["obligation_ids"][i-1],"observation_name":name,"exact_observation":value,"expected_label":f"complete-chan-{i:03d}-observation-retained","source_ids":["SFT-V3-INDEPENDENT-EXACT-FINITE-CHANNEL-OBSERVER","SFT-V1-V2-INFORMATION-OBSERVATION-CORPUS"],"all_rows_preserved":True} for i,(name,value) in enumerate(values,1)]
 p={"schema":"sft-v3-information-science-chan-observation-vector/1","date":"2026-07-29","authority":"Maria Smith","registry_identity":ri,"outcomes_opened_only_after_registry_freeze":True,"records":rows,"record_count":18,"all_rows_preserved":True,"protected_engine_or_verifier_edit_made":False};p["vector_identity"]=canonical(p);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(p,indent=2,sort_keys=True)+"\n");print(json.dumps({"records":18,"identity":p["vector_identity"]},indent=2))
if __name__=="__main__":main()
