#!/usr/bin/env python3
"""Freeze CPLXX claim identities and questions before observation access."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"census/computation_cplxx_001_033_target_registry_v1.json"
IDS=(
"SFT-COMP-CPLXX-INPUT-LENGTH-CARRIER-001","SFT-COMP-CPLXX-DETERMINISTIC-TIME-CLASS-002","SFT-COMP-CPLXX-DETERMINISTIC-SPACE-CLASS-003","SFT-COMP-CPLXX-HIERARCHY-SUCCESSION-004","SFT-COMP-CPLXX-NONDETERMINISTIC-SUPPORT-005","SFT-COMP-CPLXX-CERTIFICATE-VERIFICATION-RESOURCE-006","SFT-COMP-CPLXX-FOLD-P-NP-SCOPE-007","SFT-COMP-CPLXX-CONVENTIONAL-P-NP-TRANSPORT-008","SFT-COMP-CPLXX-COMPLEMENT-CLASS-009","SFT-COMP-CPLXX-ALTERNATION-SPACE-010","SFT-COMP-CPLXX-EXPONENTIAL-SUCCESSION-011","SFT-COMP-CPLXX-CIRCUIT-UNIFORMITY-012","SFT-COMP-CPLXX-CIRCUIT-SIZE-DEPTH-WIDTH-013","SFT-COMP-CPLXX-FORMULA-BRANCHING-CIRCUIT-014","SFT-COMP-CPLXX-PARALLEL-WORK-DEPTH-015","SFT-COMP-CPLXX-COMMUNICATION-ROUNDS-DISTINCTIONS-016","SFT-COMP-CPLXX-DECISION-TREE-QUERY-LOWER-017","SFT-COMP-CPLXX-RANDOMIZED-RESOURCE-018","SFT-COMP-CPLXX-DERANDOMIZATION-BOUNDARY-019","SFT-COMP-CPLXX-COUNTING-SUPPORT-020","SFT-COMP-CPLXX-REDUCTION-COMPLETE-PROBLEM-021","SFT-COMP-CPLXX-UPPER-BOUND-CERTIFICATE-022","SFT-COMP-CPLXX-LOWER-BOUND-ADVERSARY-023","SFT-COMP-CPLXX-ARBITRARY-FOLD-CIRCUIT-LOWER-024","SFT-COMP-CPLXX-WORST-AVERAGE-DISTRIBUTION-025","SFT-COMP-CPLXX-APPROXIMATION-RATIO-026","SFT-COMP-CPLXX-PARAMETERIZED-SIZE-027","SFT-COMP-CPLXX-KERNELIZATION-BOUNDARY-028","SFT-COMP-CPLXX-AMORTIZED-RESOURCE-029","SFT-COMP-CPLXX-ONLINE-COMPETITIVE-030","SFT-COMP-CPLXX-DESCRIPTION-PROGRAM-SIZE-031","SFT-COMP-CPLXX-REVERSIBLE-TRADEOFF-032","SFT-COMP-CPLXX-COMPLETENESS-033")
def canonical(v):return "sha256:"+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def main():
    if OUT.exists():raise SystemExit("CPLXX target registry already frozen")
    census=json.loads((ROOT/"census/computation_discipline_obligations.json").read_text());rows=[x for x in census["obligations"] if x["family"]=="CPLXX"]
    if len(rows)!=len(IDS) or len(IDS)!=33:raise SystemExit("CPLXX census changed")
    payload={"schema":"sft-v3-classical-computation-cplxx-value-free-registry/1","date":"2026-07-29","authority":"Maria Smith","frozen_before_observation_access":True,"target_content_present":False,"classical_computation_census_identity":census["census_identity"],"claim_ids":IDS,"obligation_ids":[x["obligation_id"] for x in rows],"question_titles":[x["title"] for x in rows],"completion_unit":"all thirty-three claims; no proper subset","prohibited_target_fields":["expected complexity result","selected survivor","match result","imported class or lower-bound answer"]};payload["registry_identity"]=canonical(payload);OUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n");print(json.dumps({"claims":len(IDS),"identity":payload["registry_identity"]},indent=2))
if __name__=="__main__":main()
