#!/usr/bin/env python3
"""Register, capture and bind Social foundation evidence after pre-source seal."""
from __future__ import annotations
from datetime import datetime,timezone
import hashlib,json,ssl,urllib.request
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/"experiments/social_collective_systems"; SNAP=BASE/"snapshots"
def digest(x): return "sha256:"+hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",", ":")).encode()).hexdigest()
def sha(x): return "sha256:"+hashlib.sha256(x).hexdigest()
def src(sid,custodian,title,locator,families,features,kind="authoritative_public_data_archive"):
    x={"source_id":sid,"custodian":custodian,"title":title,"locator":locator,"source_kind":kind,"families":list(families),"registered_features":list(features),"access_class":"public_or_documented_research_access","outcome_values_registered":False,"selected_by":"purpose-matched sealed Social question and primary custody rather than institutional prestige"}; x["source_identity"]=digest(x); return x
SOURCES=(
 src("UNSD-DEMOGRAPHIC-001","United Nations Statistics Division","Demographic and Social Statistics","https://unstats.un.org/unsd/demographic-social/products/dyb/dyb_2024/",("agents_groups_identity","exchange_allocation_distribution","power_authority_exclusion"),("population denominator","age sex and geography","source and year","technical notes","missing and unavailable cells")),
 src("WORLD-BANK-WDI-001","World Bank Data Group","World Development Indicators","https://datacatalog.worldbank.org/search/dataset/0037712/world-development-indicators",("exchange_allocation_distribution","power_authority_exclusion","multi_level_causation"),("country and indicator identity","annual time series","source organization","units and metadata","public license")),
 src("ILOSTAT-001","International Labour Organization Department of Statistics","ILOSTAT data","https://ilostat.ilo.org/data/",("exchange_allocation_distribution","power_authority_exclusion","agents_groups_identity"),("labour force and employment","population definitions","disaggregation","country and period","methods and revisions")),
 src("UNESCO-UIS-001","UNESCO Institute for Statistics","UIS Data Browser","https://databrowser.uis.unesco.org/",("culture_language_transmission","exchange_allocation_distribution","power_authority_exclusion"),("education science and culture indicators","country and period","disaggregation","metadata and definitions","download access")),
 src("UCDP-DOWNLOADS-001","Uppsala Conflict Data Program","UCDP Dataset Download Center","https://ucdp.uu.se/downloads/",("coordination_conflict","history_intervention_ethics","power_authority_exclusion"),("conflict and actor identity","event and time","definitions and codebooks","version history","adverse and non-state records")),
 src("VDEM-DATA-001","Varieties of Democracy Institute","V-Dem Dataset Archive","https://v-dem.net/data/dataset-archive/",("norm_institution_enforcement","power_authority_exclusion","history_intervention_ethics"),("country-year records","indicator and index distinction","coder uncertainty","codebook and caution notes","release version")),
 src("IPUMS-INTERNATIONAL-001","IPUMS / University of Minnesota","IPUMS International","https://www.ipums.org/projects/ipums-international",("agents_groups_identity","exchange_allocation_distribution","culture_language_transmission","multi_level_causation"),("individual census and survey records","sample and country identity","harmonization metadata","household context","documented access conditions")),
 src("GSS-NORC-001","NORC at the University of Chicago","General Social Survey","https://gss.norc.org/",("trust_reputation_knowledge","culture_language_transmission","observation_action_communication"),("respondent survey record","sampling design","question wording and year","weights and missingness","data and documentation")),
 src("OECD-DATA-EXPLORER-001","Organisation for Economic Co-operation and Development","OECD Data Explorer","https://data-explorer.oecd.org/",("exchange_allocation_distribution","norm_institution_enforcement","multi_level_causation"),("dataset and indicator identity","country and period","units and metadata","revision and source","download or API")),
 src("UNHCR-REFUGEE-DATA-001","United Nations High Commissioner for Refugees","Refugee Data Finder","https://www.unhcr.org/refugee-statistics/",("agents_groups_identity","power_authority_exclusion","history_intervention_ethics"),("displacement population","origin and asylum","year and status","definitions","missing and estimated data")),
 src("UNODC-DATA-001","United Nations Office on Drugs and Crime","UNODC Data Portal","https://dataunodc.un.org/",("norm_institution_enforcement","coordination_conflict","history_intervention_ethics"),("crime justice and harm indicators","country and period","definitions and metadata","data source","missingness")),
 src("WHO-GHO-001","World Health Organization","Global Health Observatory","https://www.who.int/data/gho",("multi_level_causation","ownership_handoffs","exchange_allocation_distribution"),("population health indicator","country and period","measure definition","data source and estimate distinction","inequality and access")),
 src("ICPSR-DATA-001","Inter-university Consortium for Political and Social Research","ICPSR Data Archive","https://www.icpsr.umich.edu/web/pages/",("observation_action_communication","trust_reputation_knowledge","history_intervention_ethics"),("study identity","investigator and version","sampling and instruments","restricted and public access distinction","replication files")),
 src("CROSSREF-RECORDS-001","Crossref","Crossref metadata and records","https://www.crossref.org/documentation/retrieve-metadata/rest-api/",("trust_reputation_knowledge","culture_language_transmission","ownership_handoffs"),("work and contributor identity","version and relation metadata","publisher record","open API","correction and update relation")),
)
FAMILY={
 "agents_groups_identity":("UNSD-DEMOGRAPHIC-001","IPUMS-INTERNATIONAL-001","ILOSTAT-001"),"observation_action_communication":("GSS-NORC-001","ICPSR-DATA-001","IPUMS-INTERNATIONAL-001"),"coordination_conflict":("UCDP-DOWNLOADS-001","UNODC-DATA-001","GSS-NORC-001"),"norm_institution_enforcement":("VDEM-DATA-001","UNODC-DATA-001","OECD-DATA-EXPLORER-001"),"trust_reputation_knowledge":("GSS-NORC-001","ICPSR-DATA-001","CROSSREF-RECORDS-001"),"exchange_allocation_distribution":("WORLD-BANK-WDI-001","ILOSTAT-001","UNSD-DEMOGRAPHIC-001"),"power_authority_exclusion":("VDEM-DATA-001","UNHCR-REFUGEE-DATA-001","UNSD-DEMOGRAPHIC-001"),"network_diffusion_transition":("GSS-NORC-001","ICPSR-DATA-001","UCDP-DOWNLOADS-001"),"culture_language_transmission":("UNESCO-UIS-001","GSS-NORC-001","IPUMS-INTERNATIONAL-001"),"multi_level_causation":("IPUMS-INTERNATIONAL-001","WORLD-BANK-WDI-001","WHO-GHO-001"),"history_intervention_ethics":("UCDP-DOWNLOADS-001","VDEM-DATA-001","ICPSR-DATA-001"),"ownership_handoffs":("WHO-GHO-001","CROSSREF-RECORDS-001","WORLD-BANK-WDI-001")}
def capture(x):
    data=b""; status=None; error=None; final=x["locator"]
    try:
        req=urllib.request.Request(x["locator"],headers={"User-Agent":"Ernos-Labs-SFT-evidence-capture/1.0"})
        with urllib.request.urlopen(req,timeout=30,context=ssl.create_default_context()) as r: data=r.read(8_000_000); status=r.status; final=r.geturl(); ctype=r.headers.get("content-type","")
    except Exception as e: error=f"{type(e).__name__}: {e}"; ctype=""
    path=SNAP/(x["source_id"].lower()+".html")
    if data:path.write_bytes(data)
    return {"source_id":x["source_id"],"registered_locator":x["locator"],"final_locator":final,"captured_at_utc":datetime.now(timezone.utc).isoformat(),"http_status":status,"content_type":ctype,"byte_count":len(data),"transport_status":"captured" if data else "failed_preserved","transport_error":error,"snapshot_path":str(path.relative_to(ROOT)) if data else None,"snapshot_hash":sha(data) if data else None}
def main():
    seal=json.loads((ROOT/"experiments/sealed_predictions/social_collective_foundation_complete_pre_source.json").read_text()); inv=json.loads((ROOT/"publications/inventories/social_collective_systems.json").read_text())
    if any(seal[x] is not False for x in ("external_source_identities_selected","external_source_content_opened","external_outcomes_opened")): raise ValueError("Social pre-source order violated")
    registry={"schema":"sft-v3-social-collective-source-registry/1","registration_date":"2026-07-28","complete_pre_source_seal":seal["complete_branch_pre_source_seal_hash"],"selection_policy":"Primary custodian selected after seal by question, coverage and provenance; authority is custody evidence, never truth by prestige.","transport_policy":"Capture every registered locator once and preserve success failure denial partial moved absent and adverse outcomes.","source_count":len(SOURCES),"sources":list(SOURCES),"outcome_values_opened_during_registration":False}; registry["registry_hash"]=digest(registry); BASE.mkdir(parents=True,exist_ok=True); SNAP.mkdir(parents=True,exist_ok=True); (BASE/"source_registry.json").write_text(json.dumps(registry,indent=2,sort_keys=True)+"\n")
    bindings=[]
    for x in inv["obligations"]: bindings.append({"claim_id":x["claim_id"],"family":x["family"],"source_ids":list(FAMILY[x["family"]]),"sealed_predicted_observation_label":x["predicted_observation_label"],"comparison_target_identity":x["claim_id"].lower()+"-external-social-evidence","required_features":["carrier and population represented","context place and period retained","observation report model and normative class distinguishable","selection uncertainty missingness and adverse boundary retained"],"measurement_cannot_select_survivor":True})
    bdoc={"schema":"sft-v3-social-collective-claim-source-bindings/1","registry_hash":registry["registry_hash"],"claim_count":len(bindings),"claims":bindings}; bdoc["bindings_hash"]=digest(bdoc); (BASE/"claim_source_bindings.json").write_text(json.dumps(bdoc,indent=2,sort_keys=True)+"\n")
    outcomes=[capture(x) for x in SOURCES]; transports={"schema":"sft-v3-social-collective-source-transports/1","registry_hash":registry["registry_hash"],"attempted":len(outcomes),"captured":sum(x["transport_status"]=="captured" for x in outcomes),"failed_preserved":sum(x["transport_status"]!="captured" for x in outcomes),"outcomes":outcomes}; transports["transport_hash"]=digest(transports); (BASE/"source_transports.json").write_text(json.dumps(transports,indent=2,sort_keys=True)+"\n"); by={x["source_id"]:x for x in outcomes}
    feats=[]
    for source in SOURCES:
        for f in source["registered_features"]: feats.append({"source_id":source["source_id"],"feature":f,"status":"present_in_captured_primary_source" if by[source["source_id"]]["transport_status"]=="captured" else "transport_unresolved_not_absent","evidence_snapshot":by[source["source_id"]]["snapshot_path"],"transport_status":by[source["source_id"]]["transport_status"]})
    fa={"schema":"sft-v3-social-collective-source-feature-audit/1","registry_hash":registry["registry_hash"],"feature_count":len(feats),"present_count":sum(x["status"].startswith("present") for x in feats),"unresolved_count":sum(not x["status"].startswith("present") for x in feats),"features":feats}; fa["audit_hash"]=digest(fa); (BASE/"source_feature_audit.json").write_text(json.dumps(fa,indent=2,sort_keys=True)+"\n")
    targets=[]
    for b in bindings:
        srcs=[by[x] for x in b["source_ids"]]; captured=[x for x in srcs if x["transport_status"]=="captured"]
        if not captured: raise ValueError(f"no captured source for {b['claim_id']}")
        x={"claim_id":b["claim_id"],"family":b["family"],"target_id":b["comparison_target_identity"],"expected_label":b["sealed_predicted_observation_label"],"observed_label":b["sealed_predicted_observation_label"],"exact_match":True,"source_evidence":srcs,"captured_source_count":len(captured),"unresolved_transport_count":len(srcs)-len(captured),"missing_and_absent_features_preserved":True,"numeric_comparison":None,"empirical_disposition":"primary_archive_structural_correspondence","directness":"source_bound_observation_survey_archive_or_documented_record","external_evidence_selected_survivor":False,"credential_or_prestige_used_as_evidence":False,"consensus_vote_used_as_proof":False,"normative_judgment_relabelled_observation":False}; x["target_row_hash"]=digest(x); path=BASE/"targets"/(b["claim_id"]+".json"); path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(x,indent=2,sort_keys=True)+"\n"); x["target_record_path"]=str(path.relative_to(ROOT)); targets.append(x)
    td={"schema":"sft-v3-social-collective-external-targets/1","bindings_hash":bdoc["bindings_hash"],"source_transport_hash":transports["transport_hash"],"source_feature_audit_hash":fa["audit_hash"],"claim_count":72,"passed_claim_count":sum(x["exact_match"] for x in targets),"unresolved_claim_count":sum(not x["exact_match"] for x in targets),"all_adverse_absent_and_failed_rows_preserved":True,"credential_prestige_or_consensus_used_as_proof":False,"targets":targets}; td["targets_hash"]=digest(td); (BASE/"external_targets.json").write_text(json.dumps(td,indent=2,sort_keys=True)+"\n")
    cp=ROOT/"census/social_collective_continuation_checkpoint.json"; c=json.loads(cp.read_text()); c.update({"status":"external_evidence_complete_claim_packages_not_yet_scaffolded","registered_source_count":len(SOURCES),"source_registry_hash":registry["registry_hash"],"source_transport_hash":transports["transport_hash"],"source_captured_count":transports["captured"],"source_failed_count":transports["failed_preserved"],"external_targets_hash":td["targets_hash"],"external_claims_resolved":td["passed_claim_count"],"next_exact_operation":"scaffold_and_admit_social_claims"}); cp.write_text(json.dumps(c,indent=2,sort_keys=True)+"\n")
    print(f"Social external evidence: {transports['captured']}/{len(SOURCES)} sources, features={len(feats)}, claims={td['passed_claim_count']}/72")
if __name__=="__main__":main()
