#!/usr/bin/env python3
"""Audit V1/V2, freeze Social inventory and seal all pre-source derivations."""
from __future__ import annotations
from collections import Counter
from dataclasses import asdict
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from sft.social_collective_systems.generated_law import SOCIAL_BLUEPRINTS,unique_survivor
from sft.social_collective_systems.obligations import SOCIAL_OBLIGATIONS,FAMILY_ORDER
ENGINE="sha256:4f4cdd7986808e6a6102d650c85e6093d6425e49f14a5f05d70fa05e6031d46a"; AUTH="sha256:bf810a190b504f0f874a778a52e23251904b17b40a7364135e74b34e8ba0c3b8"
V1_MAP={"XIV-5":"SFT-SOCIAL-SOCIAL-CYCLE-001","XIII-1":"SFT-SOCIAL-EMERGENCE-001"}
V2_MAP={177:"SFT-SOCIAL-SOCIAL-CYCLE-001",185:"SFT-SOCIAL-SYNCHRONIZATION-001",307:"SFT-SOCIAL-MULTI-AGENT-001"}
HANDOFFS={"V1:G8":"Computation owns network communication structure; Social Science owns human meaning, access and institutional context.","V2:338":"Computation owns distributed consensus and impossibility; Social Science owns collective decision procedures and observed institutions.","V2:295":"Biology owns ecosystem dynamics; Social Science owns human organization and coupled social evidence."}
def digest(x): return "sha256:"+hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",", ":")).encode()).hexdigest()
def file_hash(p): return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
def main():
    v1=json.loads((ROOT/"audits/v1_theorem_manifest_observation_census.json").read_text()); v2=json.loads((ROOT/"audits/v2_407_step_observation_census.json").read_text()); rows=[]; atoms=[]
    for version,source,key_name,hash_name,mapping in (("v1",v1["rows"],"v1_claim_id","source_row_sha256",V1_MAP),("v2",v2["steps"],"step","source_block_sha256",V2_MAP)):
        for r in source:
            key=r[key_name]; target=mapping.get(key); label=f"{version.upper()}:{key}"; atom=None
            if target:
                atom={"atom_id":f"SFT-PRIOR-{version.upper()}-{str(key).replace('-','')}-SOCIAL","source_entry":label,"question":f"What exact V3 collective carrier, context, retained record and falsification boundary accounts for the question historically recorded at {label} without importing its answer?","mapped_foundation_claim":target,"boundary":"Collective observations and institutions are Social-owned; abstract mathematics, computation and individual mechanisms remain typed dependencies."}; atoms.append(atom)
            rows.append({"source":version,"source_entry":key,"source_hash":r[hash_name],"source_observation":r["prior_result_observation"],"social_owned":bool(target),"disposition":"social_question_registered" if target else "reviewed_no_social_owned_atom","explicit_handoff":HANDOFFS.get(label),"social_atom":atom})
    audit={"schema":"sft.social-collective.v1-v2-initial-atomic-ownership-audit.v1","status":"ownership_questions_frozen_derivations_not_yet_admitted","authority_boundary":{"canonical_engine_seal":ENGINE,"verification_authority_seal":AUTH,"engine_called":False,"engine_modified":False,"prior_answers_used_as_premises":False,"external_outcomes_opened":False},"source_surface":{"v1_rows_reviewed":len(v1["rows"]),"v2_steps_reviewed":len(v2["steps"]),"total_entries_reviewed":len(rows)},"ownership_law":{"social_owner":"Collective identities, relations, institutions, distributions, power, culture and source-dated social histories.","consumed_not_reowned":["abstract mathematics","distributed computation","individual biology and consciousness","clinical state","Earth hazard"],"engineering_handoff":"Policy, platform and organizational implementation cannot select the social law."},"summary":{"owned_source_entry_count":len(atoms),"atomic_question_count":len(atoms),"unique_atom_ids":len({x['atom_id'] for x in atoms})==len(atoms),"explicit_handoff_count":len(HANDOFFS),"same_strength_admitted_count":0},"atomic_questions":atoms,"source_rows":rows}; audit["audit_identity"]=digest(audit); audit_path=ROOT/"audits/social_collective_v1_v2_initial_atomic_ownership.json"; write(audit_path,audit); (ROOT/"audits/social_collective_v1_v2_initial_atomic_ownership.md").write_text("# Social and Collective Sciences V1/V2 initial atomic ownership audit\n\n"+f"All **{len(rows)}** entries reviewed; **{len(atoms)}** Social-owned questions registered without importing answers.\n\n"+"\n".join(f"- `{x['atom_id']}` → `{x['mapped_foundation_claim']}`" for x in atoms)+f"\n\nAudit identity: `{audit['audit_identity']}`\n")
    census=json.loads((ROOT/"census/claims.json").read_text()); admitted={x["claim_id"] for x in census["claims"] if x.get("model_admitted") is True}; upstream=sorted({d for x in SOCIAL_BLUEPRINTS for d in x.dependencies if not d.startswith("SFT-SOCIAL-")}); missing=[x for x in upstream if x not in admitted]
    if missing: raise ValueError(f"unadmitted Social dependencies: {missing}")
    blue={x.claim_id:x for x in SOCIAL_BLUEPRINTS}; counts=Counter(x.family for x in SOCIAL_OBLIGATIONS); inv_rows=[]
    for i,o in enumerate(SOCIAL_OBLIGATIONS,1):
        b=blue[o.claim_id]; x=asdict(o); x.update({"position":i,"candidate_count":256,"unique_survivor":"__".join(c.name for c in unique_survivor(b)),"dependencies":list(b.dependencies),"predicted_observation_label":b.predicted_observation_label,"status":"registered_not_admitted"}); inv_rows.append(x)
    mapping={x["atom_id"]:x["mapped_foundation_claim"] for x in atoms}
    inv={"schema":"sft-v3-social-collective-foundation-inventory/1","branch_id":"social_collective_systems","inventory_frozen":True,"inventory_date":"2026-07-28","derivation_target":"current-evidence foundational closure, extension-open","scope":"Agents, relations, groups, collective identity, observation, communication, coordination, institutions, trust, exchange, distribution, power, networks, culture, cross-level causation, history, intervention, ethics and typed handoffs.","ownership_boundary":{"owned":"Genuinely collective human and multi-agent phenomena with historical, cultural and institutional context retained.","consumed_not_reowned":["mathematical graphs","distributed computation","individual cognition and biology","clinical medicine","physical environmental hazard"],"downstream":["Engineering Translation"]},"prior_audit":str(audit_path.relative_to(ROOT)),"prior_audit_identity":audit["audit_identity"],"prior_atomic_question_count":len(mapping),"prior_atom_to_foundation_claim":mapping,"inventory_completion_explanation":"Each of the twelve declared roadmap families decomposes into six distinct carrier/relation/record/evidence/falsification obligations. The resulting count follows the decomposition rather than a requested target.","family_order":list(FAMILY_ORDER),"family_counts":{f:counts[f] for f in FAMILY_ORDER},"required_claim_count":len(inv_rows),"required_claim_ids":[x.claim_id for x in SOCIAL_OBLIGATIONS],"candidate_count":len(inv_rows)*256,"admitted_claim_count_at_freeze":0,"upstream_dependency_count":len(upstream),"upstream_dependency_claim_ids":upstream,"all_upstream_dependencies_model_admitted_at_freeze":True,"external_source_identities_selected_at_freeze":False,"external_outcomes_opened_at_freeze":False,"unclassified_obligations":[],"foundation_frontier_obligations":[],"later_full_field_extensions":["complete social network group organization and institution census","complete anthropology archaeology sociology family and community studies","complete governance law politics economics labour and inequality evidence","complete demography migration geography city and settlement evidence","complete culture language education religion media and knowledge transmission","complete criminology justice conflict peace and social-harm evidence","complete multi-agent artificial collective and institutional knowledge studies","complete causal intervention replication ethics and cross-context limits"],"obligations":inv_rows}; inv["inventory_hash"]=digest(inv); inv_path=ROOT/"publications/inventories/social_collective_systems.json"; write(inv_path,inv)
    sealed_files=["publications/inventories/social_collective_systems.json","sft/social_collective_systems/obligations.py","sft/social_collective_systems/structural_model.py","sft/social_collective_systems/generated_law.py","audits/social_collective_v1_v2_initial_atomic_ownership.json"]
    predictions=tuple((x.claim_id,x.exact_result,x.predicted_observation_label,x.falsification_condition) for x in SOCIAL_BLUEPRINTS); seal={"schema":"sft-v3-social-collective-complete-pre-source-seal/1","seal_date":"2026-07-28","required_claim_count":72,"candidate_count":18432,"inventory_hash":inv["inventory_hash"],"claim_prediction_set_hash":digest(predictions),"sealed_files":{x:file_hash(ROOT/x) for x in sealed_files},"external_source_identities_selected":False,"external_source_content_opened":False,"external_outcomes_opened":False,"prior_answers_present_in_derivation_runtime":False,"conventional_social_models_present_in_derivation_runtime":False,"credential_prestige_or_consensus_used_to_select_law":False,"measurement_used_to_select_law":False,"canonical_engine_seal":ENGINE,"verification_authority_seal":AUTH}; seal["complete_branch_pre_source_seal_hash"]=digest(seal); seal_path=ROOT/"experiments/sealed_predictions/social_collective_foundation_complete_pre_source.json"; write(seal_path,seal)
    checkpoint={"schema":"sft-v3-social-collective-continuation-checkpoint/1","branch":"social_collective_systems","status":"complete_foundation_derivations_sealed_before_external_sources","foundation_required_claim_count":72,"candidate_count":18432,"admitted_claim_count":0,"remaining_claim_count":72,"prior_entries_reviewed":len(rows),"prior_atomic_questions":len(atoms),"initial_audit_path":str(audit_path.relative_to(ROOT)),"initial_audit_identity":audit["audit_identity"],"inventory_path":str(inv_path.relative_to(ROOT)),"inventory_hash":inv["inventory_hash"],"pre_source_seal_path":str(seal_path.relative_to(ROOT)),"pre_source_seal_hash":seal["complete_branch_pre_source_seal_hash"],"previous_branch_terminal_claim":"SFT-ASTRO-ASTRO-HANDOFF-001","engine_seal":ENGINE,"verification_authority_seal":AUTH,"protected_authority_modified":False,"remote_publication_authorized":False,"next_exact_operation":"preregister_primary_social_evidence_sources"}; write(ROOT/"census/social_collective_continuation_checkpoint.json",checkpoint)
    print(f"Social prepared: reviewed={len(rows)} atoms={len(atoms)} claims=72 candidates=18432 seal={seal['complete_branch_pre_source_seal_hash']}")
if __name__=="__main__":main()
