#!/usr/bin/env python3
"""Mechanically emit separate claim packages from the frozen ECHEM-002-004 batch."""
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from sft.chemistry.echem_potential_batch_v1 import CELL_POTENTIAL_SPEC, COMPLETENESS_CERTIFICATES, CONCENTRATION_POTENTIAL_SPEC, ELECTRODE_POTENTIAL_SPEC
from sft.engine.canonical import sha256_identity

CONFIG = {
    "002": (ELECTRODE_POTENTIAL_SPEC, "ElectrodePotentialValidator", "SFT-CHEM-OBL-ECHEM-002", "electrode-potential relation", "NIST-JRES-AGCL-STANDARD-POTENTIAL-1954", 17, "experiments/external_sources/chemistry/echem_002_target_identities_v1.json", "experiments/sealed_predictions/chemistry_echem_002_electrode_potential_pre_source_v1.json"),
    "003": (CELL_POTENTIAL_SPEC, "CellPotentialValidator", "SFT-CHEM-OBL-ECHEM-003", "cell-potential composition", "NIST-JRES-AGCL-COMPLETE-CELL-1954", 88, "experiments/external_sources/chemistry/echem_003_target_identities_v1.json", "experiments/sealed_predictions/chemistry_echem_003_cell_potential_pre_source_v1.json"),
    "004": (CONCENTRATION_POTENTIAL_SPEC, "ConcentrationPotentialValidator", "SFT-CHEM-OBL-ECHEM-004", "concentration-dependent potential", "NIST-JRES-AGCL-HCL-CONCENTRATION-SERIES-1954", 176, "experiments/external_sources/chemistry/echem_004_target_identities_v1.json", "experiments/sealed_predictions/chemistry_echem_004_concentration_potential_pre_source_v1.json"),
}
DOMAINS = {
    "002": (("voltage-answer-only", "complete-half-cell-transfer-account"), ("unbound-electrode-number", "one-held-reference-electrode"), ("mixed-temperature-or-state", "same-held-standard-condition"), ("unnormalized-total-work", "exact-work-per-held-transfer-carrier"), ("signed-native-number", "held-above-below-or-coincident-orientation"), ("numerical-zero-potential", "structural-EmptyOne-reference-coincidence"), ("selected-standard-potential", "complete-standard-potential-reference-vector"), ("species-specific-offset", "common-work-successor-preserves-order")),
    "003": (("anonymous-voltage-pair", "two-distinct-held-half-cell-carriers"), ("mixed-reference-subtraction", "one-common-held-reference"), ("mixed-condition-subtraction", "one-common-held-condition"), ("unordered-potential-difference", "held-source-terminal-reaction-path"), ("signed-arithmetic-premise", "exact-positive-sum-or-Take-composition"), ("numerical-zero-cell-potential", "structural-EmptyOne-cell-coincidence"), ("selected-cell-voltage", "complete-full-cell-potential-vector"), ("irreversible-sign-flip", "exact-cell-reversal-preserves-positive-separation")),
    "004": (("concentration-number-only", "complete-half-reaction-activity-state"), ("signed-or-continuum-activity-coordinate", "held-product-reactant-or-coincident-orientation"), ("arbitrary-real-activity-premise", "complete-generated-doubling-support"), ("imported-logarithm", "layer-count-additive-product-composition"), ("unscaled-electron-count", "exact-layer-per-held-carrier-ratio"), ("numerical-zero-standard-state", "structural-EmptyOne-standard-state"), ("selected-concentration-point", "complete-concentration-potential-series"), ("refitted-concentration-coefficient", "common-generator-successor-preserves-separation")),
}

NATIVE = {
    "002": '''from fractions import Fraction\ndef relation(subject,reference):\n if subject==reference:return ("coincident","EmptyOne")\n if subject>reference:return ("above",subject-reference)\n return ("below",reference-subject)\nnative={"above":relation(Fraction(5),Fraction(3))==("above",Fraction(2)),"below":relation(Fraction(1),Fraction(3))==("below",Fraction(2)),"coincident":relation(Fraction(3),Fraction(3))==("coincident","EmptyOne"),"common_successor":relation(Fraction(7),Fraction(5))==relation(Fraction(5),Fraction(3))}''',
    "003": '''from fractions import Fraction\ndef compose(first,second):\n fd,fm=first;sd,sm=second\n if fd==sd and fm==sm:return ("coincident","EmptyOne")\n if fd!=sd:return (sd,fm+sm)\n return (sd,sm-fm) if sm>fm else (fd,fm-sm)\ndef reverse(cell):return ({"above":"below","below":"above","coincident":"coincident"}[cell[0]],cell[1])\nopposed=compose(("below",Fraction(2)),("above",Fraction(3)));aligned=compose(("above",Fraction(2)),("above",Fraction(5)));native={"opposed_sum":opposed==("above",Fraction(5)),"aligned_take":aligned==("above",Fraction(3)),"coincident":compose(("above",Fraction(2)),("above",Fraction(2)))==("coincident","EmptyOne"),"reverse_magnitude":reverse(opposed)==("below",Fraction(5))}''',
    "004": '''from fractions import Fraction\ndef support(layers):\n value=1\n for _ in range(layers):value+=value\n return value\ndef shift(orientation,layers,carriers):return ("toward-reactants" if orientation=="product-heavy" else "toward-products",Fraction(layers,carriers))\nnative={"three_layers":support(3)==8,"product_direction":shift("product-heavy",3,2)==("toward-reactants",Fraction(3,2)),"reactant_direction":shift("reactant-heavy",2,2)==("toward-products",Fraction(1)),"product_composition":support(2)*support(3)==support(5),"common_successor":(5-2)==(6-3)}''',
}

def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists(): raise SystemExit(f"refusing to overwrite {path.relative_to(ROOT)}")
    path.write_text(content if isinstance(content, str) else json.dumps(content, indent=2, sort_keys=True) + "\n")

def main():
    for key, (spec, validator, obligation, label, source_id, measurement_count, identity, seal) in CONFIG.items():
        package = ROOT / "claims" / spec.claim_id
        experiment = ROOT / "experiments/chemistry" / spec.experiment_id
        registration = {"$schema": "../../governance/claim.schema.json", "branch": "chemistry", "candidate_grammar": {"boundary": spec.grammar_boundary, "completeness_certificate": COMPLETENESS_CERTIFICATES[spec.claim_id], "expected_cardinality": 256, "generator": spec.generation_rule}, "claim_id": spec.claim_id, "dependencies": list(spec.dependencies), "empirical_protocol": f"experiments/chemistry/{spec.experiment_id}/registration.json", "excluded_inputs": list(spec.exclusions), "provenance_classes": ["observational_derivation", "complete_external_record_reconstruction"], "registered_by": "Maria Smith", "registration_date": "2026-07-28", "required_controls": ["false_premise", "tampered_source", "tampered_artifact", "boundary"], "statement": spec.statement, "status": "registered", "title": spec.title}
        write(package / "registration.json", registration)
        write(package / "STATUS.md", f"# {spec.claim_id}\n\nStatus: `registered_pending_untouched_engine_admission`\n")
        write(package / "WHY_DERIVATION_CHECK.md", f"# Why {obligation.rsplit('-', 1)[-1]} requires a derivation check\n\nA conventional displayed value cannot by itself establish the {label}. The claim generates all 256 forms before comparison, retains every chemical carrier and condition, and opens the complete eight-page NIST record only after its own value-free seal. All fitted equations, smoothing, conventional signs, zero glyphs, corrections, uncertainties, adverse differences and absences remain external provenance and cannot select the native Fold law.\n")
        execution = f'''import sys\nfrom sft.chemistry.echem_potential_batch_v1 import AUTHORITIES, {"ELECTRODE_POTENTIAL_SPEC" if key=="002" else "CELL_POTENTIAL_SPEC" if key=="003" else "CONCENTRATION_POTENTIAL_SPEC"} as CLAIM_SPEC\nfrom sft.chemistry.echem_potential_validation_v1 import {validator}\nfrom sft.chemistry.generated_observational_law import GeneratedObservationalChemistryProgram\nfrom sft.engine import ExternalCommandValidator\nfrom sft.engine.source import build_source_manifest\nfrom sft.verification import ClaimExecution\ndef build_execution(root):\n fixed=("sft/chemistry/echem_potential_batch_v1.py","sft/chemistry/echem_potential_validation_v1.py","sft/chemistry/generated_law.py","sft/chemistry/generated_observational_law.py","sft/physics/generated_empirical_law.py",*(p for p,_ in AUTHORITIES),"claims/{spec.claim_id}/execution.py");files=tuple(dict.fromkeys(root/p for p in fixed if (root/p).is_file()));independent=root/"claims/{spec.claim_id}/independent_validator.py";return ClaimExecution(GeneratedObservationalChemistryProgram(CLAIM_SPEC,build_source_manifest(root,files).manifest_hash),ExternalCommandValidator("sft-chem-echem-{key}-independent-python/1",(sys.executable,str(independent)),independent.parent,(independent,)),files,{validator}(root))\n'''
        write(package / "execution.py", execution)
        domains = repr(DOMAINS[key])
        independent = f'''from itertools import product\nimport json,sys\nCLAIM_ID={spec.claim_id!r};DOMAINS={domains};SURVIVOR="__".join(x[1] for x in DOMAINS)\n{NATIVE[key]}\ndef main():\n s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={{x["candidate_id"]:x["survives"] for x in s["decisions"]}};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={{x:x==SURVIVOR for x in generated}} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({{"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}}}},sort_keys=True))\nif __name__=="__main__":main()\n'''
        write(package / "independent_validator.py", independent)
        experiment_registration = {"$schema": "../../../governance/experiment.schema.json", "absence_boundary": {"display_glyph": "0", "external_signed_and_zero_inscriptions_are_provenance_only": True, "native_proof_form": "held orientation, positive exact ratio and structural EmptyOne coincidence", "numerical_zero_admitted": False}, "claim_id": spec.claim_id, "evaluation_protocol": {"acceptance_condition": f"All {len(spec.target_rows)} preregistered comparisons, all eight NIST pages and all {measurement_count} registered measurement entries are retained.", f"all_{len(spec.target_rows)}_targets_required": True, "falsification_condition": spec.falsification_condition}, "evidence_mode": "observational_derivation_plus_complete_external_record_reconstruction", "experiment_id": spec.experiment_id, "external_measurement_sources": [{"complete_measurement_entries": measurement_count, "complete_pages": 8, "measurement_body": "National Bureau of Standards / National Institute of Standards and Technology", "source_id": source_id}], "frozen_relation": {"relation_hash": sha256_identity(spec.exact_result), "statement": spec.exact_result, "targets_did_not_select_survivor": True}, "identity_registry": identity, "prediction_seal": seal, "registered_by": "Maria Smith", "registration_date": "2026-07-28", "schema": "sft-v3-chemistry-experiment-registration/1", "status": "registered_sources_captured_postseal"}
        write(experiment / "registration.json", experiment_registration)
    print("scaffolded three separate ECHEM-002-004 claim packages")

if __name__ == "__main__": main()
