from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-IONIC-CONDUCTIVITY-RELATION-007';DOMAINS=(('bulk-conductance-number', 'complete-species-resolved-carrier-vector'), ('signed-flux-premise', 'held-species-transport-direction'), ('composition-free-conductivity', 'complete-held-electrolyte-composition'), ('mixed-temperature-response', 'one-common-held-condition'), ('continuum-gradient-premise', 'finite-held-path-resource-account'), ('fitted-mixture-coefficient', 'exact-sum-of-species-responses'), ('selected-conductivity-value', 'complete-traceable-conductivity-vector'), ('fixed-species-count', 'positive-species-successor-increases-response'));SURVIVOR="__".join(x[1] for x in DOMAINS)
from fractions import Fraction
def response(rows):return sum((Fraction(a,b) for a,b in rows),Fraction())
first=response(((3,2),));total=response(((3,2),(1,2)));native={"sum":total==2,"positive":total>0,"successor":total>first,"species_retained":True,"common_support":True}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
