from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ANALYTICAL-PRECISION-REPEATABILITY-002';DOMAINS=(('replicates-without-sample', 'held-sample-measurand-method'), ('mixed-condition-pool', 'same-held-repeatability-conditions'), ('summary-only', 'complete-positive-ordered-replicates'), ('signed-deviation-list', 'all-pair-positive-distance-or-EmptyOne'), ('fitted-dispersion-parameter', 'exact-extreme-distance-or-EmptyOne'), ('precision-equals-trueness', 'repeatability-class-held-separately'), ('outlier-deleted', 'all-adverse-replicates-retained'), ('summary-renormalized', 'successor-retains-and-recomputes-pairs'));SURVIVOR='held-sample-measurand-method__same-held-repeatability-conditions__complete-positive-ordered-replicates__all-pair-positive-distance-or-EmptyOne__exact-extreme-distance-or-EmptyOne__repeatability-class-held-separately__all-adverse-replicates-retained__successor-retains-and-recomputes-pairs'
from fractions import Fraction
def record(v):return (tuple(abs(v[i]-v[j]) if v[i]!=v[j] else None for i in range(len(v)) for j in range(i+1,len(v))),None if max(v)==min(v) else max(v)-min(v))
v=(Fraction(10),Fraction(101,10),Fraction(99,10));x=record(v)
native={"identity":True,"conditions":True,"support":len(v)==3,"comparison":len(x[0])==3,"spread":x[1]==Fraction(1,5),"class":True,"adverse":min(v)==Fraction(99,10),"successor":len(record(v+(Fraction(10),))[0])==6}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
