"""Implementation-distinct value-free KIN-012 reconstruction."""
from fractions import Fraction
from itertools import product
import json,sys
CLAIM='SFT-CHEM-KINETIC-ISOTOPE-EFFECT-RELATION-012'
DOMAINS=(('isotopologue-identities-collapsed-or-replaced-by-numerical-mass', 'two-distinct-held-isotopologue-identities'), ('different-truncated-or-answer-only-paths-compared', 'same-complete-reaction-path-and-condition'), ('imported-rate-law-continuum-time-or-fitted-rate', 'completed-events-per-exact-positive-observation-parts'), ('imported-KIE-mass-frequency-exponent-or-statistical-law', 'ordered-quotient-of-two-exact-positive-event-rates'), ('signed-difference-negative-or-zero-number', 'positive-ratio-plus-held-greater-less-or-equal-orientation'), ('selected-average-or-single-favorable-isotope-effect', 'complete-90-rate-ratio-3-decay-and-adverse-vector'), ('experimental-fitted-calculated-and-interpretive-records-mixed', 'experimental-vectors-separated-from-source-models-and-review-questions'), ('rate-ratio-value-workbook-or-target-readable-before-seal', 'value-free-71-record-identity-seal-and-depth-independent-pair-successor'))
SURVIVOR='two-distinct-held-isotopologue-identities__same-complete-reaction-path-and-condition__completed-events-per-exact-positive-observation-parts__ordered-quotient-of-two-exact-positive-event-rates__positive-ratio-plus-held-greater-less-or-equal-orientation__complete-90-rate-ratio-3-decay-and-adverse-vector__experimental-vectors-separated-from-source-models-and-review-questions__value-free-71-record-identity-seal-and-depth-independent-pair-successor'
def main():
 d=json.load(open(sys.argv[1])); generated=["__".join(row) for row in product(*DOMAINS)]; received=[row["candidate_id"] for row in d["census"]["candidates"]]; decisions={row["candidate_id"]:row["survives"] for row in d["decisions"]}
 roles=("entry","boundary","event","product"); numerator=("reaction","path","light",roles,"condition",Fraction(3,2)); denominator=("reaction","path","heavy",roles,"condition",Fraction(2,2)); normal=numerator[-1]/denominator[-1]; inverse=Fraction(2,2)/Fraction(3,2); equal=Fraction(2,2)/Fraction(2,2); orientations=("numerator-rate-greater" if normal>1 else "wrong","denominator-rate-greater" if inverse<1 else "wrong","rates-exactly-equal" if equal==1 else "wrong"); prior=(("pair-a",normal),); extended=prior+(("pair-b",inverse),)
 witnesses=(numerator[2]!=denominator[2] and numerator[0:2]==denominator[0:2] and numerator[3:5]==denominator[3:5] and normal==Fraction(3,2) and inverse==Fraction(2,3) and equal==Fraction(1,1) and orientations==("numerator-rate-greater","denominator-rate-greater","rates-exactly-equal") and extended[:len(prior)]==prior and len(extended)==len(prior)+1)
 passed=(d["claim_id"]==CLAIM and received==generated and len(generated)==256 and len(set(received))==256 and d["census"]["expected_cardinality"]==256 and decisions=={candidate:candidate==SURVIVOR for candidate in generated} and sum(decisions.values())==1 and d["closure"]["scope"]=="depth_independent" and d["closure"]["minimality_passed"] and d["closure"]["named_shape_uniqueness_passed"] and {row["kind"] for row in d["controls"]}=={"false_premise","tampered_source","tampered_artifact","boundary"} and all(row["passed"] for row in d["controls"]) and witnesses)
 print(json.dumps({"validated_seal_hash":d["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"two_distinct_held_isotope_identities_on_same_complete_path_reconstructed":witnesses,"exact_positive_ordered_rate_quotient_and_all_three_held_orientations_reconstructed":witnesses,"kinetic_isotope_pair_successor_preserves_prior_family":witnesses,"numerical_zero_negative_irrational_imaginary_signed_or_continuum_proof_value_used":False,"KIE_equation_numerical_mass_mass_frequency_transition_state_fit_exponent_statistical_weight_target_measurement_or_source_file_accessed":False}},sort_keys=True))
if __name__=="__main__":main()
