from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-EXACT-MOLECULAR-SIMILARITY-DISTINCTION-010'
DOMAINS=(('identifier-only-left', 'held-left-molecular-graph'), ('identifier-only-right', 'held-right-molecular-graph'), ('learned-descriptor-vector', 'all-registered-exact-graph-distinctions'), ('weighted-common-score', 'exact-shared-distinction-support'), ('symmetric-distance-only', 'separate-left-and-right-difference-support'), ('thresholded-same-molecule', 'exact-isomorphism-retained-separately'), ('fitted-ranking-weight', 'componentwise-exact-partial-order'), ('near-neighbour-conflation', 'every-unshared-distinction-preserved'))
SURVIVOR='held-left-molecular-graph__held-right-molecular-graph__all-registered-exact-graph-distinctions__exact-shared-distinction-support__separate-left-and-right-difference-support__exact-isomorphism-retained-separately__componentwise-exact-partial-order__every-unshared-distinction-preserved'
DIMENSION_KEYS=('left', 'right', 'features', 'intersection', 'differences', 'identity', 'ordering', 'adverse')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
