from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ELECTROANALYTICAL-RESPONSE-020'
DOMAINS=(('current-curve-without-system', 'held-analyte-electrode-cell-identity'), ('unordered-potential-points', 'held-ordered-applied-potential-path'), ('signed-current-as-native-number', 'held-oxidation-reduction-current-side'), ('floating-current', 'exact-positive-current-magnitude-or-EmptyOne'), ('peak-without-electrode-reaction', 'held-electrode-reaction-correspondence'), ('scan-rate-free-curve', 'held-scan-medium-reference-condition'), ('selected-peak-values', 'complete-trace-error-background-custody'), ('refitted-longer-scan', 'successor-appends-path-without-changing-prior-response'))
SURVIVOR='held-analyte-electrode-cell-identity__held-ordered-applied-potential-path__held-oxidation-reduction-current-side__exact-positive-current-magnitude-or-EmptyOne__held-electrode-reaction-correspondence__held-scan-medium-reference-condition__complete-trace-error-background-custody__successor-appends-path-without-changing-prior-response'
DIMENSION_KEYS=('system', 'path', 'orientation', 'response', 'reaction', 'condition', 'custody', 'extension')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
