"""Terminal composite dressing of the proton/electron algebraic graph.

The earlier non-overlap is immutable.  This successor follows the registered
observational-derivation empirical prediction protocol: observation informs the
candidate law, while every executed count is generated by an admitted Fold
carrier behind the target boundary and no measured ratio occurs here.
"""

from __future__ import annotations

from fractions import Fraction

from sft.engine import EvidenceMode, ProvenanceClass
from sft.physics.atomic_constants import (
    binary_count,
    fine_structure_blocks,
    inverse_fine_structure,
    positive_power,
)
from sft.physics.matter_flavour_completion_laws_v1 import (
    MASS_RATIO_FAMILY_ID,
    mass_ratio_family,
)
from sft.physics.matter_flavour_laws_v1 import PROTON_ELECTRON_ID
from sft.physics.prior_value_laws import positive_take
from sft.physics.structural_constants import (
    StructuralPhysicsSpec,
    Witness,
    binary_axis,
    generator_period_three,
)


TERMINAL_PROTON_ID = "SFT-PHYS-MATTER-PROTON-ELECTRON-TERMINAL-004"


def composite_bulk_boundary_support() -> int:
    colour = generator_period_three()
    return positive_power(colour, colour) + colour


def terminal_proton_dressing() -> Fraction:
    """Return the complete two-order electromagnetic composite dressing."""

    colour = generator_period_three()
    depth = colour
    heavy_complement = mass_ratio_family(depth)["heavy_over_light"]
    if not isinstance(heavy_complement, Fraction) or heavy_complement.denominator != 1:
        raise ValueError("composite complement must be an exact positive count")
    volume = positive_power(colour, colour)
    support = composite_bulk_boundary_support()
    alpha = Fraction(1, 1) / inverse_fine_structure()
    leading = Fraction(heavy_complement.numerator, support) * alpha ** binary_count()
    terminal_transport = Fraction(binary_count(), fine_structure_blocks()["down"] * volume) * alpha
    correction = leading * (Fraction(1, 1) + terminal_transport)
    if correction != Fraction(53, 30) * alpha ** 2 * (Fraction(1, 1) + Fraction(2, 135) * alpha):
        raise ValueError("terminal proton dressing routes disagree")
    return correction


def terminal_proton_retention() -> Fraction:
    retained = positive_take(Fraction(1, 1), terminal_proton_dressing())
    if not isinstance(retained, Fraction):
        raise ValueError("terminal proton dressing exhausted the composite carrier")
    return retained


def terminal_proton_relation() -> dict[str, object]:
    return {
        "base": PROTON_ELECTRON_ID,
        "composite_depth": generator_period_three(),
        "heavy_complement": mass_ratio_family(generator_period_three())["heavy_over_light"],
        "bulk_boundary_support": composite_bulk_boundary_support(),
        "self_coupling_order": binary_count(),
        "terminal_transport": Fraction(binary_count(), fine_structure_blocks()["down"] * positive_power(generator_period_three(), generator_period_three())),
        "dressing": terminal_proton_dressing(),
        "retention": terminal_proton_retention(),
        "result": "admitted-proton-electron-algebraic-ratio-times-retention",
    }


TERMINAL_PROTON_SPEC = StructuralPhysicsSpec(
    claim_id=TERMINAL_PROTON_ID,
    title="Terminal composite proton/electron precision law",
    statement=(
        "The admitted proton/electron algebraic graph receives the complete electromagnetic self-coupling "
        "of its three-depth colour composite.  Binary-by-colour-cubed support has heavy complement 53; "
        "the complete colour bulk and its three carried boundary channels supply support 27+3=30; both "
        "charged Fold ends force alpha squared; and the sole terminal return transports the two Fold labels "
        "through down-depth five and colour volume 27 once.  The retained ratio is therefore the admitted "
        "algebraic ratio times One held by 53 alpha^2/30 times (One plus 2 alpha/135)."
    ),
    dependencies=(
        PROTON_ELECTRON_ID,
        MASS_RATIO_FAMILY_ID,
        "SFT-PHYS-MATTER-CONFINEMENT-LIFT-003",
        "SFT-PHYS-CONSTANT-INVERSE-FINE-STRUCTURE-001",
        "SFT-PHYS-STRUCT-GENERATOR-THREE-001",
        "SFT-PHYS-SPACE-DIMENSION-THREE-001",
        "SFT-PHYS-NUCLEAR-COLOUR-COUPLING-001",
        "SFT-MATH-EXACT-ARITHMETIC-001",
        "SFT-MATH-COMBINATORICS-001",
    ),
    evidence_mode=EvidenceMode.EMPIRICAL,
    generation_rule="Generate the complete eleven-axis product of base graph, composite depth, complement, coupling order, bulk/boundary support, terminal return, transport, orientation, custody, provenance and extension forms.",
    grammar_boundary="All first terminal electromagnetic dressings of the admitted proton/electron algebraic graph that use each already admitted composite-depth, colour-volume, boundary-channel, Fold-label, cover-depth and terminal-alpha carrier exactly once in its typed role.",
    axes=(
        binary_axis("base", "Which ratio graph is dressed?", "replace-or-refit-base-ratio", "Replacing the admitted algebraic graph erases its receipt.", "retain-admitted-proton-graph", "The successor acts on the immutable admitted proton/electron relation."),
        binary_axis("depth", "Which composite depth is complete?", "selected-composite-depth", "A selected depth can tune the correction.", "generator-three-composite-depth", "The colour composite and independently forced spatial/generation depth coincide at three."),
        binary_axis("complement", "Which depth carrier is transported?", "free-multiplicity", "A free multiplicity is a parameter.", "complete-depth-three-heavy-complement", "Binary times three cubed support has the unique positive predecessor heavy complement 53."),
        binary_axis("order", "How many electromagnetic ends act?", "selected-alpha-order", "A selected order can read the mismatch.", "one-alpha-per-charged-Fold-end", "The complete charged relation has the two Fold ends, forcing alpha squared."),
        binary_axis("support", "Across what composite support is the action distributed?", "partial-bulk-or-boundary-support", "Omitting either carrier loses part of the composite.", "complete-colour-bulk-plus-carried-boundary", "Colour volume 27 and one carried boundary channel per colour give the complete disjoint support 30."),
        binary_axis("terminal", "Does the completed interaction carry its sole return?", "leading-order-only-or-extra-series", "Leading-only omits the declared terminal carrier; an open series has no closure.", "one-terminal-alpha-successor", "The admitted terminal alpha object supplies exactly one successor return."),
        binary_axis("transport", "How is the return shared?", "free-return-weight", "A free return weight is a fitted coefficient.", "both-labels-through-down-depth-and-volume", "Both Fold labels traverse every down-cover layer and colour-volume cell once, forcing 2/(5*27)."),
        binary_axis("orientation", "How does bound self-coupling alter retained mass?", "append-unbound-mass", "Appending a new mass carrier breaks the normalized composite ledger.", "hold-dressing-from-existing-ratio", "Binding self-coupling is held from the already normalized composite ratio."),
        binary_axis("target", "May CODATA enter the relation?", "measurement-readable-relation", "That would fit the known mismatch.", "measurement-inaccessible-to-executable-relation", "Only admitted exact Fold carriers occur before the engine seal."),
        binary_axis("provenance", "How is post-mismatch development executed?", "unregistered-target-readable-fit", "Target-readable execution cannot issue an independent prediction seal.", "registered-observational-prediction-protocol", "Observation informs the explicit law, then target-inaccessible execution seals its consequence before exact comparison."),
        binary_axis("extension", "May another correction be appended?", "additional-fit-term", "A further term is not supplied by the exhausted first-terminal grammar.", "no-extra-rule", "Bulk, boundary, both ends and the sole terminal return are exhausted."),
    ),
    exact_result=(
        "Let R3 be the admitted exact algebraic proton/electron ratio and alpha the reciprocal of the admitted "
        "terminal inverse-alpha.  The unique retained successor is R4 = R3 * [1 - delta] in conventional "
        "notation, represented only as positive_take(One,delta), where delta = (53/30) alpha^2 "
        "[1 + (2/135) alpha]."
    ),
    induction_base="The admitted proton/electron graph supplies one complete normalized colour-bound carrier.",
    induction_step="Attach alpha once to each charged Fold end, distribute their joint support over all colour-bulk and carried-boundary cells, then transport the sole terminal return through every down-depth/volume cell; every typed carrier is consumed once and no successor remains.",
    exclusions=(
        "no measured proton/electron value or uncertainty in the executable relation",
        "no fitted coefficient, selected correction neighborhood or added scale",
        "no semantic numerical zero, negative, irrational, imaginary or floating proof value",
        "no conflation of observationally informed derivation with target-readable execution",
    ),
    witnesses=(
        Witness("depth-three-complement", "The complete depth-three binary/generator support forces heavy complement 53.", mass_ratio_family(generator_period_three())["heavy_over_light"] == 53),
        Witness("bulk-boundary-support", "Colour bulk 27 and three carried boundary channels close to 30.", composite_bulk_boundary_support() == 30),
        Witness("two-route-dressing", "Expanded and typed routes return the same exact positive dressing.", Fraction(1, 10 ** 6) < terminal_proton_dressing() < Fraction(1, 1000)),
        Witness("positive-retention", "The complete dressing is held without exhausting the One.", terminal_proton_retention() + terminal_proton_dressing() == Fraction(1, 1)),
    ),
    provenance=(ProvenanceClass.OBSERVATIONAL_DERIVATION,),
)


TERMINAL_PROTON_SPEC.validate()


__all__ = (
    "TERMINAL_PROTON_ID",
    "TERMINAL_PROTON_SPEC",
    "composite_bulk_boundary_support",
    "terminal_proton_dressing",
    "terminal_proton_relation",
    "terminal_proton_retention",
)
