"""Post-seal independent Cambridge comparison for orbital dimension stability."""
from __future__ import annotations
from fractions import Fraction
import json,platform
from pathlib import Path
from sft.claim_evidence import CapabilityClosedFoldInterpreter,CrossPlatformCustodyExchange,FoldWord,HostilePackageAuditor,TargetVault,fold_program_from_mapping,snapshot_protected_tree,target_identity_from_release
from sft.engine import EmpiricalValidation,seal_isolation_certificate,seal_target_custody_certificate,unsealed_isolation_certificate,unsealed_target_custody_certificate
from sft.engine.canonical import sha256_identity
from sft.engine.empirical import BlindExperimentBoundary,PredictionEnvelope
from sft.engine.exact import HeldLabel
from sft.engine.source import hash_file
from sft.physics.orbital_dimension_stability_terminal_law_v1 import CLAIM_ID,EXPERIMENT_ID,dimension_certificate,displaced_magnitudes,orbital_stability_class
SOURCE_ID="D9F-EXTERNAL-ORBITAL-DIMENSION-STABILITY";SOURCE_IDS=(SOURCE_ID,);SOURCE_RECORD_PATH="experiments/external_sources/physics/snapshots/orbital-dimension-stability-source-record.json";SOURCE_RECORD_HASH="sha256:f8fca45480808d3863b7c528e811c1563c1c988d9289248f1f39409f05ebbacb";CAMBRIDGE_PATH="experiments/external_sources/physics/snapshots/cambridge-central-forces-chapter6.pdf";CAMBRIDGE_HASH="sha256:59de9d143492b1fdf2f1f0b96c9653d861822081f6ee57c7689b943e31210024";TONG_PATH="experiments/external_sources/physics/snapshots/tong-central-forces-four.pdf";TONG_HASH="sha256:2d999345dd33fce016498a1ed2dc5085f8e7513530f75dfeb94dfbff05aad44e";TARGET_IDS=("D9F-WITHHELD-ORBITAL-STABILITY-RECORD",)
FALSIFICATION_CONDITION="Reject if either Cambridge source or the source record changes; if any force-power, balance, perturbation, stability, dimension, marginal, unstable-family, potential or effective-potential row is omitted; if the exact positive-magnitude census differs; if dimension one is silently admitted; if a signed force, negative exponent, measured fit or free correction enters proof; or if targets enter before sealing."
def source_hashes()->dict[str,str]:return {SOURCE_RECORD_PATH:SOURCE_RECORD_HASH,CAMBRIDGE_PATH:CAMBRIDGE_HASH,TONG_PATH:TONG_HASH}
def authoritative_record(root:Path)->dict[str,object]:
 for relative,expected in source_hashes().items():
  if hash_file(root/relative)!=expected:raise ValueError(f"D9f source changed: {relative}")
 record=json.loads((root/SOURCE_RECORD_PATH).read_text());target=record.get("registered_target",{});required=("gravity_dimension_domain","gravity_force_power","centrifugal_force_power","circular_balance","perturbation_direction","external_force_stability_criterion","external_dimension_boundary","stable_dimensions","marginal_dimension","unstable_dimension_family","potential_power_boundary","effective_potential_condition","higher-dimensional-topology_assumed","measured_parameter_fitted")
 if record.get("source_id")!=SOURCE_ID or len(record.get("snapshots",()))!=2 or tuple(target)!=required or target["stable_dimensions"]!=["2","3"] or target["marginal_dimension"]!="4" or target["higher-dimensional-topology_assumed"] is not False or target["measured_parameter_fitted"] is not False:raise ValueError("D9f record changed")
 custody=record.get("custody",{});
 if not all((custody.get("formal_claim_contains_external_target_values") is False,custody.get("target_inaccessible_during_prediction_execution") is True,custody.get("prediction_sealed_before_target_release_within_run") is True,custody.get("all_registered_rows_retained") is True,custody.get("measurements_select_formal_survivor") is False)):raise ValueError("D9f custody changed")
 return record
def exact_measurement_analysis(target:dict[str,object])->dict[str,object]:
 ratios=(Fraction(3,2),Fraction(2,1),Fraction(5,2));rows=tuple({"dimension":d,"classes":tuple(orbital_stability_class(d,q) for q in ratios),"magnitudes":tuple(displaced_magnitudes(d,q) for q in ratios)} for d in range(2,13));stable=tuple(r["dimension"] for r in rows if set(r["classes"])=={"stable-restoring"});marginal=tuple(r["dimension"] for r in rows if set(r["classes"])=={"marginal"});unstable=tuple(r["dimension"] for r in rows if set(r["classes"])=={"unstable-nonrestoring"});return {"ratios":ratios,"rows":rows,"stable_dimensions":stable,"marginal_dimensions":marginal,"unstable_dimensions":unstable,"external_stable_match":stable==tuple(int(v) for v in target["stable_dimensions"]),"external_marginal_match":marginal==(int(target["marginal_dimension"]),),"unstable_family_match":unstable==tuple(range(5,13)) and target["unstable_dimension_family"]=="every-positive-whole-N-at-least-five","all_target_rows_retained":len(target)==14,"negative_or_fitted_proof_value":False}
def formal_prediction_inputs()->dict[str,object]:return {"dimension_relation":HeldLabel("dimension-domain","complete-positive-wholes-at-least-two"),"gravity_relation":HeldLabel("gravity-dilution","positive-denominator-q-to-d-minus-One"),"centrifugal_relation":HeldLabel("centrifugal-dilution","positive-denominator-q-cubed"),"comparison_relation":HeldLabel("outward-comparison","denominator-order-only"),"partition_relation":HeldLabel("stability-partition","stable-two-three-marginal-four-unstable-above"),"scope_relation":HeldLabel("orbital-scope","circular-central-force-positive-magnitudes")}
def prediction_program_document()->dict[str,object]:
 keys=tuple(formal_prediction_inputs());instructions=[{"opcode":"input","destination":k,"arguments":[k]} for k in keys];instructions.extend(({"opcode":"word","destination":"prediction","arguments":list(keys)},{"opcode":"emit","destination":"","arguments":["prediction"]}));return {"schema":"sft-v3-fold-program/1","program_id":EXPERIMENT_ID+"-exact-prediction","instructions":instructions}
def experiment_registration_record()->dict[str,object]:return {"schema":"sft-v3-orbital-dimension-stability-experiment/1","claim_id":CLAIM_ID,"experiment_id":EXPERIMENT_ID,"registered_by":"Maria Smith","evidence_mode":"observational_derivation","protocol":"observational-data-informed_target-inaccessible_sealed-comparison","frozen_relation":"Positive denominator ordering between q^(d-1) gravity and q^3 centrifugal response uniquely partitions all orbital dimensions.","prediction_program":prediction_program_document(),"withheld_target_ids":TARGET_IDS,"source_id":SOURCE_ID,"source_ids":SOURCE_IDS,"source_record_path":SOURCE_RECORD_PATH,"source_record_hash":SOURCE_RECORD_HASH,"source_hashes":source_hashes(),"row_retention_policy":"both complete Cambridge snapshots and all fourteen registered mathematical comparison rows","target_access_policy":"capability-closed prediction; release only after matching seal","comparison_protocol":"independent exact-rational all-dimension census at three outward ratios with complete external criterion comparison","falsification_condition":FALSIFICATION_CONDITION}
def output_mapping(output:object,keys:tuple[str,...])->dict[str,object]:
 if not isinstance(output,FoldWord) or len(output.cells)!=len(keys):raise ValueError("D9f prediction shape changed")
 return dict(zip(keys,output.cells))
class OrbitalDimensionStabilityValidator:
 def __init__(self,root:Path):self.root=root.resolve()
 def validate(self,sealed)->EmpiricalValidation:
  if sealed.claim_id!=CLAIM_ID:raise ValueError("wrong D9f seal")
  registration=experiment_registration_record();rh=sha256_identity(registration);doc=prediction_program_document();program=fold_program_from_mapping(doc);inputs=formal_prediction_inputs();keys=tuple(inputs);envelope=PredictionEnvelope(EXPERIMENT_ID,{k:sha256_identity(v) for k,v in inputs.items()},TARGET_IDS,sha256_identity((sealed.seal_hash,registration["frozen_relation"])),rh);targets={TARGET_IDS[0]:authoritative_record(self.root)["registered_target"]};vault=TargetVault(experiment_id=EXPERIMENT_ID,custodian_id=EXPERIMENT_ID+"-external-target-custodian",targets=targets,custody_nonce=sha256_identity((rh,SOURCE_RECORD_HASH,source_hashes())),expected_envelope_hash=sha256_identity(envelope));before=snapshot_protected_tree(self.root);execution=CapabilityClosedFoldInterpreter().execute(program,inputs);boundary=BlindExperimentBoundary(envelope);seal=boundary.seal_prediction(execution.output,execution.trace);after=snapshot_protected_tree(self.root);audited,audit=HostilePackageAuditor().audit_program_document(doc,before,after)
  if sha256_identity(audited)!=execution.program_hash or not audit.passed:raise ValueError("D9f hostile audit failed")
  release=vault.release(seal);CrossPlatformCustodyExchange.verify(vault.commitment,release,seal);_,context=boundary.measurement_context(release.targets)
  if output_mapping(execution.output,keys)!=inputs:raise ValueError("D9f prediction changed")
  a=exact_measurement_analysis(context[TARGET_IDS[0]]);c=dimension_certificate();formal=c["stable_dimensions"]==(2,3) and c["marginal_dimensions"]==(4,) and not c["negative_exponent_required"];all_rows=a["all_target_rows_retained"] and len(a["rows"])==11 and all(len(r["classes"])==3 for r in a["rows"]);controls=all((a["stable_dimensions"]==(2,3),a["marginal_dimensions"]==(4,),a["unstable_dimensions"]==tuple(range(5,13)),a["external_stable_match"],a["external_marginal_match"],a["unstable_family_match"],a["negative_or_fitted_proof_value"] is False));passed=all((formal,all_rows,controls));ih=sha256_identity(CapabilityClosedFoldInterpreter.interpreter_id);ch=sha256_identity(("exact-orbital-dimension-stability-comparator/1",rh,FALSIFICATION_CONDITION));isolation=seal_isolation_certificate(unsealed_isolation_certificate(executor_id=EXPERIMENT_ID+"-prediction-executor",host_platform=platform.system() or "registered-host",python_implementation=platform.python_implementation(),interpreter_hash=ih,program_hash=execution.program_hash,input_manifest_hash=execution.input_manifest_hash,registered_target_identity_hash=vault.commitment.target_identity_hash,comparison_implementation_identity_hash=ch,prediction_seal_hash=seal.seal_hash,output_hash=execution.output_hash,trace_hash=execution.trace_hash));ti=target_identity_from_release(release);custody=seal_target_custody_certificate(unsealed_target_custody_certificate(custodian_id=release.custodian_id,experiment_registration_hash=rh,registered_target_identity_hash=ti,prediction_seal_hash=seal.seal_hash,target_release_manifest_hash=release.release_hash));payload={"seal":sealed.seal_hash,"prediction_seal":seal.seal_hash,"sources":source_hashes(),"target":ti,"analysis":a,"formal":formal,"rows":all_rows,"controls":controls};measurements=("Both Cambridge derivations are byte-locked and opened only after the V3 prediction seal.","The independent census retains dimensions two through twelve at outward ratios three-halves, two and five-halves.","Dimensions two and three are restoring at every registered ratio; dimension four is exactly marginal; every tested dimension from five through twelve is nonrestoring.","The successor proof extends the unstable result to every higher positive whole dimension because each dimension successor multiplies only the gravity denominator by q greater than One.","The external inverse-(N-1) force result, N<4 boundary, potential-power boundary and strict-minimum criterion all match without fitting.","No signed force, negative exponent, irrational, measured parameter or correction enters the Fold proof.");return EmpiricalValidation(sealed.seal_hash,rh,isolation,custody,True,True,all_rows,SOURCE_IDS,measurements,sha256_identity(payload),FALSIFICATION_CONDITION,passed)
__all__=("OrbitalDimensionStabilityValidator","authoritative_record","exact_measurement_analysis","experiment_registration_record")
