"""Depth-independent exact Fold gravitational self-source fixed point."""
from __future__ import annotations
from dataclasses import dataclass,replace
from fractions import Fraction
from functools import lru_cache
from itertools import product
from typing import Sequence
from sft.engine import Candidate,CandidateCensus,CandidateDecision,ClaimRegistration,ClosureEvidence,ClosureScope,ControlKind,ControlResult,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.engine.canonical import sha256_identity
CLAIM_ID="SFT-PHYS-POST-NEWTONIAN-FIXED-POINT-TERMINAL-009";EXPERIMENT_ID="SFT-EXP-PHYS-POST-NEWTONIAN-FIXED-POINT-TERMINAL-009"
def structural_values()->dict[str,Fraction]:
 binary=2;colour=3;matter=Fraction(binary*colour+1,binary**4);coupling=Fraction(1,binary);fixed=coupling*coupling;return {"matter":matter,"coupling":coupling,"fixed":fixed}
def self_source_successor(field:Fraction)->Fraction:
 if not isinstance(field,Fraction) or not 0<field<=1:raise ValueError("field must be an exact positive Fold part")
 v=structural_values();return v["coupling"]*(v["matter"]+field*field)
def fixed_point_candidates()->tuple[Fraction,...]:
 return tuple(Fraction(n,16) for n in range(1,17) if Fraction(n,16)==self_source_successor(Fraction(n,16))) + tuple(Fraction(n,16) for n in range(17,29) if Fraction(n,16)==Fraction(1,2)*(Fraction(7,16)+Fraction(n,16)**2))
def admissible_fixed_points()->tuple[Fraction,...]:return tuple(v for v in fixed_point_candidates() if v<=1)
def iterate(depth:int)->tuple[Fraction,...]:
 if isinstance(depth,bool) or not isinstance(depth,int) or depth<1:raise ValueError("positive depth required")
 v=structural_values();values=[v["coupling"]*v["matter"]]
 for _ in range(depth):values.append(self_source_successor(values[-1]))
 return tuple(values)
def convergence_certificate(depth:int=8)->dict[str,object]:
 values=iterate(depth);fixed=structural_values()["fixed"];errors=tuple(fixed-v for v in values);corrections=tuple(values[i+1]-values[i] for i in range(len(values)-1));error_factors=tuple(errors[i+1]/errors[i] for i in range(len(errors)-1));correction_factors=tuple(corrections[i+1]/corrections[i] for i in range(len(corrections)-1));return {"structural":structural_values(),"fixed_candidates":fixed_point_candidates(),"admissible_fixed_points":admissible_fixed_points(),"values":values,"errors":errors,"corrections":corrections,"error_factors":error_factors,"correction_factors":correction_factors,"values_increase_below_fixed":all(values[i]<values[i+1]<fixed for i in range(len(values)-1)),"errors_strictly_shrink":all(errors[i+1]<errors[i] for i in range(len(errors)-1)),"corrections_strictly_shrink":all(corrections[i+1]<corrections[i] for i in range(len(corrections)-1)),"all_factors_below_quarter":all(f<Fraction(1,4) for f in error_factors+correction_factors),"general_error_identity":"e-next=e-times-(fixed-plus-current)-over-two","general_correction_identity":"c-next=c-times-(next-plus-current)-over-two"}
@dataclass(frozen=True)
class CandidateForm:
 source_construction:str;coupling:str;nonlinear_action:str;fixed_point:str;convergence_law:str;scope:str;target_boundary:str;extension:str
 @property
 def candidate_id(self)->str:return "__".join((self.source_construction,self.coupling,self.nonlinear_action,self.fixed_point,self.convergence_law,self.scope,self.target_boundary,self.extension))
SOURCES=("binary-colour-source-seven-sixteenths","free-matter-source","target-assigned-source");COUPLINGS=("forced-half-One","free-coupling","target-assigned-coupling");ACTIONS=("matter-plus-field-square","linear-no-self-source","target-assigned-correction");FIXED_POINTS=("unique-admissible-quarter-One","select-larger-root","measurement-selected-fixed-point");CONVERGENCES=("exact-error-and-correction-contraction","finite-prefix-only","assumed-series-convergence");SCOPES=("exact-Fold-scalar-self-source-channel","universal-general-relativity-convergence","historical-sequence-only");TARGET_BOUNDARIES=("sealed-before-observation-release","observation-readable-before-seal");EXTENSIONS=("empty-extension","free-convergence-correction")
GENERATION_RULE="Generate the complete product of every structural, free or target-assigned source; every forced, free or measured coupling; every quadratic, linear or target-assigned action; every admissible, larger-root or measured fixed point; every exact, finite-only or assumed convergence law; every Fold-scalar, universal-GR or historical-only scope; both target custody states; and both extension states."
GRAMMAR_BOUNDARY="The exact self-source scalar channel generated by binary support, generator-three colour, half-One coupling, positive Fold parts, quadratic field-energy feedback and every positive iteration depth. The theorem does not claim numerical convergence of every post-Newtonian expansion for every physical source."
def candidate_forms()->tuple[CandidateForm,...]:return tuple(CandidateForm(*v) for v in product(SOURCES,COUPLINGS,ACTIONS,FIXED_POINTS,CONVERGENCES,SCOPES,TARGET_BOUNDARIES,EXTENSIONS))
@lru_cache(maxsize=1)
def axis_facts()->dict[str,dict[str,bool]]:
 c=convergence_certificate();exact=c["admissible_fixed_points"]==(Fraction(1,4),) and c["values_increase_below_fixed"] and c["errors_strictly_shrink"] and c["corrections_strictly_shrink"] and c["all_factors_below_quarter"]
 return {"source":{n:v for n,v in zip(SOURCES,(exact,False,False))},"coupling":{n:v for n,v in zip(COUPLINGS,(exact,False,False))},"action":{n:v for n,v in zip(ACTIONS,(exact,False,False))},"fixed":{n:v for n,v in zip(FIXED_POINTS,(exact,False,False))},"convergence":{n:v for n,v in zip(CONVERGENCES,(exact,False,False))},"scope":{n:v for n,v in zip(SCOPES,(exact,False,False))},"target":{TARGET_BOUNDARIES[0]:True,TARGET_BOUNDARIES[1]:False},"extension":{EXTENSIONS[0]:True,EXTENSIONS[1]:False}}
def candidate_facts(f:CandidateForm)->dict[str,bool]:
 a=axis_facts();return {"source":a["source"][f.source_construction],"coupling":a["coupling"][f.coupling],"action":a["action"][f.nonlinear_action],"fixed":a["fixed"][f.fixed_point],"convergence":a["convergence"][f.convergence_law],"scope":a["scope"][f.scope],"target":a["target"][f.target_boundary],"extension":a["extension"][f.extension]}
def form_survives(f:CandidateForm)->bool:return all(candidate_facts(f).values())
class PostNewtonianFixedPointProgram:
 def __init__(self,source_hash:str):self.source_hash=source_hash;self._forms=candidate_forms();self._by_id={f.candidate_id:f for f in self._forms}
 @property
 def registration(self)->ClaimRegistration:return ClaimRegistration(CLAIM_ID,"Exact gravitational self-source fixed point and correction contraction","physics","Binary support and generator-three colour force matter source seven-sixteenths; half-One is the coupling; quadratic field energy supplies self-source feedback. The exact map f-next=half-One times (seven-sixteenths plus f squared) has one admissible Fold-part fixed point, quarter-One. Starting from the linear field seven-thirty-seconds, every iterate remains below and approaches quarter-One; both its positive gap and each added correction contract at every successor by an exact factor below quarter-One. This depth-independent Fold theorem corresponds post-seal to weak-field post-Newtonian iteration without claiming universal numerical convergence outside its registered scalar channel.",EvidenceMode.EMPIRICAL,(ROOT_THEOREM,),("SFT-PHYS-GRAVITY-NONLINEAR-SELF-SOURCE-003","SFT-PHYS-STRUCT-GENERATOR-THREE-001","SFT-FOUNDATION-HALF-ONE-001","SFT-MATH-SELF-SIMILAR-CONVERGENCE-002","SFT-MATH-EXACT-ARITHMETIC-001","SFT-MATH-DYNAMICAL-SYSTEMS-001","SFT-FOUNDATION-MEASURED-VALUE-BOUNDARY-001","SFT-PHYS-MEAS-TARGET-CUSTODY-001"),(),(),(ProvenanceClass.FORWARD_FORCING,ProvenanceClass.OBSERVATIONAL_DERIVATION),self.source_hash)
 def generate_candidates(self)->CandidateCensus:
  cs=tuple(Candidate(f.candidate_id,str(f),sha256_identity({"rule":GENERATION_RULE,"form":f,"facts":candidate_facts(f)})) for f in self._forms);return CandidateCensus(GENERATION_RULE,GRAMMAR_BOUNDARY,len(cs),sha256_identity({"axis_cardinalities":(3,3,3,3,3,3,2,2),"candidate_ids":tuple(x.candidate_id for x in cs)}),cs)
 def decide_candidate(self,c:Candidate)->CandidateDecision:
  facts=candidate_facts(self._by_id[c.candidate_id]);s=all(facts.values());fails=tuple(k for k,v in facts.items() if not v);reason="Structural source, half-One coupling and quadratic feedback uniquely force the admissible quarter-One fixed point and depth-independent contraction." if s else "Rejected by computed Fold predicates: "+", ".join(fails)+".";return CandidateDecision(c.candidate_id,s,reason,sha256_identity({"trace":c.trace_hash,"facts":facts,"survives":s,"reason":reason}))
 def closure_evidence(self,ds:Sequence[CandidateDecision])->ClosureEvidence:
  ss=tuple(x.candidate_id for x in ds if x.survives);c=convergence_certificate();closed=len(ss)==1 and c["admissible_fixed_points"]==(Fraction(1,4),) and c["errors_strictly_shrink"] and c["corrections_strictly_shrink"] and c["all_factors_below_quarter"];return ClosureEvidence(ClosureScope.DEPTH_INDEPENDENT,GRAMMAR_BOUNDARY,closed,closed and len(set(ss))==1,sha256_identity({"certificate":c,"decisions":tuple(ds),"survivors":ss}),sha256_identity({"base":"linear field is seven-thirty-seconds below quarter-One","successor":"exact difference of squares makes each next error and correction the prior one times a positive factor below quarter-One","larger_fixed_candidate":"seven-quarters lies outside Fold-part domain","universal_PN_convergence_not_claimed":True,"targets_absent":True}))
 def run_controls(self)->tuple[ControlResult,...]:
  ss=tuple(f for f in self._forms if form_survives(f));
  if len(ss)!=1:raise ValueError("controls require one survivor")
  f=ss[0];records=((ControlKind.FALSE_PREMISE,Fraction(7,4) in fixed_point_candidates() and Fraction(7,4) not in admissible_fixed_points(),"Reject larger algebraic root as a Fold part.","Seven-quarters exceeds the One."),(ControlKind.TAMPERED_SOURCE,sha256_identity({"changed":self.source_hash})!=self.source_hash,"Reject changed source identity.","Identity differs."),(ControlKind.TAMPERED_ARTIFACT,len({x.candidate_id for x in self._forms})==len(self._forms),"Reject duplicate candidates.","All identities unique."),(ControlKind.BOUNDARY,not form_survives(replace(f,scope=SCOPES[1])) and not form_survives(replace(f,target_boundary=TARGET_BOUNDARIES[1])) and not form_survives(replace(f,extension=EXTENSIONS[1])),"Reject universalization, target access and correction.","Only scalar scope, sealed target and empty extension survive."));return tuple(ControlResult(k,p,e,o,sha256_identity({"kind":k,"passed":p,"expected":e,"observed":o})) for k,p,e,o in records)
__all__=("CLAIM_ID","EXPERIMENT_ID","PostNewtonianFixedPointProgram","admissible_fixed_points","candidate_forms","convergence_certificate","fixed_point_candidates","form_survives","iterate","self_source_successor","structural_values")
