"""Exact static spherical exterior coefficient, flux and clock law."""
from __future__ import annotations
from dataclasses import dataclass,replace
from fractions import Fraction
from functools import lru_cache
from itertools import product
from typing import Sequence
from sft.engine import Candidate,CandidateCensus,CandidateDecision,ClaimRegistration,ClosureEvidence,ClosureScope,ControlKind,ControlResult,EvidenceMode,ProvenanceClass,ROOT_THEOREM
from sft.engine.canonical import sha256_identity
CLAIM_ID="SFT-PHYS-STATIC-EXTERIOR-CLOCK-TERMINAL-011";EXPERIMENT_ID="SFT-EXP-PHYS-STATIC-EXTERIOR-CLOCK-TERMINAL-011"
ONE=Fraction(1,1);BINARY=2
def positive_remainder(whole:Fraction,taken:Fraction)->Fraction|tuple[()]:
 if not isinstance(whole,Fraction) or not isinstance(taken,Fraction) or not 0<taken<=whole:raise ValueError("exact positive taken part required")
 if taken==whole:return ()
 remainder=whole-taken
 if remainder<=0:raise ValueError("remainder must be positive or empty")
 return remainder
def generated_horizon_radius(mass:Fraction)->Fraction:
 if not isinstance(mass,Fraction) or not 0<mass<=Fraction(1,BINARY):raise ValueError("mass must retain a positive doubled radius no greater than the One")
 return BINARY*mass
def exterior_state(mass:Fraction,radius:Fraction)->dict[str,object]:
 horizon=generated_horizon_radius(mass)
 if not isinstance(radius,Fraction) or radius<horizon:raise ValueError("static exterior chart requires radius at or outside its generated boundary")
 well=horizon/radius;coefficient=positive_remainder(ONE,well);field=horizon/(radius*radius);flux=field*radius*radius
 if flux!=horizon or well*radius!=horizon:raise ValueError("exterior source ledger failed")
 if coefficient==():return {"mass":mass,"horizon":horizon,"radius":radius,"well_share":well,"coefficient":(),"clock_record":(),"field":field,"flux":flux,"region":"boundary"}
 if coefficient+well!=ONE:raise ValueError("positive complement failed")
 return {"mass":mass,"horizon":horizon,"radius":radius,"well_share":well,"coefficient":coefficient,"field":field,"flux":flux,"region":"exterior"}
def exact_clock_pair()->dict[str,object]:
 mass=Fraction(1,4);near=exterior_state(mass,Fraction(8,7));far=exterior_state(mass,Fraction(25,18));near_rate=Fraction(3,4);far_rate=Fraction(4,5)
 if near["coefficient"]!=near_rate*near_rate or far["coefficient"]!=far_rate*far_rate:raise ValueError("exact rational clock carriers changed")
 return {"mass":mass,"near":near,"far":far,"near_rate":near_rate,"far_rate":far_rate,"far_over_near_rate":far_rate/near_rate,"far_clock_faster":far_rate>near_rate}
def exterior_certificate(depth:int=10)->dict[str,object]:
 if isinstance(depth,bool) or not isinstance(depth,int) or depth<2:raise ValueError("at least binary positive successor depth required")
 mass=Fraction(1,4);horizon=generated_horizon_radius(mass);boundary=exterior_state(mass,horizon);rows=tuple(exterior_state(mass,horizon*(BINARY**step)) for step in range(1,depth+1));clock=exact_clock_pair()
 return {"mass":mass,"horizon":horizon,"boundary":boundary,"rows":rows,"all_exterior_coefficients_positive":all(isinstance(row["coefficient"],Fraction) and row["coefficient"]>0 for row in rows),"all_fluxes_equal_horizon":all(row["flux"]==horizon for row in rows),"all_well_radius_products_equal_horizon":all(row["well_share"]*row["radius"]==horizon for row in rows),"all_complements_complete_One":all(row["coefficient"]+row["well_share"]==ONE for row in rows),"well_halves_each_successor":all(rows[i+1]["well_share"]*BINARY==rows[i]["well_share"] for i in range(len(rows)-1)),"field_quarters_each_successor":all(rows[i+1]["field"]*(BINARY**2)==rows[i]["field"] for i in range(len(rows)-1)),"coefficient_increases_each_successor":all(rows[i+1]["coefficient"]>rows[i]["coefficient"] for i in range(len(rows)-1)),"horizon_clock_record_empty":boundary["clock_record"]==(),"exact_clock_pair":clock,"weak_field_successor":"At every positive depth, well share is One over binary-to-depth, the coefficient is its positive complement from the One, and no completed infinity is invoked.","general_flux_identity":"field times radius paired with radius equals generated horizon radius","general_coefficient_identity":"coefficient paired with horizon-radius over radius completes the One","physical_unit_conversion_not_formal_input":True,"negative_zero_irrational_or_imaginary_proof_scalar_used":False}
@dataclass(frozen=True)
class CandidateForm:
 horizon_normalization:str;field_law:str;well_law:str;coefficient_law:str;clock_law:str;boundary_law:str;target_boundary:str;extension:str
 @property
 def candidate_id(self)->str:return "__".join((self.horizon_normalization,self.field_law,self.well_law,self.coefficient_law,self.clock_law,self.boundary_law,self.target_boundary,self.extension))
HORIZON_NORMALIZATIONS=("twice-mass-generated-horizon","free-radius-scale","target-assigned-horizon");FIELD_LAWS=("inverse-square-with-conserved-horizon-flux","free-field-power","target-assigned-field");WELL_LAWS=("radius-times-field-gives-horizon-over-radius-share","independent-potential-profile","target-assigned-well");COEFFICIENT_LAWS=("positive-One-complement-of-well","signed-subtraction-import","target-assigned-coefficient");CLOCK_LAWS=("exact-square-carriers-and-empty-horizon-record","unrestricted-irrational-root","target-assigned-clock");BOUNDARY_LAWS=("finite-successor-flat-boundary-and-vacuum","completed-infinity-or-interior-extension","target-assigned-boundary");TARGET_BOUNDARIES=("sealed-before-observation-release","observation-readable-before-seal");EXTENSIONS=("empty-extension","free-exterior-correction")
GENERATION_RULE="Generate the complete product of every generated, free or target-assigned horizon normalization; every conserved inverse-square, free-power or target-assigned field; every radius-derived, independent or target-assigned well; every positive complement, signed import or target-assigned coefficient; every exact-square, unrestricted-root or target-assigned clock; every finite-successor, completed/inward or target-assigned boundary; both target custody states; and both extension states."
GRAMMAR_BOUNDARY="Every exact positive mass whose generated doubled boundary does not exceed the One, every exact radius at or outside that boundary, and every finite outward binary successor. The coefficient theorem covers every exact exterior radius; numerical clock rates are evaluated only on generated exact-square carriers, and the boundary is an empty clock record rather than a numerical zero."
def candidate_forms()->tuple[CandidateForm,...]:return tuple(CandidateForm(*values) for values in product(HORIZON_NORMALIZATIONS,FIELD_LAWS,WELL_LAWS,COEFFICIENT_LAWS,CLOCK_LAWS,BOUNDARY_LAWS,TARGET_BOUNDARIES,EXTENSIONS))
@lru_cache(maxsize=1)
def axis_facts()->dict[str,dict[str,bool]]:
 c=exterior_certificate();exact=c["horizon"]==Fraction(1,2) and c["all_exterior_coefficients_positive"] and c["all_fluxes_equal_horizon"] and c["all_well_radius_products_equal_horizon"] and c["all_complements_complete_One"] and c["well_halves_each_successor"] and c["field_quarters_each_successor"] and c["coefficient_increases_each_successor"] and c["horizon_clock_record_empty"] and c["exact_clock_pair"]["far_over_near_rate"]==Fraction(16,15) and c["exact_clock_pair"]["far_clock_faster"] and not c["negative_zero_irrational_or_imaginary_proof_scalar_used"]
 return {"horizon":{name:value for name,value in zip(HORIZON_NORMALIZATIONS,(exact,False,False))},"field":{name:value for name,value in zip(FIELD_LAWS,(exact,False,False))},"well":{name:value for name,value in zip(WELL_LAWS,(exact,False,False))},"coefficient":{name:value for name,value in zip(COEFFICIENT_LAWS,(exact,False,False))},"clock":{name:value for name,value in zip(CLOCK_LAWS,(exact,False,False))},"boundary":{name:value for name,value in zip(BOUNDARY_LAWS,(exact,False,False))},"target":{TARGET_BOUNDARIES[0]:True,TARGET_BOUNDARIES[1]:False},"extension":{EXTENSIONS[0]:True,EXTENSIONS[1]:False}}
def candidate_facts(form:CandidateForm)->dict[str,bool]:
 a=axis_facts();return {"horizon":a["horizon"][form.horizon_normalization],"field":a["field"][form.field_law],"well":a["well"][form.well_law],"coefficient":a["coefficient"][form.coefficient_law],"clock":a["clock"][form.clock_law],"boundary":a["boundary"][form.boundary_law],"target":a["target"][form.target_boundary],"extension":a["extension"][form.extension]}
def form_survives(form:CandidateForm)->bool:return all(candidate_facts(form).values())
class StaticExteriorClockProgram:
 def __init__(self,source_hash:str):self.source_hash=source_hash;self._forms=candidate_forms();self._by_id={form.candidate_id:form for form in self._forms}
 @property
 def registration(self)->ClaimRegistration:return ClaimRegistration(CLAIM_ID,"Exact static spherical exterior coefficient, flux and clock law","physics","The generated horizon radius is twice the positive mass carrier. Rank-two boundary conservation forces field equal to horizon radius over radius paired with radius; one retained radius converts this to the well share horizon radius over radius; its positive complement completes the One and is the unique exterior clock-square coefficient. Flux is identical at every exact exterior radius, every outward binary successor halves the well and quarters the field, the boundary closes the clock record, and exact-square exterior pairs force the farther clock to run faster without irrational proof values.",EvidenceMode.EMPIRICAL,(ROOT_THEOREM,),("SFT-PHYS-GRAVITY-WEAK-FIELD-FLUX-003","SFT-PHYS-GRAVITY-STATIC-CLOCK-003","SFT-PHYS-GRAVITY-STRONG-FIELD-HORIZON-003","SFT-PHYS-GRAVITY-REDSHIFT-EQUIVALENCE-003","SFT-PHYS-VALIDATION-GRAVITY-CLOCK-EQUIVALENCE-003","SFT-PHYS-FIELD-INVERSE-SQUARE-001","SFT-PHYS-SPACE-BOUNDARY-RANK-TWO-001","SFT-PHYS-SYMMETRIC-SOURCE-CONSERVATION-TERMINAL-010","SFT-MATH-EXACT-ARITHMETIC-001","SFT-FOUNDATION-MEASURED-VALUE-BOUNDARY-001","SFT-PHYS-MEAS-TARGET-CUSTODY-001"),(),(),(ProvenanceClass.FORWARD_FORCING,ProvenanceClass.OBSERVATIONAL_DERIVATION),self.source_hash)
 def generate_candidates(self)->CandidateCensus:
  candidates=tuple(Candidate(form.candidate_id,str(form),sha256_identity({"rule":GENERATION_RULE,"form":form,"facts":candidate_facts(form)})) for form in self._forms);return CandidateCensus(GENERATION_RULE,GRAMMAR_BOUNDARY,len(candidates),sha256_identity({"axis_cardinalities":(3,3,3,3,3,3,2,2),"candidate_ids":tuple(candidate.candidate_id for candidate in candidates)}),candidates)
 def decide_candidate(self,candidate:Candidate)->CandidateDecision:
  facts=candidate_facts(self._by_id[candidate.candidate_id]);survives=all(facts.values());failed=tuple(name for name,value in facts.items() if not value);reason="Generated horizon, conserved flux, radius-derived well, positive complement and exact clock boundary force the complete exterior law." if survives else "Rejected by computed Fold predicates: "+", ".join(failed)+".";return CandidateDecision(candidate.candidate_id,survives,reason,sha256_identity({"trace":candidate.trace_hash,"facts":facts,"survives":survives,"reason":reason}))
 def closure_evidence(self,decisions:Sequence[CandidateDecision])->ClosureEvidence:
  survivors=tuple(item.candidate_id for item in decisions if item.survives);c=exterior_certificate();closed=len(survivors)==1 and c["all_fluxes_equal_horizon"] and c["all_complements_complete_One"] and c["well_halves_each_successor"] and c["field_quarters_each_successor"] and c["horizon_clock_record_empty"] and c["exact_clock_pair"]["far_clock_faster"];return ClosureEvidence(ClosureScope.DEPTH_INDEPENDENT,GRAMMAR_BOUNDARY,closed,closed and len(set(survivors))==1,sha256_identity({"certificate":c,"decisions":tuple(decisions),"survivors":survivors}),sha256_identity({"base":"At the first exterior doubling, the well is half-One, the coefficient is its positive complement and flux reconstructs the doubled-mass boundary.","successor":"Every radius doubling halves the well, quarters the field, preserves field times radius squared and retains a positive complement closer to the One.","completed_infinity_not_used":True,"targets_absent":True}))
 def run_controls(self)->tuple[ControlResult,...]:
  survivors=tuple(form for form in self._forms if form_survives(form));
  if len(survivors)!=1:raise ValueError("controls require one computed survivor")
  form=survivors[0];c=exterior_certificate();records=((ControlKind.FALSE_PREMISE,c["boundary"]["coefficient"]==() and c["boundary"]["clock_record"]==(),"Reject a numerical boundary coefficient or exterior clock record at complete well depth.","The boundary is the empty structural record."),(ControlKind.TAMPERED_SOURCE,sha256_identity({"changed":self.source_hash})!=self.source_hash,"Reject changed source identity.","Identity differs."),(ControlKind.TAMPERED_ARTIFACT,len({item.candidate_id for item in self._forms})==len(self._forms),"Reject duplicate candidates.","All identities are unique."),(ControlKind.BOUNDARY,not form_survives(replace(form,coefficient_law=COEFFICIENT_LAWS[1])) and not form_survives(replace(form,target_boundary=TARGET_BOUNDARIES[1])) and not form_survives(replace(form,extension=EXTENSIONS[1])),"Reject signed import, pre-seal observation and free correction.","Only positive complement, sealed target and empty extension survive."));return tuple(ControlResult(kind,passed,expected,observed,sha256_identity({"kind":kind,"passed":passed,"expected":expected,"observed":observed})) for kind,passed,expected,observed in records)
__all__=("CLAIM_ID","EXPERIMENT_ID","StaticExteriorClockProgram","candidate_forms","exact_clock_pair","exterior_certificate","exterior_state","form_survives","generated_horizon_radius","positive_remainder")
