"""Terminal strong-CP alignment and baryon/proton stability law.

The older corpora name the two questions audited here, but this execution reads
neither their answer artifacts nor any physical measurement.  Structural
absence is the empty-One record; it is never a numerical proof scalar.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import combinations, product

from sft.engine import EvidenceMode, ProvenanceClass
from sft.physics.lineage_particle_laws import cp_phase_position, parity_fibre
from sft.physics.sector_inventory_law_v1 import mediator_count, prime_sector_ladder
from sft.physics.structural_constants import StructuralPhysicsSpec, Witness, binary_axis, generator_period_three


CLAIM_ID = "SFT-PHYS-STRONG-CP-BARYON-STABILITY-TERMINAL-063"
ONE = Fraction(1, 1)
EMPTY_ONE = ("empty-One",)
HANDS = ("lower-held", "upper-held")


def nonempty_hand_subsets() -> tuple[tuple[str, ...], ...]:
    """Enumerate every nonempty restriction of the admitted handed fibre."""

    return tuple(
        subset
        for width in range(1, len(HANDS) + 1)
        for subset in combinations(HANDS, width)
    )


def cp_position(hand_support: tuple[str, ...]) -> tuple[str, Fraction]:
    """Return the only phase class generated by a handed-support restriction."""

    if hand_support not in nonempty_hand_subsets():
        raise ValueError("CP position requires a complete generated hand subset")
    if hand_support == HANDS:
        return "aligned-One", ONE
    return "self-antipodal-half-One", cp_phase_position()


def strong_hand_census() -> tuple[dict[str, object], ...]:
    """Test all hand restrictions against complete colour-times-hand support."""

    colour = generator_period_three()
    rows = []
    for hands in nonempty_hand_subsets():
        represented = tuple(product(range(1, colour + 1), hands))
        complete = len(represented) == colour * len(HANDS)
        rows.append(
            {
                "hands": hands,
                "represented_cells": represented,
                "complete_colour_hand_product": complete,
                "phase": cp_position(hands),
            }
        )
    return tuple(rows)


def strong_alignment_certificate() -> dict[str, object]:
    rows = strong_hand_census()
    survivors = tuple(row for row in rows if row["complete_colour_hand_product"])
    if len(survivors) != 1 or survivors[0]["hands"] != HANDS:
        raise ValueError("strong vectorial hand census did not close uniquely")
    weak = parity_fibre()
    if weak != {
        "left_held": Fraction(1, 4),
        "image": Fraction(1, 2),
        "right_held": Fraction(3, 4),
    }:
        raise ValueError("admitted weak handed fibre changed")
    return {
        "strong_hands": survivors[0]["hands"],
        "strong_phase": survivors[0]["phase"],
        "weak_phase": ("self-antipodal-half-One", cp_phase_position()),
        "strong_cp_violation_carrier": EMPTY_ONE,
        "electric_dipole_carrier": EMPTY_ONE,
        "extra_compensator_required": EMPTY_ONE,
        "phase_classes": (("aligned-One", ONE), ("self-antipodal-half-One", cp_phase_position())),
    }


def sector_action_signatures() -> tuple[tuple[int, int, int], ...]:
    """Enumerate all admitted mediator actions with fibre-typed endpoints."""

    rows = []
    for sector in prime_sector_ladder():
        for cell in range(1, mediator_count(sector) + 1):
            rows.append((sector, sector, cell))
    return tuple(rows)


def cross_fibre_label_pairs() -> tuple[tuple[int, int, int, int], ...]:
    """Enumerate every ordered label pair whose source and image fibres differ."""

    return tuple(
        (source_sector, source_label, target_sector, target_label)
        for source_sector in prime_sector_ladder()
        for target_sector in prime_sector_ladder()
        if source_sector != target_sector
        for source_label in range(1, source_sector + 1)
        for target_label in range(1, target_sector + 1)
    )


def sector_action_certificate() -> dict[str, object]:
    signatures = sector_action_signatures()
    cross_pairs = cross_fibre_label_pairs()
    return {
        "sectors": prime_sector_ladder(),
        "mediator_counts": tuple(mediator_count(sector) for sector in prime_sector_ladder()),
        "mediator_total": len(signatures),
        "all_actions_fibre_preserving": all(source == target for source, target, _ in signatures),
        "cross_fibre_pair_count": len(cross_pairs),
        "generated_cross_fibre_actions": tuple(
            pair
            for pair in cross_pairs
            if any(pair[0] == source and pair[2] == target for source, target, _ in signatures)
        ),
        "quark_to_lepton_pair_count": sum(1 for row in cross_pairs if row[0] == 3 and row[2] == 2),
    }


def baryon_tally(colour_word: tuple[int, ...]) -> Fraction:
    colour = generator_period_three()
    if len(colour_word) != colour or any(label not in range(1, colour + 1) for label in colour_word):
        raise ValueError("baryon tally requires one complete colour-three word")
    return sum((Fraction(1, colour) for _ in colour_word), Fraction(1, colour)) - Fraction(1, colour)


def complete_colour_words() -> tuple[tuple[int, ...], ...]:
    colour = generator_period_three()
    return tuple(product(range(1, colour + 1), repeat=colour))


def proton_transition_certificate() -> dict[str, object]:
    words = complete_colour_words()
    initial = tuple(range(1, generator_period_three() + 1))
    action = sector_action_certificate()
    if action["generated_cross_fibre_actions"] != ():
        raise ValueError("a cross-fibre action entered the closed mediator grammar")
    return {
        "initial_colour_word": initial,
        "initial_baryon_tally": baryon_tally(initial),
        "generated_one_step_images": words,
        "generated_image_count": len(words),
        "all_images_retain_baryon_One": all(baryon_tally(word) == ONE for word in words),
        "quark_to_lepton_action": EMPTY_ONE,
        "lepton_only_decay_image": EMPTY_ONE,
        "finite_composition_law": "composition-of-same-fibre-maps-remains-same-fibre",
        "baryogenesis_boundary": (
            "the admitted retained-residue law has a distinct cosmological tally-changing premise; "
            "the complete mediator grammar contains no such low-energy proton transition"
        ),
    }


def theorem_certificate() -> dict[str, object]:
    alignment = strong_alignment_certificate()
    actions = sector_action_certificate()
    proton = proton_transition_certificate()
    return {
        "alignment": alignment,
        "actions": actions,
        "proton": proton,
        "unique_strong_hand_form": sum(row["complete_colour_hand_product"] for row in strong_hand_census()) == 1,
        "only_two_phase_classes": len({row["phase"] for row in strong_hand_census()}) == 2,
        "no_extra_compensator": alignment["extra_compensator_required"] == EMPTY_ONE,
        "baryon_One_invariant": proton["initial_baryon_tally"] == ONE and proton["all_images_retain_baryon_One"],
    }


SPEC = StructuralPhysicsSpec(
    claim_id=CLAIM_ID,
    title="Terminal strong-CP alignment and proton/baryon stability law",
    statement=(
        "The complete colour-three fibre is independent of the binary handed fibre. With no generated hand selector, "
        "complete colour-times-hand support retains both hands; enumeration of all three nonempty hand subsets leaves "
        "that vectorial form uniquely complete. Opposition composed with paired parity therefore returns the aligned "
        "One, whereas either one-hand restriction returns the already admitted self-antipodal half-One weak phase. "
        "Strong CP violation, its electric-dipole carrier and any compensating axion-like rule are consequently absent "
        "empty-One records, not tuned numerical values. Independently, all 83 generated mediator signatures preserve "
        "their prime fibre. Complete enumeration finds 202 cross-fibre label pairs, including six colour-to-binary "
        "pairs, but no generated carrier for any of them. Every one of the 27 colour-three proton images retains "
        "three one-third baryon parts, exactly the One; finite composition preserves the same fibre."
    ),
    dependencies=(
        "SFT-PHYS-WEAK-PARITY-FIBRE-002",
        "SFT-PHYS-NEUTRINO-CP-PHASE-002",
        "SFT-PHYS-FORCE-COMPLETE-SECTOR-INVENTORY-003",
        "SFT-PHYS-MATTER-PARTICLE-ANTIPARTICLE-001",
        "SFT-PHYS-MATTER-CONSERVED-LABELS-001",
        "SFT-PHYS-MATTER-COMPOSITE-HADRONS-001",
        "SFT-PHYS-NUCLEON-BINDING-TERMINAL-005",
        "SFT-PHYS-BARYOGENESIS-DEPENDENCY-TERMINAL-021",
        "SFT-MATH-EXACT-ARITHMETIC-001",
        "SFT-MATH-COMBINATORICS-001",
        "SFT-FOUNDATION-MEASURED-VALUE-BOUNDARY-001",
    ),
    evidence_mode=EvidenceMode.FORMAL,
    generation_rule=(
        "Generate the complete product of immutable predecessor, CP carrier, handed support, strong-sector product, "
        "compensator, sector-action typing, baryon tally, finite transition, baryogenesis boundary, measurement custody "
        "and extension forms."
    ),
    grammar_boundary=(
        "All nonempty subsets of the exact two-hand fibre; complete colour-three times hand support; every mediator "
        "cell in prime sectors two, three, five and seven; every ordered cross-fibre label pair; every colour-three "
        "word; and every finite composition of the generated typed actions."
    ),
    axes=(
        binary_axis("predecessor", "How are admitted laws used?", "rewrite-or-bypass-predecessors", "A successor cannot change an admitted receipt.", "compose-immutable-predecessors", "The new law composes only registered exact fibres, sectors and conserved labels."),
        binary_axis("cp", "Which exact CP carrier is available?", "continuum-angle-or-fitted-small-value", "A continuum angle or small fitted value is inadmissible.", "aligned-One-or-self-antipodal-half-One", "The admitted Fold phase grammar contains exactly alignment and self-antipode."),
        binary_axis("hand", "Which strong-sector hands are retained?", "selected-single-hand", "Selecting one hand omits half the colour-times-hand product.", "complete-two-hand-support", "With no strong hand selector, every colour label occurs with both held hands."),
        binary_axis("strong", "Where does vectorial strong CP land?", "weak-antipode-reused-for-strong", "A one-hand weak carrier contradicts complete strong support.", "paired-parity-returns-aligned-One", "Opposition composed with paired parity returns the Fold-invariant One."),
        binary_axis("compensator", "Is an additional phase-restoring field required?", "add-axion-or-free-compensator", "An extra carrier has no discrepancy to act on and forks the closed inventory.", "empty-One-no-extra-compensator", "Exact structural alignment leaves no unclosed phase and generates no added field."),
        binary_axis("sector", "Can a mediator change fibre identity?", "invent-cross-fibre-mediator", "A two-sector signature is absent from every complete sector action table.", "all-generated-actions-are-fibre-preserving", "Each of all 83 mediator signatures has the same source and image fibre."),
        binary_axis("baryon", "How is proton baryon support counted?", "untyped-particle-name", "A name alone does not establish conservation.", "three-one-third-parts-close-to-One", "The complete colour-three word carries three exact one-third parts."),
        binary_axis("transition", "What happens under repeated actions?", "assume-an-unregistered-decay-step", "An unregistered fibre crossing inserts the desired decay.", "finite-composition-preserves-the-fibre", "Composition of same-fibre maps remains same-fibre at every finite successor."),
        binary_axis("baryogenesis", "Does the cosmological residue law create proton decay?", "conflate-distinct-process-grammars", "A cosmological tally-changing premise is not a low-energy mediator.", "retain-explicit-cosmological-boundary", "The prior residue law remains intact while no such premise appears in the proton grammar."),
        binary_axis("measurement", "May EDM or lifetime data select the result?", "target-readable-before-seal", "That would tune alignment or stability to observation.", "targets-inaccessible-until-seal", "The formal census closes before either experiment is opened."),
        binary_axis("extension", "May an added angle, carrier or decay operation enter?", "free-angle-carrier-or-operation", "Any such addition is an unforced parameter.", "no-extra-rule", "The handed, sector, mediator and finite-composition supports exhaust the declared grammar."),
    ),
    exact_result=(
        "Strong-sector CP is the aligned One; the strong-violation, electric-dipole and added-compensator records are "
        "empty-One. The weak one-hand phase remains the self-antipodal half-One. All 83 generated mediators are "
        "fibre-preserving; all 202 ordered cross-fibre label pairs and all six colour-to-binary pairs lack a generated "
        "carrier. The proton carries baryon One = 3*(1/3), all 27 generated colour-three images retain it, and every "
        "finite composition remains in the colour fibre. Proton decay is absent within the complete declared grammar."
    ),
    induction_base=(
        "The first colour-three proton word contains exactly three one-third parts, while each primitive mediator "
        "action has identical source and image fibre types."
    ),
    induction_step=(
        "Composing another fibre-preserving action with a fibre-preserving path cannot change its endpoint type; "
        "therefore every finite successor retains the complete colour-three baryon One."
    ),
    exclusions=(
        "no V1/V2 executable, certificate, answer table, survivor identifier or measurement as a premise",
        "no conventional theta continuum, fitted small angle, negative, irrational, imaginary, floating, NaN or infinite proof scalar",
        "no neutron electric-dipole bound or proton-lifetime limit in formal execution",
        "no imported Peccei-Quinn, axion, grand-unification or Standard Model mechanism as a proof premise",
        "no contradiction of the separately admitted cosmological baryogenesis dependency law",
    ),
    witnesses=(
        Witness("strong-hand-census", "All three nonempty hand subsets are generated and only the paired form completes colour-times-hand support.", len(strong_hand_census()) == 3 and theorem_certificate()["unique_strong_hand_form"]),
        Witness("phase-census", "The complete census yields only aligned One and self-antipodal half-One phase classes.", theorem_certificate()["only_two_phase_classes"] and strong_alignment_certificate()["strong_phase"] == ("aligned-One", ONE)),
        Witness("no-compensator", "Exact alignment leaves no strong-violation, EDM or compensator carrier.", theorem_certificate()["no_extra_compensator"] and strong_alignment_certificate()["electric_dipole_carrier"] == EMPTY_ONE),
        Witness("sector-actions", "All 83 generated mediators preserve fibre and none of 202 cross-fibre pairs is generated.", sector_action_certificate()["mediator_total"] == 83 and sector_action_certificate()["cross_fibre_pair_count"] == 202 and sector_action_certificate()["generated_cross_fibre_actions"] == ()),
        Witness("proton-invariant", "All 27 complete colour-three images retain baryon One.", proton_transition_certificate()["generated_image_count"] == 27 and theorem_certificate()["baryon_One_invariant"]),
    ),
    provenance=(ProvenanceClass.OBSERVATIONAL_DERIVATION,),
)


SPEC.validate()


__all__ = (
    "CLAIM_ID",
    "EMPTY_ONE",
    "HANDS",
    "ONE",
    "SPEC",
    "baryon_tally",
    "complete_colour_words",
    "cp_position",
    "cross_fibre_label_pairs",
    "nonempty_hand_subsets",
    "proton_transition_certificate",
    "sector_action_certificate",
    "sector_action_signatures",
    "strong_alignment_certificate",
    "strong_hand_census",
    "theorem_certificate",
)
