from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CONFORMER-ENUMERATION-006'
DOMAINS=(('formula-only-conformer', 'held-canonical-molecular-graph'), ('all-single-bonds-assumed-rotatable', 'forced-rotatable-bond-support'), ('continuum-angle-premise', 'declared-finite-torsion-fibre-resolution'), ('sampled-random-conformers', 'complete-torsion-word-support'), ('duplicate-conformers-retained', 'exact-graph-symmetry-quotient'), ('fitted-force-field-selection', 'admitted-state-order-consumer-only'), ('lowest-only-output', 'complete-member-and-equivalence-certificate'), ('unbounded-conformer-claim', 'explicit-graph-and-resolution-boundary'))
SURVIVOR='held-canonical-molecular-graph__forced-rotatable-bond-support__declared-finite-torsion-fibre-resolution__complete-torsion-word-support__exact-graph-symmetry-quotient__admitted-state-order-consumer-only__complete-member-and-equivalence-certificate__explicit-graph-and-resolution-boundary'
DIMENSION_KEYS=('carrier', 'rotors', 'resolution', 'generation', 'symmetry', 'energy', 'certificate', 'boundary')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
