from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-CLASSICAL-QUANTUM-ALGORITHM-CORRESPONDENCE-014'
DOMAINS=(('different-classical-quantum-chemical-laws', 'one-shared-admitted-chemical-law'), ('different-mode-specific-inputs', 'one-held-chemical-input-carrier'), ('opaque-classical-library-output', 'exact-classical-transition-trace'), ('amplitude-only-output', 'complete-reversible-branchwise-trace'), ('statistical-output-similarity', 'exact-branch-state-projection'), ('collapse-erases-record', 'held-observation-and-retained-record'), ('unreported-mode-cost', 'separate-time-space-branch-record-cost'), ('approximately-same-result', 'identical-canonical-terminal-carrier'))
SURVIVOR='one-shared-admitted-chemical-law__one-held-chemical-input-carrier__exact-classical-transition-trace__complete-reversible-branchwise-trace__exact-branch-state-projection__held-observation-and-retained-record__separate-time-space-branch-record-cost__identical-canonical-terminal-carrier'
DIMENSION_KEYS=('chemistry', 'input', 'classical', 'quantum', 'mapping', 'observation', 'resource', 'terminal')
def main():
 sealed=json.load(open(sys.argv[1]));generated=["__".join(item) for item in product(*DOMAINS)];decisions={item["candidate_id"]:item["survives"] for item in sealed["decisions"]};controls=sealed["controls"];passed=sealed["claim_id"]==CLAIM_ID and len(DOMAINS)==8 and all(len(domain)==2 for domain in DOMAINS) and len(set(DIMENSION_KEYS))==8 and [item["candidate_id"] for item in sealed["census"]["candidates"]]==generated and decisions=={item:item==SURVIVOR for item in generated} and sum(decisions.values())==1 and sealed["closure"]["scope"]=="depth_independent" and len(controls)>=4 and all(item["passed"] for item in controls);print(json.dumps({"validated_seal_hash":sealed["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"dimension_count":len(DOMAINS),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,"all_registered_controls_passed":all(item["passed"] for item in controls),"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_native_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
