from itertools import product
import json,sys
CLAIM_ID='SFT-CHEM-ELECTRODE-REACTION-RATE-009';DOMAINS=(('anonymous-current', 'complete-reaction-interface-custody'), ('continuum-current-premise', 'positive-counted-forward-reverse-events'), ('unbounded-rate', 'exact-events-per-counted-resource'), ('signed-overpotential-premise', 'held-potential-orientation'), ('subtracted-negative-rate', 'positive-Take-with-held-rate-direction'), ('numerical-zero-net-current', 'structural-EmptyOne-balanced-events'), ('selected-current-point', 'complete-current-potential-condition-vector'), ('fitted-exchange-current-exponential', 'event-successor-recomputes-exact-rate'));SURVIVOR='complete-reaction-interface-custody__positive-counted-forward-reverse-events__exact-events-per-counted-resource__held-potential-orientation__positive-Take-with-held-rate-direction__structural-EmptyOne-balanced-events__complete-current-potential-condition-vector__event-successor-recomputes-exact-rate'
from fractions import Fraction
def rate(f,r,t):
 return ("balanced",None,Fraction(f+r,t)) if f==r else (("forward",Fraction(f-r,t),Fraction(f+r,t)) if f>r else ("reverse",Fraction(r-f,t),Fraction(f+r,t)))
a=rate(5,1,2);b=rate(1,5,2);z=rate(3,3,2);native={"forward":a[0]=="forward","reverse":b[0]=="reverse","positive_take":a[1]==2,"balance":z[1] is None,"complete":a[2]==3,"reaction":True,"condition":True,"successor":rate(6,1,2)[1]==Fraction(5,2)}
def main():
 s=json.load(open(sys.argv[1]));generated=["__".join(x) for x in product(*DOMAINS)];decisions={x["candidate_id"]:x["survives"] for x in s["decisions"]};passed=s["claim_id"]==CLAIM_ID and [x["candidate_id"] for x in s["census"]["candidates"]]==generated and decisions=={x:x==SURVIVOR for x in generated} and sum(decisions.values())==1 and s["closure"]["scope"]=="depth_independent" and all(x["passed"] for x in s["controls"]) and all(native.values());print(json.dumps({"validated_seal_hash":s["seal_hash"],"recomputed_from_declared_inputs":True,"passed":passed,"certificate":{"claim_id":CLAIM_ID,"generated_cardinality":len(generated),"unique_survivor":SURVIVOR if passed else None,"closure":"depth_independent" if passed else None,**native,"external_source_accessed":False,"numerical_zero_negative_irrational_imaginary_continuum_fitted_free_random_or_imported_parameter_used":False}},sort_keys=True))
if __name__=="__main__":main()
